### ISSUE TITLE
Warning for unused map output

### ISSUE THREAD

**Issue by michaelmior** [bbatsov/rubocop#1052]
If the output of a call to `map` is thrown away, then it feels like it would be much better to use `each`.

```ruby
[1, 2, 3].map { |n| puts n }
```

vs

```ruby
[1, 2, 3].each { |n| puts n }
```

**Comment by bbatsov** [comment]
Seems we won't be doing this any time soon. If someone wants to pick it up - PRs are welcome! :-)
