### ISSUE TITLE
Thoughts on GuardClause

### ISSUE THREAD

**Issue by mockdeep** [bbatsov/rubocop#1138]
We enabled the `GuardClause` rubocop but found that in some cases the results are disagreeable. I don't know of a good way for rubocop to handle this, but thought I'd see if there were any thoughts. Basically, it would be nice to be able to have nested conditions where there is an error state:

```ruby
# good
if error_state
  flash[:error] = 'bad state'
  render :new
end

# bad
return unless error_state

flash[:error] = 'bad state'
render :new
```

But code should not be nested when it is part of the happy flow:

```ruby
# good
return unless value

user.value = value
user.do_some_magic!

# bad
if value
  user.value = value
  user.do_some_magic!
end
```

I think one thing that might help is for `GuardClause` to only check at the beginning of the method for conditionals, though that wouldn't catch everything.

**Comment by alexdowad** [comment]
I don't think there is any way for RC to know what is the "good" path and what is the "bad" path. I suggest that this issue be closed. If someone here has a good idea, they can re-open it.
