### ISSUE TITLE
--display-cop-names from .rubocop.yml?

### ISSUE THREAD

**Issue by dankohn** [bbatsov/rubocop#1324]
Can I specify to always use the flag `--display-cop-names` from my .rubocop.yml?

**Comment by jonas054** [comment]
I think that what stops me or anyone from getting started on an implementation is the fact that there are today 20 command line options. Some of them make sense as configuration options, some don't. Some are easy to implement as configuration options, some are hard.

My suggestion is that we handle only the option originally requested in this issue; `AllCops/DisplayCopNames`. If more are wanted/needed we do them in separate issues.

**Comment by bbatsov** [comment]
Fair enough.

On Sunday, January 4, 2015, Jonas Arvidsson <notifications@github.com>
wrote:

> I think that what stops me or anyone from getting started on an
> implementation is the fact that there are today 20 command line options.
> Some of them make sense as configuration options, some don't. Some are easy
> to implement as configuration options, some are hard.
>
> My suggestion is that we handle only the option originally requested in
> this issue; AllCops/DisplayCopNames. If more are wanted/needed we do them
> in separate issues.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bbatsov/rubocop/issues/1324#issuecomment-68642340>.
>


-- 
Best Regards,
Bozhidar Batsov

http://www.batsov.com

**Comment by mnquintana** [comment]
@jonas054 @bbatsov Do you think it would be good if I made another "master" issue for tracking which flags people want added as config options?

**Comment by jonas054** [comment]
@mnquintana Yes, please create it.

**Comment by bbatsov** [comment]
I'm not fond of meta-issues that stay open forever. Let's wrap this first.
If other options are needed someone will certainly create tickets regarding
them.

On Sunday, January 4, 2015, Jonas Arvidsson <notifications@github.com>
wrote:

> @mnquintana <https://github.com/mnquintana> Yes, please create it.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bbatsov/rubocop/issues/1324#issuecomment-68648662>.
>


-- 
Best Regards,
Bozhidar Batsov

http://www.batsov.com

**Comment by mnquintana** [comment]
@bbatsov Fair enough. What about a label / milestone? (Just something to keep track of each individual issue as they crop up.)

**Comment by bbatsov** [comment]
Having a custom label for this type of issues sounds fine.

**Comment by tansaku** [comment]
I'd love to be able to use:

AllCops/DisplayCopNames

and

AllCops/DisplayStyleGuide

would be hugely useful for our team - particularly with houndci integration
