### ISSUE TITLE
Rails-compatible indentation of private and protected methods

### ISSUE THREAD

**Issue by grn** [bbatsov/rubocop#1342]
# Problem

Currently Rubocop can check the indentation of `private`, `protected` and `public` modifiers. Unfortunately it isn't able to check whether the code that follows uses the Rails convention of indenting private and protected methods with respect to `private` and `protected`. For example the style

```ruby
class MyClass
  def a_public_method
  end

  private

    def a_private_method
    end
end
```

should be supported.

# Solution

The `Style/AccessModifierIndentation` cop could support a new `EnforcedStyle` called `rails` that would use the Rails convention.

`rubocop -V` returns

```
0.26.1 (using Parser 2.2.0.pre.4, running on ruby 2.0.0 x86_64-linux)
```

**Comment by Proghat** [comment]
I would like to implement this. In my style guide it may looks like:

1. Don't use explicit `public` access modifier. Keep all public methods on top of class defenition.
2. Write `protected` and `private` keywords in the same level of indentation as public methods.
3. Indent protected and private methods relative to `protected` and `private` keywords.

Example:

```ruby
class Cat
  def meow
    puts('Meow!')
  end

  protected

    def can_we_be_friends?(another_cat)
      # some logic
    end

  private

    def meow_at_3am?
      rand < 0.8
    end
end
```

As I understand changes could affect `Cop::Style::IndentationConsistency` and `Cop::Style::IndentationWidth`. I'm not sure where to store config for this. I think about:
```yaml
Style/IndentationConsistency:
  AllowProtectedAndPrivateMethodsBeIndented: true
```
but is it ok if I will check this config in `IndentationWidth` cop?

@bbatsov can you please help me? Will it be merged?

**Comment by fgarcia** [comment]
>  Initially I assumed that this is the style used in Rails source code but in reality it's very inconsistent. 

@mikegee. I thought that Rails source code was inconsistent because they could not use Rubocop goodness to solve it :relieved:

**Comment by bbatsov** [comment]
I'm OK with adding support for the suggested style. Not sure what'd be best regarding `IndentationConsistency`. Guess @jonas054 will be of more help regarding this.

**Comment by Proghat** [comment]
@jonas054 What do you think about it?

**Comment by bbatsov** [comment]
@jonas054 is on vacation. He'll be back in about a month.

**Comment by Proghat** [comment]
Oh, ok. Thank you for response, Bozhidar @bbatsov.

**Comment by jonas054** [comment]
@Proghat Go ahead and start coding if you like. I'll try to review your work if you submit a PR. Some  thoughts:
* Just check which cops report offenses for your style. Those are the ones you need to make changes in.
* Yes, it's okay to store configuration in one cop and use it from several cops.
* Don't allow two styles at the same time. You used the word "allow" in the parameter name but we should always enforce one style or another, not leave room for preferences within one style.

**Comment by amanattou44** [comment]
Hello.
How's the hear?

**Comment by SaimonL** [comment]
This rubocop is designed for pure Ruby. Rails is a full framework and uses different style guides all together. Just use Rail generator and you will see the style is different, which will not change for 1000 years and same goes for the community. For Rails please use the gem "rubocop-rails" instead with will work with the '.rubocop.yml' file. For more visit https://github.com/bbatsov/rubocop

**Comment by bbatsov** [comment]
> This rubocop is designed for pure Ruby. Rails is a full framework and uses different style guides all together. Just use Rail generator and you will see the style is different, which will not change for 1000 years and same goes for the community. For Rails please use the gem "rubocop-rails" instead with will work with the '.rubocop.yml' file. For more visit https://github.com/bbatsov/rubocop

Internally they can use whatever code style they want, but no framework defines the code style of a project.

**Comment by carlomartinucci** [comment]
For those who came here looking for a solution (noobs like me), just use:
```
Layout/IndentationConsistency:
  EnforcedStyle: rails
```

**Comment by erickveras** [comment]
The property:

`Style/IndentationConsistency:
  AllowProtectedAndPrivateMethodsBeIndented: true`

Its not in default.yml and set a notice when call rubocop: 

`
Warning: unrecognized parameter Layout/IndentationConsistency:AllowProtectedAndPrivateMethodsBeIndented found in .rubocop.yml
`

But the option exist, works and solve my problem.
http://www.rubydoc.info/gems/rubocop/0.47.1/RuboCop/Cop/Style/IndentationConsistency

In project the class not exist:
https://github.com/bbatsov/rubocop/tree/master/lib/rubocop/cop/style

I want no indent on private methods when set rails
`Layout/IndentationConsistency:
  EnforcedStyle: rails`

**Comment by Molszew** [comment]
Since Rubocop v0.72 `EnforcedStyle: rails` have beed renamed. Use this instead:
```
Layout/IndentationConsistency:
  EnforcedStyle: indented_internal_methods
```
