### ISSUE TITLE
Align hash's and array's closing curly/bracket with the opening curly/bracket column

### ISSUE THREAD

**Issue by jfelchner** [bbatsov/rubocop#1400]
I have no idea how difficult this would be, but most often, I want my hashes and arrays aligned like this:

```ruby
this_is_a_hash = {
                   my_key:       'my_value',
                   my_other_key: 'my other value',
                 }
```

Currently the cop wants the last 3 lines to be back-dented so that the `}` is on the first column.

The configuration I'm proposing would allow for the style above, but also be configurable so that if that style causes the lines to go past the maximum line length, it would revert back to the current style.

Any thoughts?

**Comment by alexdowad** [comment]
This has been dealt with elsewhere and can be closed.

**Comment by jfelchner** [comment]
@alexdowad indeed it has! :grinning:
