### ISSUE TITLE
Railcop for avoiding Time.now

### ISSUE THREAD

**Issue by dankohn** [bbatsov/rubocop#1405]
Would you be interested in a Rubocop for Rails that autocorrects usage of `Time.now` to `Time.zone.now`?

The good and bad examples here could be searched for:
http://danilenko.org/2012/7/6/rails_timezones/

**Comment by bbatsov** [comment]
@dankohn Ping

**Comment by dankohn** [comment]
Haven't been able to work on this. Please feel free to close and I'll
reopen when I have a pull request to look at.

--
Dan Kohn <mailto:dan@dankohn.com>
tel:+1-415-233-1000

**Comment by palkan** [comment]
@bbatsov @dankohn 
I would like to work on this cop if you don't mind

**Comment by bbatsov** [comment]
Fine by me.

On 19 February 2015 at 23:32, Vladimir Dementyev <notifications@github.com>
wrote:

> @bbatsov <https://github.com/bbatsov> @dankohn
> <https://github.com/dankohn>
> I would like to work on this cop if you don't mind
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bbatsov/rubocop/issues/1405#issuecomment-75140544>.
>



-- 
Best Regards,
Bozhidar Batsov

http://www.batsov.com

**Comment by dankohn** [comment]
I'd be thrilled. I haven't had a chance to jump into it.
