### ISSUE TITLE
Severe: Rubocop silently accepts complete garbage as configuration

### ISSUE THREAD

**Issue by e2** [bbatsov/rubocop#1428]
Rubocop shows no error, even if the config file is complete garbage (anything that's a valid UTF-8 stream at least).

How to reproduce:
1. `echo '"' > bad.yml`
2. `rubocop -c bad.yml`

Expected: e.g. "Psych::SyntaxError: (<unknown>): found unexpected end of stream"
Actual: no errors

Introduced by commit: https://github.com/bbatsov/rubocop/commit/57aadf2eaad903a1294a58eea2d77b8ffadf2985

This would ultimately solve the problem (somewhat related):
https://github.com/bbatsov/rubocop/issues/1151

So, while Rubocop is extremely fussy about Ruby code, Rubocop's config files have a "get out of jail" card.

Oh the irony :D

(I marked this as severe because of how much time people can waste reproducing and reporting issues)

**Comment by bbatsov** [comment]
I seem to recall us fixing this recently, but I can't find the related PR.

**Comment by bquorning** [comment]
I think it might be fixed by https://github.com/bbatsov/rubocop/issues/1504

**Comment by bquorning** [comment]
Or rather #1511.

**Comment by bbatsov** [comment]
Thanks, @bquorning!

**Comment by e2** [comment]
:heart_eyes: Thanks, @bquorning!
