### ISSUE TITLE
Style/HashSyntax to support hash rockets when pointing to symbols

### ISSUE THREAD

**Issue by brodock** [bbatsov/rubocop#1437]
While this is not covered by the **ruby style guide** yet, I've seen benefits of using hash rocket instead of 1.9 when pointing to symbols:

```ruby
# bad
{key: :value}

# good
{:key => :value}
```
As I beleive this may not be consensus, I suggest to make it specific configurable:
```yml
Style/HashSyntax:
  AllowHashRocketForSymbolicValues: true/false
```

This may be related to #519.

**Comment by rrosenblum** [comment]
I have an idea on how to implement this feature and have started on some code for it. I will try to put together a pull request soon.
