### ISSUE TITLE
Allow configuration of visibility_and_def_on_same_line? method

### ISSUE THREAD

**Issue by maksar** [bbatsov/rubocop#1467]
Ruby 2.1 syntax allows method modifiers to be placed right before method declarations, like:
```
private def current_profile
  current_user.profile
end
```
Currently, only `[:public, :protected, :private, :module_function]`method modifiers supported.
It would be nice to have this list configured by `.rubocop.yml` file. In particular, Rails features like helper_method or before_action, etc.:
```
helper_method def current_profile
  current_user.profile
end
```

All mentioned happens in `lib/rubocop/cop/mixin/on_method.rb` file. Please, suggest similar place in codebase, where such configuration is already implement, so I can take a look and create a pull request for this ticket.

**Comment by fphilipe** [comment]
Just came across this myself. What about not caring what comes before the `def`?

**Comment by bbatsov** [comment]
Patches welcome. :-)

**Comment by fphilipe** [comment]
@bbatsov Would you say it's OK not to check what comes before `def` or would you prefer the list of allowed words to be configurable?
