### ISSUE TITLE
Cops should be limitable to match RuboCop release tags.

### ISSUE THREAD

**Issue by jdickey** [bbatsov/rubocop#1468]
From [a comment](https://github.com/bbatsov/rubocop/pull/1463#issuecomment-64436962) I made on PR #1463:

> I'm beginning to think we need some more blanket method of specifying what cops are included/excluded than updating the YAML config file every time a new cop is added. Say, something like a CLI option or environment variable specifying a release number; if I have the option `--cops-as-version 0.26.1`, I shouldn't see any offences reported by `Metrics/AbcSize` (new to 0.27.0).
>
> Have the default be whatever the latest and greatest gaggle of cops is, but when you're working on a project for more than a week or two, having a continually shifting validation target just adds to the workload. Let people add *bring RuboCop cops up to date* as a part of their workflow of their own choosing.
>
> Why don't I just specify an old version in my Gemfile? New versions have bug fixes unrelated to new cops, for one obvious reason.

----

It's great that so many new cops have been added all through the history of this project. What's not so great is continually going back and changing code you've already written, that was approved by the Rubocop of the day (say, a couple of weeks or months ago), but gives offenses now (that break your CI if it depends on `rake rubocop` coming back clean). What you wind up with is a continually growing series of moving targets, with very little heads-up about what's going to start moving next.

Our workflow has historically treated `.rubocop.yml` basically as a canary; if we need entries to modify or disable cops, then *our code* needs fixing somewhere.We're *very* uncomfortable with the idea of saying "Our standard is just like theirs, *except for* these things they mark as Naughty Bits." There's just a *huge* can of worms opened there.

@bbatsov responded to my original comment on #1463 talking about "introducing some cop metadata". That's half of it, as far as I can see; you still have to have RuboCop support the CLI option/environment variable/etc to say "silence cops that were introduced after *this* version". Using such a mechanism, in a self-respecting team, *should* be an indication that "we know that we need to get current with cop compliance, but we've made the deliberate choice not to do it yet for the usual reasons." That's better than just throwing stuff into a `.rubocop.yml` and nobody paying attention to them again; CLI options and environment variables leave traces in your CI logs, etc.

**Comment by jonas054** [comment]
How about we add an option `--only-from COP_LIST_FILE` that works like `--only COP(S)` but reads from a file containing cop names separated by line breaks? Then we add files called `config/cop_list_v0.27.0.txt` etc.

**Comment by jdickey** [comment]
I could live with that, especially with a list of such in the Gem config directory. I think that'd be a very handy reference to have going forward, as well: "here's a list of the cops enabled in the default `enabled.yml` for *this release*". That would help in diagnosing suddenly-failing cops, analysing how the list of cops used grows and changes over time, and even as a supporting artefact for "what ought we to include in the next release?"

Great idea!

**Comment by alexdowad** [comment]
I think what needs to be remembered here is that RuboCop is still < 1.0. It's "in beta". Right now, it is expected that things will change quickly from one release to the next.

RC is moving steadily forward and will hopefully reach a state where it can be released as 1.0 before long. After that point, I'm sure that new cops will not be introduced without a bump in the minor version number. If there is demand for bug fixes to be backported to older versions (and released with a bump in the tiny version number), I'm sure that will also be done... just like the way that the Ruby team may bump Ruby 2.1.0 up to 2.1.1 and then 2.1.2, even after 2.2.0 has already been released.

So if you don't want to break your build, you can stick to the 1.0 series (for example) even after 1.1 and 1.2 are out. And still get your bug fixes.

Actually, there is no reason to think that adding new cops will continue forever. We should hit a saturation point eventually, after which adding new cops will become a rare event. So this issue is temporary.

I suggest this can be closed.

**Comment by bbatsov** [comment]
> Actually, there is no reason to think that adding new cops will continue forever. We should hit a saturation point eventually, after which adding new cops will become a rare event. So this issue is temporary.

That's the plan. :-)

**Comment by jdickey** [comment]
@alexdowad I'd be fine with that (simply using a fixed version number) *except* for the idea that bugs might be fixed in later releases *independently of* new cops being added. In an ideal world, the RuboCop "engine" and cops would be separately versioned, but I accept that that ship has sailed; probably years ago.

Thanks for the discussion.

**Comment by alexdowad** [comment]
@jdickey Understood. One of my points is that hopefully sooner rather than later, there won't *be* new cops added. So this will cease to be an issue.

**Comment by bbatsov** [comment]
And we'll probably remove some cops (cops of limited usefulness, cops that produce very unreliable results and all the Rails cops).

**Comment by jdickey** [comment]
@alexdowad, @bbatsov Understood and empathised with. Stability would be a wonderful thing. :grinning: 

Thanks again.

**Comment by alexdowad** [comment]
@jdickey, thank you. Our goal is to achieve stability by pushing development ahead quickly and bringing the project to maturity. If we try to enforce stability right now, it will just delay that goal.
