### ISSUE TITLE
"Shadowing outer local variable" is not smart enough

### ISSUE THREAD

**Issue by killthekitten** [bbatsov/rubocop#1518]
I have a case of using ruby blocks like this:
```
lib/export_tools/xlsx_writer.rb:13:40: W: Shadowing outer local variable - package.
      package = Axlsx::Package.new do |package|
                                       ^^^^^^^
```

In this case `package` variable is set only after block will eval and return it's value, so shadowing doesn't take place. Should we fix the behavior of rubocop here?

**Comment by bbatsov** [comment]
At least the RuboCop inspection can the turned off (unlike the one in MRI). :-) As @jonas054 - PR welcome. I don't think we'll be able to allocate any attention to this in the foreseeable future, so I'm closing the issue.
