### ISSUE TITLE
Allow Style/WordArray not just to be disabled but have alternate EnforcedStyle

### ISSUE THREAD

**Issue by lloeki** [bbatsov/rubocop#1543]
Style/WordArray can only be Enabled: false, have MinSize set or WordRegex defined.

If one wants to enforce word array percent syntax *not* to be used, even hacking into MinSize (setting it to a huge value) or WordRegex (setting it to something clever that will never match) doesn't work.

Having an EnforcedStyle with values of `array` or `percent`, defaulting to the latter, would be quite useful.

**Comment by alexdowad** [comment]
So once we have `array` and `percent` styles, what should happen with the `MinSize` parameter? Do we keep it? (Presumably it would only apply when the `percent` style is selected?)

**Comment by jonas054** [comment]
Another way to go would be to let the cop enforce array literals when there are `MinSize` words or fewer. Today it allows either syntax in those cases.

**Comment by alexdowad** [comment]
@jonas054 And presumably we error out if both `EnforcedStyle: array` and `MinSize` > 0?

**Comment by jonas054** [comment]
Sorry. I wasn't very clear. What I meant was, that if we're just more strict and always require array literals or require `%w` or `%W`, depending on the `MinSize`setting, then we don't need to add `EnforcedStyle`. Setting `MinSize: 1000000` will have the same effect as `EnforcedStyle: array`.

**Comment by bbatsov** [comment]
> Another way to go would be to let the cop enforce array literals when there are MinSize words or fewer. Today it allows either syntax in those cases.

Seems to me we should go with the simplest possible option - just add one more style. If people want to use only `[]` we'll ignore the MinSize.
