### ISSUE TITLE
Style/FileName should accept a regex parameter

### ISSUE THREAD

**Issue by lloeki** [bbatsov/rubocop#1545]
Homebrew has formula files with dashes, but otherwise respect the convention, while other projects may have stricter rules than the default. Having a regex parameter available to enforce one's own rules will certainly be useful.

**Comment by ixio** [comment]
Same thing for Style/CommentAnnotation, I don't really like to add a colon in 
# TODO comment about stuff
But in order to just drop the colon from the rule it seems like my only option is to use a rubocop fork. It would be much better if the format was detailed in a regex that I could change in my .rubocop.yml conf file.

**Comment by alexdowad** [comment]
> Having a regex parameter available to enforce one's own rules will certainly be useful.

Are you looking for a "good" regex which must match, or a "bad" regex which must not match?

**Comment by alexdowad** [comment]
> Same thing for Style/CommentAnnotation, I don't really like to add a colon in 
> # TODO comment about stuff

Hmm. If there is enough demand for this, I would code something up, but I doubt that there is. I am inclined to suggest that a custom cop would be your best bet.

Right now we don't have an official, documented API for custom cops, but there will be before long.

**Comment by alexdowad** [comment]
Ping @lloeki.

**Comment by lloeki** [comment]
The "good" one, looking for a match.

**Comment by alexdowad** [comment]
Maintainers, what do you say?

**Comment by jonas054** [comment]
A positive regex for how file names should look sounds good to me.

**Comment by alexdowad** [comment]
Should the regex be applied only to the basename? Or the entire path? Or each component of the path individually?

**Comment by jonas054** [comment]
Only the basename is ok for me. I think that's what we're checking today.

**Comment by alexdowad** [comment]
Do we drop the `.rb` suffix (and other suffixes) before applying the regex?

**Comment by alexdowad** [comment]
I think I know the answer. Opening PR now.
