### ISSUE TITLE
Style/AlignParameters and `system`

### ISSUE THREAD

**Issue by lloeki** [bbatsov/rubocop#1546]
`Style/AlignParameters` wants to change things this way:

```ruby
     system "make", "-C", "ace", "-f", "GNUmakefile.ACE",
                    "INSTALL_PREFIX=#{prefix}",
                    "LDFLAGS=",
                    "DESTDIR=",
                    "INST_DIR=/ace",
                    "debug=0",
                    "shared_libs=1",
                    "static_libs=0",
                    "install"
# into
     system "make",
            "-C", "ace", "-f", "GNUmakefile.ACE",
            "INSTALL_PREFIX=#{prefix}",
            "LDFLAGS=",
            "DESTDIR=",
            "INST_DIR=/ace",
            "debug=0",
            "shared_libs=1",
            "static_libs=0",
            "install"
```

It sounds sensible to have `system` be a special case. It may apply to more methods than `system`. I don't know what the best course of action is (special cop? "smart" enforced style?, "any_parameter"?).

**Comment by bbatsov** [comment]
While I understand your reasoning I don't think we should implement special handling like this for anything. Given the fact that pretty much no Ruby dev env support such indentation in the end you're likely to be its only user. :-)
