### ISSUE TITLE
Updating Wiki for autocorrected cops

### ISSUE THREAD

**Issue by mattjmcnaughton** [bbatsov/rubocop#1548]
I was looking around at what cops still need autocorrection and it looks like the Wiki for tracking this ([here](https://github.com/bbatsov/rubocop/wiki/Automatic-Corrections)) is out of date. I'm more than happy to update it, just wanted to check in first because I'm new to this project. There doesn't seem to be a way to make a wiki pull request where it would be reviewed first, and I didn't want to change things without review. Would updating it be helpful?

**Comment by bbatsov** [comment]
Sure.

**Comment by mattjmcnaughton** [comment]
Sweet! Done!
