### ISSUE TITLE
Taboo word list

### ISSUE THREAD

**Issue by brondavies** [bbatsov/rubocop#1552]
Maybe I haven't seen this in the documentation yet, but I need a cop that can look for specific words as an offence.  This could be old nomenclature, old branding, specific unwanted methods (like save_and_open_screenshot) or foul language.

**Comment by jdickey** [comment]
@brondavies I'd respectfully suggest that that's rather beyond the scope of a "Ruby style guide" or enforcer therefor. Perhaps you'd be better off with a Rake/Thor task (or a Git pre-commit hook) that goes through and `grep`s (changed) files against the contents of a `config/disallowed-words.yml` file?

**Comment by brondavies** [comment]
@jdickey you're right but I think this could also future proof against needing to add cops for deprecated APIs and so forth.

**Comment by bquorning** [comment]
For deprecated APIs etc. where the “taboo words” are method names, you could write a custom cop based on the [`Debugger` cop](https://github.com/bbatsov/rubocop/blob/master/lib/rubocop/cop/lint/debugger.rb).

See https://github.com/bbatsov/rubocop/blob/master/README.md#extensions on how to use custom cops.

**Comment by brondavies** [comment]
OK, I had not seen that little line item in the readme.  Thanks!
