### ISSUE TITLE
Fails with F: Invalid byte sequence In windows if EOL is not UNIX

### ISSUE THREAD

**Issue by rstar111** [bbatsov/rubocop#1560]
**Environment**

OS: Windows 7 x64 Enterprise

ruby -v
ruby 2.0.0p481 (2014-05-08) [i386-mingw32]

rubocop -v
0.28.0

**Problem**

In windows, source file must be UTF-8 w/o BOM and EOL must be UNIX.
Otherwise the only offense found will be:

source_fille.rb:1:1: F: Invalid byte sequence in utf-8.

**Comment by bbatsov** [comment]
I'm not sure I understand the exact nature of your problem. In any case, fatal errors come directly from `parser`. //cc @whitequark

**Comment by whitequark** [comment]
Unless you specify a magic encoding comment (`# encoding: windows-1251`, for example), all text in files, including in comments, must be in UTF-8. This differs from Ruby's behavior somewhat.

**Comment by rstar111** [comment]
Thanks adding the proper encoding comment fixed this for me. I was sure I tired this before. I suppose I must not have spcified the correct encoding charcter set in use.

Thanks
