### ISSUE TITLE
EmptyLinesAroundBlockBody unless top level block

### ISSUE THREAD

**Issue by mockdeep** [bbatsov/rubocop#1568]
When I'm writing specs, I like to leave empty lines around the top level block, much like I would with a class or module, so it would be nice to be able to require empty lines around top level blocks, but require no lines in nested blocks:

```ruby
describe MyClass, '#my_method' do

  it 'does something' do
    expect(MyClass.new.my_method).to do_something
  end

  it 'does something else' do
    expect(MyClass.new.my_method).to do_something_else
  end

end
```

**Comment by jonas054** [comment]
If we are to implement something, I suggest adding a new cop `Style/EmptyLinesAroundTopLevelBlockBody` and letting `Style/EmptyLinesAroundBlockBody` stay away from the top level. It gets messy otherwise.

**Comment by alexdowad** [comment]
> It gets messy otherwise.

Not necessarily. I'm going to open a PR for this one, have a look and see what you think.

**Comment by alexdowad** [comment]
Based on discussion in #2532, it looks like this is not going to happen. Let's close.

**Comment by alexdowad** [comment]
Again, suggest this should be closed.
