### ISSUE TITLE
Several auto-correction/offense disparities in Style/TrivialAccessors

### ISSUE THREAD

**Issue by lumeet** [bbatsov/rubocop#1580]
I've found all of the following usages in a form or another in real code.

```ruby
# encoding: utf-8
# test_trivial_methods.rb
# Auto-correction failing in this class.
class MyTrivialMethods
  def one_value
    @another_value
  end

  def good?
    @good
  end

  def value(value)
    @value = value
  end

  def store_my_block(&block)
    @block = block
  end
end
```
Then...
```shell
$ bin/rubocop --auto-correct -f s test_trivial_methods.rb
== test_trivial_methods.rb ==
C:  5:  3: [Corrected] Use attr_reader to define trivial reader methods.
C:  9:  3: [Corrected] Use attr_reader to define trivial reader methods.
C: 13:  3: [Corrected] Use attr_writer to define trivial writer methods.
C: 17:  3: [Corrected] Use attr_writer to define trivial writer methods.

1 file inspected, 4 offenses detected, 4 offenses corrected
```

...but nothing is actually changed. What do you think should be the correct behavior here? Spontaneously, I find at least methods 2-4 useful in some contexts, and while number 1 doesn't feel like a good idea, there might be reasons to do that, too.

**Comment by glittershark** [comment]
:+1:

**Comment by jonas054** [comment]
@lumeet You can allow all those methods with the following configuration:

```yaml
Style/TrivialAccessors:
  ExactNameMatch: true
  AllowDSLWriters: true
```

The fact that `[Corrected]` is printed when nothing was changed is a bug, though.

**Comment by lumeet** [comment]
Thanks, @jonas054. I'm still forgetting all the configs. Anyway, I can try to fix the bug bit later unless someone else is quick to do it before me.
