### ISSUE TITLE
How do I get from an error (e,g, "Missing Top Level Class Documentation Comment") to the yml setting to control it?

### ISSUE THREAD

**Issue by pitosalas** [bbatsov/rubocop#1582]
I am looking all over default.yml and don't see the setting corresponding, e.g. to that error. Is there an easier way to find the mapping? Thanks!

**Comment by bbatsov** [comment]
Try `rubocop -D`.

**Comment by pitosalas** [comment]
Thanks! And now, I assume when I see this:

hardway/lesson40/ex40_class.rb:6:14: E: unexpected token tCOLON
	attr_reader : tangerine
             ^

38 files inspected, 1 offense detected

This means it’s an outright syntax error and those are always reported, yes?

— Pito

On January 19, 2015 at 3:42:17 PM, Bozhidar Batsov (notifications@github.com) wrote:

Try rubocop -D.

**Comment by jonas054** [comment]
Yes, that's a syntax error. You should get the same from `ruby -wc hardway/lesson40/ex40_class.rb`.
