### ISSUE TITLE
Style/MethodDefParentheses doesn't support middle-ground

### ISSUE THREAD

**Issue by zenspider** [bbatsov/rubocop#1599]
"Seattle Style" says no _extra_ parens. We use parens for any of the "odd" arguments (splats, blocks, etc). Can there be some middle ground setting besides "all on" or "all off"?

**Comment by bbatsov** [comment]
Could you be a bit more specific with some examples? Outside of:

```ruby
def example(a, b, *)
  ...
end
```

I can't think of other scenarios where the parens are strictly required and according to my brief "research" Seattle style says "don't use parens unless required". Guess there might be different interpretations of what Seattle style means, though.

**Comment by zenspider** [comment]
Ya know what? I think I change my mind. :)

I will be filing a new ticket for seattle style call enforcement. Seems like there's NO config for parens on a call?
