### ISSUE TITLE
Style/Blocks poorly named and/or doesn't support other styles

### ISSUE THREAD

**Issue by zenspider** [bbatsov/rubocop#1600]
Style/Blocks is about using `{}` for single-line blocks and `do end` for multi-line blocks. Either it should be renamed to be specifically about that, or it would be nice if it were expanded to be smarter about other styles. I'm thinking specifically about the Weirich method.

**Comment by Koronen** [comment]
Related: bbatsov/ruby-style-guide#162

**Comment by zenspider** [comment]
thanks for the linkage. good commentary over there.
