### ISSUE TITLE
Style/EmptyLinesAroundModuleBody and friends should support mixed style

### ISSUE THREAD

**Issue by zenspider** [bbatsov/rubocop#1603]
Namely, that there should be an empty line after `class/module` start, but not before the end. This helps make rdoc more readable. Eg:

```ruby
class X

  ##
  # doco
  def method
  end
end
```

There's no reason to have an extra line at the end of a module/class in this case. It is only for the rdoc/eyes.

**Comment by Koronen** [comment]
Related: #1568.

**Comment by zenspider** [comment]
related or dupe? you decide.

**Comment by Koronen** [comment]
This issue concerns modules, the one I linked concerns blocks. They belong to the same "family" of cops, but I wouldn't call it a duplicate.

**Comment by zenspider** [comment]
Kk. I'm really not familiar, so I appreciate it.

**Comment by alexdowad** [comment]
@bbatsov commented on this ([link](https://github.com/bbatsov/rubocop/pull/2532#issuecomment-168494546)):

> Hmm, seems to me that the body_start_only is something quite specific (when we factor the rdoc stuff) and it's probably not worth supporting it out-of-the-box.

Therefore, let's close this issue, and reopen (or create a new one) if there is significant demand later.
