### ISSUE TITLE
Style/IndentHash w/ consistent style is buggy?

### ISSUE THREAD

**Issue by zenspider** [bbatsov/rubocop#1608]
Says this isn't indented correctly?

```ruby
    options = {
               :io => $stdout,
              }
```

**Comment by bbatsov** [comment]
Such code is commonly indented as:

```ruby
options = {
  :io => $stdout,
}
```

Our beloved Emacs behaves like this as well. :-)

**Comment by zenspider** [comment]
Our beloved emacs does both.

**Comment by jfelchner** [comment]
:+1: for this style.  I honestly use both depending on the situation (usually a gut feel on what looks better based on the contents of the hash) and dislike rubocop making me unindent the hash in those situations.

**Comment by jawshooah** [comment]
:+1: , and same for arrays. Example in #1609.
