### ISSUE TITLE
Style/ClassMethods gets singleton methods wrong

### ISSUE THREAD

**Issue by zenspider** [bbatsov/rubocop#1610]
```ruby
    UNDEFINED = Object.new # :nodoc:

    def UNDEFINED.inspect # :nodoc:
      "UNDEFINED" # again with the rdoc bugs... :(
    end
```

**Comment by bbatsov** [comment]
Could you elaborate on the nature of the problem? This code should be ignored by `Style/ClassMethods`.

**Comment by zenspider** [comment]
```ruby
Inspecting 14 files
..C...........

Offenses:

lib/minitest/assertions.rb:19:9: C: Use self.inspect instead of UNDEFINED.inspect.
    def UNDEFINED.inspect # :nodoc:
        ^^^^^^^^^
```

**Comment by zenspider** [comment]
Sorry, I should have included the output.

**Comment by bbatsov** [comment]
Ah, I think I get it now. We're currently walking through all static method definitions inside the bodies of classes and modules and check if their names are prefixed with a constant (but we don't care what that constant is as we've assumed it's the class/module name). We should actually check if that constant is the name of the containing class/module.
