### ISSUE TITLE
Prefer Double Quoted Strings by Default

### ISSUE THREAD

**Issue by mattdbridges** [bbatsov/rubocop#1615]
This one always was an annoyance to switch back and forth, but the reasoning made sense to make it explicit.

However, this article did some analysis on speed differences between the two: http://viget.com/extend/just-use-double-quoted-ruby-strings. I suggest we make the default `Style/StringLiterals` to `double_quotes`.

Thoughts?

**Comment by bbatsov** [comment]
See the first few comments of the article. This has been the default since day 1 and I don't really want to change it. In short - the reason why this is the default has nothing to do with performance.

**Comment by juanibiapina** [comment]
What is the reason for this default, if not performance? Style guide recommendation?

Consider this blog post instead: http://anti-pattern.com/always-use-double-quoted-strings-in-ruby

I was about to open a new issue but decided not to.

**Comment by bbatsov** [comment]
Blog posts like this one pop all the time, but there are few absolute truths in Ruby and I don't think this is one of them. I guess one of those days I should write a post on the subject as well. :-)

**Comment by perlun** [comment]
Yes please Bozhidar, looking forward to read it! :smile:

(I also favor the One True string literal style. :wink:)

**Comment by juanibiapina** [comment]
2016 now. Both github and thoughtbot always prefer double quotes.

**Comment by alexdowad** [comment]
This is why RC is configurable.

**Comment by bbatsov** [comment]
This was the case few years back as well. I didn't care back then and I don't care now. I ask people to respect my wishes and just let this matter go. 

@alexdowad said it best - RC is configurable for a reason.
