### ISSUE TITLE
FirstParameterIndentation unindents parenthesized arguments 

### ISSUE THREAD

**Issue by bquorning** [bbatsov/rubocop#1622]
I think I found a bug in `FirstParameterIndentation`.

```rb
x = { a: 1 }

puts x.
  merge(
    b: 2
  )
```

When I run Rubocop with `-a --only FirstParameterIndentation` against the above code, the `special_for_inner_method_call` wants the `b: 2` line indented an extra 3 spaces, while `special_for_inner_method_call_in_parentheses` and `consistent` wants to *unindent* by 2 spaces.

But I think the indentation is correct as it is.

**Comment by jonas054** [comment]
I agree. This is a case that I missed. Working on a solution.
