### ISSUE TITLE
[Question] Override default severity

### ISSUE THREAD

**Issue by revett** [bbatsov/rubocop#1624]
> Asked this on **IRC** but it isn't very active at the moment.

By **default** all cops have a severity of `convention` - how do I override this to be `warning` for example?

**Comment by jonas054** [comment]
You'll find it on the [README](https://github.com/bbatsov/rubocop#severity) page.

`Lint` cops have a default severity of `warning` by the way.

**Comment by revett** [comment]
Yep have read that - it gives an example of overriding a single cop (see below), how do I override **all** cops? Do I have to do it one by one?

```yaml
Metrics/CyclomaticComplexity:
  Severity: warning
```

**Comment by jonas054** [comment]
There's no way to change the default severity for all or a group of cops in one place, you would have to override the severity for each cop one by one. But I'm curious about why you would want to. Can you explain the use case? What is it you want to achieve?

**Comment by revett** [comment]
Ah okay. I need to make the severity levels consistent to the needs of my team - is there a list of the default severity levels for each type of cop (e.g. `Lint`, `Metric`)?

**Comment by jonas054** [comment]
It's not described in the documentation, but `Lint` cops have `warning` as default and all other cops (that's `Metrics`, `Rails`, and `Style`) have `convention`.

**Comment by revett** [comment]
Cool thanks - worthwhile adding to the [#Severity](https://github.com/bbatsov/rubocop#severity) section of the REAME?
