### ISSUE TITLE
Powerpack dependency

### ISSUE THREAD

**Issue by jspanjers** [bbatsov/rubocop#1632]
Hi

I notice that rubocop has a dependency on powerpack 0.0.
Now that you have released powerpack 0.1.0, 
rubocop still only uses versions from the 0.0 series.

It seems to me powerpack uses semantic versioning. Is this true?

If this is the case, should we change the rubocop dependency 
from:
s.add_runtime_dependency('powerpack', '~> 0.0.6')
to:
s.add_runtime_dependency('powerpack', '~> 0.0')

?

**Comment by bbatsov** [comment]
> It seems to me powerpack uses semantic versioning. Is this true?

Not really. There are no breaking changes between 0.0.6 and 0.1.0. I just wanted to be able to use the minor version to denote new features and the patchlevel for bugfixes. The project will adopt semver after it reaches version 1.0.

**Comment by bbatsov** [comment]
I've updated the dep.
