### ISSUE TITLE
FirstParameterIndentation in interpolated string works strangely

### ISSUE THREAD

**Issue by bquorning** [bbatsov/rubocop#1638]
```rb
puts %(
  <p>
    #{Array(
      42
    )}
  </p>
)
```

Running `bin/rubocop --only Style/FirstParameterIndentation` on the above code, I am told to properly indent the line containing `42`.

The strange thing here is that the recommended position seems to be 2 spaces more than *the position of `<p>`*. I would assume the indentation of the un-interpolated parts of the string would have no influence on the indentation recommendation of the interpolated parts.

From my testing, it seems that this bug only presents itself when the interpolated string contains a method call with its argument(s) on a new line(s).

**Comment by jonas054** [comment]
It's the old regexp matching trap. `    #{Array(` is mistaken for a comment line. I'll have it fixed soon.
