### ISSUE TITLE
Rubocop localization

### ISSUE THREAD

**Issue by arbox** [bbatsov/rubocop#1650]
Hi!

We have a lot of useful translations for the Ruby and Rails style guides. Why not localyze Rubocop messages as well? Should we work on that?

**Comment by bbatsov** [comment]
That'd be too much work which will likely end up mostly unused. I don't recall a single lint tool which is localized.

**Comment by petRUShka** [comment]
That can be useful. There are localized Style Guides and it is make sense to have localized rubocop output. E.g. in teaching purposes.
