### ISSUE TITLE
Style/FirstParameterIndentation is making me sad :-(

### ISSUE THREAD

**Issue by tmornini** [bbatsov/rubocop#1667]
As always, thank you very much for rubocop, love it to death!

Just upgraded to 0.29.1 and started receiving messages from Style/FirstParameterIndentation.

On code like this (shorted for anonymity)...

```
a = send_request(
      b,
      c,
      d)
```

rubocop would prefer

```
a = send_request(
  b,
  c,
  d)
```

And I'm having a really hard time believing anyone would see this as an improvement, as the indentation recommended serves zero purpose and does not help indicate which method is receiving the parameters.

Would it be possible to implement a new SupportedStyle, perhaps ```relative_to_method_name```?

**Comment by bbatsov** [comment]
> And I'm having a really hard time believing anyone would see this as an improvement, as the indentation recommended serves zero purpose and does not help indicate which method is receiving the parameters.

This is an extremely popular style, although it's generally used like this:

```
a = send_request(
  b,
  c,
  d
)
```

Is there any tool that would actually indent the code as you're suggesting? The other problem with what you're suggesting is that it can potentially introduce a huge indentation for arguments in case like:

```
a = ala.bala.portokala.tralala.send_request(
                                                 b,
                                                 c,
                                                 d)
```

**Comment by tmornini** [comment]
> Is there any tool that would actually indent the code as you're suggesting?

Well, I'd prefer not to call myself a tool! :-)

> The other problem with what you're suggesting is that it can potentially introduce a huge indentation

Ah, right, but that's not where I'd indent it.

```
a = ala.bala.portokala.tralala.send_request(
      b,
      c,
      d
    )
```

**Comment by bbatsov** [comment]
> Well, I'd prefer not to call myself a tool! :-)

Btw, I'm fond of this indentation scheme:

```
a = 
  ala.bala.portokala.tralala.send_request(
      b,
      c,
      d
    )
```

Editor-friendly middle ground.

> Would it be possible to implement a new SupportedStyle, perhaps relative_to_method_name?

Guess we can add one, but it won't be before @jonas054 is back from his vacation. My workload is crazy these days and I won't be able to address this soon.

**Comment by tmornini** [comment]
```
a = 
  ala.bala.portokala.tralala.send_request(
      b,
      c,
      d
    )
```

Oh, that's interesting, but shouldn't that be:

```
a = 
  ala.bala.portokala.tralala.send_request(
    b,
    c,
    d
  )
```

If the second makes rubocop happy, I'm in. :-)

**Comment by bbatsov** [comment]
Yes, it should be as you wrote. For some reason Github messes up the original indentation.

And yes - RuboCop will happily accept this style. :-)

**Comment by tmornini** [comment]
OK, that works for me, closing this ticket.
