### ISSUE TITLE
Default `Style/TrivialAccessors` to match names exactly

### ISSUE THREAD

**Issue by marxarelli** [bbatsov/rubocop#1673]
The default behavior of `Style/TrivialAccessors` is quite a bit more strict than the [style guide rule](https://github.com/bbatsov/ruby-style-guide/blob/04d1e8012d0bcd08a53e93b92275316ef8b629eb/README.md#attr_family). I suggest defaulting `ExactNameMatch` to `true` to improve the rule's style guide congruency.

**Comment by bbatsov** [comment]
> The default behavior of Style/TrivialAccessors is quite a bit more strict than the style guide rule. I suggest defaulting ExactNameMatch to true to improve the rule's style guide congruency.

On the other hand the current default reveals "hidden" accessors, which is not a bad thing IMO.
