### ISSUE TITLE
Inconsistent indentation for a begin ... end block

### ISSUE THREAD

**Issue by matthewford** [bbatsov/rubocop#1674]
Hello, I'm getting an error with the following code

```
begin :associations
  belongs_to :account
  has_many :things
end
```

```
Offenses:

test.rb:2:3: C: Inconsistent indentation detected.
  belongs_to :account
  ^^^^^^^^^^^^^^^^^^^
test.rb:3:3: C: Inconsistent indentation detected.
  has_many :things
  ^^^^^^^^^^^^^^^^

1 file inspected, 2 offenses detected
```

It seems to not detect the begin/end block

**Comment by bbatsov** [comment]
```
begin :associations
  belongs_to :account
  has_many :things
end
```

There's some symbol after `begin`, which seems pretty odd to me.

**Comment by matthewford** [comment]
It is somewhat unusual, we use it for code folding as being/end blocks are recognised by most editors, and the symbol is just used for naming the block, it kind of doesn't do anything.

**Comment by bbatsov** [comment]
Btw, your example unveiled a bug in the `Void` check and in the latest RuboCop version you'll also start getting a warning about a symbol literal used in void context. 

I understand your reasoning, but as this use-case is highly unidiomatic it doesn't make sense to add support for it in RuboCop.

**Comment by matthewford** [comment]
:) 

Well I'm happy to close this issue as I know it's not idiomatic
