### ISSUE TITLE
Incorrect handling of multiline blocks in the middle of the method

### ISSUE THREAD

**Issue by andrusha** [bbatsov/rubocop#1676]
`0.29.1 (using Parser 2.2.0.3, running on ruby 2.1.5 x86_64-darwin14.0)`
`ruby 2.1.5p273 (2014-11-13 revision 48405) [x86_64-darwin14.0]`

Happens in Rails 4-style association definition

```diff
-  has_many :kittens, -> {
+  has_many :kittens, lambda do
     where(cats: Cat.young.where_values_hash)
-  }, source: :cats, class_name: 'Cat'
+  end, source: :cats, class_name: 'Cat'
```

Causes `SyntaxError`:

```
.../2.1.0/gems/activesupport-4.1.1/lib/active_support/dependencies.rb:247:in `require': ../Projects/catbook/app/models/master.rb:11: syntax error, unexpected ',', expecting keyword_end (SyntaxError)
  end, source: :cats, class_name: 'Cat'
      ^
```

**Comment by jonas054** [comment]
It looks like you have run `rubocop --autocorrect` to get the above syntax error. Then we have a bug in the `Lambda` cop that I think can be fixed by using the `AutocorrectUnlessChangingAST` module.
