### ISSUE TITLE
Allow content piped to binary?

### ISSUE THREAD

**Issue by jfelchner** [bbatsov/rubocop#1682]
I'd actually really like to be able to run `rubocop -a` on my files as I'm working with them.  In vim, any filetype can have a format program associated with it as well as have its contents (or a visual selection) run through an external program which will then replace the selection/buffer with the result.

Has there been any talk or potential plans for allowing rubocop to do something like this?

```sh
cat some/ruby/file.rb | rubocop -a
```

This would allow me to do something like:

```vim
nnoremap <leader>rp :% !rubocop -a
```

**Comment by jfelchner** [comment]
The above is actually a bad example because you can do it another way, but the format program must be something that can read from STDIN.

**Comment by bbatsov** [comment]
It will probably involve a lot of work, as we're making assumptions that the code is backed by files all over the place. I've written a simple Emacs plugin that runs autocorrect on the file you're currently editing, so I guess the same approach can be used with vim.

The idea is not bad, but the efforts to implement it might not be worth it.

**Comment by jfelchner** [comment]
@bbatsov agreed!  I can make due with what I have.  I think efforts are better spent elsewhere.  Gracias!
