### ISSUE TITLE
Style/TrivialAccessors tells me to perform the impossible there is a variable/method name mismatch

### ISSUE THREAD

**Issue by drbrain** [bbatsov/rubocop#1683]
From #1605:

```
  def name
      @NAME
    end

    def name= o
      @NAME = o
    end
Gives me:

lib/minitest.rb:245:5: C: Style/TrivialAccessors: Use attr_reader to define trivial reader methods.
    def name
    ^^^
lib/minitest.rb:252:5: C: Style/TrivialAccessors: Use attr_writer to define trivial writer methods.
    def name= o
    ^^^
```

It is not possible to replace such a method with attr_reader or attr_writer, so why is rubocop complaining at me?  Shouldn't the default be reversed (require an exact name match)?

**Comment by drbrain** [comment]
See also #1653, #308, #408.

**Comment by bbatsov** [comment]
Guess you saw my rationale behind that default - exposing "hidden" attributes. That said, I might change the default just to stop getting these recurring issue reports. :-)
