### ISSUE TITLE
hash symbol key incorrectly converted to string

### ISSUE THREAD

**Issue by EdvardM** [bbatsov/rubocop#1684]
This is a rare case I assume, but in a certain app we have all hash keys as symbols. However, one particular key may contain spaces, so we have to represent that key as string, which is then turned into symbol. An example:

`{ ... :"custom column" => 42 }`

Rubocop transforms this to

`{ ... "custom column": 42 }`

which breaks the code. I wonder would be the proper solution: could it be just assumed that if form :"" is used, it's explicitly made so and should be preserved?

**Comment by bbatsov** [comment]
I'm having trouble reproducing this on the current `master`. Can you check if the problem is present there? If so - add more detailed steps on how to reproduce it.

**Comment by EdvardM** [comment]
Sure. And thanks for checking this issue, it's the only thing that's wrong with auto-correct in our current projects. Code follows:

<pre>
$ cat test.rb
h = { :"foo" => 1 }
puts h

$ rubocop -a test.rb
Inspecting 1 file
C

Offenses:

test.rb:1:7: C: [Corrected] Use the new Ruby 1.9 hash syntax.
h = { :"foo" => 1 }
      ^^^^^^^^^

1 file inspected, 1 offense detected, 1 offense corrected

$ cat test.rb
h = { "foo": 1 }
puts h

$ cat .rubocop.yml
Lint/AssignmentInCondition:
  AllowSafeAssignment: true

Style/EmptyElse:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/TrivialAccessors:
  AllowPredicates: true

Style/GlobalVars:
  AllowedVariables: [$logger]

Style/GuardClause:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/CaseEquality:
  Enabled: true

Metrics/LineLength:
  Enabled: true
  AllowURI: true
  Max: 100

Metrics/MethodLength:
  Max: 16

Metrics/AbcSize:
  Max: 45

Metrics/CyclomaticComplexity:
  Max: 12

Style/SignalException:
  Enabled: false

AllCops:
  Include:
    - '**/config.ru'
  Exclude:
    - 'lib/templates/**/*'
    - 'db/**/*'
    - 'script/**/*'
    - 'bin/**/*'
    - 'config/**/*'
</pre>

**Comment by bbatsov** [comment]
With the extra info I located and eradicated the bug. :-)

**Comment by EdvardM** [comment]
Ah, dem regexes :) Always write-only they are. Thank you!

**Comment by bbatsov** [comment]
Actually the problem wasn't in the regexp, but in the fact that the parser normalizes string names and strips their quotes when their are not needed.
