### ISSUE TITLE
Question mark reader method

### ISSUE THREAD

**Issue by Mehonoshin** [bbatsov/rubocop#1686]
Hi folks!

I've used search, but probably didn't find any similar issue.

I have the following method:

```
@load_all = true

def load_all?
  @load_all
end
```

Rubocop tells me: "Use attr_reader to define trivial reader methods."
But method with question mark is more semantically correct.

What is better way to handle such situation?
Maybe I'm missing come Rubocop configuration option?

**Comment by bbatsov** [comment]
See https://github.com/bbatsov/rubocop/issues/1683
