### ISSUE TITLE
Cop that detects inclusion of the debugger

### ISSUE THREAD

**Issue by anatolydwnld** [bbatsov/rubocop#1689]
Some code configurations require that you add `require 'byebug'` to use debugger calls. It would be nice if the debugger cop detected these lines and complained. Leaving the `requires` is noisy and dangerous. 

I will be glad to provide a patch once I get some time, unless someone has any objections.

**Comment by bbatsov** [comment]
Yeah, we can definite have a cop looking for a list of requires. There are some things to consider though:

* what do you do in case of the presence of some auto-loading mechanism (e.g. in Rails)? There debugging libs can be loaded without being required. Guess nothing...

* what do you do for conditional requires (requires that are not top-level)?

* in many gems all used libs are required in a source file loaded early on, which would make checking all the other file in the project an overkill, as there will be no requires there at all. Ruby's file loading policy doesn't exactly promote having granular requires within your sources files.
