### ISSUE TITLE
Add per file todos

### ISSUE THREAD

**Issue by steakunderscore** [bbatsov/rubocop#1696]
Currently the `--auto-gen-config` flag generates a todo list of cops which are violated somewhere in the whole project. This todo list disables cops for the whole repo, even if the cop has been violated in a single place.

When new code is being written, there is nothing stopping the same cop being broken, and running `rubocop` does not help with picking up on the issues in the newly written code.

Ideally, the generated todo list would be generated in such a way, that each new violation would be reported to the user. However an intermediate step would be to disable the cop on a per file basis. This would mean that new code would have to adhear to the rules set out only in `.rubocop.yml`.

**Comment by steakunderscore** [comment]
[My patch](1697) probably needs tidying up a little, but I wanted to push it up for review to make sure that I am on the right track. What do you people think? Good idea?

**Comment by bbatsov** [comment]
Probably there should be some config for this - for many offending files it might be a better idea to disable a cop globally.

**Comment by jonas054** [comment]
Looks like this is mostly the same as #1531, a pull request that I've made but haven't followed up on.

**Comment by steakunderscore** [comment]
This does look the same as #1531, this ticket should be closed in favour of #1531.
