### ISSUE TITLE
Suspect false alert

### ISSUE THREAD

**Issue by technion** [bbatsov/rubocop#1698]
Hi,

I'm seeing this warning:

    cadump.rb:8:3: C: Use next to skip iteration.
    f.each_line do |line|

On this code:
https://github.com/technion/cadump/blob/master/cadump.rb

As far as anything I can read anywhere - the line is correct. Changing it to "next" results in broken code.

Version:
$ rubocop -V
0.29.1 (using Parser 2.2.0.3, running on ruby 2.2.0 x86_64-linux)

**Comment by jonas054** [comment]
The `Style/Next` cop highlights the call to the method that does the iteration and not the line it wants you to change. I guess this can be confusing. In this case it wants you to change `if line.match(/Exponent: 3 /)` on line 14 to `next unless line.match(/Exponent: 3 /)`.

**Comment by technion** [comment]
Many thanks, that explains it.
