### ISSUE TITLE
FirstParameterIndentation gives a somewhat uninformative message

### ISSUE THREAD

**Issue by agrimm** [bbatsov/rubocop#1708]
The following code

    RSpec.describe Foo do
      it "can bar" do
        foo = Foo.new
        # Not correct
        expect(foo.bar).to eq(
                             "First line\n" \
                             )
        # Correct
        expect(foo.bar).to eq(
          "First line\n" \
                             )
      end
    end

gives me

    spec/foo_spec.rb:6:26: C: Indent the first parameter one step more than the previous line.
                             "First line\n" \
                             ^^^^^^^^^^^^^^

As far as I can tell, RuboCop is working as intended when it complains about the "Not correct" version, but the message is somewhat uninformative. Indent the parameter compared to what in the previous line? I assumed it was compared to the `eq` method name, not the `expect` method name.

Maybe you could indicate the column number expected versus the column number in the actual code, or highlight what in the previous line was being looked at.

**Comment by oliverbarnes** [comment]
+1

**Comment by daniel-johnson** [comment]
+1
