### ISSUE TITLE
"force TTY" command line option

### ISSUE THREAD

**Issue by aishek** [bbatsov/rubocop#1725]
I'd like colorized output in Gitlab CI, but there "TTY only" color output in Rubocop. Maybe it'll be great to have "force TTY" command line option? What do you think?

**Comment by tknerr** [comment]
+1

**Comment by tknerr** [comment]
...and `--force-color` should explicitly set `Rainbow.enabled = true` to override whatever [rainbow.rb](https://github.com/sickill/rainbow/blob/master/lib/rainbow.rb) tries to auto-detect

**Comment by arantir** [comment]
:+1:
