### ISSUE TITLE
Crash while trying to run 'rubocop' on 'rubocop' project

### ISSUE THREAD

**Issue by ShockwaveNN** [bbatsov/rubocop#1726]
I cloned this repository on my computer, and tried to run rubocop command from root of repository and I get an error:
```
user@comp:~/rubocop$ rubocop
/home/user/.rvm/gems/ruby-2.1.5/gems/rubocop-0.29.1/lib/rubocop/formatter/disabled_config_formatter.rb:10:in `<class:DisabledConfigFormatter>': uninitialized constant RuboCop::Formatter::DisabledConfigFormatter::Version (NameError)
        from /home/user/.rvm/gems/ruby-2.1.5/gems/rubocop-0.29.1/lib/rubocop/formatter/disabled_config_formatter.rb:7:in `<module:Formatter>'
        from /home/user/.rvm/gems/ruby-2.1.5/gems/rubocop-0.29.1/lib/rubocop/formatter/disabled_config_formatter.rb:4:in `<module:RuboCop>'
        from /home/user/.rvm/gems/ruby-2.1.5/gems/rubocop-0.29.1/lib/rubocop/formatter/disabled_config_formatter.rb:3:in `<top (required)>'
        from /home/user/.rvm/rubies/ruby-2.1.5/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /home/user/.rvm/rubies/ruby-2.1.5/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /home/user/.rvm/gems/ruby-2.1.5/gems/rubocop-0.29.1/lib/rubocop.rb:279:in `<top (required)>'
        from /home/user/.rvm/rubies/ruby-2.1.5/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /home/user/.rvm/rubies/ruby-2.1.5/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /home/user/.rvm/gems/ruby-2.1.5/gems/rubocop-0.29.1/bin/rubocop:6:in `<top (required)>'
        from /home/user/.rvm/gems/ruby-2.1.5/bin/rubocop:23:in `load'
        from /home/user/.rvm/gems/ruby-2.1.5/bin/rubocop:23:in `<main>'
        from /home/user/.rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in `eval'
        from /home/user/.rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in `<main>'
```

If I go up by one directory and run
```
user@comp:~/$ rubocop rubocop/
```
it's correctly start to check files for offenses

I'm using rubocop:
```0.29.1 (using Parser 2.2.0.3, running on ruby 2.1.5 x86_64-linux)```

**Comment by steakunderscore** [comment]
I am struggling to reproduce this. I have tried to use both tag: v0.29.1 and HEAD on master. Any further steps to reproduce? I take it you haven't changed the code at all?

**Comment by ShockwaveNN** [comment]
I'm sorry, problem didn't repoduces on latest version, I cloned old repository with latest version 0.15

**Comment by ShockwaveNN** [comment]
Hm, on other hand - if rubocop failed to check some code (even it it's own code, but pretty old) - it may be a bug?

**Comment by jonas054** [comment]
Sorry, I didn't read the whole conversation. Yes, that should be investigated.

**Comment by ShockwaveNN** [comment]
@jonas054 No proble, that idea come to mind after you closed this issue :)

So to reproduce bug:
```
user@comp:~/rubocop$ git checkout tags/v0.18.0
user@comp:~/rubocop$ rubocop
/home/user/.rvm/gems/ruby-2.1.5/gems/rubocop-0.29.1/lib/rubocop/formatter/disabled_config_formatter.rb:10:in `<class:DisabledConfigFormatter>': uninitialized constant RuboCop::Formatter::DisabledConfigFormatter::Version (NameError)
        from /home/user/.rvm/gems/ruby-2.1.5/gems/rubocop-0.29.1/lib/rubocop/formatter/disabled_config_formatter.rb:7:in `<module:Formatter>'
        from /home/user/.rvm/gems/ruby-2.1.5/gems/rubocop-0.29.1/lib/rubocop/formatter/disabled_config_formatter.rb:4:in `<module:RuboCop>'
        from /home/user/.rvm/gems/ruby-2.1.5/gems/rubocop-0.29.1/lib/rubocop/formatter/disabled_config_formatter.rb:3:in `<top (required)>'
        from /home/user/.rvm/rubies/ruby-2.1.5/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /home/user/.rvm/rubies/ruby-2.1.5/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /home/user/.rvm/gems/ruby-2.1.5/gems/rubocop-0.29.1/lib/rubocop.rb:279:in `<top (required)>'
        from /home/user/.rvm/rubies/ruby-2.1.5/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /home/user/.rvm/rubies/ruby-2.1.5/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /home/user/.rvm/gems/ruby-2.1.5/gems/rubocop-0.29.1/bin/rubocop:6:in `<top (required)>'
        from /home/user/.rvm/gems/ruby-2.1.5/bin/rubocop:23:in `load'
        from /home/user/.rvm/gems/ruby-2.1.5/bin/rubocop:23:in `<main>'
        from /home/user/.rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in `eval'
        from /home/user/.rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in `<main>'

**Comment by mattjmcnaughton** [comment]
Not sure if this is helpful, but it looks like the enclosing module for version is `Rubocop::Version`, while DisabledConfigFormatter is within the module `RuboCop`. So I'm thinking it has something to do with the difference in capitalization. I'm still not totally sure where this difference in naming is coming from though.

**Comment by jonas054** [comment]
@mattjmcnaughton Wrote in this issue
> Not sure if this is helpful, but it looks like the enclosing module for version is `Rubocop::Version`, while `DisabledConfigFormatter` is within the module `RuboCop`. So I'm thinking it has something to do with the difference in capitalization. I'm still not totally sure where this difference in naming is coming from though.

This comment seems to be lost now. Anyway, it's a good clue. It turns out that when you execute the gem installation of `rubocop` while standing in a `rubocop` project directory root, some strange things happen. The `Gemfile` in the current directory is read and executed as part of the running of `rubocop`. This is where `lib/rubocop/version.rb` is loaded, and because the namespace in `v0.18.0` was `Rubocop`, not `RuboCop`, we get the above problem.

This is all very strange to me. Why is `Gemfile` loaded? Why is the current directory in `$LOAD_PATH`? Maybe this is a bug in `rubygems` or `bundler`. I don't think it's something that we should solve within RuboCop.
