### ISSUE TITLE
if - else turned into wrong code with -a option

### ISSUE THREAD

**Issue by mohamed-mahmoud** [bbatsov/rubocop#1751]
i run
 rubcop -a 
and one of the results for if else turned like this:
    
    def hc_last_error
     errs = cc_errors()
     if errs[0]
       errs[0].sf_message
     else
       nil
     end
    end

    def hc_last_error
      errs = cc_errors
      if errs[0]
        errs[0].sf_messag e
        els e
        ni l
     end
    end

Notice els e  and ni l

**Comment by bbatsov** [comment]
RuboCop version info?

**Comment by mohamed-mahmoud** [comment]
rubocop (0.29.1)

**Comment by jonas054** [comment]
@mohamed-mahmoud With an inspected file containing only your example code, and with default configuration, I have not been able to reproduce the error. Can you provide the output from `rubocop -a` as well? And check if you get the problem with nothing else than the above code in the file.
