### ISSUE TITLE
Modifying default configuration in config/rubocop.rb is unclear

### ISSUE THREAD

**Issue by bf4** [bbatsov/rubocop#1774]
I want to specify `config/rubocop.rb` in my `.rubocop.yml` files, and in that ruby file, use a gem I own to load in configs, but I haven't been able to figure out or get working how to do this via the config loader.  I've looked through the rspec cop code, but have no working solution.

Pseudo code in my `config/rubocop.rb` (adapted from https://github.com/nevir/rubocop-rspec/blob/605caf1480215b185d36fd0c345869554924d896/lib/rubocop/rspec/inject.rb )

```ruby
require "mygem/rubocop"
mygem_rubocop_config = MyGem.rubocop_config
config = ConfigLoader.merge_with_default(mygem_rubocop_config.hash, mygem_rubocop_config.path)
ConfigLoader.instance_variable_set(:@default_configuration, config)
```

but there's no way I see how to do that right now.  I'm happy to make  a PR to update the docs (or even code) if you can help me figure this out.

Up until now, I've had an inherited file in every repo, but that's getting hard to maintain.

**Comment by jonas054** [comment]
I think I understand what you want. You want to use RubyGems to handle versioning and dependencies towards common configuration. And for that you need to involve a Ruby file. It's can't all be YAML.

I've done an experiment [here](https://github.com/bbatsov/rubocop/commit/9f6fc195be724f4e6195269a6fc1f1c53b2f4fce), that takes from your idea and goes in a slightly different direction. See what you think.

**Comment by bf4** [comment]
@jonas054 pretty much, though I was doing

```yaml
require: "config/rubocop.rb"
```

**Comment by alexdowad** [comment]
Can't you use `inherit_gem`?

**Comment by alexdowad** [comment]
Maintainers, I believe this can be closed, as `inherit_gem` can be used to load config from a gem.
