### ISSUE TITLE
Why isn't there a Metrics/ModuleLength cop?

### ISSUE THREAD

**Issue by sdeframond** [bbatsov/rubocop#1779]
There are both ClassLength and MethodLength but no ModuleLength.

What is the rational behind this? Am I the only one to stumble upon modules too fat for their own good?

**Comment by jonas054** [comment]
I don't think there's any specific reason. We just haven't gotten around to do it.

**Comment by sdeframond** [comment]
Is there any development going on about this? Would you consider this feature for merging?

**Comment by bbatsov** [comment]
> Is there any development going on about this?

Not to my knowledge.

> Would you consider this feature for merging?

Yes.
