### ISSUE TITLE
Cop to require parens on method calls that pass arguments?

### ISSUE THREAD

**Issue by tmornini** [bbatsov/rubocop#1786]
I'm on a project where the lead is stickler for parens on method calls with arguments.

Any chance of adding a cop for this?

**Comment by bbatsov** [comment]
Even methods like `attr_reader`, etc? We tried adding a cop like this in the past, but most people don't use parens in certain DSL methods and it's impossible to differentiate those reliably from "regular" methods.

**Comment by tmornini** [comment]
@bbatsov Ah, makes total sense, thanks.

**Comment by aripollak** [comment]
I'd also love to have a cop like this. What if it ignored method calls that took place outside of a method definition, like how `attr_reader` and Rails DSL methods usually are? Or at the very least, enforce full parens on the RHS of assignment?
