### ISSUE TITLE
Performance/Sample cop incorrectly autocorrects `#shuffle[0, 3]`

### ISSUE THREAD

**Issue by tindron** [bbatsov/rubocop#1792]
`#shuffle[0, 3]` is autocorrected to `#sample` instead of `#sample(3)`.

**Comment by bbatsov** [comment]
//cc @rrosenblum

**Comment by rrosenblum** [comment]
Sorry about that. I didn't realize that `shuffle` could take in multiple arguments. I don't think this will be difficult to fix.

**Comment by rrosenblum** [comment]
...On closer look, that isn't multiple arguments, it is an array selector on the end of `shuffle`. This can still be accounted for.

**Comment by rrosenblum** [comment]
I have found a fix for `#shuffle[0, 3]`. I have been stuck on trying to fix `shuffle(random: Random.new(1))`. My big pain right now is that issue with `random` is causing me to have to rewrite the entire cop. Parsing of the `node` for `#shuffle[0, 3]` produces completely different results than `shuffle(random: Random.new(1))`.
