### ISSUE TITLE
Performance/Detect Cop Breaks ActiveRecord select.first

### ISSUE THREAD

**Issue by brentmurphy** [bbatsov/rubocop#1798]
Hi,

I recently ran rubocop against a repo and the Performance/Detect cop attempts to make a breaking change to an ActiveRecord select statement.

```
def find_by_oauth_id(oauth_id)
-   by_oauth_id(oauth_id).select(quoted_table_name + '.*').first
+  by_oauth_id(oauth_id).find(quoted_table_name + '.*')
end
```

I've disabled the cop with a comment in that case, but wondered whether that cop might be a bit too eager.

**Comment by bbatsov** [comment]
This is fixed on `master`.

**Comment by brentmurphy** [comment]
Great, thanks.
