### ISSUE TITLE
Cop suggestion: prefer Array#find

### ISSUE THREAD

**Issue by SebastianEdwards** [bbatsov/rubocop#1799]
Cop could suggest `Array#find` over any instances where Array#select or Array#filter is chained with an Array#first

**Comment by bquorning** [comment]
Take a look at the `Performance/Detect` cop that was added in [v0.30.0](https://github.com/bbatsov/rubocop/releases/tag/v0.30.0). It will detect at least the `Array#select ... #first` form.

**Comment by SebastianEdwards** [comment]
Right you are. Closing this issue.
