### ISSUE TITLE
Check indentation by tab-stops

### ISSUE THREAD

**Issue by printercu** [bbatsov/rubocop#1800]
Hi!

Can't find if it's possible to restrict indentation only to tab-stops. Is it possible to perform checks now?

eg, for 2-spaces tab-stops:
```ruby
# bad:
# | | | | | | | tab-stops
call :arg1,
     :arg2
# good:
# | | | | | | | tab-stops
call  :arg1,
      :arg2
```

**Comment by jonas054** [comment]
No, that's not supported.

**Comment by bbatsov** [comment]
This is a pretty uncommon style and we have no plans to support it.
