### ISSUE TITLE
Add a cop that enforces call instance method setters instead of setting instance variables directly

### ISSUE THREAD

**Issue by jeremyf** [bbatsov/rubocop#1813]
Below is what I've been spitballing. This is a cop that might start out 'Enabled' == false.

```ruby
# encoding: utf-8

require 'spec_helper'

describe RuboCop::Cop::Style::InitializeSetsInstanceVariables, :config do
  subject(:cop) { described_class.new(config) }
  let(:cop_config) { { 'Enabled' => true } }

  it 'will police the initialize method for setting of ivars' do
    inspect_source(cop,
                   [' def initialize(value)',
                    '   @value = value',
                    ' end'])
    expect(cop.offenses).to_not be_empty
  end

  it 'will police the initialize method for setting of ivars' do
    inspect_source(cop,
                   [' def initialize(value, value2)',
                    '   self.value = value',
                    '   @value2 = value2',
                    ' end'])
    expect(cop.offenses).to_not be_empty
  end
end
```

**Comment by jdickey** [comment]
What about ivars that have `attr_readers` defined but no writers? I *very* common idiom is to have `#initialize` be the sole method in the class that assigns to an ivar, which is read pervasively throughout the code. To do its job properly (IMO), your cop would have to check that the ivar in question is writeable from `#initialize`, through either a public or private method (or `attr_writer`/`attr_accessor`).

**Comment by jeremyf** [comment]
@jdickey Your assessment makes sense and would be the ideal form of the cop. However, I'm willing to live with the approximation of "Don't set instance variables directly in the initialize method."

I also understand that this cop is perhaps not something that makes sense in rubocop but as a plugin that could be included for those looking for similar behavior.

I have the first example working but have not delved into the second example.

**Comment by alexdowad** [comment]
> I also understand that this cop is perhaps not something that makes sense in rubocop but as a plugin

I agree with that. Hopefully before long we will have some documentation on how to extend RC and make "plugins". In the meantime, I suggest this should be closed.
