### ISSUE TITLE
add white list for NamePrefixBlacklist

### ISSUE THREAD

**Issue by Hanmac** [bbatsov/rubocop#1825]
i found after running rubocop on some of my gist files that it does have problems with defining "is_a?"
https://gist.github.com/Hanmac/4619845

```ruby
  def is_a?(klass)
    super || __getobj__.is_a?(klass)
  end
```

**Comment by bbatsov** [comment]
Yeah, this makes sense. Something like this would be useful for `AccessorMethodName` as well.

**Comment by alexdowad** [comment]
Just opening a PR with `NameWhitelist`. @bbatsov, I can add the same for `AccessorMethodName`... but what will be on the default whitelist??

**Comment by Hanmac** [comment]
i don't know if its possible but i think there should be a whitelist check for all methods which are defined in parent classes/modules in case of overloading/overwriting of them (and the should be already reported in the parent class if they are part of the project too)

**Comment by alexdowad** [comment]
Hmm, interesting idea. @bbatsov @jonas054 @rrosenblum What do you think of automatically whitelisting predicate methods which are known to exist in a parent class/module?

**Comment by bbatsov** [comment]
> What do you think of automatically whitelisting predicate methods which are known to exist in a parent class/module?

This will be extremely hard to track down with our current approach which doesn't keep track of any file state. After all, the parent classes will likely be in other files.

**Comment by bbatsov** [comment]
> I can add the same for AccessorMethodName... but what will be on the default whitelist??

It can be just empty. I have the feeling many people would put `get_` there. Anyways, I won't lose any sleep if we don't add this to RuboCop.
