### ISSUE TITLE
Erronous `Use sample instead of shuffle.each`

### ISSUE THREAD

**Issue by terlar** [bbatsov/rubocop#1826]
I have some code that does the following:

```ruby
queue = Queue.new
tests.shuffle.each do |test|
  queue.push test
end
```

And rubocop complains and says: `Use sample instead of shuffle.each`. I am wondering how sample could replace shuffle in this case or if this is an error in the parser?

**Comment by terlar** [comment]
Might be that this is fixed on master, I was running the version `0.30.1`.

**Comment by rrosenblum** [comment]
Yes, this is a bug that was introduced in version `0.30.1`. The bug has been fixed in `master`, but it has not made it to a release yet. If you are interested in more information about the bug, take a look at issue #1816 and pull request #1817.

Thank you for taking the time to file the bug.

**Comment by terlar** [comment]
Thank you for your information. I just realized after I posted this when I checked the recent commits.
