### ISSUE TITLE
Problems with AutoCorrect configuration parameter

### ISSUE THREAD

**Issue by jonas054** [bbatsov/rubocop#1834]
A generic `AutoCorrect` configuration parameter that can be used in for any cop was introduced in #1657. It has two shortcomings:
1. It needs to be configured like this
```yaml
CopName:
  AutoCorrect: "False"
```
So neither `False` nor `false` will work, which is counter-intuitive for this parameter.
2. When the parameter is added in `.rubocop.yml`, RuboCop prints a warning, e.g.:
```
Warning: unrecognized parameter Style/StringLiterals:AutoCorrect found in /home/jonas/dev/rubocop/.rubocop.yml
```

**Comment by rrosenblum** [comment]
I saw the issue with the string false earlier and I hadn't gotten a chance to write up the issue yet. I am glad to see that someone else found it as well.
