### ISSUE TITLE
Style/AndOr Cop changes output 

### ISSUE THREAD

**Issue by snowe2010** [bbatsov/rubocop#1844]
```
Then(/^all reason for visit results should contain "(.*?)"$/) do |value|
  START_RESULTS_INDEX = 1
  MAX_RESULTS_INDEX = 200

  for i in START_RESULTS_INDEX..MAX_RESULTS_INDEX
    begin
      # Table sometimes contains empty rows, making this check necessary
      # in addition to catching the exceptions below.
      # binding.pry
      txt = @current_page.reason_for_visit_results_element[i].text.downcase
      if txt != "" and !txt.include? "diag code"
        txt.should include value
      else
        if i == START_RESULTS_INDEX
          fail 'No results in rfv cart.'
        end
        break
      end
    rescue Watir::Exception::UnknownObjectException, NoMethodError
      if i == START_RESULTS_INDEX
        raise 'No results in rfv cart.'
      else
        # At the end of the procedures list
        break
      end
    end
  end
end
```

results in this:

```
λ ~\Docu\reco\tool\wati\trunk rubocop --auto-correct
Inspecting 117 files
..................C..................................................................................................

Offenses:

features/step_definitions/procedures_steps.rb:86:20: C: Use && instead of and.
      if txt != "" and !txt.include? "diag code"
                   ^^^

117 files inspected, 1 offense detected
```
 
As soon as I change the `and` to `&&` I get this output instead:

```
λ ~\Docu\reco\tool\wati\trunk rubocop --auto-correct
Inspecting 117 files
..................E..................................................................................................

Offenses:

features/step_definitions/procedures_steps.rb:86:37: E: unexpected token tSTRING
      if txt != "" && !txt.include? "diag code"
                                    ^^^^^^^^^^^
features/step_definitions/procedures_steps.rb:88:7: W: else without rescue is useless
      else
      ^^^^
features/step_definitions/procedures_steps.rb:94:5: E: unexpected token kRESCUE
    rescue Watir::Exception::UnknownObjectException, NoMethodError
    ^^^^^^
features/step_definitions/procedures_steps.rb:94:67: E: unexpected token tNL
    rescue Watir::Exception::UnknownObjectException, NoMethodError

features/step_definitions/procedures_steps.rb:103:1: E: unexpected token kEND
end
^^^

117 files inspected, 5 offenses detected
```

**Comment by snowe2010** [comment]
Changing the line to this removed solved the problem for me, but it still seems like a bug.
```
if !(txt == "" || txt.include?("diag code")) # De Morgan's Law
```

**Comment by rrosenblum** [comment]
I had a chance to test this out and got the same result when I changed `if txt != '' and !txt.include? 'diag code'` to `if txt != '' && !txt.include? 'diag code'`. It is important to note that in my case RuboCop did not auto correct the source code to the invalid syntax.

Running ruby's syntax check with `ruby -c` produces the same warning on this code.
```ruby
test.rb:13: syntax error, unexpected tSTRING_BEG, expecting keyword_then or ';' or '\n'
      if txt != '' && !txt.include? 'diag code'
                                     ^
test.rb:18: warning: else without rescue is useless
test.rb:19: syntax error, unexpected keyword_rescue, expecting keyword_end
    rescue Watir::Exception::UnknownObjectException, NoMethodError
          ^
test.rb:19: syntax error, unexpected '\n', expecting '='
test.rb:28: syntax error, unexpected keyword_end, expecting end-of-input
```

I am not sure of the exact reason why, but it appears as though ruby is confused about what is a part of the if statement. It seems like ruby is expecting the if statement to end at `!txt.include?`. It seems like this is one of those times in ruby where you need parenthesis.

Wrapping the entire if statement in parentheses did not fix the problem `if (txt != '' && !txt.include? 'diag code')`

It seems that the correct syntax for this is `if txt != '' && !txt.include?('diag code')` or what you included above.

**Comment by rrosenblum** [comment]
I didn't notice it before, but it appears that there is a test case for this exact example. RuboCop purposefully does not auto correct this code because it knows that it could produce issues.

```ruby
    it 'leaves *or* as is if auto-correction changes the meaning' do
      src = "x = y or teststring.include? 'b'"
      new_source = autocorrect_source(cop, src)
      expect(new_source).to eq(src)
    end
```

**Comment by alexdowad** [comment]
Precedence, operator precedence.

The Ruby parser is a complex and fearsome beast. In this case, `&&` is binding tighter (higher precedence) than the method call `txt.include?` binds to its argument `"diag code"`. So it's like you wrote:

```ruby
((txt != "") && !txt.include?) "diag code"
```

When you look at it like that, it should be obvious why it complains about "unexpected token tSTRING".

The question is how to make `Style/AndOr` smart enough to understand the precedence of all the surrounding expressions.

**Comment by bbatsov** [comment]
I was under the impression that we test the entire AST of the file in question after we do such changes which is both simple and effective. @jonas054 correct me if I'm wrong (don't have time to check the code itself).

**Comment by alexdowad** [comment]
You are right. That is exactly what it does. So `AndOr` no longer breaks the code in this issue.

However, it doesn't autocorrect it either. If `AndOr` was a little bit smarter, it could autocorrect this code. Expect a PR soon...

**Comment by alexdowad** [comment]
I have a fix for this one ready, but am waiting for some other PRs to go through first.

**Comment by alexdowad** [comment]
With PR #2378, `Style/AndOr` will be able to autocorrect this code without breaking anything.

**Comment by snowe2010** [comment]
Very nice. Thank you!
