### ISSUE TITLE
Module name should be consistent with filename

### ISSUE THREAD

**Issue by agrimm** [bbatsov/rubocop#1847]
I currently think that for each file, there should be a class or module name that is consistent with the filename. For example, if the file is called foo_bar.rb, there should be a class or module called FooBar.

I think this is possible to check with RuboCop, as it can check a file's name.

The main concerns I have are:
* Some files don't match this convention. You'd have foo_bar_spec.rb, but the class or module mentioned in it would be FooBar, not FooBarSpec.
* Should folders in the file's path also be considered? If you have `lib/foo/bar.rb`, would you check for module `Foo` being mentioned, as well as module `Bar`? Of course, there'd be no module `Lib`.

**Comment by alexdowad** [comment]
You can now check this by setting `ExpectMatchingDefinition: true` for `Style/FileName`.

Maintainers, please close this issue.

**Comment by TSMMark** [comment]
FTR in newer versions of Rubocop, the `Style/FileName` rule is now named: `Naming/FileName`
