### ISSUE TITLE
Bug with parallel assignment auto-correct

### ISSUE THREAD

**Issue by infertux** [bbatsov/rubocop#1873]
See #1831, the auto-correct function is broken with this edge case:

```diff
-        best_separator, best_score = separator, score if score > best_score
+        best_separator = separator
+        best_score = score if score > best_score
```

Both assignments should stay conditional.

As a side note, I don't get why this cop is in the _Performance_ category - does it have any performance implications? Shouldn't it be in _Style_?

**Comment by bbatsov** [comment]
> Shouldn't it be in Style?

It should be. I totally missed this.

**Comment by infertux** [comment]
Actually, I just came across https://github.com/JuanitoFatas/fast-ruby#parallel-assignment-vs-sequential-assignment-code - so I guess _Performance_ makes sense too :smile:.

**Comment by bbatsov** [comment]
While this is true, the bigger value is the improved readability of the code, so I still think this should be a style cop.

**Comment by bbatsov** [comment]
//cc @rrosenblum

**Comment by infertux** [comment]
Agreed.

**Comment by rrosenblum** [comment]
Thank you for the bug report. I agree, this is a bug. I will start working on a fix for it soon. 

As for Performance vs Style, it falls into both categories. It was brought up as an old feature request and in talking about performance cops. When we are talking about the ability to assign variables in the millions per second, doubling the performance is negligible except in extreme cases. I agree that the bigger gain is readability, therefore making this better suited as a Style Cop. I will also go ahead and make this change.

**Comment by infertux** [comment]
Good stuff @rrosenblum :clap:
