### ISSUE TITLE
Allow `Time.at` method in rails

### ISSUE THREAD

**Issue by ixti** [bbatsov/rubocop#1882]
Why is `.at` marked as danger? In fact this is not the only case I'm a bit misunderstading. E.g. following are all good examples (rubocop thinks otherwise):

``` ruby
Time.at(0).utc
Time.now.utc
```

**Comment by ojab** [comment]
.utc (and some other) methods are marked as acceptable, so you can disable warning with
```yaml
Rails/TimeZone:
  EnforcedStyle: acceptable
```
in config

**Comment by ixti** [comment]
@ojab Oh. Nice. Thanks! Overlooked that!
