### ISSUE TITLE
Relax TrivialAccessors to allow different-named accessors

### ISSUE THREAD

**Issue by lowjoel** [bbatsov/rubocop#1892]
Currently, a code fragment like this would trigger a violation:
```ruby
  def current_course
    @course
  end
```
I do not think that `attr_accessor` would allow defining a method whose name is different from the variable it returns. Perhaps it should check that the name of the method and the name of the instance variable it is returning are the same before flagging this as a violation?

**Comment by bbatsov** [comment]
Guess you're using an old version of RuboCop as this was recently changed. The old default had the aim to uncover "hidden" attribute accessor methods, but I guess most people were confused by it, so it was changed to what you suggested.

**Comment by lowjoel** [comment]
Oh, OK, thanks! I was using Hound, so maybe it isn't the latest.

Thanks again!

**Comment by bbatsov** [comment]
Seems they are still on 0.29.1.
