### ISSUE TITLE
wrong autocorrect 

### ISSUE THREAD

**Issue by badal** [bbatsov/rubocop#1897]
With the following code
```
if condition
   do_this ; do_that
end
```
Rubocop-0.31 fixes it as
```
do_this ; do_that if condition
```
which is not equivalent.
Note 1 : I use the semi-colon in the following case
```
if error_condition
   complain("error message") ; return
end
```
which look really better than
```
if error_condition
   complain ...
   return
end
```
Note 2: I should use the one-liner guard with parentheses 
_md

**Comment by bbatsov** [comment]
Looks like a bug indeed.
