### ISSUE TITLE
Redundant curly braces around a hash parameter.

### ISSUE THREAD

**Issue by OrelSokolov** [bbatsov/rubocop#1898]
Seems like here is 2 different situations. For 1 hash argument, and for hash + another. Rubocop does not recognize different situations. In first case we can leave braces, in second is better to remove it.

```
src/lib/database.rb:109:46: C: Redundant curly braces around a hash parameter.
          DataMapper.setup( @repository_key, { :adapter => 'mysql', :database => db_path, :username => db_username, :password => db_password, :host => db_host } )
                                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
features/support/hooks.rb:7:35: C: Redundant curly braces around a hash parameter.
  person = Person.first_or_create({first_name: 'Test', last_name: 'User'})
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by bbatsov** [comment]
> In first case we can leave braces, in second is better to remove it.

That's super subjective IMO.  I can imagine it might be better to leave the braces if the previous argument was a hash literal as well, but otherwise it makes no difference to me.
