### ISSUE TITLE
`rubocop -a` bug: Hash + comment

### ISSUE THREAD

**Issue by dcu** [bbatsov/rubocop#1899]
The following program:

```ruby
def foo(opts = {})
  r = opts.merge({
    p1: opts[:a],
    p2: (opts[:b] || opts[:c]) # a comment
  })

  return r
end
```

converted to:

```ruby
def foo(opts = {})
  r = opts.merge(    p1: opts[:a],
    p2: (opts[:b] || opts[:c]) # a comment)

  return r
end
```

**Comment by jonas054** [comment]
I'm considering a generic solution that stops any auto-correct from creating files with syntax errors in them. Is that a good idea or not? Are we hiding bugs if we do it like that?

**Comment by dcu** [comment]
Errors are fine, I mean I found a couple in a large codebase and they were easy to fix .
I reported them to make the feature better and if you hide them you won't get that.

**Comment by bbatsov** [comment]
> I'm considering a generic solution that stops any auto-correct from creating files with syntax errors in them. Is that a good idea or not? Are we hiding bugs if we do it like that?

We'll probably hide the bugs this way (would you report a ticket for something that's not causing you problems?). I think the current model works just fine - if something's wrong we have to correct it.

**Comment by jonas054** [comment]
Good. I'll make a solution for this particular problem only.
