### ISSUE TITLE
Rubocop on Circle-CI seems to want to check the world

### ISSUE THREAD

**Issue by krainboltgreene** [bbatsov/rubocop#1910]
```
$ bin/rake rubocop
Running RuboCop...
Inspecting 8312 files
HERE IT SPENDS 45m COPPING EVERYTHING
```

It's only happening on CircleCi and happens if I use `bin/rake rubocop` or `bundle exec rubocop`. I think there might be some weird environment variable?

**Comment by krainboltgreene** [comment]
Turns out we added our own exclude, which overwrote the original `vendor` exclude, which is populated during circle ci.

**Comment by rafaelcamargo** [comment]
@krainboltgreene Oh god, who could imagine that CircleCI puts stuff on the vendors directory... It almost drove me crazy. Your comment was a valuable clue to help me find my problem. Thanks a lot 🙏
