### ISSUE TITLE
How to disable all cops except some

### ISSUE THREAD

**Issue by cheunghy** [bbatsov/rubocop#1918]

**Comment by jonas054** [comment]
You use the `--only` command line option. For example
```
rubocop --only Metrics
rubocop --only Style/FormatString,Style/HashSyntax
```

**Comment by cheunghy** [comment]
Thanks, but how to do it with config file?

**Comment by jonas054** [comment]
I'm not sure why you would want to do that exactly, but the normal workflow when starting to use RuboCop is to run `rubocop --auto-gen-config`, then add `inherit_from: .rubocop_todo.yml` in `.rubocop.yml`. It achieves the same goal as disabling all cops, except that the cops that have not found any offenses remain enabled.

**Comment by jbodah** [comment]
I was wondering the same thing. I don't want to inherit all of the default style checks that Rubocop provides by default and would much rather just specify the things we want rather than have to keep going back in to override things

**Comment by jbodah** [comment]
Tried messing around in a fork a bit to see if we can just get rid of the default config, but it looks like we're expecting configuration values to be present for all the cops (as opposed to reading the configs and only loading cops that are declared)

https://github.com/backupify/rubocop/pull/1

**Comment by jonas054** [comment]
Opening this issue again to make a pull request with a solution.

**Comment by cheunghy** [comment]
👍

**Comment by jbodah** [comment]
Sweet thanks!

**Comment by tisba** [comment]
This is a great feature, thanks! Is there any ETA on the upcoming release containing this?

**Comment by pschambacher** [comment]
It would actually be nice to have the same option for each category. I'm interested in everything except all the `Style/`

**Comment by jonas054** [comment]
@pschambacher This issue talks about a few different options, so can you clarify a bit what it is that you want?

**Comment by pschambacher** [comment]
@jonas054 this is what I was thinking about:

```yml
AllCops:
  DisableByDefault: false

Style/AllCops:
  DisableByDefault: true
```

This way I get all existing (and future) cops enabled except for any existing (and future) Style cops.
Making it the other way around would be "I only care for Style cops"

**Comment by jonas054** [comment]
That's a good idea. But the syntax should be
```yaml
Style:
  DisableByDefault: true
```
Currently, such a setting is silently ignored, which is clearly not what we want.

**Comment by pschambacher** [comment]
I'm completely fine with this syntax :)

**Comment by chadxz** [comment]
I came looking for 

```
Metrics:
  DisableByDefault: true
```

and found this ticket. is anyone working on it?

**Comment by bbatsov** [comment]
Most likely no.

**Comment by wangsitan** [comment]
For people get here later and interested in this, you can found doc at:
<https://docs.rubocop.org/rubocop/configuration.html#generic-configuration-parameters>

What you want may look like this:
```yml
AllCops:
  DisabledByDefault: true
  
Style:
  Enabled: true
```
