### ISSUE TITLE
missing runtime_dependency on json

### ISSUE THREAD

**Issue by lpramuk** [bbatsov/rubocop#1919]
rubocop gemspec should specify runtime depency on json as it is required to run

$ ruby -v
ruby 2.0.0p598 (2014-11-13) [x86_64-linux]

$ rubocop -v
/usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- json (LoadError)
	from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/share/gems/gems/rubocop-0.31.0/lib/rubocop/formatter/json_formatter.rb:3:in `<top (required)>'
	from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/share/gems/gems/rubocop-0.31.0/lib/rubocop.rb:308:in `<top (required)>'
	from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/share/gems/gems/rubocop-0.31.0/bin/rubocop:6:in `<top (required)>'
	from /usr/local/bin/rubocop:23:in `load'
	from /usr/local/bin/rubocop:23:in `<main>'

**Comment by bbatsov** [comment]
`json` is part of the standard library. See https://github.com/bbatsov/rubocop/pull/755

**Comment by lpramuk** [comment]
I see,  then we can close this issue.
