### ISSUE TITLE
Potential Parser Breaking Change in Newest Version (2.2.2.5)

### ISSUE THREAD

**Issue by pbrown-fiksu** [bbatsov/rubocop#1934]
It looks like parser made a breaking change recently that is effecting Rubocop.

```
$ rubocop -V
warning: parser/current is loading parser/ruby21, which recognizes
warning: 2.1.6-compliant syntax, but you are running 2.1.5.
/Users/pbrown/.rvm/gems/ruby-2.1.5@fma-dev/gems/parser-2.2.2.5/lib/parser/ruby21.rb:13:in `<top (required)>': undefined method `check_for_encoding_support' for Parser:Module (NoMethodError)
	from /Users/pbrown/.rvm/gems/ruby-2.1.5@fma-dev/gems/parser-2.2.2.5/lib/parser/current.rb:36:in `require'
	from /Users/pbrown/.rvm/gems/ruby-2.1.5@fma-dev/gems/parser-2.2.2.5/lib/parser/current.rb:36:in `<module:Parser>'
	from /Users/pbrown/.rvm/gems/ruby-2.1.5@fma-dev/gems/parser-2.2.2.5/lib/parser/current.rb:1:in `<top (required)>'
	from /Users/pbrown/.rvm/gems/ruby-2.1.5@fma-dev/gems/rubocop-0.31.0/lib/rubocop.rb:3:in `require'
	from /Users/pbrown/.rvm/gems/ruby-2.1.5@fma-dev/gems/rubocop-0.31.0/lib/rubocop.rb:3:in `<top (required)>'
	from /Users/pbrown/.rvm/gems/ruby-2.1.5@fma-dev/gems/rubocop-0.31.0/bin/rubocop:6:in `require'
	from /Users/pbrown/.rvm/gems/ruby-2.1.5@fma-dev/gems/rubocop-0.31.0/bin/rubocop:6:in `<top (required)>'
	from /Users/pbrown/.rvm/gems/ruby-2.1.5@fma-dev/bin/rubocop:23:in `load'
	from /Users/pbrown/.rvm/gems/ruby-2.1.5@fma-dev/bin/rubocop:23:in `<main>'
	from /Users/pbrown/.rvm/gems/ruby-2.1.5@fma-dev/bin/ruby_executable_hooks:15:in `eval'
	from /Users/pbrown/.rvm/gems/ruby-2.1.5@fma-dev/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by whitequark** [comment]
Er, no. That function is defined in `lib/parser.rb`, and `lib/parser/ruby21.rb` starts like:
```
require 'parser'
Parser.check_for_encoding_support
```

Something is wrong with your install.

**Comment by pbrown-fiksu** [comment]
This has been experienced by 2 other people in my office, and we’ve all destroyed our gemsets and rebuilt to confirm.

Is there any information I can provide to help debug?

**Comment by whitequark** [comment]
Then some other gem defines a `lib/parser.rb` file. Try looking in `$LOADED_FEATURES` after `require 'parser'`.

**Comment by pbrown-fiksu** [comment]
Ah! That was it!

```ruby
pry(main)> ap $LOADED_FEATURES.select{ |n| /lib\/parser.rb/.match(n) }
[
    [0] "/Users/pbrown/.rvm/gems/ruby-2.1.5@fma-dev/gems/ruby-imagespec-0.3.1/lib/parser.rb"
]
```

Thanks :)

**Comment by xacaxulu** [comment]
+1

**Comment by typeoneerror** [comment]
Same issue here. Anyone have an idea how to remedy this?

    pry(main)> $LOADED_FEATURES.select{ |n| /lib\/parser.rb/.match(n) }
    => ["/Users/typeoneerror/.rvm/gems/ruby-2.1.5@doki/gems/parser-2.3.0.pre.2/lib/parser.rb"]

**Comment by whitequark** [comment]
@typeoneerror What is the exact error you're getting?

**Comment by typeoneerror** [comment]
@whitequark 

> $ rubocop -v
warning: parser/current is loading parser/ruby21, which recognizes
warning: 2.1.7-compliant syntax, but you are running 2.1.5.
0.32.1

**Comment by typeoneerror** [comment]
Just curious if this warning is safe to ignore and if I can silence it if so?

**Comment by whitequark** [comment]
See https://github.com/whitequark/parser#compatibility-with-ruby-mri for why it exists. You can silence it with `ruby -W0 -S rubocop`

**Comment by typeoneerror** [comment]
@whitequark thanks, that makes sense. and thank you for the silencer :+1:

**Comment by typeoneerror** [comment]
I guess I don't understand this. Seems to be one version ahead no matter what I try?

> warning: parser/current is loading parser/ruby22, which recognizes
warning: 2.2.3-compliant syntax, but you are running 2.2.2.
0.32.1

**Comment by whitequark** [comment]
Why are you using parser from git?

**Comment by whitequark** [comment]
Or, well, pre-release, which is more or less same thing

**Comment by typeoneerror** [comment]
Honestly don't know. I just installed ruby 2.2.2 via rvm.

**Comment by whitequark** [comment]
How did you install parser?

**Comment by typeoneerror** [comment]
It was installed as a dependency of rubocop, as far as I can tell. 

    rubocop (0.32.1)
          astrolabe (~> 1.3)
          parser (>= 2.2.2.5, < 3.0)
          powerpack (~> 0.1)
          rainbow (>= 1.99.1, < 3.0)
          ruby-progressbar (~> 1.4)

Never explicitly installed it to my recollection and can't find it on my system outside of the gemset that rubocop was installed to. Puzzling!

**Comment by whitequark** [comment]
Hm, so what's the exact parser version that got selected? This is odd.

**Comment by typeoneerror** [comment]
Just deleted my gemset, recreated and did a fresh `bundle install`. _Gemfile.lock_ is showing:

    parser (2.3.0.pre.2)

and

    astrolabe (1.3.0)
      parser (>= 2.2.0.pre.3, < 3.0)

Whole thing [here](https://gist.github.com/typeoneerror/57da5d5876e616a4453e).

**Comment by whitequark** [comment]
@yujinakayama Filed a big here https://github.com/yujinakayama/astrolabe/issues/3

**Comment by typeoneerror** [comment]
Great, appreciate your time looking into this. Thanks!

**Comment by asaaki** [comment]
If you still have the issue, this worked for me:

```shell
gem install parser # should install the current stable, not pre (currently 2.2.2.6)
gem uninstall parser -v=2.3.0.pre.2
```

In a Gemfile you might need to add `parser` gem with desired version (`gem 'parser', '~> 2.2.2.6`).

I wonder why the _pre_ version is installed anyway (I thought one would have to explicitly opt-in for that).

**Comment by gjtorikian** [comment]
@asaaki Thanks! Your instructions worked for me. :metal:
