### ISSUE TITLE
Do not use Date.current in rails unsuspected error

### ISSUE THREAD

**Issue by mli-max** [bbatsov/rubocop#1939]
I see `Do not use Date.current without zone. Use Time.zone.today instead` in my rails project.
But It has already overrided in activesupport.
Look here https://www.omniref.com/ruby/gems/activesupport/4.2.0/symbols/Date/current?d=372865379&n=0#

```
lib/active_support/core_ext/date/calculations.rb

    # Returns Time.zone.today when <tt>Time.zone</tt> or <tt>config.time_zone</tt> are set, otherwise just returns Date.today.
    def current
      ::Time.zone ? ::Time.zone.today : ::Date.today
    end
```
How is possible? Am I wrong or rubocop?

**Comment by bbatsov** [comment]
See the configuration options for this cop. There's also an `acceptable` setting. The idea of the default is simply consistency, as most of `Date`'s methods are problematic.

**Comment by waghanza** [comment]
I understand that this behavior could be added to `rubocop`, but still the doc is not correct

With `rails`, the following
```
Using Date.today is dangerous, because it doesn’t know anything about Rails time zone. You must use Time.zone.today instead.
```

is not wrong

It could also be nice to have a `cop` that enforces usage of `Date.current` / `Date.today` as well as `Time.current`

wdyt @bbatsov ?
