### ISSUE TITLE
Rails: Check for indexs in tables for fields with XXX_id name

### ISSUE THREAD

**Issue by mpz** [bbatsov/rubocop#1940]
It can be possible to create cop for check field with "XXX_id" name. (Ended with "_id")
Such fields must be index field in database.

**Comment by bbatsov** [comment]
You can check for this by just inspecting the source code.

**Comment by mpz** [comment]
We can check all code issues by "just inspecting". :)

Ussualy we forgot add index to field.
And then in production we have slowly speed for some response. 
Need to check such slowly response in NewRelic - it is big time for such easy bug.

**Comment by mpz** [comment]
below is check code example. Now i use it in tests:

    tables = []

    ActiveRecord::Base.connection.tables.each do |table|
      next if table.match(/\Aschema_migrations\Z/)
      klass = table.singularize.camelize.constantize
      tables << { table => klass.name }
    end

    tables.each do |table|
      klass = table.values[0]
      klass = klass.constantize
      assert klass.columns[0].primary,
             "First column '#{klass.columns[0].name}' ".bold +
               "is not Primary in model #{klass}".red

      klass.columns.each do |col|
        next if col.name[-3..-1] != '_id'
        exist = ActiveRecord::Base.connection.index_exists?(
          table.keys[0], col.name)
        assert exist, "Column '#{col.name}' ".bold +
          "is not index in model #{klass}".red
      end
    end

**Comment by bbatsov** [comment]
RuboCop is a **static code analyzer**. It just inspects the AST of the Ruby source code, we can't do checks like the one you suggested.

**Comment by bquorning** [comment]
@mpz You might want to take a look at [the lol_dba gem](https://rubygems.org/gems/lol_dba) instead. It can “scan your application models and displays a list of columns that probably should be indexed”.

**Comment by mpz** [comment]
@bbatsov, @bquorning thank you. It is true - rubocop is static code analyzer.
