### ISSUE TITLE
Not finish auto correcting with TODO notation including a comma

### ISSUE THREAD

**Issue by naoty** [bbatsov/rubocop#1943]
I'm using Ruby 2.2.2p95 and rubocop v0.31.0. Auto correcting below code will not be finished.

```rb
# TODO:,
def main
end
```

```bash
$ rubocop -a
Inspecting 1 file
(Not finishing)
```

**Comment by bbatsov** [comment]
I think this is fixed on `master`.

**Comment by naoty** [comment]
Sorry. I ensured that this is fixed.
