### ISSUE TITLE
Bug (?): `--lint` silently ignored with `--only`

### ISSUE THREAD

**Issue by fj** [bbatsov/rubocop#1960]
I would like to be able to run all the Lint cops and specific style cops, working from the command line.

I expected to be able to do `rubocop --lint --only c1,c2,c3 dir`, since the help says this will "run only the lint cops" and "run only the selected cops" -- but for me, this actually checks only cops `c1`, `c2`, and `c3`, and silently ignores all the lint checks.

More strangely, if I use the Rubocop Rake task and pass `task.options = [ '--lint' ]`, it doesn't seem to check anything, because I get no failures. If I run `rubocop --lint dir`, the expected failures appear.

**Comment by jonas054** [comment]
An alternative syntax is `rubocop --only Lint,c1,c2,c3 dir`, but the command you described should also work, and it does when I try.

Can you check if there really are any lint violations in the code you're checking? What version are you running?

**Comment by fj** [comment]
@jonas054 Let me see if I can reproduce this with a minimal test case instead of on the project I'm working on, which is pretty large and is probably introducing too much noise into this issue. If I can I'll update the issue here accordingly.
