### ISSUE TITLE
Style/RedundantBegin auto correct on empty rescue with trailing comment results in invalid syntax

### ISSUE THREAD

**Issue by DMA57361** [bbatsov/rubocop#1964]
When auto correcting this:
```
def method
  begin
    do_some_stuff
  rescue # rubocop:disable Lint/RescueException
  end
end
```
Rubocop produces the following output:
```
Offenses:

rbfail_repro.rb:2:3: C: [Corrected] Style/RedundantBegin: Redundant begin block detected.
  begin
  ^^^^^
rbfail_repro.rb:3:8: E: unexpected token kEND
rescue end
       ^^^
rbfail_repro.rb:4:10: W: Unnecessary disabling of Lint/RescueException.
  rescue # rubocop:disable Lint/RescueException
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

And the file is left looking like this, which as you can see is not valid:
```
def method
  do_some_stuff
rescue end
```

Extra notes
* It's failed for me when trying random trailing comments, not just the rubocop:disable (that's just how I came across the error in our code. )
* It will also break if there's a `=> e` (or equivalent) after the rescue (assuming there's a trailing comment afterwards)

It does work if there's any content in the rescue (with or without the comment) and when there's no comment present.

**Comment by jonas054** [comment]
Confirmed as a bug. I'll try to fix it.
