### ISSUE TITLE
Autocorrect on Annotation keywords loops forever

### ISSUE THREAD

**Issue by coorasse** [bbatsov/rubocop#1976]
simply write a comment like
```
# TODO:I18n
```
and run rubocop with autocorrection and it will loop forever

**Comment by bbatsov** [comment]
Didn't we fix this already https://github.com/bbatsov/rubocop/pull/1908

What version of RuboCop are you running?

**Comment by rrosenblum** [comment]
I just checked on this. It does not appear to be an issue in 0.32.1.

**Comment by coorasse** [comment]
Was still in place for 0.32.0 but has been fixed in 0.32.1 now.
