### ISSUE TITLE
Broken advice when using DateTime.now

### ISSUE THREAD

**Issue by somebody32** [bbatsov/rubocop#1984]
Hi!

Rubocop advices you to use `DateTime.zone.now` when sees `DateTime.now` which is wrong:

```ruby
NoMethodError: undefined method `zone' for DateTime:Class
```
[Rails API DateTime](http://api.rubyonrails.org/classes/DateTime.html)

I think only Time class should be in this list: https://github.com/bbatsov/rubocop/blob/master/lib/rubocop/cop/rails/time_zone.rb#L38

**Comment by bbatsov** [comment]
//cc @palkan

**Comment by lpil** [comment]
Has this been released yet?

**Comment by palkan** [comment]
Yes, since 0.33.0.

**Comment by lpil** [comment]
Thank you.
