### ISSUE TITLE
RailsCop detects variable to_time as method when used in a range

### ISSUE THREAD

**Issue by EdvardM** [bbatsov/rubocop#1985]
In my code, I have

`foo(resource_id: rid, range: from_time..to_time)` and I get this:

Convention: Do not use to_time on Date objects,because it knows nothing about time zone in use.

While it could be argued that to_time is somewhat ill-conceived name for a variable, it should not be reported as an error.

**Comment by bbatsov** [comment]
That's definitely a bug. //cc @palkan
