### ISSUE TITLE
An error occurred while Style/ParallelAssignment cop ...

### ISSUE THREAD

**Issue by dblock** [bbatsov/rubocop#1988]
Haven't debugged, seems to come from this line.

```ruby
curr_best_cost, curr_best_meeting_round = Float::INFINITY
```

This is on https://github.com/ilyakava/sup, I can narrow it down to a spec soon if nobody picks this up. RuboCop 0.32.1.

**Comment by rrosenblum** [comment]
Thanks for submitting the bug report. There wound up being an easy fix for this.

**Comment by dblock** [comment]
:+1:

**Comment by kdeberk** [comment]
This also fixed `foo, bar = super` !
