### ISSUE TITLE
MethodCallParentheses lacks exception for distinguishing local variables and methods

### ISSUE THREAD

**Issue by agrimm** [bbatsov/rubocop#1992]
def foo
      42
    end
    
    # Assigns 42
    foo = foo()
    
    # Assigns nil
    foo = foo

RuboCop gives an Style/MethodCallParentheses for the former, which may encourage people to do the latter, which will create incorrect code.

For people encountering this problem, use the following instead as a workaround. RuboCop doesn't complain about this:

    foo = self.foo

**Comment by bbatsov** [comment]
Yeah, that's a nasty corner case. The problem is that the two look exactly the same in the AST. The only workaround I can think of checking if you're trying to assign the result of method named the same way as the lvar.

**Comment by jonas054** [comment]
> The problem is that the two look exactly the same in the AST.

@bbatsov Maybe I misunderstand what you mean, but I've found that there *is* a difference in AST that shows whether the name without parentheses is a method call or a local variable access:
```ruby
def bar
  42
end

bar = 1

foo = bar
```
gives
```
(begin
  (def :bar
    (args)
    (int 42))
  (lvasgn :bar
    (int 1))
  (lvasgn :foo
    (lvar :bar)))
```
but
```ruby
def bar
  42
end

bar = 1

foo = bar()
```
gives
```
(begin
  (def :bar
    (args)
    (int 42))
  (lvasgn :bar
    (int 1))
  (lvasgn :foo
    (send nil :bar)))
```
So we can check if removing the empty parentheses would change the AST.

**Comment by bbatsov** [comment]
> @bbatsov Maybe I misunderstand what you mean, but I've found that there is a difference in AST that shows whether the name without parentheses is a method call or a local variable access:

Unless something has appeared as a local variable assignment in the current scope it will be treated as method call by the AST. This is what I meant. Your examples are not incorrect, but @agrimm's problem is somewhat different.
