### ISSUE TITLE
Integration with teamcity

### ISSUE THREAD

**Issue by alexandru-calinoiu** [bbatsov/rubocop#1993]
Hi,

Do you happen to plan integration with teamcity, I will love to get the output properly reported on my CI, all I get now is a `exit code 1`.

**Comment by bbatsov** [comment]
Guess some custom reporter is needed for RuboCop to work properly with TeamCity. Provide us with more details out the expected output and we'll get this done (eventually).

**Comment by balauru** [comment]
It all boils down to passing messages in a special format to teamcity city, details can be found here https://confluence.jetbrains.com/display/TCD9/Build+Script+Interaction+with+TeamCity#BuildScriptInteractionwithTeamCity-Reporting.NETCodeCoverageResults

**Comment by y8** [comment]
There checkstyle custom formatter exists, check the https://github.com/eitoball/rubocop-checkstyle_formatter. It integrates nicely with Teamcity, you just need to add build step that fires rubocop, and then add "XML report processing" Build Feature to load the results from the generated xml file.

Only one problem here is that rubocop exits with non-zero code, so teamcity thinks that build step is failed. 

It will be nice to have an option to exit with 0, even if there any errors/warnings.

**Comment by jonas054** [comment]
If you run `rubocop --fail-level F`, then it will only exit with error if there are parsing errors.

**Comment by y8** [comment]
Yeah, just found that in documentation :)

Thanks!

**Comment by jonas054** [comment]
So I guess everything is all right then.

**Comment by lawliet89** [comment]
If you are still looking for a formatter, there is one here: https://github.com/GovTechSG/rubocop-teamcity-formatter
