### ISSUE TITLE
Runtime error in Lint/DefEndAlignment auto-correct

### ISSUE THREAD

**Issue by gotrevor** [bbatsov/rubocop#2015]
Using this file (`crash.rb`) as input:
```
# encoding: utf-8
def func
  foo
rescue
  baz
  end
```

With this option enabled:
```
Lint/DefEndAlignment:
  AutoCorrect: true
```

I get the following crash:
```
[~/repos/rubocop] $ bin/rubocop crash.rb -a -d
...
An error occurred while Lint/DefEndAlignment cop was inspecting /Users/gotrevor/repos/rubocop/crash.rb.
undefined method `expression' for nil:NilClass
/Users/gotrevor/repos/rubocop/lib/rubocop/cop/mixin/end_keyword_alignment.rb:49:in `align'
/Users/gotrevor/repos/rubocop/lib/rubocop/cop/lint/def_end_alignment.rb:52:in `autocorrect'
...
```

I've tracked the problem down to the method `investigate` here:
https://github.com/bbatsov/rubocop/blob/v0.32.1/lib/rubocop/cop/variable_force.rb#L71-L79
`processed_source` enters with 
```
processed_source.ast.ancestors.first == nil
```
it exists with
```
processed_source.ast.ancestors.first != nil 
&& processed_source.ast.ancestors.first.loc == nil
```

This causes the crash here:
https://github.com/bbatsov/rubocop/blob/v0.32.1/lib/rubocop/cop/mixin/end_keyword_alignment.rb#L49
Which assumes that a non-nil node will have a `loc`.  Is that a valid assumption?

I suspect that `VariableForce#investigate` shouldn't be mutating `processed_source.ast`.
Am I right about that?

**Comment by jonas054** [comment]
Thanks, @gotrevor for the analysis. I'm working on this problem already, but hadn't gotten down to `VariableForce#investigate` yet. I'll take your views in to consideration, and will make a PR soon.

**Comment by jonas054** [comment]
To answer your question, I think it *is* reasonable for `EndKeywordAlignment#align` to expect that nodes given to it as the base for alignment have a `loc` attribute. When the node turns out to be a "fake" `begin` node, then it's the caller that's in error.
