### ISSUE TITLE
Metrics/ParameterLists should have a different behavior for named hash parameters

### ISSUE THREAD

**Issue by sdeframond** [bbatsov/rubocop#2016]
Hi there,

`Metrics/ParameterLists` is limiting the number of parameters in a method. This is very good.

Ruby 2.0 introduces "named hash parameters", For example `def my_method(a:, b:, c:)`. It offers a stricter alternative to passing a loose hash.

While rubocop does not enforce any limit on the size of hash arguments when calling a method, it does enforce a limit to the named hash arguments when defining a method. This is not very consistent.

What is the recommended approach? Use a old-fashioned hash? Disable this cop temporarily?

Should we consider altering this cop's behaviour?

**Comment by jonas054** [comment]
I'm not sure if I understand your question, but let me try to provide some answers. We'll see if they correspond to what you meant.

First of all, if a method takes too many arguments, it's the definition that's wrong. The caller can only call the method as it is, it's no use RuboCop reporting the calls as offenses.

If you've defined a method with too many arguments (according to `Metrics/ParameterLists`) you can either:
* set a higher `Metrics/ParameterLists: Max` in `.rubocop_todo.yml`
* disable locally with `# rubocop:disable Metrics/ParameterLists`, or
* rewrite the method so it takes fewer arguments, perhaps grouping some of them together in a new class

The last one is the recommended approach, generally speaking.

**Comment by bbatsov** [comment]
Perhaps @sdeframond is referring to the `CountKeywordArguments` option of the cop? I'm not totally sure about this.

**Comment by sdeframond** [comment]
@bbatsov aaah, that's right. This option would do the trick. Thank you so much!
