### ISSUE TITLE
Exclusions by Line Number

### ISSUE THREAD

**Issue by nslocum** [bbatsov/rubocop#2019]
Is it possible to exclude specific lines of code in .rubycop.yml?

````
Metrics/CyclomaticComplexity:
  Exclude:
    - app/models/model_name.rb:78
````

I think this approach is superior to intermingling rubycop exclusions with code:

````
 rubocop:disable Metrics/LineLength, Style/StringLiterals
[...]
# rubocop:enable Metrics/LineLength, Style/StringLiterals
````

**Comment by nslocum** [comment]
It appears that it isn't possible to do exclusions by line number.

Is this a featire that would be considered for merging?

**Comment by bbatsov** [comment]
See https://github.com/bbatsov/rubocop/pull/1440

Work on this started, but was never finished.

**Comment by bbatsov** [comment]
PR welcome, but for the time being I'm closing this.
