### ISSUE TITLE
Cop to require keyword arguments instead of an options hash

### ISSUE THREAD

**Issue by yob** [bbatsov/rubocop#2030]
Rails has made the following form of method signature quite popular, and we have lots of instances in our own code:

```ruby
def foo(bar, options = {})
  ..
end
```

I'd like a cop to force these methods to be defined with optional keyword args instead:

```ruby
def foo(bar, baz: true)
  ..
end
```

The second form is nicely self documenting and avoids a small amount of hash fetch code inside the method.

**Comment by bbatsov** [comment]
Can't argue with this. I hate option hashes.

**Comment by yob** [comment]
Cheers. It's probably not a good default - lots of library authors are likely still supporting Ruby versions without keyword arguments - but it'd be great for application code.
