### ISSUE TITLE
Specifying absolute path for rubocop file disregards exclusions

### ISSUE THREAD

**Issue by RAbraham** [bbatsov/rubocop#2050]
Hi,
If I am running rubocop from the terminal from the directory `/Users/sports`, I get different behaviour wrt to the following commands
`/Users/sports> rubocop -c /Users/sports/.rubocop.yml <sub_dir>`
and
`/Users/sports> rubocop -c .rubocop.yml <sub_dir>`

Actually the first one does not consider the `Excludes` in the `.rubocop.yml` file but the second one does. I thought they would both produce the same output?

Using `0.31.0 (using Parser 2.2.2.2, running on ruby 2.2.0 x86_64-darwin14)`

**Comment by jonas054** [comment]
I have not been able to reproduce this problem. I tried by adding this spec example in `cli_spec.rb`:
```ruby
    describe '--config' do
      let(:target_file) { File.join(Dir.home, 'sub_dir/example.rb') }
      let(:config_file) { File.join(Dir.home, '.rubocop.yml') }

      before do
        create_file(target_file, ['# encoding: utf-8',
                                  '#' * 90])

        create_file(config_file, ['AllCops:',
                                  '  Exclude:',
                                  '    - sub_dir/**/*'])
      end

      it 'excludes files specified in the configuration Exclude' do
        Dir.chdir(Dir.home) do
          expect(cli.run(['--config', config_file, 'sub_dir'])).to eq(0)
        end
      end
    end
```
but it passed, both on `v0.31.0` and on the current `master`
