### ISSUE TITLE
Create a RuboCop website

### ISSUE THREAD

**Issue by bbatsov** [bbatsov/rubocop#2051]
I came by this web site recently http://eslint.org/ and was quite impressed. Quite clear and informative.

It will be great if we develop some similar site for RuboCop, although it's definitely not something we can't live without. Pouring more and more stuff into the README will be become problematic at some point.

**Comment by rrosenblum** [comment]
I think this is a great idea. It would be a good place to provide more information and examples for cops.

**Comment by bbatsov** [comment]
The only problem is that this would also be a lot of work. :-)

**Comment by pratik60** [comment]
Why not just host a wiki at read the docs? Seen quite a few repos leverage it amazingly well

**Comment by deivid-rodriguez** [comment]
Now RuboCop has a nice documentation website, can this be closed?

**Comment by bbatsov** [comment]
Guess it can be closed, but the documentation really sucks right now, so we've got a lot more work to do there.

**Comment by Dorian** [comment]
@bbatsov What about using github pages generated from the docs? `rubocop.github.io` would be great

**Comment by bbatsov** [comment]
I'm fine with this provided someone wants to work on it. rtd seemed like the simplest solution to me at the time and this is why I went with it. I have no doubt we can do a bit better.
