### ISSUE TITLE
TrivialAccessors gives false advice on modules with module_function

### ISSUE THREAD

**Issue by alexanderadam** [bbatsov/rubocop#2059]
[TrivialAccessors](https://github.com/bbatsov/rubocop/blob/master/lib/rubocop/cop/style/trivial_accessors.rb) complains with

```
Use attr_writer to define trivial writer methods.
  def bar=(new_bar)
  ^^^
```

in a case like

```ruby
module Foo
  module_function

  def bar=(new_bar)
    @bar = new_bar
  end
end

module Bar
  module_function

  attr_writer :foo
end

Foo.bar = 'works'
Bar.foo = "this doesn't"
```

but ruby will complain with
```
undefined method `foo=' for Bar:Module (NoMethodError)
```

when following `TrivialAccessors` advice.

PS: @bbatsov thank you for your work! I love rubo:cop:!

**Comment by bbatsov** [comment]
Ah, yeah. Seems the best solution would be to simply ignore modules altogether in this cop. 

Alternative suggestions are welcome.

**Comment by alexanderadam** [comment]
I guess it would be the simplest solution for now so… yes
