### ISSUE TITLE
`Redundant curly braces around a hash parameter' detect is not suitable.

### ISSUE THREAD

**Issue by zw963** [bbatsov/rubocop#2063]
```ruby
    order_params = ActionController::Parameters.new(params)
    .permit(
      :seller_id,
      :location_id,
      :recipient_info_id,
      {
       line_items: [
          :title,
          :image_url,
          :price,
          :quantity,
          :description,
          :product_id
        ]
      },
      { # => Redundant curly braces around a hash parameter.
        gifts: [
          :title,
          :image_url,
          :price,
          :quantity,
          :description
        ]
      }
      )
```

If multi hash argument, it should not element last hash curly braces.

**Comment by DMA57361** [comment]
Looks like that cop has a "context_dependent" mode you can activate that requires the last param to be wrapped in braces if it's a hash, but only when the penultimate param is also a hash (see https://github.com/bbatsov/rubocop/blob/master/config/default.yml#L234). This may meet your needs.

Try putting this in your `.rubocop.yml`:
```
Style/BracesAroundHashParameters:
  EnforcedStyle: context_dependent
```
When I tested it the offence was successfully removed from the example code you provided.

**Comment by zw963** [comment]
Thanks, I missing this config, rubycop is fancy!!
