### ISSUE TITLE
Style/Copyright Bug

### ISSUE THREAD

**Issue by philoserf** [bbatsov/rubocop#2068]
I decided to give the copyright style cop a try. No joy. I will dig in to the spec/code tomorrow.

```plain
An error occurred while Style/Copyright cop was inspecting [snip]/test_file.rb.
Errors are usually caused by RuboCop bugs.
Please, report your problems to RuboCop's issue tracker.
Mention the following information in the issue report:
0.32.1 (using Parser 2.2.2.6, running on ruby 2.2.2 x86_64-darwin14)
```

**Comment by bbatsov** [comment]
A minimal reproducible use-case would be much appreciated. The cop's not on by default and hasn't been tested much in the field so far.

**Comment by philoserf** [comment]
Here was my use case. On OS X and Ruby 2.2.2 run `bundle gem test`, `touch .robocop..yml`, add

```yml
Style/Copyright:
  Enabled: true
```

Run `rubocop -a`

**Comment by bbatsov** [comment]
I meant we need some Ruby file that will produce this offense.

**Comment by philoserf** [comment]
The boiler plate created by bundle gem is enough. Even one of its .rb files is enough.

**Comment by philoserf** [comment]
I'll be able to look more closely at the code, the spec, and try some other ruby versions today.

**Comment by philoserf** [comment]
I have tested with clean ruby installations of Ruby 2.0.0-p645, 2.1.6, and 2.2.2 on OS X 10.10 using rbenv.

The Style/Copyright cop works with `rubocop` on the boilerplate created by `bundler gem test` on all these versions.

It fails with autocorrect enabled, `rubocop -a` on all these versions.

I will look at the autocorrect code in that cop next.

**Comment by philoserf** [comment]
I see the issue now.

When run as `rubocop -a` the error message is `An error occurred while Style/Copyright cop was inspecting /[snip]/test/Gemfile.`

But when rub as `rubocop -ad` we see the needed message `An error occurred while Style/Copyright cop was inspecting /Users/x3c3/test/spec/test_spec.rb.
An AutocorrectNotice must be defined in your RuboCop config`.

I am missing a required config value in my .rubocop.yml BUT I only learn that with debug enabled.

**Comment by philoserf** [comment]
**More detail**

With a `.rubocop.yml` with this content:

```yml
Style/Copyright:
  Enabled: true
  AutocorrectNotice: 'Copyright 2015 by name'
```

The autocorrect runs BUT injects the value as written `Copyright 2015 by name` which is invalid ruby. The correct output of the autocorrect must be `# Copyright 2015 by name`; however, if the `.rubocop.yml` is as follows:

```yml
Style/Copyright:
  Enabled: true
  AutocorrectNotice: '# Copyright 2015 by name'
```

then the cop fails with `AutocorrectNotice '# Copyright 2015 by name' must match Notice /^Copyright (\(c\) )?2[0-9]{3} .+/`
