### ISSUE TITLE
Drop syntax cop and replace it with separate RuboCop cops

### ISSUE THREAD

**Issue by bbatsov** [bbatsov/rubocop#207]
The syntax cop has several major issues:

* Running it is extremely slow - 3/4 of the time is spend spawing the external Ruby process, if we were spawning JRuby processes that would totally kill performance
* All Ruby interpreters have different warning/error messages
* Messages differ even between different versions of the same interpreter

I propose we change this like in the following manner:

* Use Parser's built-in capabilities to detect syntax errors
* Implement the most popular warnings from MRI as separate cops(unused variable, statement used in void context, assignment to constant, assignment in a condition, etc).

That shouldn't be too much work, but will make RuboCop run 3 times faster and truly portable.

Thoughts?

**Comment by alexdowad** [comment]
`Lint/AmbiguousOperator` has the "ambiguous first argument" warning covered.

**Comment by alexdowad** [comment]
`Style/SpaceAroundOperators` seems to warn in almost every circumstance where Ruby gives the "op after local variable is interpreted..." warning. Although the warning is a bit different from Ruby's, we are warning in those cases.

**Comment by alexdowad** [comment]
When Ruby warns about "Float out of range", RuboCop warns that "Line is too long"... :laughing:

**Comment by alexdowad** [comment]
The only way I can figure to get an "empty expression" warning out of Ruby, gives a `Lint/ParenthesesAsGroupedExpression` warning out of RC.

I think this issue can be closed.

**Comment by bbatsov** [comment]
> When Ruby warns about "Float out of range", RuboCop warns that "Line is too long"...

Probably we should have a proper lint for this and we can close this issue.

**Comment by alexdowad** [comment]
> Probably we should have a proper lint for this and we can close this issue.

MRI just relies on libc's `strtod` to convert from string to float. If `strtod` returns `ERANGE`, then Ruby displays the "Float out of range" error.

So what does `strtod` look like? I'm just looking at glibc's implementation... it's more than 1000 lines of C. Sigh...

**Comment by alexdowad** [comment]
It looks like glibc somehow computes the number of bits requires for the float's exponent and compares that to the number of bits available (which is platform-dependent). I haven't delved into the details more than that.

IEEE754's standard for double-precision floats gives 11 bits for the exponent and 52 bits for the fraction. A couple of bit patterns have special meanings, and the remaining ones can represent exponents of -1023 up to 1023 (I think). That's 2 ** -1023 up to 2 ** 1023. Multiply that by ((1 + fraction) * sign bit) to get the value of the number.

So any number with more than 1024 binary digits should overflow. If I'm not confused about my math, I think we can divide that by log2(10) to get the maximum number of decimal digits. It should be about 308.

**Comment by alexdowad** [comment]
I've confirmed that 308-309 decimal digits is where overflow of Floats occurs.

**Comment by bbatsov** [comment]
Guess this is good enough in terms of precision.
