### ISSUE TITLE
Can one use rubocop to correct ruby code in slim files?

### ISSUE THREAD

**Issue by AlexVPopov** [bbatsov/rubocop#2077]
I want to replace all old-hash syntax occurances in my slim view files in a rails project. I tried running `rubocop --only HashSyntax --auto-correct`, but it didn't do any corrections in `*.html.slim` files. Is it possible to do this?

**Comment by bbatsov** [comment]
See https://github.com/sds/slim-lint

**Comment by AlexVPopov** [comment]
:+1:
