### ISSUE TITLE
2.2 Hash syntax Cop

### ISSUE THREAD

**Issue by syndbg** [bbatsov/rubocop#2082]
The Ruby 2.2 Hash string key syntax completely breaks ruby code for versions < 2.2. Hence a cop for this would be immensely useful.

```
{
    'break': 'stuff'
}
```

I started researching the idea of adding a cop that checks for that. However the issue I faced so far is that Ruby string hashes get converted to symbols.

A simple string check in `hash_syntax.rb` is not enough. Ex:

```ruby
def on_hash(node)
   ...
   key.str_type?
   ...
end
```

My other ideas are parsing the `processed_source` using `investigate`, however at first this will be too troublesome to get working and will require a lot of tests to make sure that it performs well. Last but not at least, it looks like an overcomplicated solution.
  

As I'm thinking through this problem. From your experience, what approach would you suggest, guys?

**Comment by dziulius** [comment]
Rails 5.0 will be requiring ruby >= 2.2.2. And most stuff in ruby world is related to rails. So not sure what's the point of this cop?

**Comment by syndbg** [comment]
@dziulius Afaik Rubocop is not just for exclusive Rails use

**Comment by dziulius** [comment]
I'm not saying that it is. But there is lots of focus on that. Also I don't see a point not to use ruby 2.2. Which is faster, safer and has more features than rubies before.

**Comment by dziulius** [comment]
Just like when ruby 1.9 introduced json like hashes (for symbols) and now there is a cop which says that you should not use ```{ :key => :value }```, for ruby 2.2 there should be a cop which says that one should use ```{ 'some-key': 'value' }``` instead of ```{ 'some-key' => 'value' }``` - not the cop which says other way.

**Comment by pnomolos** [comment]
Not everyone can update to the latest and greatest.  A cop for library authors to ensure they guarantee backwards compatibility to whatever ruby version would be very helpful (and will return results faster than a CI server breaking on that ruby version).

**Comment by syndbg** [comment]
Can we agree that we need to have the options:
* to warn if 2.2 hash syntax is used
* to warn if 1.9 hash syntax is used

Which means that Ruby 1.9 developer should be able to:
* disable hash rockets
* disable 2.2 hash syntax

And Ruby 2.2 developer should be able to:
* disable hash rockets
* disable 1.9 hash syntax

**Comment by dziulius** [comment]
@syndbg this sounds awesome. How hard would it be to extend existing hash syntax cop?

**Comment by syndbg** [comment]
@dziulius Options - should be easy. The only problem is how to detect Hash 2.2 syntax usage. From my limited research (mentioned in the my first post), I have to manually traverse the AST. I'm still looking for other solutions.

**Comment by bbatsov** [comment]
@syndbg Feel free to work on this. In the mean time I'll close the ticket.
