### ISSUE TITLE
Show cop name in parenthesis

### ISSUE THREAD

**Issue by brauliobo** [bbatsov/rubocop#2083]
It is very hard to identify the cop only by the message it produces for a given line. For example:

    C: Avoid parameter lists longer than 5 parameters.

I'm forced to use github's repository search to find which Cop belongs the message.

**Comment by maxjacobson** [comment]
Rubocop has an option to display cop names. They're not in parentheses, but they're there :smile: 

Add this to your `.rubocop.yml`:

```
AllCops:
   DisplayCopNames: true
```

or run

`rubocop -D`

**Comment by brauliobo** [comment]
thanks @maxjacobson. but a default behaviour for this would help new users.
