### ISSUE TITLE
Favour Ternary Operation on Multi-branch if/elsif/elsif constructs.

### ISSUE THREAD

**Issue by TamerShlash** [bbatsov/rubocop#2090]
This code works fine without any warnings:

    if @operation.status == 'finished'
      'success'
    elsif @operation.status == 'failed'
      'danger'
    elsif @operation.status == 'started'
      'warning'
    end

The same code but with single-line if/then statements:

    if @operation.status == 'finished' then 'success'
    elsif @operation.status == 'failed' then 'danger'
    elsif @operation.status == 'started' then 'warning'
    end

Generates the warning:

> RuboCop: Favor the ternary operator (?:) over if/then/else/end constructs.

Maybe it should not :confused: 

RuboCop Version:

    $ rubocop -V
    0.32.1 (using Parser 2.2.2.6, running on ruby 2.2.2 x86_64-darwin14)

**Comment by bbatsov** [comment]
Yeah, that's clearly a bug.

**Comment by lumeet** [comment]
This seems to be fixed with #2095.
