### ISSUE TITLE
Space added inside do and end during --auto-correct when replacing a { }

### ISSUE THREAD

**Issue by Pierre-Sassoulas** [bbatsov/rubocop#2091]
Unfortunately I can't give the full code, but in loop with nokogiri (4/5 imbrications) I had the following change made with --auto-correct :
-        foo.each{
-        }
+        foo.each d  o
+        en  d

With a space in "do" and "end".

**Comment by Pierre-Sassoulas** [comment]
Here is an example of the problem. We can see that the rubocop add 2 spaces near the end instead of indenting for two spaces.

Before :
  def my_function(xml)
    xml['spams'].violations(:toolname => @spams.violations.toolname(),
                            :version => @spams.violations.version()){
        @spams.violations.get_violating_files.each { |file|
        xml['violations'].file(:path => file){
          violations = @spams.violations.violations(file)
          violations.each{ |violation|
            xml['violations'].violation(:column => violation.column ,
                                        :key => violation.key,
                                        :line => violation.line,
                                        :message => violation.message,
                                        :severity => violation.severity)
          }
        }
      }
    }
    return xml
  end

What rubocop output :

  def my_function(xml)
    xml['spams'].violations(toolname: @spams.violations.toolname(),
                            version: @spams.violations.version()) do
      @spams.violations.get_violating_files.each do |file|
        xml['violations'].file(path: file) d  o
        violations = @spams.violations.violations(file  )
        violations.each do |violation  |
          xml['violations'].violation(column: violation.column   ,
                                      key: violation.key  ,
                                      line: violation.line  ,
                                      message: violation.message  ,
                                      severity: violation.severity  )
        en  d
      end
      end
    end
    return xml
  end

Can run :

  def my_function(xml)
    xml['spams'].violations(toolname: @spams.violations.toolname(),
                            version: @spams.violations.version()) do
      @spams.violations.get_violating_files.each do |file|
        xml['violations'].file(path: file) do
        violations = @spams.violations.violations(file)
        violations.each do |violation|
          xml['violations'].violation(column: violation.column,
                                      key: violation.key,
                                      line: violation.line,
                                      message: violation.message,
                                      severity: violation.severity)
        end
      end
      end
    end
    return xml
  end

Better :

  def my_function(xml)
    xml['spams'].violations(toolname: @spams.violations.toolname,
                            version: @spams.violations.version) do
      @spams.violations.get_violating_files.each do |file|
        xml['violations'].file(path: file) do
          violations = @spams.violations.violations(file)
          violations.each do |violation|
            xml['violations'].violation(column: violation.column,
                                        key: violation.key,
                                        line: violation.line,
                                        message: violation.message,
                                        severity: violation.severity)
          end
        end
      end
    end
    xml
  end

**Comment by Pierre-Sassoulas** [comment]
Here is an example of the problem. You have before, after rubocop, a modification so that it runs again and the expected output.

Before :    
      def my_function(xml)
        xml['spams'].violations(:toolname => @spams.violations.toolname(),
                                :version => @spams.violations.version()){
            @spams.violations.get_violating_files.each { |file|
            xml['violations'].file(:path => file){
              violations = @spams.violations.violations(file)
              violations.each{ |violation|
                xml['violations'].violation(:column => violation.column ,
                                            :key => violation.key,
                                            :line => violation.line,
                                            :message => violation.message,
                                            :severity => violation.severity)
              }
            }
          }
        }
        return xml
      end

What rubocop output :

      def my_function(xml)
        xml['spams'].violations(toolname: @spams.violations.toolname(),
                                version: @spams.violations.version()) do
          @spams.violations.get_violating_files.each do |file|
            xml['violations'].file(path: file) d  o
            violations = @spams.violations.violations(file  )
            violations.each do |violation  |
              xml['violations'].violation(column: violation.column   ,
                                          key: violation.key  ,
                                          line: violation.line  ,
                                          message: violation.message  ,
                                          severity: violation.severity  )
            en  d
          end
          end
        end
        return xml
      end

Can run :

      def my_function(xml)
        xml['spams'].violations(toolname: @spams.violations.toolname(),
                                version: @spams.violations.version()) do
          @spams.violations.get_violating_files.each do |file|
            xml['violations'].file(path: file) do
            violations = @spams.violations.violations(file)
            violations.each do |violation|
              xml['violations'].violation(column: violation.column,
                                          key: violation.key,
                                          line: violation.line,
                                          message: violation.message,
                                          severity: violation.severity)
            end
          end
          end
        end
        return xml
      end

Better :

      def my_function(xml)
        xml['spams'].violations(toolname: @spams.violations.toolname,
                                version: @spams.violations.version) do
          @spams.violations.get_violating_files.each do |file|
            xml['violations'].file(path: file) do
              violations = @spams.violations.violations(file)
              violations.each do |violation|
                xml['violations'].violation(column: violation.column,
                                            key: violation.key,
                                            line: violation.line,
                                            message: violation.message,
                                            severity: violation.severity)
              end
            end
          end
        end
        xml
      end

**Comment by Pierre-Sassoulas** [comment]
Here is an example of the problem. You have before, after rubocop, a modification so that it runs again and the expected output.

Before :    
          def my_function(xml)
            xml['spams'].violations(:toolname => @spams.violations.toolname(),
                                    :version => @spams.violations.version()){
                @spams.violations.get_violating_files.each { |file|
                xml['violations'].file(:path => file){
                  violations = @spams.violations.violations(file)
                  violations.each{ |violation|
                    xml['violations'].violation(:column => violation.column ,
                                                :key => violation.key,
                                                :line => violation.line,
                                                :message => violation.message,
                                                :severity => violation.severity)
                  }
                }
              }
            }
            return xml
          end

What rubocop output :

      def my_function(xml)
        xml['spams'].violations(toolname: @spams.violations.toolname(),
                                version: @spams.violations.version()) do
          @spams.violations.get_violating_files.each do |file|
            xml['violations'].file(path: file) d  o
            violations = @spams.violations.violations(file  )
            violations.each do |violation  |
              xml['violations'].violation(column: violation.column   ,
                                          key: violation.key  ,
                                          line: violation.line  ,
                                          message: violation.message  ,
                                          severity: violation.severity  )
            en  d
          end
          end
        end
        return xml
      end

Can run :

      def my_function(xml)
        xml['spams'].violations(toolname: @spams.violations.toolname(),
                                version: @spams.violations.version()) do
          @spams.violations.get_violating_files.each do |file|
            xml['violations'].file(path: file) do
            violations = @spams.violations.violations(file)
            violations.each do |violation|
              xml['violations'].violation(column: violation.column,
                                          key: violation.key,
                                          line: violation.line,
                                          message: violation.message,
                                          severity: violation.severity)
            end
          end
          end
        end
        return xml
      end

Better :

      def my_function(xml)
        xml['spams'].violations(toolname: @spams.violations.toolname,
                                version: @spams.violations.version) do
          @spams.violations.get_violating_files.each do |file|
            xml['violations'].file(path: file) do
              violations = @spams.violations.violations(file)
              violations.each do |violation|
                xml['violations'].violation(column: violation.column,
                                            key: violation.key,
                                            line: violation.line,
                                            message: violation.message,
                                            severity: violation.severity)
              end
            end
          end
        end
        xml
      end

**Comment by Pierre-Sassoulas** [comment]
Here is an example of the bug. First the code before, the code after rubocop, 
a code that run after correcting rubocop, and what I think is the expected output.


Before :    
    def my_function(xml)
      xml['spams'].violations(:toolname => @spams.violations.toolname(),
                              :version => @spams.violations.version()){
          @spams.violations.get_violating_files.each { |file|
          xml['violations'].file(:path => file){
            violations = @spams.violations.violations(file)
            violations.each{ |violation|
              xml['violations'].violation(:column => violation.column ,
                                          :key => violation.key,
                                          :line => violation.line,
                                          :message => violation.message,
                                          :severity => violation.severity)
            }
          }
        }
      }
  return xml
end

What rubocop output :

      def my_function(xml)
        xml['spams'].violations(toolname: @spams.violations.toolname(),
                                version: @spams.violations.version()) do
          @spams.violations.get_violating_files.each do |file|
            xml['violations'].file(path: file) d  o
            violations = @spams.violations.violations(file  )
            violations.each do |violation  |
              xml['violations'].violation(column: violation.column   ,
                                          key: violation.key  ,
                                          line: violation.line  ,
                                          message: violation.message  ,
                                          severity: violation.severity  )
            en  d
          end
          end
        end
        return xml
      end

Can run :

      def my_function(xml)
        xml['spams'].violations(toolname: @spams.violations.toolname(),
                                version: @spams.violations.version()) do
          @spams.violations.get_violating_files.each do |file|
            xml['violations'].file(path: file) do
            violations = @spams.violations.violations(file)
            violations.each do |violation|
              xml['violations'].violation(column: violation.column,
                                          key: violation.key,
                                          line: violation.line,
                                          message: violation.message,
                                          severity: violation.severity)
            end
          end
          end
        end
        return xml
      end

Better :

      def my_function(xml)
        xml['spams'].violations(toolname: @spams.violations.toolname,
                                version: @spams.violations.version) do
          @spams.violations.get_violating_files.each do |file|
            xml['violations'].file(path: file) do
              violations = @spams.violations.violations(file)
              violations.each do |violation|
                xml['violations'].violation(column: violation.column,
                                            key: violation.key,
                                            line: violation.line,
                                            message: violation.message,
                                            severity: violation.severity)
              end
            end
          end
        end
        xml
      end

**Comment by Pierre-Sassoulas** [comment]
Here is an example of the bug. First the code before, the code after rubocop, 
a code that run after correcting rubocop, and what I think is the expected output.


Before :    
      def my_function(xml)
        xml['spams'].violations(:toolname => @spams.violations.toolname(),
                                :version => @spams.violations.version()){
            @spams.violations.get_violating_files.each { |file|
            xml['violations'].file(:path => file){
              violations = @spams.violations.violations(file)
              violations.each{ |violation|
                xml['violations'].violation(:column => violation.column ,
                                            :key => violation.key,
                                            :line => violation.line,
                                            :message => violation.message,
                                            :severity => violation.severity)
              }
            }
          }
        }
      return xml
      end

What rubocop output :

      def my_function(xml)
        xml['spams'].violations(toolname: @spams.violations.toolname(),
                                version: @spams.violations.version()) do
          @spams.violations.get_violating_files.each do |file|
            xml['violations'].file(path: file) d  o
            violations = @spams.violations.violations(file  )
            violations.each do |violation  |
              xml['violations'].violation(column: violation.column   ,
                                          key: violation.key  ,
                                          line: violation.line  ,
                                          message: violation.message  ,
                                          severity: violation.severity  )
            en  d
          end
          end
        end
        return xml
      end

Can run :

      def my_function(xml)
        xml['spams'].violations(toolname: @spams.violations.toolname(),
                                version: @spams.violations.version()) do
          @spams.violations.get_violating_files.each do |file|
            xml['violations'].file(path: file) do
            violations = @spams.violations.violations(file)
            violations.each do |violation|
              xml['violations'].violation(column: violation.column,
                                          key: violation.key,
                                          line: violation.line,
                                          message: violation.message,
                                          severity: violation.severity)
            end
          end
          end
        end
        return xml
      end

Better :

      def my_function(xml)
        xml['spams'].violations(toolname: @spams.violations.toolname,
                                version: @spams.violations.version) do
          @spams.violations.get_violating_files.each do |file|
            xml['violations'].file(path: file) do
              violations = @spams.violations.violations(file)
              violations.each do |violation|
                xml['violations'].violation(column: violation.column,
                                            key: violation.key,
                                            line: violation.line,
                                            message: violation.message,
                                            severity: violation.severity)
              end
            end
          end
        end
        xml
      end

**Comment by Pierre-Sassoulas** [comment]
Here is an example of the bug. First the code before, the code after rubocop, 
a code that run after correcting rubocop, and what I think is the expected output.


Before :
      def my_function(xml)
        xml['spams'].violations(:toolname => @spams.violations.toolname(),
                                :version => @spams.violations.version()){
            @spams.violations.get_violating_files.each { |file|
            xml['violations'].file(:path => file){
              violations = @spams.violations.violations(file)
              violations.each{ |violation|
                xml['violations'].violation(:column => violation.column ,
                                            :key => violation.key,
                                            :line => violation.line,
                                            :message => violation.message,
                                            :severity => violation.severity)
              }
            }
          }
        }
      return xml
      end

What rubocop output :

      def my_function(xml)
        xml['spams'].violations(toolname: @spams.violations.toolname(),
                                version: @spams.violations.version()) do
          @spams.violations.get_violating_files.each do |file|
            xml['violations'].file(path: file) d  o
            violations = @spams.violations.violations(file  )
            violations.each do |violation  |
              xml['violations'].violation(column: violation.column   ,
                                          key: violation.key  ,
                                          line: violation.line  ,
                                          message: violation.message  ,
                                          severity: violation.severity  )
            en  d
          end
          end
        end
        return xml
      end

Can run :

      def my_function(xml)
        xml['spams'].violations(toolname: @spams.violations.toolname(),
                                version: @spams.violations.version()) do
          @spams.violations.get_violating_files.each do |file|
            xml['violations'].file(path: file) do
            violations = @spams.violations.violations(file)
            violations.each do |violation|
              xml['violations'].violation(column: violation.column,
                                          key: violation.key,
                                          line: violation.line,
                                          message: violation.message,
                                          severity: violation.severity)
            end
          end
          end
        end
        return xml
      end

Better :

      def my_function(xml)
        xml['spams'].violations(toolname: @spams.violations.toolname,
                                version: @spams.violations.version) do
          @spams.violations.get_violating_files.each do |file|
            xml['violations'].file(path: file) do
              violations = @spams.violations.violations(file)
              violations.each do |violation|
                xml['violations'].violation(column: violation.column,
                                            key: violation.key,
                                            line: violation.line,
                                            message: violation.message,
                                            severity: violation.severity)
              end
            end
          end
        end
        xml
      end

**Comment by jonas054** [comment]
This was corrected in #2086. Merged to `master` but not released as a gem version yet.
