### ISSUE TITLE
Rubocop segfaults inside emacs

### ISSUE THREAD

**Issue by funglaub** [bbatsov/rubocop#2094]
I'm using rubocop 0.29.0 without any issues from my shell. However, inside emacs 24.5 (through prelude) rubocop throws a segmentation fault when invoked directly through `rubocop-check-current-file` or started inside Emacs' eshell or shell.

The output is simply `segmentation fault (core dumped)`. Any ideas what might cause the segmentation fault or any ideas how to track the problem down?

EDIT: I forgot to mention that this only happnes on linux, rubocop with an identical emacs configuration on OSX works inside emacs.

**Comment by bbatsov** [comment]
Hmm, this never happened to me, but I'm not using Linux myself (and I wrote Prelude, RuboCop and the Emacs integration). Do you have the problem with the latest RuboCop release as well?

**Comment by funglaub** [comment]
Yep, I tried 0.32.1 as well with the same result.

**Comment by funglaub** [comment]
The problem was that the stack size limit was too low. So not rubocop's fault ;)
