### ISSUE TITLE
Similar to #1898, consider the case that my method compares two hashes.

### ISSUE THREAD

**Issue by BCkwilliams** [bbatsov/rubocop#2099]
Get a redundant curly braces around a hash parameter error on the following line:
expect(diff({ 'a' => 's1' }, { 'a' => 's2' }).length).to eq(0)

I'm not sure that I should be getting a warning for this case. Yes, for test code I could pass in pre-defined hashes to avoid the error, but I shouldn't have to.

**Comment by jonas054** [comment]
There's already support for this special case: https://github.com/bbatsov/rubocop/blob/master/config/default.yml#L237
