### ISSUE TITLE
Capybara specific rules?

### ISSUE THREAD

**Issue by michaelachrisco** [bbatsov/rubocop#2104]
Does there exist a separate gem or something I can add that would lint capybara feature tests? 
I can think of a few off the top of my head:

* `feature` in favor of `describe ..., :type => :feature`
* `given` in favor of `let`
* `scenario` in favor of `it`
* `background` in favor of `begin`

If not, I suppose I can take a stab at a PR.

**Comment by bbatsov** [comment]
Nothing like this exists (to my knowledge). You can create a gem similar to [rubocop-rspec](https://github.com/nevir/rubocop-rspec) for this.
