### ISSUE TITLE
Style/OptionHash is possibly overeager

### ISSUE THREAD

**Issue by wli** [bbatsov/rubocop#2106]
First, I know this is disabled by default, so it's not super critical. However, I'd love to enable this cop by default in my projects.

I have the following function signature:

````
def get_unique_photo(photo_size = :large, used_photos = {})
````

`used_photos` isn't an option hash - it actually stores data that we use to calculate certain properties. I could change this to keyword arguments to get around this cop (or locally disable), but it doesn't seem like the right solution.

What do you think of changing this so it only errors out for `options = {}`, `args = {}`, or some other whitelist of acceptable names?

@maxjacobson - this was originally added in https://github.com/bbatsov/rubocop/issues/2030

**Comment by maxjacobson** [comment]
hey @wli! 

I did consider that...

What would the list be? I started thinking about people programming Ruby using non-English words for variable names and got dizzy

**Comment by maxjacobson** [comment]
Curious to hear from @yob and @bbatsov on this

**Comment by wli** [comment]
I can see how maintaining a list can be a nightmare. Maybe you can make an option on the cop for individual projects to specify their own whitelist/blacklist? Then rubocop-the-project doesn't care, but it'll work for more use cases.

**Comment by bbatsov** [comment]
I'm OK with having a list of param names that would trigger the offense.

**Comment by jfelchner** [comment]
@wli I think that's a great idea.  Maybe with some safe defaults: `options` and `args` makes sense.  Maybe look at rails/rails to get some more ideas?

**Comment by jfelchner** [comment]
Just throwing out more ideas for defaults: `rest`, `params`, `parameters`...

**Comment by bbatsov** [comment]
Sounds reasonable.

On 6 August 2015 at 12:10, Jeff Felchner <notifications@github.com> wrote:

> Just throwing out more ideas for defaults: rest, params, parameters...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bbatsov/rubocop/issues/2106#issuecomment-128300870>.
>



-- 
Best Regards,
Bozhidar Batsov

http://www.batsov.com

**Comment by wli** [comment]
I took a stab at this: https://github.com/bbatsov/rubocop/pull/2114

**Comment by bbatsov** [comment]
Fixed by https://github.com/bbatsov/rubocop/pull/2114
