### ISSUE TITLE
Style/InitialIndentation detects UTF-8 BOM as indentation

### ISSUE THREAD

**Issue by stefan-kolb** [bbatsov/rubocop#2111]
The new cop `Style/InitialIndentation` detects the UTF-8 Byte Order Mark (BOM) as indentation.
Maybe @jonas054 can have a look at it.

**Comment by TLmaK0** [comment]
@jonas054 with version 0.35.1 I can reproduce the problem:

```vi test.rb```

```
require 'test'
#
class TestBom
end
```

```:set bomb```

```:wq ```

```rubocop test.rb```

returns:

```
Inspecting 1 file
C

Offenses:

test.rb:3:1: C: Inconsistent indentation detected.
class TestBom
^^^^^^^^^^^^^

1 file inspected, 1 offense detected
```

**Comment by jonas054** [comment]
@TLmaK0 Can you open a new issue? It looks like the problem needs to be fixed in `Style/IndentationConsistency` too.

**Comment by TLmaK0** [comment]
sure, thanks
