### ISSUE TITLE
Breaking change in 6b73c740a5e40793c231b0a8d2c1c87f4e3ab604

### ISSUE THREAD

**Issue by l8nite** [bbatsov/rubocop#2117]
This commit (6b73c740a5e40793c231b0a8d2c1c87f4e3ab604) breaks existing rubocop.yml files with an explicit EnforcedStyle set - I'm not sure what rubocop's versioning strategy is, but this seems like a good thing to call out in release notes or major version change.

**Comment by bbatsov** [comment]
Every such change is documented in the changelog, I don't think anything else needs to be done regarding this.

**Comment by l8nite** [comment]
@bbatsov Have you considered moving to semantic versioning? http://semver.org/

**Comment by bbatsov** [comment]
Eventually we'll adopt semver. But not yet.

On Friday, August 7, 2015, Shaun Guth <notifications@github.com> wrote:

> @bbatsov <https://github.com/bbatsov> Have you considered moving to
> semantic versioning? http://semver.org/
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bbatsov/rubocop/issues/2117#issuecomment-128769736>.
>


-- 
Best Regards,
Bozhidar Batsov

http://www.batsov.com
