### ISSUE TITLE
An error occurred while Style/RescueEnsureAlignment cop was inspecting

### ISSUE THREAD

**Issue by rrosenblum** [bbatsov/rubocop#2119]
The error message is `undefined method 'include?' for nil:NilClass`. This is happening in version `0.33.0`.

I am trying to limit down the code that causes this issue to provide example source. Placing breakpoints in the code, it appears that `investigate` isn't being run so `@modifier_locations` is not set. 

A quick fix would be 
```ruby
def modifier?(node)
  @modifier_locations.include?(node.loc.keyword) if @modifier_locations
end
```
or initializing `@modifier_locations` to `[]`.

One of the safeguards is worthwhile, but I am more curious why `investigate` does not appear to be running at all.

**Comment by lumeet** [comment]
Any news on this, @rrosenblum? I haven't been able to reproduce the issue.

**Comment by rrosenblum** [comment]
I am working on reproducing the issue. I have been unable to boil the code down to a small reproducible state. The error consistently happens on one of my machines, but I can not reproduce it on another. 

The issue is that `investigate` is not being run, before or after `on_resbody` is being run. One of the fixes listed earlier will fix this issue, but I am unsure why the issue is happening in the first place.

**Comment by rrosenblum** [comment]
I found the issue, and a way to reproduce it. The issue isn't specifically with `Style/RescueEnsureAlignment`. It seems to be caused by excluding a file from a specific cop not working properly.

```yaml 
# .rubocop.yml
Style/RescueEnsureAlignment:
  Exclude:               
    - 'test.rb' 
```

```ruby
# test.rb
begin
  foo 
rescue
  bar 
end
```

When RuboCop is run, it will wind up inspecting the code in `test.rb` even though it is excluded. `investigate` is not run because of the code in `Commissioner#invoke_custom_processing` which is why `@modifier_locations` is `nil`.

This issue does not happen when the file is excluded from AllCops.

I am going to have to do some digging into how to fix this issue. 

Looping in @bbatsov and @jonas054.

**Comment by rrosenblum** [comment]
It appears that the way Excluded files are handled is that the cop runs all `on_` handlers in that file and then the offenses for that cop are ignored. `invoke_custom_processing` will skip running the `investigate` method on the file.

From the commissioner code
```ruby
  def investigate(processed_source)
    reset_errors
    prepare(processed_source)
    invoke_custom_processing(@cops, processed_source)
    invoke_custom_processing(@forces, processed_source)
    process(processed_source.ast) if processed_source.ast
    @cops.each_with_object([]) do |cop, offenses|
      filename = processed_source.buffer.name
      # ignore files that are of no interest to the cop in question
      offenses.concat(cop.offenses) if cop.relevant_file?(filename)
    end
  end
```

This doesn't seem like the best way to handle this. It would be preferable if we could avoid running the `on_` handlers in these cops all together. I will continue researching, but as of right now, I can not think of a way to implement this.

I will add a bug fix for `undefined method 'include?'` and continue researching a more thorough solution.
