### ISSUE TITLE
gsub -> tr cop messes up escaped string

### ISSUE THREAD

**Issue by cheerfulstoic** [bbatsov/rubocop#2154]
First off, thanks for rubocop!

So if I have a file like this:

```ruby
"".gsub('/', '\\')
```

rubocop (0.33.0 as well as GitHub `master`) transforms it to this:

```ruby
"".tr('/', '\')
```

This isn't good because Ruby sees the second single quote as being escaped and there syntax errors.

Here's the rubocop output:

```
$ rubocop -aD test.rb
Inspecting 1 file
F

Offenses:

test.rb:1:4: C: [Corrected] Performance/StringReplacement: Use tr instead of gsub.
"".gsub('/', '\\')
   ^^^^^^^^^^^^^^^
test.rb:1:12: F: unterminated string meets end of file
"".tr('/', '\')
           ^

1 file inspected, 2 offenses detected, 1 offense corrected
```

`rubocop -V`:

```
$ rubocop -V
0.33.0 (using Parser 2.2.2.6, running on ruby 2.0.0 x86_64-darwin14.3.0)
```

You can also see my `.rubocop.yml` and `.rubocop_todo.yml` here:

https://gist.github.com/cheerfulstoic/062fa3b79e8397b82c19

**Comment by rrosenblum** [comment]
Thanks for the bug report. Escape characters tend to get nasty when dealing with auto-correct. I have a test case for `"\n"`, but I guess that isn't good enough. I will look into a fix for this.

**Comment by cheerfulstoic** [comment]
Awesome, thanks ;)

**Comment by cheerfulstoic** [comment]
:metal: Thanks

**Comment by aevernon** [comment]
I see the behavior below on `master`:

```
$ git branch -v
* master a584c06
$ cat test.rb
''.gsub('\\', '')
$ rubocop -aD test.rb
Inspecting 1 file
F

Offenses:


test.rb:1:4: C: [Corrected] Performance/StringReplacement: Use delete instead of gsub.
''.gsub('\\', '')
   ^^^^^^^^^^^^^^
test.rb:1:11: F: unterminated string meets end of file
''.delete('\')
          ^

1 file inspected, 3 offenses detected, 2 offenses corrected
```

**Comment by rrosenblum** [comment]
Good catch. `'\\'` seems to be a special case compared to other escaped strings. I will find a fix.
