### ISSUE TITLE
Broken autocorrect behaviour with EndAlignment AlignWith: variable.

### ISSUE THREAD

**Issue by savef** [bbatsov/rubocop#2155]
I'm getting strange autocorrect behaviour with a file that looked like this:
```ruby
Rails.application.config.ideal_postcodes_key =
  if Rails.env.production? || Rails.env.staging?
    "AAAA-AAAA-AAAA-AAAA"
  else
    "BBBB-BBBB-BBBB-BBBB"
  end
```
Rubocop thought it should be this:
```ruby
Rails.application.config.ideal_postcodes_key =
  if Rails.env.production? || Rails.env.staging?
  "AAAA-AAAA-AAAA-AAAA"
else
  "BBBB-BBBB-BBBB-BBBB"
  end
```

This doesn't happen with a blank rubocop.yml, all you have to enable to cause it is:
```yml
Lint/EndAlignment:
  AlignWith: variable
```

---
Version (but I tried both the release and master on github and got the same behaviour):
`0.33.0 (using Parser 2.2.2.6, running on ruby 2.2.2 x86_64-linux)`

**Comment by bbatsov** [comment]
@jonas054 would you take a look at this?

**Comment by jonas054** [comment]
Yes.

**Comment by savef** [comment]
Thanks! :smile:
