### ISSUE TITLE
# rubocop:disable doesn't work on shebang comment lines

### ISSUE THREAD

**Issue by dmolesUC3** [bbatsov/rubocop#2166]
## Steps to reproduce:

1. Create the following file and name it `foo-bar`:

```ruby
#!/usr/bin/env ruby

puts 'foo'
```

2. Execute `rubocop ./foo-bar`:

```
$ rubocop ./foo-bar 
Inspecting 1 file
C

Offenses:

foo-bar:1:1: C: Use snake_case for source file names.
#!/usr/bin/env ruby
^
```

3. Edit the file and change the first line to

```ruby
#!/usr/bin/env ruby # rubocop:disable Style/FileName
```

4. Execute `rubocop ./foo-bar` again

## Expected:

File name style issue is ignored.

## Actual:

Same error as in step 2.

**Comment by bbatsov** [comment]
As this pertains to the entire file it can't be ignored inline. You can disable such checks using excluded files in `.rubocop.yml`.

**Comment by lain0** [comment]
```
#!/usr/bin/env ruby  # rubocop:disable Style/FrozenStringLiteralComment
# my_superscript.rb # rubocop:enable Style/FrozenStringLiteralComment
puts 'foo'
```
