### ISSUE TITLE
Style/HashSyntax (1.9 style) reports false positive with :[] as hash key

### ISSUE THREAD

**Issue by paulfri** [bbatsov/rubocop#2167]
Using `:[]` as a hash key (e.g. `{ :[] => 'value' }`, the Style/HashSyntax cop considers the hashrocket a violation, but `{ []: 'value' }` is a syntax error.

`0.30.0 (using Parser 2.2.2.6, running on ruby 2.2.2 x86_64-darwin14)`

**Comment by bbatsov** [comment]
Can't reproduce this with the latest version. Please, upgrade.

**Comment by paulfri** [comment]
Confirmed fixed, thanks.
