### ISSUE TITLE
Add RuboCop "team" on Gratipay?

### ISSUE THREAD

**Issue by L2G** [bbatsov/rubocop#2172]
It seems as if Gratipay has done away with allowing people to send donations to other Gratipay accounts "just because." It now looks like they require a "team" to be created for accepting donations for a particular cause.

At this writing, the existing link to Gratipay points directly to Bozhidar's profile, which provides no way to donate other than through the CIDER team.

**Comment by bbatsov** [comment]
I've been meaning to fix this, but gratipay's UI is pretty confusing and I can't understand how to add another team to my profile. Any pointers would be welcome! :-)

**Comment by jonas054** [comment]
There's an "Apply for a Team" link on this page: https://gratipay.com/about/features/payroll
Is that it?

**Comment by bbatsov** [comment]
So, I've added a new team - https://gratipay.com/rubocop/

Next step, how do I update the gratipay icon...
