### ISSUE TITLE
Request: CLI option for listing all the files rubocop plans to inspect

### ISSUE THREAD

**Issue by maxjacobson** [bbatsov/rubocop#2179]
Use case:

I'm using Circle CI for continuous integration, and it has a neat feature where you can split work over multiple machines and they'll be run in parallel. Here's a page from their docs explaining how to configure your build to split your tests across multiple machines: https://circleci.com/docs/parallel-manual-setup

If I had easy access to the list of files RuboCop is going to inspect (based on the default list + whatever is added in AllCops: Include) I could pipe that into a script like the bash script referenced in that page, and then split the work of inspecting code style across multiple machines.

What do you think? I'm happy to try and do it if you think it might be useful to other people than just me :smile: 

* [x] pick a name for the option
* [x] add tests for the option
* [x] make the tests pass
* [x] document in README

**Comment by bbatsov** [comment]
Another use case for this would be simply check if you got your excludes right. :-)

**Comment by mattjmcnaughton** [comment]
:+1: This sounds like a great idea!

**Comment by stardiviner** [comment]
Great idea, I like it too.

**Comment by bbatsov** [comment]
I guess the name of the option can be `--list-target-files`.

**Comment by maxjacobson** [comment]
Glad to see the enthusiasm :smile: https://github.com/bbatsov/rubocop/pull/2184

**Comment by jwg2s** [comment]
Anyone used this with test suite parallelism to have multiple containers run a subset of rubocop file targets?
