### ISSUE TITLE
Display only cops for files and lines that have changed

### ISSUE THREAD

**Issue by kbrock** [bbatsov/rubocop#2182]
Hello,

We display the rubocop warnings for only the lines changed in a pull request and not the whole code base. [example]

This allows us to

1. make warnings stringent without getting inundated with messages from our existing code base
2. prevent warning from getting introduced
3. slowly improve our code base

[script] uses git to determine the differences across revisions and prune the results of the actual rubocop call. (kudos to [gist])

Would anyone be interested in a feature like this?

[script]: https://github.com/zeari/miq-helpers/blob/master/murphy.sh
[gist]: https://gist.github.com/skanev/9d4bec97d5a6825eaaf6
[example]: https://github.com/ManageIQ/manageiq/pull/3730#issuecomment-128147990

**Comment by bbatsov** [comment]
Looks useful, but I'd rather us not include any VC-specific features.
