### ISSUE TITLE
Please consider adding an alias from --auto-correct to --autocorrect

### ISSUE THREAD

**Issue by shevegen** [bbatsov/rubocop#2189]
Hi there,

Please consider adding an alias from --auto-correct to --autocorrect so
that rubocop can be invoked via --autocorrect as well. The middle -
is a bit awkward for me to type, I would like to be able to also use
--autocorrect in addition to this.

If this is not to your liking, just close the issue request here, no problem
at all.

Thank you for reading!

**Comment by bbatsov** [comment]
We already have `-a`, as an alias for `--auto-correct`, so adding one more seems kind of redundant to me. @jonas054 Thoughts?

**Comment by jonas054** [comment]
Agreed. The long options are for readability, the short for ease of typing. A third seems redundant.
