### ISSUE TITLE
-auto-gen-config and --rails are order sensitive

### ISSUE THREAD

**Issue by agrimm** [bbatsov/rubocop#2194]
I can do

    bundle exec rubocop --rails --auto-gen-config

but not

    bundle exec rubocop --auto-gen-config --rails

getting the error message

    --auto-gen-config can only be combined with --exclude-limit.

There may be a good reason to only allow `--rails` before `--auto-gen-config`, rather than afterwards, but as it's currently written, people may think that it's just not possible to use `--rails` at all.

**Comment by jonas054** [comment]
I think I was the one who added the validation for `--auto-gen-config` a long time ago, and I obviously made a mistake. This might be a good opportunity to improve it and not be more strict that we need to. What's wrong with combining `--auto-gen-config` with other options really? How about assuming that people know what they're doing instead?
