### ISSUE TITLE
Handle string continuations as a single string

### ISSUE THREAD

**Issue by FooBarWidget** [bbatsov/rubocop#2195]
My program outputs long messages. In order to adhere to the 80-column limit, I break my strings into multiple lines using the `\` operator, like this:

    UnionStationHooks::Log.debug("[Union Station log to null] " \
      "#{@txn_id} #{Utils.timestamp_string} #{text}")

However, despite the fact that this is in fact a single string, Rubocop thinks it's two separate strings. It therefore complaints that the first line uses double quotes instead of single quotes. I think mixing single and double quotes *in the same string* is ugly.

Please handle string continuations like a single string.

**Comment by bbatsov** [comment]
I consider the current behaviour to be just fine. While the string is treated as one in the end, it's really several separate strings at parse time.

**Comment by dragostis** [comment]
The behavior is fine, but you may get something like:

```
'This is a very long paragraph ' \
'that will be split into multiple lines ' \
"but which can also have #{string} interpolation. " \
'You see?'
```

Here, you're using two types of quotes for the same string. If this is a problem or not, remains for you to consider.

**Comment by bbatsov** [comment]
Yeah, yeah - it was clear to me what you were referring to. It's definitely not a problem for me, but we can  always make this configurable.

**Comment by FooBarWidget** [comment]
It looks ugly to me. I prefer to have consistent style within the same string, even if the string is split into parts. A configuration option would be preferable to me.

**Comment by bbatsov** [comment]
PR welcome. :-)

**Comment by alexdowad** [comment]
Is anyone planning to take this one on? If not, I would suggest that it be closed.

**Comment by bbatsov** [comment]
Guess not. Let's close it.
