### ISSUE TITLE
Wrong exit code when there are only UnneededDisable offenses

### ISSUE THREAD

**Issue by jonas054** [bbatsov/rubocop#2199]
Discovered something while looking at #2198.

The [Travis build](https://travis-ci.org/bbatsov/rubocop/builds/77897800) on `master` passes even though we have an offense detected by the `Lint/UnneededDisable` cop. My fault so I will fix it.

**Comment by bbatsov** [comment]
Ops, should have read https://github.com/bbatsov/rubocop/pull/2198 first. :-)
