### ISSUE TITLE
Spurious Lint/UnusedBlockArgument for lambda in MiniTest::Spec test setup.

### ISSUE THREAD

**Issue by jdickey** [bbatsov/rubocop#2202]
Fragment of spec exhibiting problem:

```ruby
describe 'Widgets::Page::FullNavbar' do
  let(:described_class) { Widgets::Page::FullNavbar }

  describe 'accepts parameters for' do
    after do
      expect { described_class.new @params }.must_be_silent
    end

    # other items omitted

    it 'menu_adder' do
      menu_adder = -> (el) { el { a('Home', href: '#') } }
      @params = { menu_adder: menu_adder }
    end
  end # describe 'accepts parameters for'
end # describe Widgets::Page::FullNavbar
```

Leaving the illustrated `it` call as is results in

```
$ bundle exec rubocop -R test/views/page/full_navbar_test.rb
Inspecting 1 file
W

Offenses:

test/views/page/full_navbar_test.rb:24:24: W: Unused block argument - el. If it's necessary, use _ or _el as an argument name to indicate that it won't be used. Also consider using a proc without arguments instead of a lambda if you want it to accept any arguments but don't care about them.
      menu_adder = -> (el) { el { a('Home', href: '#') } }
                       ^^

1 file inspected, 1 offense detected
$
```

The `el` in question is an element widget created using [`Fortitude`](https://github.com/ageweke/fortitude), if it matters.

What am I missing?

**Comment by alexdowad** [comment]
What you are missing is that the `el` in `-> (el)` is a method parameter, essentially like a local variable within the anonymous function, but the 2nd `el, in `el { a('Home', href: '#') }` is a method call on `self`.

It is the same as if you wrote `self.el { a('Home', href: '#') }`. The two instances of the identifier `el` are referring to different things.

That is why it says the `el` parameter is unused.

**Comment by alexdowad** [comment]
This can be closed.
