### ISSUE TITLE
Replacement of has_key? with key?

### ISSUE THREAD

**Issue by andrea-capri** [bbatsov/rubocop#2235]
rubocop auto_correct replaced ``has_key?`` with ``key?`` but the function was a custom function. This obviously broke functionality

**Comment by jonas054** [comment]
Can you give some more details about the code that was changed? There's not enough information here to work on a solution.

**Comment by bbatsov** [comment]
Btw, this is simply one of those cops that can produce false positives (like `CollectionMethods`). But this produces them so often that I'd simply suggest disabling it when it's problematic. On a related note - you should have probably named that custom function `key?` as well.
