### ISSUE TITLE
"Provide an exception object as an argument to fail" offense seems to do the opposite of the styleguide

### ISSUE THREAD

**Issue by UberMouse** [bbatsov/rubocop#2236]
I've just run into something that Rubocop is considering an offense despite the fact I was doing it the correct way according to the style guide (entry https://github.com/bbatsov/ruby-style-guide#exception-class-messages), it in fact wants me to do it in the way the style guide marks as bad. 

Line of code in question 
`fail Exception, errors.join(' ----- ') unless errors.empty?`

Rubocop raises the following offense
`spec/support/api_schema_matcher.rb:10:5: C: Provide an exception object as an argument to fail.`
until I change the code to 
`fail Exception.new(errors.join(' ----- ')) unless errors.empty?`

which if I am reading the style guide correctly is the exact opposite of what it recommends I do.

I am using Rubocop 0.34.0

**Comment by jonas054** [comment]
You must have

```yaml
Style/RaiseArgs:
  EnforcedStyle: compact
```
in your configuration. The default is `exploded`, which is what's recommended by the style guide.

**Comment by UberMouse** [comment]
Is it possible that was added to the `.rubocop_todo.yml` file when I auto generated the config? There were thousands of errors so it's quite large. I can't show you either of the rubocop configs since I am not at work but I definitely didn't add that to my custom .rubocop.yml, so it should be using it from the default configuration?

**Comment by jonas054** [comment]
Seems likely that it's in `.rubocop_todo.yml`. If so, it overrides the default configuration.

**Comment by UberMouse** [comment]
It was in the .rubocop_todo.yml
