### ISSUE TITLE
Configuration option to allow two empty lines between elements

### ISSUE THREAD

**Issue by kevgo** [bbatsov/rubocop#2250]
I prefer two empty lines between major parts in code, for better readability.

```ruby
class Foo

  def bar1
    return unless xxx
    return unless yyy

    # do something here
  end


  def bar2
    return unless xxx
    return unless yyy

    # do something here
  end


  def bar3
    return unless xxx
    return unless yyy

    # do something here
  end

end
```

Since blocks inside my methods can be separated by a single empty line, I like separating method declarations by double empty lines. It also makes the code read less crammed

A configuration option to specify the number of allowed empty lines between method declarations, defaulting to 1, would be useful for this type of code.

**Comment by alexdowad** [comment]
@bbatsov Do you want this style for `Style/EmptyLineBetweenDefs`? Would you merge a PR?

**Comment by bbatsov** [comment]
I don't really like this idea and nobody else has expressed interest in the suggested style. Let's close this issue. 

Btw, a simple way to solve this would be to make the number of lines between def configurable, but I really think that 0 and 1 are the only common values people would use.
