### ISSUE TITLE
[Feature Request] Support add default argument in ~/.rubocop.yml

### ISSUE THREAD

**Issue by zw963** [bbatsov/rubocop#2253]
Support add default argument in ~/.rubocop.yml, e.g. settings default formatter to emacs (-fe)

**Comment by zw963** [comment]
like a function in bash shell, e.g.

```sh
function rubocop () {
    command rubocop -fe "$@"
}
```

**Comment by jonas054** [comment]
At this point it would be difficult to introduce a configuration parameter acting as "generic default command line options", because we've already added a lot of configuration parameters that are default values for individual CLI options:
* RunRailsCops
* DisplayCopNames
* DisplayStyleGuide 
* StyleGuideCopsOnly
* DisabledByDefault
* UseCache

But I do think it would be possible to add an `AllCops: DefaultFormatter` parameter, perhaps limited to setting only one formatter, and not dealing with the `--out` option.

**Comment by zw963** [comment]
thanks.

AllCops: DefaultFormatter is good, I just hope can config more things
with my personal ~/rubocop.yml

**Comment by tigris** [comment]
I approve of this feature, I was just trying to implement it myself.

**Comment by alexdowad** [comment]
One problem with that is that `.rubocop.yml` is not just one file. There can be many; one in each project subdirectory. *When* RC is ready to check a file, it finds the configuration which applies to that particular file.

So what if you had multiple `.rubocop.yml` files in various subdirectories, with *different* `AllCops: DefaultFormatter` parameters?

I am inclined to say that a shell alias would be the best thing for you.

**Comment by apowers** [comment]
I would like to be able to set a default formatter. And especially when running rubocop as a rake task.

"What if you had multiple values of DefaultFormatter?" Well, what if you have multiple values of any parameter? You must already have an order of precedence or enabling a cop in one place and disabling it in another would be very interesting.

**Comment by alexdowad** [comment]
@apowers, there is a big difference. Most parameters make sense even if changed for each source file. And that is what RC does, if you have different RC config files in different subdirectories. The proposed `DefaultFormatter` parameter doesn't make sense if changed from one source file to the next.

Actually, the internal methods which select the formatter(s) to use don't even look at the paths to the files being checked. It shouldn't matter when selecting the formatter.

**Comment by jonas054** [comment]
@alexdowad What you say is correct, but there is a way to circumvent the problem posed by our per-directory configuration functionality. The trick is to say that a global config parameter like that is taken from the configuration for the *current directory*. I used it [here](https://github.com/bbatsov/rubocop/blob/master/lib/rubocop/result_cache.rb#L61) when I faced a similar problem for `AllCops: MaxFilesInCache`.

**Comment by alexdowad** [comment]
@jonas054, OK, let me code something up.
