### ISSUE TITLE
How should Metrics cops behave with auto-gen-config and exclude-limit?

### ISSUE THREAD

**Issue by agrimmtt** [bbatsov/rubocop#2256]
If auto-gen-config can deal with an offense with a metric cop either by increasing the metric value, or by adding it to an `Exclude` list, what approach should it take?

Scenario 1: a project has five files. do_a.rb has a Metrics/LineLength offense, caused by having a line of code with a length of 200. Under the status quo, running `--auto-gen-config` will generate

    Metrics/LineLength:
      Max: 200

Should it instead generate

    Metrics/LineLength:
      Exclude:
        - 'do_a.rb'

Scenario 2: A project has 10 files containing a line 250 characters long or longer, with the worst file having a line that's 450 characters long, and another 10 files containing a line 150 characters long. Under the status quo, running `--auto-gen-config` will generate

    Metrics/LineLength:
      Max: 450

Should it instead generate

    Metrics/LineLength:
      Max: 250
      Exclude:
        - 'bad_file_1.rb'
        - 'bad_file_2.rb'
        - 'bad_file_3.rb'
        - 'bad_file_4.rb'
        - 'bad_file_5.rb'
        - 'bad_file_6.rb'
        - 'bad_file_7.rb'
        - 'bad_file_8.rb'
        - 'bad_file_9.rb'
        - 'bad_file_10.rb'

The advantage of the current approach is that it does [ratcheting](http://martinfowler.com/articles/useOfMetrics.html#MetricsAsARatchet) on the worst offender. However, it means any file not as bad as the worst offender won't generate an offense.

This is inconvenient when I've got an attitude of "I'm aware file X has a bad metric, and don't want to / don't have the time to fix it".

**Comment by jonas054** [comment]
It's an interesting question. I've experimented a little with how such a feature could be implemented. It's a little tricky but definitely doable.

Ultimately, though, I think that the current functionality gives better support for the most productive way of working with metrics violations, which is the ratcheting methodology that you mention.

> This is inconvenient when I've got an attitude of "I'm aware file X has a bad metric, and don't want to / don't have the time to fix it".

An offense that you don't intend to fix should not be disabled in `.rubocop_todo.yml`. It make no sense to have things  you're not going to do on your todo list. Instead, the offense should be disabled locally with a `rubocop:disable` comment (as we have done a few times in the RuboCop source code), or be excluded in `.rubocop.yml`.

**Comment by agrimmtt** [comment]
> It make no sense to have things you're not going to do on your todo list.

Good point!
