### ISSUE TITLE
Parse markdown files

### ISSUE THREAD

**Issue by dblock** [bbatsov/rubocop#2279]
What do you think of RuboCop parsing markdown files' code blocks?

Would have caught https://github.com/ruby-grape/grape/pull/1166 for example.

**Comment by jonas054** [comment]
I would say that extracting Ruby code from other file formats than plain old Ruby source code is not a responsibility we want to add to RuboCop. It's better suited for some companion project. Either as a wrapper that calls the rubocop program after preparing some source code files, or as a plug-in, but that would probably require some work on the currently very basic plug-in architecture.

There's a lot of complexity in running on snippets of code. Sometimes the snippet is not parseable. Sometimes it will trigger reports that are irrelevant in the snippet context, e.g. `Lint/UselessAssignment`.

**Comment by bbatsov** [comment]
I agree that this seems outside the scope of the project. Perhaps it'd be nice if someone created a separate project to tackle this.
