### ISSUE TITLE
No such file or directory @ rb_sysopen /path_to_repo/.rubocop_todo.yml

### ISSUE THREAD

**Issue by skywinder** [bbatsov/rubocop#2283]
Got error `No such file or directory @ rb_sysopen /path_to_repo/.rubocop_todo.yml`

When there is no `.rubocop_todo.yml` file in repo.

    rubocop -v
    0.34.2

    ruby -v
    ruby 2.1.6p336 (2015-04-13 revision 50298) [x86_64-darwin14.0]

**Comment by jonas054** [comment]
I think you have the line

```yaml
inherit_from: .rubocop_todo.yml
```

in your `.rubocop.yml` file. Then the error message is expected.

**Comment by skywinder** [comment]
Exactly. Sorry. 
Just a copy-paste yml file and miss this first line (usually it's shebang string in this place and I automatically skip it, when read file)
