### ISSUE TITLE
ResultCache's path should include RUBY_VERSION

### ISSUE THREAD

**Issue by miquella** [bbatsov/rubocop#2284]
The parser gem chooses which parser to use based on `RUBY_VERSION`. Because of this, it is possible, if the same version of rubocop is installed under two different versions of ruby on the same machine, to get different results from each. But because of the caching in rubocop 0.34, one set of results would be masked/hidden.

To work around this issue, `RUBY_VERSION` should be included in the ResultCache's path.

**Comment by jonas054** [comment]
I agree. There are some offenses that are not reported for all ruby versions, so we should add `RUBY_VERSION` to the path.
