### ISSUE TITLE
Combination of cops to achieve following method call with options hash parentheses alignment

### ISSUE THREAD

**Issue by agibralter** [bbatsov/rubocop#2291]
Is there any combination of cop settings to enforce the following style for methods calls with options hashes?

```ruby
my_method(arg1, arg2,
  :option1 => 'foo',
  :option2 => 'bar',
)
```

Seems I can only achieve the enforcement of the following two:

```ruby
my_method(
  arg1,
  arg2,
  :option1 => 'foo',
  :option2 => 'bar',
)
```

or

```ruby
my_method(arg1, arg2,
  :option1 => 'foo',
  :option2 => 'bar',
         )
```

Any thoughts? I'm open to hearing opinions about why my proposed style is not worth enforcing in the first place :smile:.

**Comment by jonas054** [comment]
If you had an `arg3` that didn't fit on the same line as `arg1` and `arg2`, what would that look like?

**Comment by agibralter** [comment]
@jonas054 heh, probably

```ruby
my_method(
  arg1,
  arg2,
  :option1 => 'foo',
  :option2 => 'bar',
)
```

Ok, I'm sold. Especially seeing as keyword arguments are a first class citizen now... Thank you for humoring my curiosity.
