### ISSUE TITLE
Performance/StringReplacement doesn't check for case insensitivity

### ISSUE THREAD

**Issue by matthewd** [bbatsov/rubocop#2294]
```
0.34.2 (using Parser 2.2.2.6, running on ruby 2.2.3 x86_64-darwin14)
```

Performance/StringReplacement auto-corrects:
```ruby
s.gsub(/x/i, 'q')
s.gsub(/z/i, '')
```

to:
```ruby
s.tr('x', 'q')
s.delete('z')
```

The new versions no longer match `X` and `Z` respectively.

**Comment by rrosenblum** [comment]
Thanks for the bug report. I forgot to account for regex options. I am working on a fix for this now.
