### ISSUE TITLE
error if method name already declared

### ISSUE THREAD

**Issue by jney** [bbatsov/rubocop#2300]
it seems it is not an implemented feature - or i didn't find how to activate it - but i was wondering how rubocop could warn me if a method is declared several time in a single `module` or `class`. 
it would be a plus for me, and would have prevent a bug on the project my team is working on.

**Comment by jonas054** [comment]
The feature exists and is enabled by default.
```
$ cat multiple_def.rb 
# Example class
class C
  def a
  end

  def a
  end
end
$ rubocop -D multiple_def.rb 
Inspecting 1 file
W

Offenses:

multiple_def.rb:6:3: W: Lint/DuplicateMethods: Duplicate methods a at lines 3, 6 detected.
  def a
  ^^^

1 file inspected, 1 offense detected
```

**Comment by bbatsov** [comment]
This works only in the same lexical scope, of course. We don't keep track of all the inspected files and we don't plan do ever do so, as it would increase the complexity quite a lot.
