### ISSUE TITLE
False redundant `return` flag

### ISSUE THREAD

**Issue by pugsiman** [bbatsov/rubocop#2315]
Rubocop flags `line`'s `return` as redundant as seen here:
![capture](https://cloud.githubusercontent.com/assets/12158433/10434236/ff1924cc-7120-11e5-914b-684b900c0451.PNG)
But in this context, removing `return` will result in syntax error similar to this: 
![capture](https://cloud.githubusercontent.com/assets/12158433/10434326/8733bbba-7121-11e5-980d-15ceb006eb3a.PNG)

**Comment by bbatsov** [comment]
Auto-correct will replace this with an array. We can have a config option for people who'd prefer to use `return` is such situations.
