### ISSUE TITLE
Bug in Performance/Size

### ISSUE THREAD

**Issue by JuanitoFatas** [bbatsov/rubocop#2331]
Given this code:

```ruby
def foo
  [1, 2].count(1)
end
```

When you run rubocop 0.34.2 yields:

```
C: Performance/Size: Use size instead of count.
```

When `#count` has an argument, shouldn't give this advice? Thanks!

**Comment by rrosenblum** [comment]
You are correct. This is a bug. I will have a fix for it shortly

**Comment by JuanitoFatas** [comment]
Closed. See #2333. Thank you @rrosenblum :+1:
