### ISSUE TITLE
Style/PredicateName for has_...?

### ISSUE THREAD

**Issue by obfuscoder** [bbatsov/rubocop#2336]
I cannot find any resources explaining why Rubocop thinks it is bad to have predicate methods like **has_something?**.

RSpec is supporting such predicate names by allowing expectations for them like this:

```ruby
expect(foo).to have_something
```

To not violate this coding rule we would need to use weird wording like **with_something?** and are forced to use Rspec like this:

```ruby
expect(foo).to be_with_something
```

This, however, raises concerns within our team and we are thinking about disabling this rule as I could not find any reasons behind it.

**Comment by bbatsov** [comment]
This was based on upstream decisions in Ruby like deprecating `has_key?` in favour of `key?`. We've generally tried to stayed consistent with Matz's preferences for predicate method names. This is configurable in RuboCop, so you can disable it if you wish to.

**Comment by obfuscoder** [comment]
Is there any written statement of Matz about this topic somewhere? You stated that there is a reference in each rule as long as it is not obvious.

I'd rather not disable the rule itself - just the has_-part if possible.

**Comment by obfuscoder** [comment]
Ok, I found the options NamePrefix and NamePrefixBlacklist. I'll try and disable the has option only. The source reference would be great nonetheless.

**Comment by bbatsov** [comment]
Here you go http://blade.nagaokaut.ac.jp/cgi-bin/scat.rb/ruby/ruby-core/43765
