### ISSUE TITLE
How to avoid Multiline block chains? What is the recommended style?

### ISSUE THREAD

**Issue by wazery** [bbatsov/rubocop#2338]
I have the following code

```ruby
    EM.run do
      Pusher.get_async('/channels/' + pusher_channel).callback do |response|
        handle_response(response)
      end.errback do |error|
        handle_error(error)
      end
    end
```

For now I disable it with `# rubocop:disable Style/MultilineBlockChain` which I need to resolve.

As you can see, the block chaining is necessary for me since I need to handle the `errback`.

So what is the recommended style for this, I see that the Ruby style guide recommends avoiding using multiline block chains, but with not proposing any other option for it!

**Comment by maxjacobson** [comment]
maybe

```ruby
EM.run do
  something = Pusher.get_async('/channels/' + pusher_channel).callback do |response|
    handle_response(response)
  end

  something.errback do |error|
    handle_error(error)
  end
end
```

**Comment by alexdowad** [comment]
@wazery, does @maxjacobson's answer satisfy you?

**Comment by esad** [comment]
@bbatsov @alexdowad Can someone elaborate why this "style fix" is enabled per default? I really don't see why having an intermediate variable is a huge improvement over tacit-style of chaining blocks together?

**Comment by alexdowad** [comment]
@esad It's just an aesthetic judgement. To many (but not all) programmers' eyes, code which uses `... end.method ...` is slightly less readable than code which doesn't. This is especially so to those who are not very familiar with Ruby.

Nobody is saying it's a "huge improvement". It's a marginal improvement.

**Comment by alexdowad** [comment]
...And we do recommend that you disable the check on your own projects if you disagree.

**Comment by esad** [comment]
@alexdowad A tool such as Rubocop should be more than an arbitrary set of style choice and should aim to codify good pratices. In this sense, I think that every check should have a documented rationale why it exists and why the style it warns is considered bad.

**Comment by alexdowad** [comment]
> I think that every check should have a documented rationale why it exists

Sure. Nobody will argue with that.

There's a lot of things which RC should do but doesn't. It's a work in progress.

**Comment by esad** [comment]
//cc @jonas054

**Comment by jonas054** [comment]
If you run `rubocop -S`, you'll get a link to the [relevant style guide section](https://github.com/bbatsov/ruby-style-guide#single-line-blocks), so in this case the rule isn't arbitrary at all.

Speaking more generally, I think it's better if RuboCop is too strict by default than too lenient. There's the issue of discoverability. Cops that don't report will go unnoticed.

So don't let RuboCop be your master. If you disagree with a style choice, configure the cop if that's possible, or disable it if it's not.

**Comment by dbodow** [comment]
I've found splitting the block taking method onto the next line to be helpful for this cop, eg:
```
    EM.run do
      Pusher.
        get_async('/channels/' + pusher_channel).
        callback { |response| handle_response(response) }.
        errback { |error| handle_error(error) }
    end
```
It's particularly helpful for me when trying to comprehend what a long chain of enumerators is doing.

**Comment by klausbadelt** [comment]
@dbodow's suggestion simply changes the blocks to single line - the issue though is _multi line_ blocks. I personally agree that multi-line chaining is not 'ugly' but very 'Ruby'. 

Just my (way too late and personal) opinion - that's why Rubocop is configurable. A pleasure to use!

**Comment by dcorking** [comment]
I like the suggestion in the style guide to ask:
> is this code really readable and can the blocks' contents be extracted into nifty methods?
Like @klausbadelt  I have written lots of Ruby like this, but today I asked this, extracted my block, and feel I have made the code a little better.

**Comment by ryan2johnson9** [comment]
> I like the suggestion in the style guide to ask:
> 
> > is this code really readable and can the blocks' contents be extracted into nifty methods?
> 
> Like @klausbadelt I have written lots of Ruby like this, but today I asked this, extracted my block, and feel I have made the code a little better.

thanks for the reminder, I sometimes just give in to Rubocop and suddenly the code is way better. Happened to me in this case again.

**Comment by KelseyDH** [comment]
Doesn't this multi-line block rule force the user into creating more _variable assignments_, which then runs them afoul of rubocop's `Assignment Branch Condition size (convention:Metrics/AbcSize)`?  

It's a catch 22, you can't win!

**Comment by alexdowad** [comment]
@KelseyDH, it sounds like you need to decide which 'principles' should be followed by your project and then configure RC accordingly.

**Comment by Drenmi** [comment]
Using RuboCop and using your own judgement are not mutually exclusive but actually complementary, as RuboCop can't make any judgement calls at all, but is very good at taking care of a lot of the tedium and help with consistency. 🙂 

If your judgement tells you that you have the most well-factored or readable version of your code, then you're probably right, and can use the configuration options in conjunction with selective disabling of rules to tell RuboCop. 🙂 

There are many ways, in fact, to configure the different rules in ways that contradict each other. This is a result of the RuboCop core team at some point changing the goal of enforcing The Ruby Style Guide to being fully configurable. Some people will still insist that the default configuration is some sort of recommendation, but it is not.

**Comment by KelseyDH** [comment]
Many companies force their developer's to follow rubocop's full defaults.  I know that's not what is recommended, but that is how rubocop gets used in practice.  

Consider that when people complain about rubocop being overly arbitrary, and the response from maintainers is no justification for the rules but just that they can just disable that rule:  we can't. We tried. Management / devops said no. e.g. Shopify's default ruby parser literally auto-removes comments that disable rubocop.  We are not in a position to challenge it.  We are 100% reliant on the style choices of rubocop not being arbitrary.

**Comment by alexdowad** [comment]
@KelseyDH, that's an unfortunate position to be in. Thanks for providing this information.

I'm sure you can appreciate that it makes it difficult for the RC developers to help users if the users cannot or will not follow advice. More could be said, but I won't belabor that point.

As a suggestion, perhaps the most pragmatic course of action which you could undertake (if you want to make things better for yourself and others like you) would be to submit a PR raising the default threshold for `Metrics/AbcSize`. The primary maintainer of RC has made it clear that he wants RC's defaults to be strict rather than lenient, so completely disabling this "cop" by default would be less likely to be accepted.

Before anyone asks, I am not available to prepare a PR, review a PR, advocate for a PR, etc. It would be interesting to hear if you do get one accepted, though.

**Comment by bbatsov** [comment]
> The primary maintainer of RC has made it clear that he wants RC's defaults to be strict rather than lenient, so completely disabling this "cop" by default would be less likely to be accepted.

In recently years I'm actually learning towards more lenient defaults (in particular fewer cops enabled by default), but:

- any change of defaults is a breaking change, so it has to be considered carefully
- the metrics cops in particular don't make much sense if they are too lenient 

I wrote some thoughts about the future of RuboCop [here](https://metaredux.com/posts/2022/04/21/rubocop-turns-10.html), in case someone's curious about it.
