### ISSUE TITLE
Rubinius 2.5.8: Segmentation Faults

### ISSUE THREAD

**Issue by dblock** [bbatsov/rubocop#2348]
Seeing regular segfaults on Rubinius, here's [one](https://travis-ci.org/intridea/hashie/jobs/87430922). Didn't debug yet, but consistent on the Hashie codebase.

**Comment by mikegee** [comment]
Was this issue supposed to be opened on the Hashie repo?

**Comment by dblock** [comment]
Nope, rubocop is causing a segfault.

**Comment by bbatsov** [comment]
Pretty sure Rubinius is to blame for the segfault, as we've had a ton of issues with it over the years. Not sure what we're supposed to do about it. I'm guessing you'd like some custom handling of Rubinius to sidestep that particular problem.

**Comment by dblock** [comment]
Of course it's rubinius, I'll try to locate the code that causes the segfault regularly, then we can call out a bug in rubinius and close it here.

**Comment by alexdowad** [comment]
RuboCop does not use any C extensions, so a segfault can automatically be "blamed" on the interpreter.

I would break out my trusty `gdb`, find the source of the crash, and send them a patch, but my past experience dealing with the Rubinius team has been... less than ideal, and makes me reluctant. If it was MRI, I'd be all over it.

Have a look at the number of open issues mentioning "segfault" or "crash" at https://github.com/rubinius/rubinius/issues. There are plenty, some of them years old.

If you do want to pinpoint what is causing the crash, start with a fresh checkout of the RuboCop repo, and confirm that you can reproduce the crash consistently. Then start deleting code in the executed path which is not needed for repro. Keep checking that it still crashes, deleting more code, checking that it still crashes, and so on. When needed, you can inline methods by hand, check that it still crashes, simplify the inlined code, check again, inline more methods again, and so on.

After a number of iterations, you should be able to boil it down to a single file, hopefully with just a few lines of code.

**Comment by alexdowad** [comment]
This can be closed.
