### ISSUE TITLE
Warning: unrecognized cop inherit_gem found in {path}/.rubocop.yml

### ISSUE THREAD

**Issue by roberts1000** [bbatsov/rubocop#2367]
I have the following specified in my app's `rubocop.yml` using rubycop 0.34.2.

    inherit_gem:
      rubocop: config/default.yml
      my_gem: .rubocop.yml

I get the error

    Warning: unrecognized cop inherit_gem found in {path}/.rubocop.yml.

Rubocop runs, but it ignores the .rubocop.yml file inside the `my_gem` engine.

**Comment by alexdowad** [comment]
I can reproduce this with v0.34.2, but it seems to work with HEAD.

@bbatsov v0.34.3 please!

**Comment by roberts1000** [comment]
It's working in HEAD for me as well.  Thank You.

**Comment by alexdowad** [comment]
This can be closed.
