### ISSUE TITLE
StringReplacement incorrectly auto-corrects gsub(/./, 'a')

### ISSUE THREAD

**Issue by aripollak** [bbatsov/rubocop#2390]
If I have code like this: `string.gsub(/./, 'a')` to replace all characters in a string with 'a', then StringReplacement will register an offense and auto-correct it to `string.tr('.', 'a')`, which is not equivalent. I don't think a single dot character should be an offense in this cop.

**Comment by alexdowad** [comment]
Thanks for reporting this issue. Just opened a PR which fixes it.

**Comment by aripollak** [comment]
Thanks!
