### ISSUE TITLE
no implicit conversion of nil into String

### ISSUE THREAD

**Issue by jujugrrr** [bbatsov/rubocop#2407]
Hi,
The latest rubocop version fails to run in our Jenkins environment. It seems to be related to the user name context for the cache folder => https://github.com/bbatsov/rubocop/commit/88dc50741b7529c848bdd495506a8debcf6fa45e

`Etc.getlogin` returns nil, probably because `getlogin()` nor `ENV['USER']` are set http://ruby-doc.org/stdlib-2.2.0/libdoc/etc/rdoc/Etc.html#method-c-getlogin.

It seems `Etc.getpwuid.name` works even when `Etc.getlogin` fails.

Error : 
```
no implicit conversion of nil into String
/var/lib/jenkins/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/rubocop-0.35.0/lib/rubocop/result_cache.rb:82:in `join'
/var/lib/jenkins/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/rubocop-0.35.0/lib/rubocop/result_cache.rb:82:in `cache_root'
/var/lib/jenkins/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/rubocop-0.35.0/lib/rubocop/result_cache.rb:54:in `cleanup'
/var/lib/jenkins/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/rubocop-0.35.0/lib/rubocop/runner.rb:66:in `ensure in inspect_files'
/var/lib/jenkins/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/rubocop-0.35.0/lib/rubocop/runner.rb:68:in `inspect_files'
/var/lib/jenkins/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/rubocop-0.35.0/lib/rubocop/runner.rb:34:in `run'
/var/lib/jenkins/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/rubocop-0.35.0/lib/rubocop/cli.rb:26:in `run'
```

**Comment by jonas054** [comment]
Same problem as #2406 fixes. Interesting observation about `Etc.getpwuid.name`.

**Comment by edestecd** [comment]
I have the same issue in gitlab ci, with the Ruby2.1 Docker image.  We had to roll back to "0.34.2" to resolve.
