### ISSUE TITLE
Use count instead of reject...size.

### ISSUE THREAD

**Issue by acaron** [bbatsov/rubocop#2409]
Rubocop ask:
```
C: Use count instead of reject...count.
return if language_ids.reject(&:blank?).count > 0
```

But: `language_ids.reject(&:blank?).size` and `language_ids.size` is definitely not the same. For example, if `language_ids = ["", "2", "3"]` coming from a check boxes collection in form.

**Comment by alexdowad** [comment]
Hi @acaron,

RuboCop is suggesting that you can do this:

```ruby
return if language_ids.count(&:blank?) > 0
```

**Comment by alexdowad** [comment]
Better yet:

```ruby
return if language_ids.any? { |id| !id.blank? }
```

**Comment by alexdowad** [comment]
If that solves the issue for you, I suggest this can be closed.

**Comment by bbatsov** [comment]
> return if language_ids.any? { |id| !id.blank? }

:+1:

**Comment by acaron** [comment]
Thanks! Didn't know count could have some params, it was not a very clear message to transfer reject params to count!

**Comment by alexdowad** [comment]
@acaron I'll try to make that one autocorrect with `rubocop -a`. Right now it doesn't.

**Comment by acaron** [comment]
@alexdowad cool! Thank you
