### ISSUE TITLE
New cop to confirm that constants are frozen

### ISSUE THREAD

**Issue by dankohn** [bbatsov/rubocop#2422]
I believe it is best practice in Ruby when assigning a constant (which can be identified by SCREAMING_SNAKE_CASE) to freeze the value, in order to avoid later accidentally modifying it. The exceptions are when assigning a FixNum or Float, which are immutable, and already checked with [Style/RedundantFreeze](http://www.rubydoc.info/gems/rubocop/0.34.1/RuboCop/Cop/Style/RedundantFreeze).

This is discussed here: http://chris.finne.us/2012/03/25/freeze---i-can-modify-constants-in-ruby/

It would be great to add a cop that confirms that all values of a constant (other than FixNum and Float) are frozen.

**Comment by alexdowad** [comment]
If a cop like this is added, I would recommend that it be disabled by default, since the potential for false positives is great. For example, constants are often used to hold some global "registry", which doesn't work if the object is frozen.

**Comment by bbatsov** [comment]
Such a cop already exists. It yields no false positives but it's disabled
by default.

**Comment by dankohn** [comment]
Sorry about that. I completely missed Style/MutableConstant in https://github.com/bbatsov/rubocop/blob/master/config/disabled.yml
