### ISSUE TITLE
New safe navigation cop?

### ISSUE THREAD

**Issue by jeffreyc** [bbatsov/rubocop#2428]
I was reading the [Ruby 2.3.0 preview 1 release notes](https://www.ruby-lang.org/en/news/2015/11/11/ruby-2-3-0-preview1-released/), and the new [safe navigation operator](https://bugs.ruby-lang.org/issues/11537) seems like a candidate for a new cop: prefer safe navigation over `#try` if using MRI >= 2.3.0. Not only is `&.` shorter than `.try`, but it doesn't require ActiveSupport, and keeps your methods looking like methods (`foo&.bar(baz)` instead of `foo.try(:bar, baz)`). I know this is a cop I would find useful, both to autocorrect existing uses, and to prevent new ones.

I didn't see any existing branches/issues/PRs about this, so if this seems reasonable, I'd be happy to attempt a PR. Maybe `Style/SafeNavigation` or `Rails/SafeNavigation`?

**Comment by bbatsov** [comment]
Sure, such a cop would be a welcome addition, but ... this operator is still not support by the `parser` gem we use, so this can't be implemented right now.

**Comment by jeffreyc** [comment]
> this operator is still not support by the `parser` gem we use, so this can't be implemented right now.

Bummer. I checked `RuboCop`, but not `parser`. Thanks for the feedback, though! I'll keep my eye on https://github.com/whitequark/parser/issues/209, and attempt a PR once that's resolved.

**Comment by rrosenblum** [comment]
I was just playing around with this yesterday. Once parser supports ruby 2.3.0, I am all for this. I think this is more feasible than #2328 since there is actually a build for 2.3.0 out there.

The project that I work on implemented this with `nil_or` years ago (before Rails's `try`). I look forward to replacing it with Ruby's Safe Navigation.

**Comment by whitequark** [comment]
`&.` support is in 2.3.0.pre.1.

**Comment by whitequark** [comment]
Sorry, I mean 2.3.0.pre.3.

**Comment by bbatsov** [comment]
Now that Ruby 2.3.0 is out, it makes sense to implement this cop I guess.

**Comment by syndbg** [comment]
I'll submit a PR tomorrow regarding the Ruby 2.3 `SafeNavigationCop`

**Comment by jeffreyc** [comment]
> I'll submit a PR tomorrow regarding the Ruby 2.3 `SafeNavigationCop`

I won't have time to look at this until January, so won't complain if someone else tackles it first. Some thoughts:

- this should flag `#try` and `#try!`
- both functions are defined as `#func(*a, &b)`
  - positional arguments should be a simple autocorrect (`.try(:foo)` -> `&.foo` and `.try(:foo, bar, ...)` -> `&.foo(bar, ...)`)
  - block arguments probably can't be autocorrected (I've seen people using `#try` with blocks for `#tap`-like operations that would not work with safe navigation)
- `#try` doesn't behave exactly like the safe navigation operator (`#try` will swallow `NoMethodError` exceptions, while safe navigation will not), so it may not make sense to enable this cop by default

**Comment by syndbg** [comment]
@jeffreyc 

> this should flag #try and #try!

> #try doesn't behave exactly like the safe navigation operator (#try will swallow NoMethodError exceptions, while safe navigation will not), so it may not make sense to enable this cop by default

Since `#try` behaves differently and catches exceptions, I think we shouldn't flag it as an offense in the cop.


> both functions are defined as #func(*a, &b)
positional arguments should be a simple autocorrect (.try(:foo) -> &.foo and .try(:foo, bar, ...) -> &.foo(bar, ...))
block arguments probably can't be autocorrected (I've seen people using #try with blocks for #tap-like operations that would not work with safe navigation)

Sure, sounds fun. :beers:

**Comment by jeffreyc** [comment]
> Since `#try` behaves differently and catches exceptions, I think we shouldn't flag it as an offense in the cop.

This is my first attempt at contributing to RuboCop, so that may be more consistent/correct. In my experience, though, a lot of people don't realize that `#try` both handles when a value is `nil` and when a value is the wrong type. They assume it behaves like safe navigation does, which can lead to hidden defects. Would it make sense to include a configuration parameter that defaults to flagging `#try!`, but allows you to flag both `#try` and `#try!`? I know this is something I'd want to enable on the projects I work on.

**Comment by syndbg** [comment]
@jeffreyc Sounds reasonable to have it as an option. :+1:

**Comment by rrosenblum** [comment]
@jeffreyc I agree with @syndbg, replacing `try` should be a configuration option. It may take a little while, but knowing Rails, I have a very strong feeling that they will be removing `try` in favor of safe navigation in the future. A configuration will be very valuable, and it will help a ton of people to navigate even if it produces some errors. 

Good luck with this cop, I think there are a few things that will prove tricky to implement. In my experience, methods that optionally take blocks and/or parameters can be tricky to parse using `*node`. Some of the Performance cops do this so they may help you. I have not implemented any cops that use `NodePattern`, but I think that it will be a big help. 

The cases that I think that this cop should cover are

```ruby
foo.bar if foo.respond_to(:bar)
foo.bar(a, b, c) if foo.respond_to(:bar)
foo.bar(&:baz) if foo.respond_to(:bar)
foo.bar { |f| f.baz } if foo.respond_to(:bar)
foo.bar(a, b, c) { |f| f.baz } if foo.respond_to(:bar)
```
configuration for
```ruby
foo.try(:bar)
foo.try(:bar, a, b, c)
foo.try(:bar) { |f| f.baz }
foo.try(:bar, a, b, c) { |f| f.baz }
```

It is probably also valuable to catch occurrences of `nil` checks. I would want some input from someone else on this one.
```ruby
foo && foo.bar
foo.bar if foo
foo.bar unless foo.nil?
```

**Comment by maxjacobson** [comment]
Maybe it should only be enabled when the ruby version supports the safe navigation operator

**Comment by rrosenblum** [comment]
> Maybe it should only be enabled when the ruby version supports the safe navigation operator

Yes, I think that is a great idea. It will also be an easy check. The description should say something about this. Maybe if the cop is enabled, and the user is running Ruby < 2.3.0 we can print a warning message and not run the cop.

**Comment by bbatsov** [comment]
Btw, there are two aspects of this cop - one if the Rails-specific (which @syndbg is working on), but there should also be a cop handling the examples presented by @rrosenblum, which would be a generic Ruby cop.

**Comment by rrosenblum** [comment]
@bbatsov are you suggesting that there be 2 cops for this, `Style/SafeNavigation` and `Rails/SafeNavigation`? Would a single cop with configuration settings work for this?

**Comment by alexdowad** [comment]
> Would a single cop with configuration settings work for this?

I would suggest that 2 cops is better. The Rails stuff is going to be spun out into a separate gem soon. `try` doesn't mean anything special in a non-Rails project.

**Comment by rrosenblum** [comment]
> #try doesn't behave exactly like the safe navigation operator (#try will swallow NoMethodError exceptions, while safe navigation will not), so it may not make sense to enable this cop by default

The implementation of `try` actually changed between Rails 3 and Rails 4. In [Rails 3, `try`](http://api.rubyonrails.org/v3.2.22/classes/Object.html#method-i-try) works the same way as safe navigation. It will raise a `NoMethodError` if the object does not implement the method. [Rails 4](http://api.rubyonrails.org/v4.0.0/classes/Object.html#method-i-try) changed the functionality and added in `try!`. Now `try!` works the same as safe navigation.

If we are planning on having this cop auto-correct, we should consider adding a configuration option to specify the version of Rails being used so that auto-correct will work properly in all scenarios.

**Comment by bbatsov** [comment]
> If we are planning on having this cop auto-correct, we should consider adding a configuration option to specify the version of Rails being used so that auto-correct will work properly in all scenarios.

Or we can keep it simple and assume people are using Rails 4. :-)

**Comment by rrosenblum** [comment]
What ever happened to this? It looks like #2545 died due to inactivity.

**Comment by bbatsov** [comment]
Yep. Someone else should pick this up.

**Comment by rrosenblum** [comment]
I would be interested in working on this. I am leaving for vacation next week so if I can't get to it in the next couple of days, it will be a few weeks before I can pick it up. If anyone else is interested in working on this, please feel free to.

**Comment by rrosenblum** [comment]
Now that I have finished the `Rails/SafeNavigation` cop, I have started work the `Style/SafeNavigation` cop. As stated before, this cop will be a bit more difficult than the last. I have realized that methods that are implemented on `nil` are not safe to be used with safe navigation because the method will not be called. 

```ruby
[10] pry(main)> 'a'.join
NoMethodError: undefined method `join' for "a":String
from (pry):9:in `__pry__'
[11] pry(main)> 'a'&.split
=> ["a"]
[12] pry(main)> 'a'.to_i
=> 0
[13] pry(main)> nil.to_i
=> 0
[14] pry(main)> 'a'&.to_i
=> 0
[15] pry(main)> nil&.to_i
=> nil
[16] pry(main)> nil&.join
=> nil
[17] pry(main)> 1&.join
NoMethodError: undefined method `join' for 1:Fixnum
from (pry):16:in `__pry__'
```
