### ISSUE TITLE
Using or / and when invoking control flow

### ISSUE THREAD

**Issue by Bartuz** [bbatsov/rubocop#2438]
I spotted the issue here: https://github.com/dblock/virtus/commit/80202e321c4247f8c59274834b21f30d84cc4ff1#commitcomment-14453662

`rubocop -a` changed `||` to `or`. Is it possible to set rubocop to ignore such things?

**Comment by jonas054** [comment]
Yes. The following configuration allows `and`/`or` for control flow and only reports use in conditionals.
```yaml
Style/AndOr:
  EnforcedStyle: conditionals
```

**Comment by alexdowad** [comment]
Looks like this issue can be closed.
