### ISSUE TITLE
.rubocop.yml is not working on windows 10

### ISSUE THREAD

**Issue by vinyar** [bbatsov/rubocop#2439]
__Environment: __
Rubocop version: 0.35.1
Chef Development Kit Version: 0.10.0
chef-client version: 12.5.1
berks version: 4.0.1
kitchen version: 1.4.2

__Workflow:__
rubocop --auto-gen-config
touch .rubocop.yml
paste `inherit_from: .rubocop_todo.yml` into .rubocop.yml

__Result:__
(Windows) The .rubocop.yml file is seemingly ignored, and all of the syntax errors are still flagged.
(OSX) The exact same steps result in expected behavior (0 errors)

__Testing:__
* providing an invalid filename to `inherit_from: blabla_todo.yml` does throw an error, which means the inherit statement is being processed, but for some reason doesn't take effect on windows.
* rubocop --config .rubocop.yml does not make a different. All of the errors are reported.
* rubocop --config .rubocop_todo.yml however does work as expected, and comes back with zero offenses.

**Comment by alexdowad** [comment]
@vinyar I don't have a Windows 10 machine, so I can't reproduce this problem. But if you are willing to debug it and come up with a fix, I can guide you through the process. Do you want to try?

**Comment by alexdowad** [comment]
Ping @vinyar.

**Comment by vinyar** [comment]
I went on PTO last week leaving my workstation at repair center. I'll see if I can find a way to setup a repro somewhere.

**Comment by alexdowad** [comment]
@vinyar, are you still interested in debugging this problem?

**Comment by jonas054** [comment]
I think there's a chance that the problem was solved by #2665. Please re-open if it wasn't.

**Comment by vinyar** [comment]
will do, and I am still interested, just not working on any windows project atm.

Also, @alexdowad in case you didn't know, there are a few w10 images here:
https://atlas.hashicorp.com/boxes/search?utf8=%E2%9C%93&sort=&provider=&q=windows+10
