### ISSUE TITLE
Style/AlignParameters error while inspecting: undefined method `parent' for nil:NilClass

### ISSUE THREAD

**Issue by cgriego** [bbatsov/rubocop#2441]
The following Ruby file inspected with the Style/AlignParameters cop triggers an "undefined method `parent' for nil:NilClass" exception in the cop's message method.

```ruby
build(:house,
  :rooms => [
    build(:bedroom,
      :bed => build(:bed,
        :occupants => [],
        :size => "king"
      )
    )
  ]
)
```

0.35.1 (using Parser 2.2.3.0, running on ruby 1.9.3 x86_64-darwin14.0.0)

**Comment by gaijin1973** [comment]
See comment here for more info:

https://github.com/bbatsov/rubocop/commit/b5776f72d656418b5e2167d10b4d0711bce9dd53#commitcomment-14463689

**Comment by daviddavis** [comment]
:+1: 

I just hit this.
