### ISSUE TITLE
Question: Setting up single rubocop setup for multiple repositories

### ISSUE THREAD

**Issue by AvnerCohen** [bbatsov/rubocop#2442]
(1. Apologies if this is not the prefect place, if anywhere else is better, do let me know)
(2. Regardless, once I come up with some conclusion, this can go into the wiki).
(3. Sorry for the longish post)

**Q: How would people recommend setup a single rubocop setup for multiple repositories and across many developers?**

Partial Answer:

In our case, we defined a githook on commit, something like:

````sh
if ! bundle exec rubocop -c "../style-guide/.rubocop.yml" ; then
  exit 1
fi
````

We make sure all repositories (think >50, in a micro-services environment) are under the same "root" folder and this command picks up the configuration file relatively.

To make sure the guidelines repo is present, we also have that in the same githook file:

````sh
if ! [ -e "../style-guide/" ] ; then
  re=`git clone git@github.com:org/style-guide.git ../style-guide`
  if [ $? -ne 0 ] ; then
    echo "Failed Cloning Style Guide."
    exit 1
  fi
fi
````

So this will once in the life time of all repositories, and from that point on, all files will be style checked against the same setup.

This hack is ugly, but is working.
But than things changes in the style guide, and somehow we need to propogate this to all developers, ask them to manually pull latest master or something..
We could of course pull latest with each commit, but this would be so nice, we can implement a code to pull every X commits to reduce impact, but this is weird..
_______________________________________________

Any thoughts on best ways to approach that?

**Comment by mikegee** [comment]
You can reference remote Rubocop config via a URL these days: https://github.com/bbatsov/rubocop/pull/2306

**Comment by AvnerCohen** [comment]
OMG! this is exactly what i was after, thanks so much , and thanks @ptrippett for making that PR!

**Comment by ptrippett** [comment]
@AvnerCohen :+1:
