### ISSUE TITLE
operator must be surrounded by single space

### ISSUE THREAD

**Issue by maasha** [bbatsov/rubocop#2444]
This warning is not consistent between operators. It is given for `*=` but not for `=`. Also, it prevents alignment of code so I suggest the rule should be "at least one space".

**Comment by jonas054** [comment]
The checking for multiple spaces is [configurable](https://github.com/bbatsov/rubocop/blob/master/config/default.yml#L683) and was added in #1654. Perhaps this feature is obsolete now that `Style/ExtraSpacing` is enabled by default.

**Comment by maasha** [comment]
Hm, `Style/ExtraSpacing` does not seem to be enabled here. But I guess I can configure my way out of this as you suggested. Ty.

**Comment by alexdowad** [comment]
Looks like this can be closed.
