### ISSUE TITLE
Hide "Scanning <file>.rb" messages

### ISSUE THREAD

**Issue by tarcieri** [bbatsov/rubocop#2447]
I'm not even sure how this got turned on, but Rubocop is now displaying messages ala:

    Scanning [...].rb

This is in addition to a green "." per file (which I *do* want displayed, just not the `Scanning ...` messages)

How do I shut this off?

**Comment by bbatsov** [comment]
What's the version of RuboCop you're using? How are you invoking it?

**Comment by tarcieri** [comment]
My bad, seems it's the `-d` option
