### ISSUE TITLE
undefined method `children' for :do_find:Symbol

### ISSUE THREAD

**Issue by brandonweeks** [bbatsov/rubocop#2451]
rubocop 0.35.1 errors when parsing this file: https://github.com/theforeman/smart-proxy/blob/develop/modules/puppet_proxy/class_scanner_eparser.rb

Specifically this bit:
``` ruby
def find_CallNamedFunctionExpression o
  if o.lambda
    do_find(o.lambda)
  end
end
```
It looks like "o.lambda" is getting misinterpreted as a lambda.

Full traceback: https://gist.github.com/brandonweeks/e3684b4b882b2b378793
Test case (credit @domcleal): https://gist.github.com/domcleal/e792c526eed7275f6b4b
>0.35.1 (using Parser 2.2.3.0, running on ruby 2.2.3 x86_64-darwin14)

**Comment by domcleal** [comment]
> Test case (credit @domcleal): https://gist.github.com/domcleal/e792c526eed7275f6b4

https://gist.github.com/domcleal/e792c526eed7275f6b4b
