### ISSUE TITLE
there is a bug when the line have Chinese characters

### ISSUE THREAD

**Issue by raofeng** [bbatsov/rubocop#2458]
“Align the operands of a condition in an if statement spanning multiple lines”
there is a bug when the line have Chinese characters
after use 'rubocop -a', it looks like:
```ruby
return '今天天气不错，挺风和日丽的。' if condition1 ||
                            condition2
```

**Comment by jonas054** [comment]
I think the problem is that in most editors, even when you select a monospace font, the Chinese and Latin characters have different widths, so alignment becomes impossible. See here:

```ruby
return '今天天气不错，挺风和日丽的。' if condition1 ||
#       JTTQBC
                            condition2
```
RuboCop aligns based on the assumption that all characters have the same width.
