### ISSUE TITLE
Check for redundant visibility modifiers

### ISSUE THREAD

**Issue by agrimm** [bbatsov/rubocop#2462]
The following code doesn't generate any RuboCop offenses, even though it has a redundant visibility modifier, in that there's a second `private` call.

    # Example of a class with repeated private visibility modifiers
    class MyClass
      def foo
        # This is public
        bar
        baz
      end
    
      private
    
      def bar
        # This is private
        puts 'bar called'
      end
    
      # Redundant visibility modifier
    
      private
    
      def baz
        # This is also private
        puts 'baz called'
      end
    end
    
    MyClass.new.foo

There should be a cop that generates an offense for the second `private`.

**Comment by bbatsov** [comment]
Yeah, we should definitely generate some offence in such situations.
