### ISSUE TITLE
Style/ParallelAssignment for array swapping

### ISSUE THREAD

**Issue by ShockwaveNN** [bbatsov/rubocop#2464]
I have code like this. I just need to swap two elements in array
```
array = [1, 2, 3, 4]
array[0], array[1] = array[1], array[0]
p array
```

rubocop game me this offence:
```
test.rb:2:1: C: Style/ParallelAssignment: Do not use parallel assignment.
array[0], array[1] = array[1], array[0]
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
````
By documentation of [Style/ParallelAssignment cop](https://github.com/bbatsov/rubocop/blob/master/lib/rubocop/cop/style/parallel_assignment.rb) I cannot understand that is wrong with my code.
Is this a bug in cop, or there is better way to swap elements in my array?

I use 
`rubocop 0.35.1 (using Parser 2.2.3.0, running on ruby 2.1.6 x86_64-linux)`

**Comment by alexdowad** [comment]
> Is this a bug in cop

Yes. It's a bug.

This cop tries to find an ordering of assignments which doesn't change the meaning of the code. If it can't find one, it's not supposed to issue a warning.

**Comment by kamen-hursev** [comment]
Just a clarification, Rubocop has the same bug for swapping values of hash or object attributes:
All these result in `Style/ParallelAssignment` offences:
```
array[0], array[1] = array[1], array[0]
hash[:a], hash[:b] = hash[:b], hash[:a]
point.x, point.y = point.y, point.x
```

**Comment by rrosenblum** [comment]
I think the issue stems from the cop seeing these as method calls instead of as assignments. I will try to dig into this cop to fix it.

**Comment by rrosenblum** [comment]
@alexdowad I may need some help with this one. There was a change in the code to start using `NodePattern` to check `find_valid_order`. I am not too familiar with `NodePattern`. I am sure I could figure it out, but you can probably fix the bug faster than I can. My first thought was to reintroduce the `swapping_variables?` which was replaced by `find_valid_order`.

**Comment by alexdowad** [comment]
@rrosenblum, no problem. I am just going for dinner now, but will look at it later.

**Comment by alexdowad** [comment]
> My first thought was to reintroduce the swapping_variables? which was replaced by find_valid_order

`swapping_variables?` was replaced for good reason. It was only able to identify very basic cases where parallel assignment cannot validly be replaced. `find_valid_order` is far more robust. It just needs to be updated to handle aref assignments and attribute assignments.

**Comment by rrosenblum** [comment]
> find_valid_order is far more robust. It just needs to be updated to handle aref assignments and attribute assignments.

After looking at the cop, that is what I was thinking. I had some guesses with how it would need to be modified, but I would need to play with it to really figure out how it needs to be changed.

**Comment by alexdowad** [comment]
Hey @rrosenblum... just opened a PR which fixes this one.

If you are interested, try reading the comments at the top of `node_pattern.rb`. The intention is that other developers should be able to pick up the "node pattern" language within 10 minutes -- but if there's anything which is hard to grasp, I will try to make the docs clearer.

**Comment by rrosenblum** [comment]
I just read over the docs at the top of `node_pattern.rb`, they seem detailed enough to me. The idea behind `NodePattern` makes sense to me. I will need to play around with it before I am completely comfortable with it.
