### ISSUE TITLE
Relative paths

### ISSUE THREAD

**Issue by stereodenis** [bbatsov/rubocop#2465]
I have no .rubocop.yml file
But suddenly I have relative to parent paths
```
@MacB ➜  placeinfo rbenv:(2.2.3) git:(master) ✗ rubocop -V
0.35.1 (using Parser 2.2.3.0, running on ruby 2.2.3 x86_64-darwin14)
@MacB ➜  placeinfo rbenv:(2.2.3) git:(master) ✗ rubocop -L
../placeinfo/config.ru
../placeinfo/Gemfile
../placeinfo/Guardfile
../placeinfo/Rakefile
../placeinfo/app/controllers/admin/base_controller.rb
...
```

**Comment by jonas054** [comment]
What's the output from `rubocop -d`?

**Comment by stereodenis** [comment]
@jonas054 https://gist.github.com/stereodenis/f6ee655df79444b1be57

**Comment by stereodenis** [comment]
@jonas054 https://gist.github.com/stereodenis/f6ee655df79444b1be57

**Comment by jonas054** [comment]
It's strange that there's a capital I in `placeInfo` here:
```
For /Users/stereodenis/work/stereopark/placeInfo: configuration from /Users/stereodenis/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rubocop-0.35.1/config/default.yml
```
but then `placeinfo` is all lower case in all other messages. Do you have any idea why?

**Comment by stereodenis** [comment]
@jonas054 I don't know why...
is there something sensitive to case?

**Comment by jonas054** [comment]
Everything is case sensitive! :smile: On OS X. Right?
So do you have a directory called `/Users/stereodenis/work/stereopark/placeInfo` and one called `/Users/stereodenis/work/stereopark/placeinfo`?

**Comment by stereodenis** [comment]
@jonas054 no
i have one directory — placeinfo

**Comment by jonas054** [comment]
If `/Users/stereodenis/work/stereopark/placeInfo`doesn't exist, then I have no explanation why RuboCop put that path in its debug output. But I suspect this mystery is closely related to the problem you're having.

**Comment by stereodenis** [comment]
@jonas054 maybe it's relative to https://github.com/bbatsov/rubocop/issues/1932 ?

**Comment by jonas054** [comment]
Yes, maybe. Do you have any other ruby versions installed? Same behavior with them?

**Comment by stereodenis** [comment]
@janraasch I will try on other rubies

**Comment by stereodenis** [comment]
@jonas054 I try to rename and unrename project folder and it works as expected!

**Comment by alexdowad** [comment]
@stereodenis So the problem is resolved, right?
