### ISSUE TITLE
Consider adding --disable-cop for the CLI interface

### ISSUE THREAD

**Issue by shevegen** [bbatsov/rubocop#2469]
Heya,

If this suggestion is not considered a good addition, feel free to close it, no problem.

I suggest to add either:

    --disable

or

    --disable-cop

This can be used to disable an individual cop. (You could also use it to disable individual cops one after the other, e. g. to build incrementally; for synergy, --enable-cop should also then be added to re-add a cop that was disabled prior to that).

It could be made to append to your config file, e. g. with the way how
to disable it (or how to do so anyway).

Take this use case from IRC:

<hxegon> According to rubocop's readme, you can disable individual rules with a comment, but it's not working for me.

Ok, the user possibly failed at that BUT I think rubocop could also show-case how it is done properly, e. g. if one invokes rubocop via a --disable-cop config option.

**Comment by jonas054** [comment]
This option already exists and is called `--except`. There's also a `--only` option that overrides configuration, which is partly the same as the `--enable-cop` you described.

Disabling rules in a comment is described here: https://github.com/bbatsov/rubocop#disabling-cops-within-source-code
