### ISSUE TITLE
Add ability to specify lines to check

### ISSUE THREAD

**Issue by bronislav** [bbatsov/rubocop#2470]
I'm using rubocop to check styles in the pre-commit hook. And I am interesting in violations only in changed lines. Right now I'm using [wrapper](https://gist.github.com/bronislav/5347c246204bbd9d952d) which patches rubocop runner. Is such feature is worth adding to the core?

What do you think?

**Comment by jonas054** [comment]
Look at #2182. I'm closing this issue for the reasons that @bbatsov expressed there.
