### ISSUE TITLE
Add Cop to Enforce Alignment of Tokens on Consecutive Lines

### ISSUE THREAD

**Issue by jfelchner** [bbatsov/rubocop#2478]
Now that `ExtraSpacing` has been updated (#2035) to work so well (thanks @bbatsov!), the last thing I'd love for rubocop to be able to handle is checking and autofixing alignment of tokens across consecutive lines.

For example, if the cop is configured to align on `=`, then the following code would throw an error:

```ruby
hello = "my friend"
is_it_me ||= "you're lookin' for?"

whoomp = "there it is"
```

And autocorrect would update this to:

```ruby
hello      = "my friend"
is_it_me ||= "you're lookin' for?"

whoomp = "there it is"
```

Firstly, notice that the `whoomp` line doesn't get autocorrected because it's not on an adjacent line with the first two.  Similar to `ExtraSpacing`, it might be nice to have an option to ignore blank lines when looking for adjacency.

Secondly, it aligns on the token itself and not on the operator.  In other words, it's the above and not:

```ruby
hello    = "my friend"
is_it_me ||= "you're lookin' for?"
```

**Comment by alexdowad** [comment]
Do you want this specifically for aligning on `=`? Or on other things as well?

This is not really aligning on "tokens", as `||=` is parsed as a single `tOP_ASGN` token.

**Comment by jfelchner** [comment]
@alexdowad I'm fairly sure that I haven't thought through all the use cases yet, so let's do whatever's easiest to align `=` (or other text? configurable?) across adjacent lines and then we can go from there as people use it more. 

As a bonus, if it could do like the `ExtraSpacing` cop does where it looks on the preceding line _at the same indentation level_ to determine where the alignment should go, that'd be pretty cool. That way, for example, the assignment of a multi line hash can line up with an assignment below the hash. 

This is super minor, but I thought I would bring it up. :smile:

**Comment by alexdowad** [comment]
I think for now, we should only look at aligning `=`, and only in cases where there is one assignment statement per line, on successive lines. Otherwise, this will get completely out of hand.

**Comment by jfelchner** [comment]
@alexdowad for a first pass I agree, although I don't think the indentation thing will be too hard. I'm down to pair on this as well as the bracket alignment with you if you want! :)

**Comment by jfelchner** [comment]
@bbatsov What's up? Why'd this get closed?

**Comment by alexdowad** [comment]
@jfelchner Have a look at the above commit.

**Comment by jfelchner** [comment]
@alexdowad I'm on ioctocat and the commits don't get shown inline. :-/

Thank you so much!  😄

**Comment by alexdowad** [comment]
No problem -- please clone and try it out! (It is better if we can catch problems before the next gem release.)
