### ISSUE TITLE
A way to sort rubocop output by files with the most violations

### ISSUE THREAD

**Issue by bytenel** [bbatsov/rubocop#2481]
It would be very helpful to be able to have rubocop output just the filenames of particular violators and list out how many violations the file has with them sorted by the file with the most violations in it. That way you can take care of files with the largest number of problems first!

**Comment by bbatsov** [comment]
We already have https://github.com/bbatsov/rubocop#file-list-formatter and https://github.com/bbatsov/rubocop#offense-count-formatter

Guess you want some mixture of them - filename (total offences in file).

**Comment by alexdowad** [comment]
The offense count formatter seems to be exactly what @bytenel is asking for. I suggest this can be closed.

**Comment by jonas054** [comment]
I think what he wants is something that could be achieved with a ruby one-liner that does some processing of JSON output. I ran the following on the RuboCop project itself:
```sh
./bin/rubocop -c config/default.yml --format json | ruby -rjson -e 'JSON.parse(ARGF.read)["files"].map { |h| [h["offenses"].size, h["path"]] }.sort.each { |count, path| printf "%4d %s\n", count, path}'
```
and got
```
[...]
   9 lib/rubocop/cop/variable_force.rb
   9 lib/rubocop/formatter/disabled_config_formatter.rb
   9 lib/rubocop/node_pattern.rb
   9 lib/rubocop/options.rb
  11 lib/rubocop/cop/style/extra_spacing.rb
  14 lib/rubocop/cop/style/indentation_width.rb
  16 lib/rubocop/cop/style/conditional_assignment.rb
```
(worst offenders last).

**Comment by bbatsov** [comment]
Still, this seems like a potentially useful formatter to me.

**Comment by jonas054** [comment]
And shouldn't be too hard to implement. Coming up with a name is the worst part.
`[so]rted list of offense count per file`?

**Comment by alexdowad** [comment]
Just pushed a new formatter... still needs changelog and specs.

**Comment by jonas054** [comment]
> still needs changelog and specs

and README.
