### ISSUE TITLE
rubocop breaks code when "fixing" `attr :name, true`

### ISSUE THREAD

**Issue by radiospiel** [bbatsov/rubocop#2483]
Rubocop replaces

`attr :name, true`

with 

`attr_reader :name, true`

which is plain wrong. If it would replace that line at all, it should use

`attr_writer :name`

instead.

**Comment by jonas054** [comment]
There's not much [documentation](http://ruby-doc.org/core-2.2.3/Module.html#method-i-attr), but it looks like
`attr :name, true` is equivalent to `attr_accessor :name`
and
`attr :name, false` and `attr :name` are equivalent to `attr_reader :name`.
So we do have a bug here.

**Comment by bbatsov** [comment]
Indeed. I had not idea about this behaviour. We should fix this.

**Comment by alexdowad** [comment]
I see that @weh has created an updated spec... but no code to actually make the spec pass. The two should go together.

**Comment by alexdowad** [comment]
@weh, would you like to write the code to fix this one?

**Comment by weh** [comment]
yes, i was searching for a 24pullrequests issue to fix.

**Comment by weh** [comment]
sorry for the mess with the issue references. lesson learned :)

**Comment by bbatsov** [comment]
Noticed one more issue in the code. And regarding the commit message - it should not end with `.` (titles don't have dots in them).

**Comment by alexdowad** [comment]
@bbatsov, I like your thorough code reviews!
