### ISSUE TITLE
Idea: autocorrect on region

### ISSUE THREAD

**Issue by dcluna** [bbatsov/rubocop#2486]
I'm not sure if this exists already, but I'd like to autocorrect offenses found in a specific region (instead of correcting an entire file/directory). Does anyone else think this is an interesting addition?

I am able and willing to write the code for it, if someone could point me in the right direction. I can update the [rubocop-emacs](https://github.com/bbatsov/rubocop-emacs) project to use it too.

**Comment by bbatsov** [comment]
Some analysis won't work properly outside the context of the entire file/scope/whatever, so this is not really doable. I mean you - there might be related fixes outside the region you want to do auto-correct in, which would introduce breakages.
