### ISSUE TITLE
Add 'align_brackets' style for Style/IndentArray

### ISSUE THREAD

**Issue by jfelchner** [bbatsov/rubocop#2495]
Similar to #2395

If `align_brackets` is used for `Style/IndentArray`, then this is a problem:

```ruby
foo = [
  1,
  2
]
```

Autocorrect would change it to:

```ruby
foo = [
        1,
        2
      ]
```

**Comment by jonas054** [comment]
We did it for braces. I guess square bracket deserve the same treatment.

**Comment by alexdowad** [comment]
> I guess square bracket deserve the same treatment.

Definitely they do. I just haven't got around to it yet.

**Comment by bbatsov** [comment]
Fixed.

**Comment by alexdowad** [comment]
Thanks @jawshooah! Nice work!
