### ISSUE TITLE
rubocop should not fix magic vars 

### ISSUE THREAD

**Issue by radiospiel** [bbatsov/rubocop#2496]
rubocop's auto correction replaces magic vars like `$?` with english names. However, that breaks the code if "english" is not required.

It would be good, if RC just warns in that case. To have it awesome rubocop should either try to detect "english" when fixing, and/or include it itself.

**Comment by bbatsov** [comment]
This can't be automated, which is the reason why we mention `english` in the message itself. Typically english would be required in some top-level file and that'd be all. RuboCop processes individual files without keeping track of their relationships. 

It's not the ideal experience, but we can't do any better.

**Comment by radiospiel** [comment]
Well, in that case you should consider not to fix it automaticlly, but to just warn. The current behaviour breaks code when running auto corrections.

**Comment by bbatsov** [comment]
You disable auto-correct for each individual cop.

**Comment by radiospiel** [comment]
This issue is about RC breaking code sometimes when autocorrecting issues. Now *I* know that I can disable this particular cop, and I do so; I still like to point out that a linter like rubocop should never change code from working to not-working. I personally consider this a bug with RC's autocorrection, which I usually find quite helpful.

Of course you might disagree and find it acceptable that RC breaks code in rare circumstances.

**Comment by bbatsov** [comment]
> Of course you might disagree and find it acceptable that RC breaks code in rare circumstances.

Yep, that's exactly my point of view. If we aimed only for bullet-proof auto-corrections we'd have way less auto-corrections. I'm fine with flagging somehow "dangerous" auto-corrections and add a flag to disable them globally, but I don't have the time to do this and no one else has stepped forward to do it. I think this at least the fifth time this problem has been discussed. :-)

**Comment by radiospiel** [comment]
Ok,now I got this. Let me use this opportunity to thank for your efforts with rubocop :)

**Comment by alexdowad** [comment]
> Yep, that's exactly my point of view. If we aimed only for bullet-proof auto-corrections we'd have way less auto-corrections. I'm fine with flagging somehow "dangerous" auto-corrections and add a flag to disable them globally

Rather than a flag to disable all "dangerous" auto-corrections, I would like it if after auto-correcting, at the very bottom of its output, RC printed a list of "dangerous" corrections performed, and told you what to check to make sure your code will still work.
