### ISSUE TITLE
Don't allow string continuations in arrays or arguments

### ISSUE THREAD

**Issue by agrimm** [bbatsov/rubocop#2501]
Rubocop should detect and report an offense for string continuations in arrays or arguments

    # Bad: hard to spot the concatenation
    array = ['Item 1' 'Item 2']
    # Less bad: at least it's explicit
    array = ['Item 1' + 'Item 2']

    # Bad
    puts('Item 1' 'Item 2')
    # Less bad
    puts('Item 1' + 'Item 2')

Proposal for a different but similar problem: https://github.com/bbatsov/rubocop/issues/2426

**Comment by alexdowad** [comment]
This should be corrected to `array = ['Item 1Item 2']`. Adding `+` creates extra overhead and might not be equivalent (if `String#+` has been redefined).

**Comment by alexdowad** [comment]
Is this a "style" or "lint" cop?

**Comment by alexdowad** [comment]
OK, I'm just pushing a fix for this to my open PR. This PR is growing to monstrous proportions...

**Comment by bbatsov** [comment]
Indeed - generally I don't like big PRs, as it's very hard to review them properly (requires too much time).
