### ISSUE TITLE
The Style/SpecialGlobalVars cop does not always auto-correct the code properly

### ISSUE THREAD

**Issue by olbat** [bbatsov/rubocop#2503]
The Style/SpecialGlobalVars cop does not always auto-correct the code properly, for example, it replaces the `$/` global by the `$INPUT_RECORD_SEPARATOR` one but it does not includes the [English](http://ruby-doc.org/stdlib-2.1.0/libdoc/English/rdoc/English.html) module, so it basically breaks the code (rubocop version `0.35.1`).

To reproduce:
```bash
$ echo 'p $/' > test.rb

$ ruby test.rb
"\n"

$ rubocop --auto-correct --only="Style/SpecialGlobalVars" --format=simple test.rb
== test.rb ==
C:  1:  3: [Corrected] Prefer $INPUT_RECORD_SEPARATOR or $RS from the stdlib 'English' module over $/.

1 file inspected, 1 offense detected, 1 offense corrected

$ cat test.rb
p $INPUT_RECORD_SEPARATOR

$ ruby test.rb
nil
```

**Comment by maxjacobson** [comment]
this has been discussed recently: https://github.com/bbatsov/rubocop/issues/2496#issuecomment-164114650

**Comment by alexdowad** [comment]
This is regrettable, but there is not much we can do, for reasons already discussed. Maintainers, please close this issue.

**Comment by olbat** [comment]
Erm, I'm not really sure to follow ...
If this cop is known to produce broken auto-corrected code, why not disable the auto-correction (by default) ?
