### ISSUE TITLE
Multi-line hashes with one key/value are treated like single-line hashes and are not allowed to have a trailing comma

### ISSUE THREAD

**Issue by toph** [bbatsov/rubocop#2508]
Under this configuration...

```
Style/TrailingComma:
  EnforcedStyleForMultiline: comma
```

Rubocop thinks this is a single-line hash and shouldn't have a trailing comma.  Thus, this fails...

```
_ = {
  key: "value",
}
```

Is that intentional behavior?

I think this issue could be a duplicate of https://github.com/bbatsov/rubocop/issues/2403 , but I'm creating a new one, since there were multiple problems reported there.

**Comment by toph** [comment]
0.35.1 (using Parser 2.2.3.0, running on ruby 2.1.2 x86_64-darwin13.0)

**Comment by toph** [comment]
Just verified this still fails in master (8434555b2c62a19e5a0f17e3753e141120fae7b6).

**Comment by jfelchner** [comment]
All, I'm pretty sure this is due to #2369  I think there needs to be a check if it's talking about parameters or about a hash.

**Comment by toph** [comment]
Thanks for taking a look!  Just realized I didn't include the output, so figure I might as well include that for completeness.

```
Inspecting 1 file
C

Offenses:

test.rb:2:15: C: Avoid comma after the last item of a hash, unless each item is on its own line.
  key: "value",
              ^

1 file inspected, 1 offense detected
```
