### ISSUE TITLE
Offense counts in .rubocop_todo.yml are noisy

### ISSUE THREAD

**Issue by agrimm** [bbatsov/rubocop#2511]
Whenever `rubocop --auto-gen-config` is rerun, a lot of the changes you can see doing a `git diff` of the `.rubocop_todo.yml` are changes to the offense count lines. Usually when I incorporate the changes into git, I do `git add -p`, commit the relevant changes (such as an offense being squashed for a particular excluded file, or squashed altogether), and then `git checkout` the offense counts.

Possibilities I can think of:

* Have an option to not show offense counts.
* Only display the first significant figure (eg 3 offenses, between 10 and 19 offenses, between 200 and 299 offenses)
* If a todo file already exists, don't modify the offense count if the change is small (I don't like this option, because it results in behavior that changes depending on whether or not the file exists)

**Comment by alexdowad** [comment]
If an option was added not to show offense counts, what interface would you propose for that option?

**Comment by agrimm** [comment]
It'd presumably be a command-line option like `--no-offense-counts`. RuboCop has recently allowed configuration options to be given along with `--auto-gen-config`.

**Comment by alexdowad** [comment]
Maintainers, do you like the idea of `--no-offense-counts`?

**Comment by bbatsov** [comment]
That's fine by me.

**Comment by alexdowad** [comment]
OK, will do.
