### ISSUE TITLE
ConditionalAssignment corner cases

### ISSUE THREAD

**Issue by maxjacobson** [bbatsov/rubocop#2518]
Hello!

I'm trying out the unreleased version of RuboCop from the latest master (01953251719dfe2e07834097e27d6bae2adcc476) and wanted to offer some feedback.

The new cop Style/ConditionalAssignment is pretty cool, but it's making a lot of suggestions that I'm not sure it should. I'll give a few examples. Apologies if any of these ideas have already been discussed.

## 1) same receiver, different method

```ruby
class DogWalker
  def initialize(*dogs)
    @dogs = dogs
  end

  def add_dog(dog, index = nil)
    if index.nil?
      dogs << dog
    else
      dogs[index] = dog
    end
  end

  private

  attr_reader :dogs
end

walker = DogWalker.new("Milo", "Lola")
walker.add_dog("Bean")
walker.add_dog("Chewie", 0)
p walker
```

How would I rewrite the `add_dog` method to make use of conditional assignment? Would it be an improvement?

Suggested change: verify that the assignment is calling the same method on the same receiver in each branch of the conditional; in this case, the receiver is the same, but the method is different (`<<` vs `[]=`) so it's not necessarily possible to cleanly change the code.

Kind of related note: this cop isn't strictly checking assignment, it's also checking mutating operators like `<<`, so maybe the name will confuse people. I suggest amending the message to acknowledge this or maybe even splitting the cop into multiple cops with more accurate names.

## 2) multiple assignments in each branch of conditional

Or consider this example:

```ruby
class SftpServer
  def initialize
    if Rails.env.production?
      @ip = ENV['SFTP_IP']
      @user = ENV['SFTP_USER']
      @enabled = true
    else
      @ip = '127.0.0.1'
      @user = 'milo'
      @enabled = false
    end
  end
end
```

We have a few places where in one branch of the conditional, we set a few variables, and in the other branch of the conditional, we set a few other variables. We could change these to multiple conditionals, I guess?

Suggested change: if there are multiple assignments in either branch of the conditional, don't add an offense.

**Comment by alexdowad** [comment]
> Suggested change: if there are multiple assignments in either branch of the conditional, don't add an offense.

I agree with this.

**Comment by alexdowad** [comment]
For 1, I see that @rrosenblum specifically wrote this cop so it could enforce things like:

```ruby
array << if something
           1
         else
           2
         end
```

**Comment by alexdowad** [comment]
I've found a fix for 1.

**Comment by alexdowad** [comment]
Pushed a fix for 1 to my open PR.

You suggested that if there are multiple assignments in each branch, the conditional should not be flagged. What if there are method calls, etc? What if there are multiple assignments in just *one* branch?

Your opinion will be appreciated.

**Comment by maxjacobson** [comment]
Speaking from the perspective of someone following the recommendations of the cop, the only ones that felt right were the ones where the body of each branch of the conditional was one line (assigning a variable or shoveling an object into an array) -- which was most of them. so I would think if there are multiple assignments or other logic, it should ignore those

**Comment by maxjacobson** [comment]
(Dude, you're a machine! :sunglasses:)

**Comment by alexdowad** [comment]
> the only ones that felt right were the ones where the body of each branch of the conditional was one line

@rrosenblum, what do you think about this (as the author)?

@maxjacobson Thanks for the compliment!

**Comment by rrosenblum** [comment]
@maxjacobson thank you for the feedback. As for 1, I am very surprised to hear that it registered an offense. It should not be registering an offense because the assignment types are different (`=` and `<<`). For number 2, PR #2433 is adding a configuration setting for that. The way I have the configuration set up is that by default it will not register an offense for multiple assignment in a conditional. I took a bit of a looser stance on this than some may normally go for. By default, it will register an offense for multiple assignment in conditionals when the last assignment is to the same variable and an assignment to another variable doesn't span into any other branch

This will not register an offense unless the configuration is set to `true` because `@ip` and `@user` appear in both branches.
```ruby
if Rails.env.production?
  @ip = ENV['SFTP_IP']
  @user = ENV['SFTP_USER']
  @enabled = true
else
  @ip = '127.0.0.1'
  @user = 'milo'
  @enabled = false
end
```

This will register an offense by default because `@ip` and `@user` only appear in one branch. 
```ruby
if Rails.env.production?
  @ip = ENV['SFTP_IP']
  @enabled = true
else
  @user = 'milo'
  @enabled = false
end
```

My thought to this was that earlier assignments aren't that important if they are local to a single branch.

The cop is also designed to register an offense if there are method calls in the branch. I felt that this would help to show what the conditional is actually doing.

```ruby
if Rails.env.production?
  some_method
  another_method
  foo = important_value
else
  more_methods
  even_more_methods
  foo = more_important_values
end
```

```ruby
foo = if Rails.env.production?
          some_method
          another_method
          important_value
       else
          more_methods
          even_more_methods
          another_important_value
       end
```

**Comment by alexdowad** [comment]
> I am very surprised to hear that it registered an offense. It should not be registering an offense

@rrosenblum Have a look at c850c04.

**Comment by maxjacobson** [comment]
ah, didn't realize you already had an open pull about this! I think that last example looks nice.

The penultimate example I think is ambiguous. When I see the assignment condition pattern, it kind of implies to me that the job of the conditional is to generate this value. If it's assigning multiple variables, I don't think that's the case, it's more like it has a few disparate jobs incidentally grouped together, and then the last one gets promoted and the earlier ones kind of hidden.

Either way, I'm happy to reserve judgment and try it out with the updated version. Thanks!
