### ISSUE TITLE
extra-details option not working?

### ISSUE THREAD

**Issue by dmoran-epages** [bbatsov/rubocop#2526]
> rubocop --display-cop-names --extra-details --rails --format html -o rubocop.html 

    invalid option: --extra-details

Or am i doing something wrong?

**Comment by alexdowad** [comment]
Works for me.

`ruby -v`?
`rubocop -v`?

**Comment by dmoran-epages** [comment]
> ruby -v

ruby 2.2.3p173 (2015-08-18 revision 51636) [x86_64-linux]

    > rubocop -v

    0.34.2

**Comment by alexdowad** [comment]
Please upgrade to the newest version of RuboCop and try again.

**Comment by dmoran-epages** [comment]
ok doesnt complain anymore. Thanks.
I cant see any "extra information" in the resulting html however.

Its also a pity that the todo generated by 
   
    rubocop --auto-gen-config

doesnt include line numbers.

**Comment by alexdowad** [comment]
> todo generated by rubocop --auto-gen-config doesnt include line numbers.

You can re-enable one of the cops, run RC, and it will tell you the line numbers where it is failing. Putting the line numbers right in the TODO would mean it becomes outdated as soon as you add or remove a single line of code.

> I cant see any "extra information" in the resulting html however.

Hmm. It seems that none of the cops actually have any extra details.

Maintainers -- what was the intention for the `Details` config parameter? What kind of details did you intend to go there?

**Comment by dmoran-epages** [comment]
> You can re-enable one of the cops, run RC, and it will tell you the line numbers where it is failing. Putting the line numbers right in the TODO would mean it becomes outdated as soon as you add or remove a single line of code.

I understand and appreciate that putting line numbers into the todo isnt ideal either.

My current workflow is in fact as you describe. Enable a cop in the todo. Run rubocop (takes a while for big projects). Refresh the browser. Visually discern what file and line number is causing the problem. Goto editor/ide, open file, nav to line number .. very tedious.

Ideally one would be able to click in the html and open an editor or ide at the appropriate location, but I suppose this is a lot of effort to implement.

Maybe a help would be if one could pass an option to rubocop to sort the html by offence/file (as opposed to file/offence) as one would have to run rubocop less often with the workflow described above (since one is going through the project one offence at a time as opposed to one file at a time).

**Comment by dmoran-epages** [comment]
P.S It seems that the result of creating a todo is (silently) dependent on whether a .rubocop.yml (which possibly includes an older todo) already exists..which can can be desceptive (get less results than one expects..if one has a config/todo lying around that one is unaware of .. they are hidden files). Maybe rubocop should give a warning when creating a todo in such cases.

**Comment by alexdowad** [comment]
Suggestion: before you open up your IDE or editor, try running RC with `-a` (auto-correct) first. It may be able to make the needed edits automatically.

**Comment by dmoran-epages** [comment]
Thanks for the tip.  However even the doc warns that this is experimental and Im afraid th break my code :-)

**Comment by alexdowad** [comment]
> However even the doc warns that this is experimental and Im afraid th break my code

You use git, right?

Do a clean checkout of your code. Run RC with autocorrect turned on. Then `git diff` and look at what it has done. Commit the changes you like, then `git checkout` to flush the ones you don't.

Nothing to be afraid of!

**Comment by alexdowad** [comment]
...Actually, don't use `git diff`. Use `git add -p`. Even better.

**Comment by jonas054** [comment]
Catching up on my reading during the holidays. :smile:
 
> Maintainers -- what was the intention for the Details config parameter? What kind of details did you intend to go there?

It's up to the user. We don't have any `Details` parameters in the default configuration. It's meant as a way to provide guidance within a project, for example to beginners. I see we're not explaining this in the README.

> P.S It seems that the result of creating a todo is (silently) dependent on whether a .rubocop.yml (which possibly includes an older todo) already exists.

The contents of the `.rubocop_todo.yml` file are disregarded when re-genrating it. Other configuration is taken into account, which I think should be as expected with no need for a warning.
