### ISSUE TITLE
Style/AndOr suggests replacing "and" with "&&", and doesn't autocorrect, in places where "and" and "&&" have different semantics

### ISSUE THREAD

**Issue by dmolesUC3** [bbatsov/rubocop#2531]
Consider the following:

```ruby
@h = { a: {b: 'c'} } 

def find_value_1(k1, k2)
  h1 = @h[k1] and h1[k2]
end

def find_value_2(k1, k2)
  h1 = @h[k1] && h1[k2]
end

find_value_1(:a, :b)
# => "c"

find_value_2(:a, :b)
# NoMethodError: undefined method `[]' for nil:NilClass
#   from (irb):8:in `find_value_2'
#   from (irb):13
```

Rubocop suggests “Use **&&** instead of **and**” for methods like `find_value_1`. (To its credit, it doesn't autocorrect with `-a`, though.)

I understand that the style guide bans use of `and` for any purpose, but in that case it seems like Rubocop should suggest a different idiom (and/or warn about parentheses / precedence) here, rather than a substitution that will fail.

**Comment by alexdowad** [comment]
Did you use `--auto-correct` to fix the problem? If so, RC should add parentheses as needed, so the meaning of the expression is not changed.

...Though even if not autocorrecting, RC could mention precedence *in cases* where it makes a difference. We have the technology to do that.

**Comment by dmolesUC3** [comment]
It doesn't autocorrect. Maybe that's the bug?

```
$ bundle exec rubocop --auto-correct
Inspecting 16 files
...C............

Offenses:

lib/factory/factory/abstract_factory.rb:68:40: C: Use && instead of and.
        products = product_registry[k] and products[v.to_s]
                                       ^^^

16 files inspected, 1 offense detected
```

**Comment by dmolesUC3** [comment]
As a side note, the failure to autocorrect got me to actually read up on the `and`/`&&` difference, so I guess there's a pedagogical benefit.

**Comment by alexdowad** [comment]
When I cut-and-paste `find_value_1` into a new source file and run `rubocop -a`, it is auto-corrected, and parentheses are added, like this:

```ruby
# encoding: utf-8
def find_value_1(k1, k2)
  (h1 = @h[k1]) && h1[k2]
end
```

The second example is corrected to:

```ruby
# encoding: utf-8
(products = product_registry[k]) && products[v.to_s]
```

...Maybe there is some surrounding context in `lib/factory/factory/abstract_factory.rb` which makes a difference? Can you share that file (or a portion of it which can reproduce the problem)?

**Comment by bbatsov** [comment]
@dmolesUC3 what's your RuboCop version btw?

**Comment by jonas054** [comment]
I did a little digging. Found that the inspected code must have been and older revision (e.g. `7720451`) of https://github.com/dmolesUC3/config-factory

Stripping down the code to a minimal example, I found that there's no auto-correction of

```ruby
def x
end

def y
  a = b and a.c
end
```

but if I remove the method `x`, the expression inside `y` will be auto-corrected.

**Comment by alexdowad** [comment]
Awesome detective work @jonas054!

**Comment by alexdowad** [comment]
Just pushing a fix to my open PR. It turns out this is my bug.

**Comment by dmolesUC3** [comment]
@jonas054 Nice work! Thanks.
