### ISSUE TITLE
Style/StringLiterals Incorrectly Autofixes """

### ISSUE THREAD

**Issue by jfelchner** [bbatsov/rubocop#2537]
In Ruby you can perform multiline HEREDOC style strings with `"""`.

Example:

```ruby
my_string = """
  Multi-
  line
"""
```

If you have `Style/StringLiterals` set up to use `'` instead of `"`, it will autofix `"""` to `"''` which is incorrect.

**Comment by alexdowad** [comment]
This ain't what you think it is.

Have a look:

```
22:34 ~prog/Ruby/rubocop % cat test2.rb                                   [no_stopping]
# encoding: utf-8
str = """
hello
"""
22:34 ~prog/Ruby/rubocop % ruby-parse test2.rb                            [no_stopping]
warning: parser/current is loading parser/ruby22, which recognizes
warning: 2.2.3-compliant syntax, but you are running 2.2.2.
warning: please see https://github.com/whitequark/parser#compatibility-with-ruby-mri.
(lvasgn :str
  (dstr
    (str "")
    (dstr
      (str "\n")
      (str "hello\n"))
    (str "")))
```

Looking at that parse tree, can you tell what you are actually doing here? Hint: it's nothing like a HEREDOC.

**Comment by alexdowad** [comment]
Another hint: the auto-correction is correct.

**Comment by alexdowad** [comment]
(And it's not `"''`, it's `''"`.)

**Comment by jfelchner** [comment]
It's actually `"''` on one side and `''"` on the other.  I didn't know about that syntax. Thanks for pointing it out. :)

**Comment by alexdowad** [comment]
> I didn't know about that syntax.

It's not special syntax. What you have are 3 string literals, which are concatenated automatically, just like if you do this:

```ruby
str = "a" "b" "c"
```
