### ISSUE TITLE
Flag useless rubocop:enable comments

### ISSUE THREAD

**Issue by alexdowad** [bbatsov/rubocop#2543]
`# rubocop:disable ...` comments are flagged if they don't actually suppress any offenses. This is good and helps to keep a codebase clean of extraneous junk.

We should do the same for `# rubocop:enable` comments, which enable a cop which was never disabled.

Does anyone see any problem with this?

**Comment by ddrmanxbxfr** [comment]
Makes sense :+1:

**Comment by dgollahon** [comment]
@alexdowad: Are you still working on this / planning a PR? I see you have an implementation in your fork from a while ago (https://github.com/alexdowad/rubocop/commit/2530eba0eb5ea0c8c4b1a56a9b2c54bcdb0ba735) but it's not in rubocop proper.

I was independently wanting this feature and thinking about taking a stab at it but I decided to check the issue tracker to see if anyone else had suggested it before and found this.

**Comment by alexdowad** [comment]
@dgollahon, please go ahead. If the code in my commits is useful, please take whatever you want and don't bother crediting me. I don't have any interest in this problem right now and don't care what anybody does with this code. Or if you prefer to start from scratch, that's up to you.

**Comment by dgollahon** [comment]
@alexdowad: Great, thanks. :) I'll look into it.

**Comment by Drenmi** [comment]
@dgollahon: Did you end up making any progress on this? 🙂

**Comment by dgollahon** [comment]
@Drenmi: No, I got sidetracked by another project D: If you're interested in taking it over, that's fine by me. :) If not, I might be able to take a crack at it soon but I'm not sure exactly when.

**Comment by Drenmi** [comment]
@dgollahon: No worries. I have my eyes set on other things at the moment, and I think this issue is buried deep enough that you'll be able to come back to this when you have more time. 😉
