### ISSUE TITLE
Problems when using Ruby 2.3's safe navigation operator

### ISSUE THREAD

**Issue by lucascaton** [bbatsov/rubocop#2551]
By adding a `&.`, aka. **safe navigation operator** (released in [Ruby 2.3.0](https://www.ruby-lang.org/en/news/2015/12/25/ruby-2-3-0-released/)), it causes the following error:

`<file>:<line>:<column>: E: unexpected token tDOT`

**Comment by bbatsov** [comment]
Yeah, that's normal. We haven't release a version of RuboCop that supports Ruby 2.3 yet. If you build the gem from the `master` branch this will work. Hopefully a new stable release will land early next week.

**Comment by lucascaton** [comment]
Awesome, thanks!

**Comment by ericboehs** [comment]
@bbatsov You still planning to release this week? I'm hoping to see this on Hound CI soon. :)

Thanks!

**Comment by bbatsov** [comment]
This release is blocked by the unfinished `parser` support for Ruby 2.3. I'll wait a bit more, if there aren't signs that `parser` 2.3.0 will be released we'll go live with what we have.

**Comment by ericboehs** [comment]
It doesn't look like any squiggly heredoc progress has been made on parser. What should we do here?

**Comment by bbatsov** [comment]
This is in @whitequark's hands. Someone can probably lend him a hand with this.

**Comment by whitequark** [comment]
I'll try to get this out today...

**Comment by alexdowad** [comment]
I'm working on some other `parser`-related stuff (soon to be revealed), otherwise I'd do it.

**Comment by whitequark** [comment]
This feature has an impressive amount of moving parts for something so seemingly simple... sigh

**Comment by whitequark** [comment]
This is proving to be a real pain to spec (the discussion doesn't match the implementation...), implement and test, so probably tomorrow.

**Comment by gerrywastaken** [comment]
For anybody wondering... you need to set the following to add squiggly heredoc support:
```yaml
#.rubocop.yml
AllCops:
  TargetRubyVersion: 2.3

# If you are using the --enable-frozen-string-literal flag
# You might also want to add this:
Style/FrozenStringLiteralComment:
  Enabled: false
```
