### ISSUE TITLE
Autocorrect Style/Encoding go in an infinite loop

### ISSUE THREAD

**Issue by ptitpoulpe** [bbatsov/rubocop#2552]
If you have a file starting with a blank line like this:
     
    <blank line>
    module Toto
    end

and try to autocorrect with `Style/Encoding` it start an infinite loop
where it add `# encoding: utf-8` on the second line, giving something
like this:

    <blank line>
    # encoding: utf-8
    # encoding: utf-8
    ...
    module Toto
    end

**Comment by alexdowad** [comment]
Nice catch! I'm looking at the reason for this right now.

**Comment by alexdowad** [comment]
Just coding up a fix.

**Comment by alexdowad** [comment]
Waiting until my open PR is merged to push this one.
