### ISSUE TITLE
FirstParameterIndentation and Rubymine 4-spaces continued indentations

### ISSUE THREAD

**Issue by maia** [bbatsov/rubocop#2560]
Rubymine will (per default) use 4-spaces indentation in multi lines (hashes, method calls, etc), causing a problem with Style/FirstParameterIndentation:

````
$ cat test.rb
class Test < ActiveRecord::Base
  def do_something
    update(
        column_a: some_value,
        column_b: other_value
    )
  end
end
````
Style/FirstParameterIndentation sees a problem here:
````
$ rubocop test.rb --only Style/FirstParameterIndentation
Inspecting 1 file
C

Offenses:

test.rb:4:9: C: Indent the first parameter one step more than the start of the previous line.
        column_a: some_value,
        ^^^^^^^^^^^^^^^^^^^^^

1 file inspected, 1 offense detected
````
The Rubymine settings are:
````
[ ] Use tab character
Tab size: 2
Indent: 2
Continuation indent: 4
[ ] Keep indents on empty lines
[x] Use indents relative to expression start
````
There was a related problem with multi line method calls at #1633 which was fixed by @jonas054 by adding MultilineMethodCallIndentation. What can be done with FirstParameterIndentation?

**Comment by alexdowad** [comment]
Working on a fix for this one.

**Comment by maia** [comment]
Thanks!
