### ISSUE TITLE
Performance/RedundantMerge Auto-Correction Issue

### ISSUE THREAD

**Issue by basex** [bbatsov/rubocop#2570]
Was running the last version of the rubocop code with ruby 2.3.0 and got the following auto-correction:
```
-      event.merge!('$first_name' => sba.name, '$last_name' => sba.surname) if store && sba
+      event['$first_name'] = sba.name
+      event['$last_name'] = sba.surname if store && sba
```

The if should go around both lines, instead of only the last one.

**Comment by alexdowad** [comment]
Nice catch!

**Comment by alexdowad** [comment]
I have a fix for this. Waiting for my open PR to be merged before I open another.

**Comment by basex** [comment]
If there is a fix that is going to be merged for me the issue can be closed.
Thanks in advance :)

**Comment by alexdowad** [comment]
It will be closed soon. :smile:
