### ISSUE TITLE
performance/string_replacement broken autocorrect

### ISSUE THREAD

**Issue by cthiel** [bbatsov/rubocop#2580]
commit d4d64144cd1233652d2c0eb89b637e313fbb9496 (or a change recently introduced in master) still seems to be producing wrong corrections. Also, the message displayed was a bit misleading.

I had code like:

```
  a = somestring.gsub(/\n/,'')
```

The cop mentioned:
C: Use delete instead of gsub.

auto-correct turned the code into:

```
  a = somestring.tr('\\n', '')
```

which is neither using delete, nor is is producing the expected (same) result.

**Comment by alexdowad** [comment]
I have a fix. Pushing it to my open PR now.

**Comment by rrosenblum** [comment]
Interesting issue. `somestring.tr('\\n', '')` and `somestring.delete('\\n')` would produce the same outcome and are nearly identical in efficiency. Thanks for the fix @alexdowad.

**Comment by alexdowad** [comment]
:smile:
