### ISSUE TITLE
Gem built from repo won't install -- exclusive parser versions (rubocop and astrolabe)

### ISSUE THREAD

**Issue by nomoon** [bbatsov/rubocop#2586]
Had a problem cloning, building, and installing.
```
$ rake install:local

Resolving dependencies...
  rubocop 0.35.1 built to pkg/rubocop-0.35.1.gem.
  rake aborted!
  Couldn't install gem, run `gem install rubocop-0.35.1.gem' for more detailed output
```
```
$ gem install rubocop-0.35.1.gem

ERROR:  While executing gem ... (Gem::DependencyError)
    Unresolved dependency found during sorting - parser (~> 2.2) (requested by astrolabe-1.3.1)
```

So it seems like with the current rubocop gemspec [requiring the parser 2.3 pre-release](https://github.com/bbatsov/rubocop/blob/master/rubocop.gemspec#L42), while astrolabe [requires ~> 2.2](https://github.com/yujinakayama/astrolabe/blob/master/astrolabe.gemspec#L22), we have reached an impasse.

**Comment by nomoon** [comment]
The gem works fine as part of a bundle, but I can't install it as a base gem (which means, for example, no linting through SublimeLinter)

**Comment by alexdowad** [comment]
Unfortunately, the owner of `astrolabe` is not responding to PRs.

Maintainers, what would you think of pulling the needed code from `astrolabe` directly into `rubocop`? There is not very much of it anyhow.

**Comment by bbatsov** [comment]
Yeah, that's fine with me. Alternatively I can fork and rename the gem.

**Comment by alexdowad** [comment]
Once my current PR is merged, let me bring the needed code into `rubocop` in the next PR.
