### ISSUE TITLE
Possible bug: Style/EmptyLiteral autocorrector doesn't respect Style/StringLiterals EnforcedStyle config

### ISSUE THREAD

**Issue by DNNX** [bbatsov/rubocop#2593]
https://github.com/bbatsov/rubocop/blob/master/lib/rubocop/cop/style/empty_literal.rb#L56-L58 

It always generates single-quoted string literals, even if double-quoted are preferred, as far as I see.

```ruby
        def autocorrect(node)
          name = case node
...
                 when STR_NODE
                   "''"
                 end
...
        end
```

Can one cop (EmptyLiteral) look in the config of another cop (StringLiterals) and make decisions based on that?

**Comment by alexdowad** [comment]
> Can one cop (EmptyLiteral) look in the config of another cop (StringLiterals) and make decisions based on that?

Definitely it can. There are plenty of places in the existing code where that is done. Whether it is a good idea or not is another question -- I won't comment on that.

**Comment by DNNX** [comment]
Hmmm, could you show me an example please? Just a link or a cop name, I'll figure out the rest by myself. I tried to find such places - no luck.

**Comment by alexdowad** [comment]
Grep for `config.for_cop`.

**Comment by DNNX** [comment]
Awesome, thanks!
