### ISSUE TITLE
Dependencies between cops

### ISSUE THREAD

**Issue by DNNX** [bbatsov/rubocop#2607]
I wrote quick&dirty script to see the dependencies between cops (i.e. when a cop calls config.for_cop(another_cop)).

Strangely enough, `Lint/AmbiguousOperator` needs everyone else's configs. Or maybe it's a bug in my scripts. I excluded it from the diagram in order to keep it clean.

Other than that, the dependency graph has 28 edges.

The question is: is it worthwhile to implement a rake task (or maybe a gem) to automatically generate such graphs? Even if it's not, I thought I'd share the picture :)

![rubocop](https://cloud.githubusercontent.com/assets/447953/12206494/5a6c3b7c-b652-11e5-882e-31f196b4ce31.png)

Script source code is here: https://gist.github.com/DNNX/ffe8887e687c35e4fcbc. Code quality is far from perfect, but it shows the idea.

**Comment by alexdowad** [comment]
Nice work!

> is it worthwhile to implement a rake task (or maybe a gem) to automatically generate such graphs

I think this is valuable to have in the Rakefile, at least until the problem of cops relying on other cops' config is resolved.

The graph would make more sense if the direction of the arrows was reversed.

**Comment by DNNX** [comment]
> The graph would make more sense if the direction of the arrows was reversed.

I updated the original post and the gist.

**Comment by DNNX** [comment]
Well, I probably need to mirror the graph now to make it more consistent with [the wikipedia illustration](https://en.wikipedia.org/wiki/Dependency_graph).

**Comment by DNNX** [comment]
Done. I hope it looks right now :)

**Comment by bbatsov** [comment]
And as I mentioned we should think in a direction where common config is moved away from cops, as I really hate the idea of cops depending on each other just to share a bit of config.

**Comment by Drenmi** [comment]
Tagging and closing as there's no clear action. @DNNX: If you want to integrate your code into a rake task, feel free to open a PR. 🙂
