### ISSUE TITLE
Issues with Performance/Casecmp

### ISSUE THREAD

**Issue by deivid-rodriguez** [bbatsov/rubocop#2614]
Hi! Two issues with this cop:

- It autocorrects wrong. `'HOLA'.downcase == 'hola'` gets autocorrected to `'HOLA'.casecmp('hola')`, but the first version returns a boolean and the second an integer.

- I don't think it should be enabled by default. The correct autocorrected version would be `'HOLA'.casecmp('hola') == 0` which is arguably less readable. I think performance cops should only be enabled by defaulf if they don't harm readability.

**Comment by segiddins** [comment]
What if it autocorrected to `'HOLA'.casecmp('hola').zero?` ?

**Comment by deivid-rodriguez** [comment]
I still find it less readable, but it's not up to me... :)

**Comment by alexdowad** [comment]
@segiddens, since this cop is for "performance", could you benchmark the `zero?` fix and see if it still buys any performance?
