### ISSUE TITLE
Implement a cop that checks for something.length == 0

### ISSUE THREAD

**Issue by bbatsov** [bbatsov/rubocop#2620]
We should suggest replacing such checks with `empty?`.

This cop should also handle `!=` and the common alias `size`.

**Comment by jawshooah** [comment]
Is `coll.any?` equivalent to `!coll.empty?` in terms of performance?

**Comment by bbatsov** [comment]
It's not the same in terms of semantics.

**Comment by jawshooah** [comment]
Really? What's the difference?

**Comment by jawshooah** [comment]
I know `#any?` takes an optional predicate block, but without the block it just returns `true` on the first element it sees (I would hope).

**Comment by rrosenblum** [comment]
Interesting. I am probably guilty of using `any?` as a replacement to `!#empty?`. Glad to have learned something here.

**Comment by alexdowad** [comment]
Another difference.

```
5:50 ~ % pry
[1] pry(main)> "".any?
NoMethodError: undefined method `any?' for "":String
from (pry):1:in `__pry__'
[2] pry(main)> "".empty?
=> true
```

**Comment by Drenmi** [comment]
The same check should probably also be done for the logically equivalent:

```
0 == something.length?
```

This might seem weird to some, but the habit is carried over by some from languages where this has benefit.

**Comment by bbatsov** [comment]
Yeah, we should check this this as well.

**Comment by Drenmi** [comment]
I implemented this cop as an exercise, and soon realized that `something` can be whatever the user wants, as long as it implements `length` or `size`. But that `something` may not necessarily also implement `empty?`, as is the case, for example, with `Parser::Source::Range`. (Causing two offenses in the Rubocop source.)

What is the official strategy for dealing with such user implemented "duds"? I can see three possible paths, none of which seem ideal to me:

1. Ignore it and let the user mark it as a false positive. (This could make a potential `--auto-correct` rather dangerous.)
2. Check if the receiver is a known implementor of `empty?`. (This could get rather verbose.)
3. Do something funky and check if the receiver `respond_to?(:empty?)`. (This isn't really static code analysis any more, is it?)

Please enlighten me. :smiley:

**Comment by bbatsov** [comment]
> Ignore it and let the user mark it as a false positive. (This could make a potential --auto-correct rather dangerous.)

This is the answer. :-)

**Comment by Drenmi** [comment]
Added in https://github.com/bbatsov/rubocop/pull/2683. I guess this issue can be closed now.
