### ISSUE TITLE
 Style/IndentationConsistency detects UTF-8 BOM as indentation

### ISSUE THREAD

**Issue by TLmaK0** [bbatsov/rubocop#2628]
Related to #2111
I can reproduce the problem with version 0.35.1:

`vi test.rb`

```
require 'test'
#
class TestBom
end
```

`:set bomb`

`:wq`

`rubocop test.rb`

returns:

```
Inspecting 1 file
C

Offenses:

test.rb:3:1: C: Inconsistent indentation detected.
class TestBom
^^^^^^^^^^^^^

1 file inspected, 1 offense detected
```

**Comment by alexdowad** [comment]
Please try on the newest version. (I think @jonas054 has already fixed this.)

**Comment by bbatsov** [comment]
Yeah, he did.

**Comment by TLmaK0** [comment]
@alexdowad , @bbatsov tested with 0.37.1, same problem.

**Comment by jonas054** [comment]
Yes, it looks like `Style/IndentationConsistency` was not fixed by #2746. Reopening.

**Comment by mikegee** [comment]
I can't duplicate this issue today. Perhaps it was fixed?

**Comment by bbatsov** [comment]
Let's close this ticket then.
