### ISSUE TITLE
Performance/Casecmp autocorrect changes behavior of code

### ISSUE THREAD

**Issue by maxjacobson** [bbatsov/rubocop#2638]
`String#casecmp` is always returning a truthy value, so autocorrect changes the behavior of this code:

```ruby
# before autocorrect
if str.upcase == "HELLO" # true or false
  # something which only runs when there's a match
end
```

```ruby
# after autocorrect
if str.casecmp("HELLO") # 0 when a full match, -1 or 1 to indicate non-full-matches
  # something which always runs
end
```

the auto-corrected code should be:

```ruby
if str.casecmp("HELLO") == 0
  # ...
end
```

**Comment by segiddins** [comment]
I have an open PR fixing this that I just need to benchmark

**Comment by maxjacobson** [comment]
Whoops didn't see that. This is a dupe of https://github.com/bbatsov/rubocop/issues/2614 and should be fixed in https://github.com/bbatsov/rubocop/pull/2617

thanks :smile:
