### ISSUE TITLE
Don't substitute =~ for match() if the argument is a String

### ISSUE THREAD

**Issue by jcoyne** [bbatsov/rubocop#2639]
When we upgraded to rubocop 0.36 from 0.35 and ran `rubocop -a` it made the following transformation of our code:
```
"str".match("str") #=> #<MatchData "str">
"str" =~ "str"   # TypeError: type mismatch: String given
```
This is not a valid transformation.  See https://github.com/projecthydra/sufia/pull/1514/files#diff-eb3a22a507195c50484bec3ca2b8daa5L11

I think this is caused by https://github.com/bbatsov/rubocop/blob/ef86f4058b6f4db69d97cea2198f1a86675087e4/lib/rubocop/cop/performance/redundant_match.rb#L20

**Comment by alexdowad** [comment]
Thanks for pointing this out. Note that `/regex/ =~ "str"` is valid; that's why the `RedundantMatch` cop looks for a string argument (not just regex).

**Comment by alexdowad** [comment]
I think `RedundantMatch` should handle `(send str :match str)` as a separate case. It is also redundant, but in a different way.

**Comment by bbatsov** [comment]
> I think RedundantMatch should handle (send str :match str) as a separate case. It is also redundant, but in a different way.

Makes sense.

**Comment by alexdowad** [comment]
The example given above did not accurately reflect the problem. What @jcoyne actually had was:

```ruby
controller_name.match("my/collections")
```

We have no way to tell that `controller_name` is actually a string. From all appearances, RC is justified in concluding that it is likely a regex.

This code is very unusual and it is not worth crippling `RedundantMatch` to avoid breaking it.

Let's close this issue.
