### ISSUE TITLE
Performance/RedundantBlockCall fails when block is never referenced

### ISSUE THREAD

**Issue by segiddins** [bbatsov/rubocop#2641]
```ruby
def group(*args, &blk)
end
```

**Comment by brunoocasali** [comment]
Yeah, the same here!

I'd a method that just declare the arguments but do nothing yet. And I get this error:
**An error occurred while Performance/RedundantBlockCall cop was inspecting ../helpers/breadcrumb_helper.rb.**

The code:
```rb
def breadcrumbs(_items = {}, &_block)
end
```

**Comment by perlun** [comment]
Any chance we could get a release including this one (i.e. 0.36.1 or something)? I just happened to run into it, it breaks Rubocop on Travis for my project so therefore quite eager to have it...

Many thanks in advance.
