### ISSUE TITLE
Dynamic formatter configuration broken (v0.36)

### ISSUE THREAD

**Issue by agross** [bbatsov/rubocop#2662]
I define my formatters dynamically in my Rakefile to get different output when the check runs on a developer machine vs. a build machine.

This used to work in v0.35.1:
```ruby
RuboCop::RakeTask.new(:rubocop) do |t|
  t.formatters = %w(files)
  t.formatters << %w(html --out build/rubocop/rubocop.html)
end
```

And with v0.36 is fails with an error:
```
$ bundle exec rake rubocop
Running RuboCop...
no implicit conversion of Array into String
C:/Ruby/lib/ruby/2.2.0/optparse.rb:378:in `match'
C:/Ruby/lib/ruby/2.2.0/optparse.rb:378:in `parse_arg'
C:/Ruby/lib/ruby/2.2.0/optparse.rb:531:in `parse'
C:/Ruby/lib/ruby/2.2.0/optparse.rb:1395:in `block in parse_in_order'
C:/Ruby/lib/ruby/2.2.0/optparse.rb:1383:in `catch'
C:/Ruby/lib/ruby/2.2.0/optparse.rb:1383:in `parse_in_order'
C:/Ruby/lib/ruby/2.2.0/optparse.rb:1377:in `order!'
C:/Ruby/lib/ruby/2.2.0/optparse.rb:1469:in `permute!'
C:/Ruby/lib/ruby/2.2.0/optparse.rb:1491:in `parse!'
C:/Ruby/lib/ruby/gems/2.2.0/gems/rubocop-0.36.0/lib/rubocop/options.rb:18:in `parse'
C:/Ruby/lib/ruby/gems/2.2.0/gems/rubocop-0.36.0/lib/rubocop/cli.rb:24:in `run'
...
```

I added some debug output before options.rb:18 (`puts args.inspect`):
```
["--format", "files", "--format", ["html", "--out", "build/rubocop/rubocop.html"]]
```

**Comment by alexdowad** [comment]
`t.formatters` is an array of strings, not an array of arrays of strings.

You can use `t.formatters.concat(%w(html --out build/rubocop/rubocop.html))`.

Maintainers, please close.

**Comment by agross** [comment]
Maintainers, please do not close.

@alexdowad The problem with `concat` is that rubocop prepends `--format` in front of every array element.

```ruby
RuboCop::RakeTask.new(:rubocop) do |t|
  puts RuboCop::Version.version
  t.formatters = %w(files)
  t.formatters.concat(%w(html --out build/rubocop/rubocop.html))
end
```

rubocop v0.36:
```
$ bundle exec rake rubocop
0.36.0
Running RuboCop...
["--format", "files", "--format", "html", "--format", "--out", "--format", "build/rubocop/rubocop.html"]
No formatter for "--out"
C:/Ruby/lib/ruby/gems/2.2.0/gems/rubocop-0.36.0/lib/rubocop/formatter/formatter_set.rb:84:in `builtin_formatter_class'
C:/Ruby/lib/ruby/gems/2.2.0/gems/rubocop-0.36.0/lib/rubocop/formatter/formatter_set.rb:56:in `add_formatter'
...
```

rubocop v0.35.1:
```
$ bundle exec rake rubocop
0.35.1
Running RuboCop...
["--format", "files", "--format", "html", "--format", "--out", "--format", "build/rubocop/rubocop.html"]
No formatter for "--out"
C:/Ruby/lib/ruby/gems/2.2.0/gems/rubocop-0.35.1/lib/rubocop/formatter/formatter_set.rb:93:in `builtin_formatter_class'
...
```

**Comment by alexdowad** [comment]
> @alexdowad The problem with concat is that rubocop prepends --format in front of every array element.

OK. Thank you for pointing this out. In that case, you can use `t.options` instead.

`t.formatters` is just a shortcut for adding strings with `--format` prepended to `options`. It is intended to receive an array of strings, each of which is a formatter name.

**Comment by alexdowad** [comment]
@agross Is your problem resolved?

**Comment by agross** [comment]
@alexdowad I'm waiting for feedback of the maintainers. I'd like to learn how they think about my approach that was valid for 0.35.1, but broke in 0.36.

**Comment by jonas054** [comment]
Here's what I think. The `--format` and `--out` options are closely tied together, so it's better if we can support @agross's way of defining the options the way it worked in `v0.35.1`. This should also be documented in the [README](https://github.com/bbatsov/rubocop#rake-integration).

We need to revert the change of [this line](https://github.com/bbatsov/rubocop/commit/bcad6d23cfa1c689d30e61137c18557769bd395a#diff-06259b85319e3e0c211a53c20f02457eR54).

**Comment by alexdowad** [comment]
Sure, that's cool.

**Comment by agross** [comment]
Thank you!
