### ISSUE TITLE
TargetRubyVersion is expected to be a Float

### ISSUE THREAD

**Issue by NobodysNightmare** [bbatsov/rubocop#2663]
## Reproduction

Rubocop version: 0.36

rubocop.yml:
````yml
AllCops:
  TargetRubyVersion: "2.3"
````

## Expected

Rubocop will be satisfied

## Actual

Rubocop will reject this, forcing me to leave out the quotes:
````yml
AllCops:
  TargetRubyVersion: 2.3
````

Now please tell me if I am mistaken, but I think this means that the ruby version will be parsed as a floatingpoint number, won't it? That means you can get trouble with two digit minor numbers:

````irb
2.3.0 :001 > YAML.load('foo: 2.10')
 => {"foo"=>2.1} 
````

**Comment by alexdowad** [comment]
Two-digit minor numbers are not supported, and would not do anything useful even if they were.

The `TargetRubyVersion` parameter controls the version of the Ruby parser which is used to parse your code. The `parser` library which `rubocop` relies on to do this does not give us a `2.0.0` parser, a `2.0.1` parser, and so on. It just gives us: 1.8, 1.9, 2.0, 2.1, 2.2, and 2.3.

So those are what is supported for `TargetRubyVersion`.

The error message which RC prints if you supply an invalid `TargetRubyVersion` tells you what the supported values are.

**Comment by NobodysNightmare** [comment]
> The error message which RC prints if you supply an invalid TargetRubyVersion tells you what the supported values are.

I saw this and quite quickly came up with the desired input.

I also see that there is no ruby 2.10 now and probably also not in the future.

Still it grinds my gears, that apparently a datatype is being misused here (or I am not understanding yaml).

I realize that 2.3 (float value) is totally looking like 2.3 (a version specifier), but still those are different things and yaml has a data type for the former and no data type for the latter.

How does the parser library expect to be called? Is it `Parser.new(2.3)` or is it `Parser.new('2.3')`?

If it was the former, I should probably moan there ;)

**Comment by alexdowad** [comment]
> How does the parser library expect to be called? Is it Parser.new(2.3) or is it Parser.new('2.3')?

More like `Parser::Ruby22.new`, `Parser::Ruby23.new`, and so on.

> I realize that 2.3 (float value) is totally looking like 2.3 (a version specifier), but still those are different things and yaml has a data type for the former and no data type for the latter.

Technically, you are right about this. I'm not inclined to change this, though. I don't know if any of the other contributors are.

> P.S.: I feel obliged to say how awesome RC 0.36 is...

Thank you! Just wait for the next version, it will be much better again!

**Comment by alexdowad** [comment]
I think this can be closed.

**Comment by rhys-vdw** [comment]
> Two-digit minor numbers are not supported, and would not do anything useful even if they were.

It would be useful to not have to search for this issue when you first configure Rubocop for one.
