### ISSUE TITLE
include and extend outside of a class or module

### ISSUE THREAD

**Issue by agrimm** [bbatsov/rubocop#2672]
Should the following code cause an offense?

```
# person.rb
include ActionView::Helpers::ConvenientHelper
class Person < ActiveRecord::Base
end
```

with the "right" version either including the module within Person, or explicitly including the module within Object:

```
# Either
class Person < ActiveRecord::Base
  include ActionView::Helpers::ConvenientHelper
end

# Or
Object.class_eval do
  include ActionView::Helpers::ConvenientHelper
end
```

In this case it looks like a mistake, but I've also seen `include` outside of any class in rake files.

An example of someone else encountering this kind of code: http://stackoverflow.com/questions/5161428/in-ruby-or-rails-why-is-include-sometimes-inside-the-class-and-sometimes-outs

**Comment by alexdowad** [comment]
`include` is sometimes legitimately used at the top level. Personally, I don't like the idea of adding a cop to check this.

**Comment by benlangfeld** [comment]
I am very much in favour of this. The only times I have ever seen this done (and I just discovered several in a very large codebase so I'm in rage mode) are due to complete ignorance of what this means. +1 million on a cop for this.

**Comment by Drenmi** [comment]
Added in #4840.
