### ISSUE TITLE
Add 'stacked' style to Style::ClassAndModuleChildren

### ISSUE THREAD

**Issue by thedeeno** [bbatsov/rubocop#2673]
I've been using a 'stacked' style in my projects:

```
module Foo
module Bar

class Baz
  ...
end

end
end
```

This has the advantage of saving left side spacing for heavily nested classes while also not suffering from potential issues with the compact style.

I started looking at [rubocop-rspec](https://github.com/nevir/rubocop-rspec) for guidance on how to implement a custom cop to do this, but it seems more involved than I thought. Is this something you'd consider adding to the core?

I haven't implemented a custom cop before - how hard this one on a scale of 1-5?

**Comment by jonas054** [comment]
#1398 was closed without action, so your suggestion has little chance of getting in to RuboCop itself. A custom cop is the way to go and I think rubocop-rspec is a good example to follow. Rating the difficulty is hard. Maybe a 2.
