### ISSUE TITLE
Hash#merge! is disallowed but Hash#update is allowed

### ISSUE THREAD

**Issue by bquorning** [bbatsov/rubocop#2674]
I’m wondering if it’s an oversight that `RedundantMerge` disallows the `Hash#merge!` method but allows its alias `Hash#update`?

cc @alexdowad

**Comment by alexdowad** [comment]
> ’m wondering if it’s an oversight that RedundantMerge disallows the Hash#merge! method but allows its alias Hash#update?

It sure is! Thanks for the good catch!

**Comment by Drenmi** [comment]
I added a PR for this, but I can imagine it will cause quite a lot of false positives for Rails users, since `#update` is also used in ActiveRecord.

**Comment by alexdowad** [comment]
> I added a PR for this, but I can imagine it will cause quite a lot of false positives for Rails users, since #update is also used in ActiveRecord.

Oooh... good point. Actually, the word `update` is generic enough that it could be used in any number of places.

What to do...
