### ISSUE TITLE
Performance/RedundantMerge for many values

### ISSUE THREAD

**Issue by dziemba** [bbatsov/rubocop#2676]
This code:

```ruby
def m
  some_hash = { a: 1 }
  some_hash.merge!(b: 2, c: 3, d: 4, e: 5)

  some_hash
end
```

is currently (master/0.36.0) autocorrected to this:

```ruby
def m
  some_hash = { a: 1 }
  some_hash[:b] = 2
  some_hash[:c] = 3
  some_hash[:d] = 4
  some_hash[:e] = 5

  some_hash
end
```
In my opinion, using `#merge!` looks a lot cleaner than the second code snippet.

I have some valid usages of `#merge!` in my projects with > 10 key/values pairs where the second versions just looks bloated. I agree though that `some_hash.merge!(b: 2)` is better written as `some_hash[:b] = 2`.

Should we restrict the cop warning to calls to `#merge!` with less than N key/value pairs?

**Comment by alexdowad** [comment]
> Should we restrict the cop warning to calls to #merge! with less than N key/value pairs?

This could be a good idea. Could you benchmark and see at what point rewriting `merge!` into `[]=` ceases to benefit performance?

It's not that performance is everything, but it is a factor we should consider before making a decision.

**Comment by dziemba** [comment]
It looks like `[]=` is always faster, but it should still be fast enough to consider style/clarity over performance here IMHO.

```ruby
require 'benchmark/ips'

Benchmark.ips do |x|
  (0..15).each do |f|
    n = 2**f

    x.report "merge! n=#{n}", <<-EOC
      h = { a: 1 }
      h.merge!(
        #{(0..n).map { |i| "b#{i}: #{i}" }.join(', ')}
      )
      h
    EOC

    x.report "assign n=#{n}", <<-EOC
      h = { a: 1 }
      #{(0..n).map { |i| "h[:b#{i}] = #{i}" }.join('; ')}
      h
    EOC
  end
end
```

```
          merge! n=1    958.827k (±13.3%) i/s -      4.743M
          assign n=1      1.809M (±14.5%) i/s -      8.862M
          merge! n=2    890.668k (±10.7%) i/s -      4.409M
          assign n=2      1.633M (±15.9%) i/s -      8.016M
          merge! n=4    784.159k (±14.6%) i/s -      3.873M
          assign n=4      1.464M (±15.2%) i/s -      7.152M
          merge! n=8    194.529k (±37.7%) i/s -    799.300k
          assign n=8    365.746k (±32.8%) i/s -      1.591M
         merge! n=16    118.618k (±33.9%) i/s -    529.227k
         assign n=16    243.654k (±32.4%) i/s -      1.108M
         merge! n=32     72.867k (±34.5%) i/s -    326.150k
         assign n=32    136.011k (±30.7%) i/s -    632.415k
         merge! n=64     36.411k (±31.4%) i/s -    166.991k
         assign n=64     70.574k (±33.6%) i/s -    313.830k
        merge! n=128     19.761k (±29.8%) i/s -     91.679k
        assign n=128     37.424k (±29.1%) i/s -    175.236k
        merge! n=256      9.661k (±27.8%) i/s -     44.737k
        assign n=256     17.727k (±29.7%) i/s -     81.664k
        merge! n=512      4.993k (±29.4%) i/s -     22.638k
        assign n=512      9.518k (±27.5%) i/s -     44.345k
       merge! n=1024      2.526k (±37.4%) i/s -     11.130k
       assign n=1024      4.764k (±33.0%) i/s -     22.001k
       merge! n=2048      1.187k (±40.3%) i/s -      5.130k
       assign n=2048      2.229k (±38.2%) i/s -      9.855k
       merge! n=4096    609.446  (±41.5%) i/s -      2.650k
       assign n=4096      1.109k (±40.9%) i/s -      4.770k
       merge! n=8192    305.705  (±41.5%) i/s -      1.323k
       assign n=8192    580.123  (±39.1%) i/s -      2.548k
      merge! n=16384    154.436  (±42.1%) i/s -    663.000
      assign n=16384    304.871  (±40.7%) i/s -      1.325k
      merge! n=32768     79.978  (±43.8%) i/s -    330.000
      assign n=32768    150.165  (±39.3%) i/s -    650.000
```

**Comment by alexdowad** [comment]
@dziemba Thanks for this good information.

We should definitely have some limit. What would you suggest the limit should be?

**Comment by seanwalbran** [comment]
@alexdowad I'd like to see the limit be configurable if possible, since there are projects where readability is paramount but flagging only single-key merges would still be useful versus disabling the cop completely.

**Comment by dziemba** [comment]
I propose that it only suggests using `[]=` for single key-value `merge!` calls. It also makes more sense from a clean code perspective because `merge!` looks like a single, atomic operation (although it probably isn't under the hood) opposed to multiple assignment calls.

**Comment by savef** [comment]
:+1: 

The current state is especially bad when you have an `if` modifier at the end of your `merge!` call, it can change `hash.merge!(one: 1, two: 2) if toggle` into 4 lines, that could easily push the `Metrics/MethodLength` cop over the edge.

If not a configurable limit then I'd say all this cop needs is a switch to toggle between the current behaviour and only giving offences for single key-pairs.

**Comment by alexdowad** [comment]
> I'd say all this cop needs is a switch to toggle between the current behaviour and only giving offences for single key-pairs.

This seems simpler. Maintainers, do you agree?

**Comment by bbatsov** [comment]
I don't like this idea. I'd accept the a configurable limit, but I won't accept special handling just for single entry hashes.

**Comment by savef** [comment]
> I don't like this idea. I'd accept the a configurable limit, but I won't accept special handling just for single entry hashes.

OK, [done](https://github.com/bbatsov/rubocop/pull/2724). With a default of only operating on 2 key-value pairs. Is anybody not happy with this?
