### ISSUE TITLE
Style/TrailingComma cop removed in patch-level release

### ISSUE THREAD

**Issue by adamstrickland** [bbatsov/rubocop#2678]
Commit a0719f96bc0221cdb99413e033b27c7378520db2 removes the `Style/TrailingComma` cop, replacing it with `Style/TrailingCommaInArguments` and `Style/TrailingCommaInLiteral` cops.  This will break client applications that reference `rubocop` using the squiggle rocket (e.g. `gem "rubocop", "~> 0.34", require: false`), which, strictly speaking, breaks [Semantic Versioning](http://semver.org) principles.  Not saying that this should be rolled back, but people need to know that if they're using a similar reference in CI, stuff is gonna break.

**Comment by segiddins** [comment]
that commit first shipped in `0.36.0`, and since rubocop is pre-1.0, breaking changes in a minor version bump are acceptable

**Comment by alexdowad** [comment]
@adamstrickland The speed of RC's development is accelerating to a breakneck pace. Prepare for more breakage in future minor releases.

(This will not continue forever. We are improving the tool as fast as possible, in order to get to a point where it can become stable.)

**Comment by jawshooah** [comment]
In the meantime, pessimistic lower bounds should probably include the patch version (e.g. `~> 0.36.0`)

**Comment by adamstrickland** [comment]
Agree on all points ^, was more trying to raise awareness.  Perhaps until 1.0 ships, the recommended install procedure in the [README}(https://github.com/bbatsov/rubocop#installation) is to use a pessimistic lower bound as suggested by @jawshooah?

**Comment by bbatsov** [comment]
That's fine by me. Keep in mind, however, that most people simply don't read the docs. :-)
