### ISSUE TITLE
actual config keys for specific cops

### ISSUE THREAD

**Issue by mehulkar** [bbatsov/rubocop#2681]
I pored over the docs and couldn't figure out the actual key I needed in my `.rubocop.yml` to configure the `Style/IndentArray` cop. I ended up doing a global search on github for `"Style/IndentArray"` and found an example on the [2nd page of search results][1] that used the `EnforcedStyle` key. 

I used [the rubydoc page][2] to find the available options for this cop. 

Wondering if I'm missing something to have known to use this key? Or if there are docs that I missed?

[1]: https://github.com/search?p=2&q=Style%2FIndentArray&type=Code&utf8=%E2%9C%93
[2]: http://www.rubydoc.info/github/bbatsov/RuboCop/master/RuboCop/Cop/Style/IndentArray

**Comment by alexdowad** [comment]
> Wondering if I'm missing something to have known to use this key? Or if there are docs that I missed?

Look at `config/default.yml` in the RC repo. Scroll down to find the `Style/IndentArray` part.

**Comment by mehulkar** [comment]
ahh ok. i thought i was looking in there and the only thing i saw was ` Enabled: false` key. I see it there now. thanks!
