### ISSUE TITLE
NestedParenthesizedCalls and assignment

### ISSUE THREAD

**Issue by jcoyne** [bbatsov/rubocop#2693]
```
spec/hydra/pcdm/models/object_spec.rb:505:14: C: Style/NestedParenthesizedCalls: Add parentheses to nested method call object1.ordered_members = [object2].
      expect(object1.ordered_members = [object2]).to eq [object2]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```
So I change the line to:

```
      expect(object1.ordered_members=([object2])).to eq [object2]
```
and run again.

```
spec/hydra/pcdm/models/object_spec.rb:505:14: C: Style/NestedParenthesizedCalls: Add parentheses to nested method call object1.ordered_members=([object2]).
      expect(object1.ordered_members=([object2])).to eq [object2]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

It's not fixed. What is the correct way to write this?

**Comment by jonas054** [comment]
That's a bug in `Style/NestedParenthesizedCalls`. It should skip setter calls and only report offenses for "normal method calls". @alexdowad will you take a look?

**Comment by alexdowad** [comment]
@jonas054 I'll try to find some time tonight.

**Comment by alexdowad** [comment]
BTW @jcoyne your test trivially passes. Ruby setter methods *always* return the value on the RHS.

**Comment by alexdowad** [comment]
Just kicking off a new batched PR with a fix for this one. @jcoyne Thanks for reporting!
