### ISSUE TITLE
Array#any? is not equal to !Array#empty?

### ISSUE THREAD

**Issue by gogainda** [bbatsov/rubocop#2697]
It seems that .any? method is hugely misused in ruby community. Taking into consideration that performance [impact](https://github.com/JuanitoFatas/fast-ruby/pull/49) could be very big, It would be really useful to have some kind of performance lint for this purpose.

**Comment by envygeeks** [comment]
While we're on performance you know that `!Array#empty?` is slower than `unless Array#empty?` :wink:

**Comment by bbatsov** [comment]
The problem is that you can really distinguish a proper usage of `something.any?` from an improper one. Someone really might not care about `nil` elements in their collection...
