### ISSUE TITLE
Explicit path should override Exclude

### ISSUE THREAD

**Issue by alexdowad** [bbatsov/rubocop#2698]
In `.rubocop.yml`, we have:

```
AllCops:
  Exclude:
    - 'tmp/**/*'
```

If I try:

```
ruby -Ilib bin/rubocop tmp/repos/rails
```

(I have a checkout of the rails codebase there which I am using for various benchmarks.)

I get:

```
Inspecting 0 files


0 files inspected, no offenses detected
```

...Presumably because all files match the `Exclude` pattern. However, since I explicitly pointed RC to that directory, it would make sense for it to inspect the source files which are there.

**Comment by jonas054** [comment]
I'm not sure. When you give file names explicitly on the command line, the files are inspected. When you give directories, RuboCop inspects whatever files in can find under those directories, but then I think it makes sense to respect the `Exclude` settings.

What if you had

```
AllCops:
  Exclude:
    - 'tmp/repos/rails/**/*'
```

and:

```
ruby -Ilib bin/rubocop tmp
```

Then you would expect RuboCop to inspect everything under `tmp/`, except files under `tmp/repos/rails/`, and this is also what happens. So in that case, the command you give means "inspect everything under the given directory except excluded files". To me it makes more sense if this is always the meaning of explicit directories in the command line.

**Comment by jonas054** [comment]
BTW, the workaround is
```
ruby -Ilib bin/rubocop tmp/repos/rails/**/*.rb
```
The shell can not expand the pattern, so it sends it to RuboCop, and there it is expanded to all matching files, which are then inspected.

**Comment by alexdowad** [comment]
> BTW, the workaround is...

...And that's just what I have been doing.

Your argument makes sense. Closing.
