### ISSUE TITLE
Option to allow Lint/UselessAssignment tolerating assignments at the end of methods and the like

### ISSUE THREAD

**Issue by agrimm** [bbatsov/rubocop#2700]
The following code

    def sum(a, b)
      result = a + b
    end

triggers an Lint/UselessAssignment offense. While I have a personal preference against such code, I consider that a style issue. By contrast, an assignment in the middle of a method, such as

    def sum(a, b)
      c = a * 2 + b
      a + b
    end

is not just bad style, but a linting problem - it's a potential bug.

Currently when I run Lint/UselessAssignment, I often get too many offenses about the former type, which makes it hard to spot instances of the latter type.

I think the best approach would be to have a supported style of permit_assignment_at_end (end of method, end of block, etc.).

**Comment by bbatsov** [comment]
I'm against adding such an option unless someone presents strong arguments in its favor. In general, RuboCop has become so incredibly complex, that I don't want to stuff more and more options that most people will not use at all.

**Comment by alexdowad** [comment]
> In general, RuboCop has become so incredibly complex, that I don't want to stuff more and more options that most people will not use at all.

This, a thousand times this! :+1:
