### ISSUE TITLE
False-positive and broken autocorrect in Style/RedundantParentheses

### ISSUE THREAD

**Issue by savef** [bbatsov/rubocop#2729]
The following code gives "don't use parentheses around a literal":
`assert_equal ({ id: 1 }), some_method_call`

The parentheses here are needed and when autocorrect removes them we're left with a syntax error.

Whether or not this is a false-positive might be up for debate, I imagine some would want to force this literal into a variable declaration because it is pretty ugly, but the autocorrect is definitely broken.

**Comment by lumeet** [comment]
Thanks, that's definitely a bug. However, I'd still try to avoid those parentheses and instead put them around all arguments like this: `assert_equal({ id: 1 }, some_method_call)`.

**Comment by savef** [comment]
Thinking about whether or not this could be called a *false-positive* I've decided that it must be, because even if we don't like the code it's certainly not *redundant*. We'd have to employ a new cop to say "this style is really ugly" IMO.

**Comment by lumeet** [comment]
I was a little hasty with the wording, sorry. @savef, your comment summarizes pretty well my opinion, too. The bug will be fixed soon but I leave the `UglyButNotSoImportantParentheses` cop to someone else. ;)
