### ISSUE TITLE
Style/GuardClause triggered for complex `elsif` conditions

### ISSUE THREAD

**Issue by amw** [bbatsov/rubocop#2737]
The most recent version of RuboCop as well as current git master trigger this GuardClause errors for my if/elsif/else branches. Example file:

```
def process_file file
  if file.video?
    puts file.video_info
  elsif file.image?
    puts file.image_info
  else
    raise "unsupported file type"
  end

  puts file.general_info
end
```

Output:
```
asd.rb:4:3: C: Use a guard clause instead of wrapping the code inside a conditional expression.
  elsif file.image?
  ^^^^^
```

I think it doesn't make sense. The guard condition would have to be very complex, the more complex the more `elsif` clauses there are. Below is – in my opinion – worse code that Rubocop likes:

```
def process_file file
  raise "unsupported file type" unless file.video? || file.image?

  if file.video?
    puts file.video_info
  elsif file.image?
    puts file.image_info
  end

  puts file.general_info
end
```

If this looks OK to you then consider the same example, but with 5 `elsif` checks.

**Comment by madwort** [comment]
Using `case` will pass the cop: 
```
def process_file file
  case  
  when file.video?
    puts file.video_info
  when file.image?
    puts file.image_info
  else
    raise "unsupported file type"
  end

  puts file.general_info
end
```

**Comment by alexdowad** [comment]
> Using case will pass the cop:

That's true, but is the behavior of this cop desirable as re: `elsif`?

**Comment by madwort** [comment]
No, I think @amw 's original example is preferable when using `elsif`

**Comment by alexdowad** [comment]
This cop already has a clause which catches `elsif`s, but it does it wrongly.
