### ISSUE TITLE
SpaceAroundOperators dislikes `\` before newline

### ISSUE THREAD

**Issue by ptarjan** [bbatsov/rubocop#2762]
One this code:

```
foo = 1 \
  + 2
puts foo
```

The `rubocop -a` command yields this syntax error filled code:

```
foo = 1 \ + 2
puts foo
```

Can it just leave it alone please?

**Comment by lumeet** [comment]
Which version of RuboCop are you running? I think this has been fixed already.

**Comment by ptarjan** [comment]
0.34.0 sadly

**Comment by lumeet** [comment]
I thought the fix was even older, but in fact it's been there since 0.35.0.

**Comment by ptarjan** [comment]
Ok, if it fixed in the new version, I'm good. Thanks. Sorry for the noise.
