### ISSUE TITLE
BracesAroundHashParameters when parameters are multiple, separate hashes

### ISSUE THREAD

**Issue by maxjacobson** [bbatsov/rubocop#2776]
This is a stylistic disagreement I have with this cop. I propose a slight change in behavior or maybe a configuration option. Here is the scenario:

``` ruby
User.or({ :age.gte => 75 }, { :age.lte => 10 })
```

In Mongoid, you can write queries like this, and each hash represents one set of conditions, and you'd like all documents which match either.

In this case, each hash is sort of equal and similar. The first one needs the braces to keep the two hashes separate. Syntactically, the second one doesn't _need_ the braces, but it feels semantically wrong to remove them because it makes it look like an options hash, when really it's the same kind of thing as the first parameter.

My proposed behavior change: when all of the parameters are hashes, don't register an offense for unnecessary braces in the last parameter.

Thoughts? Feelings?

**Comment by alexdowad** [comment]
What if the second hash *was* an "options hash"?

This is not something which RC can determine reliably. I say keep the simple rule which we have right now. It's not perfect, but nothing is. If it doesn't work well on your codebase, just disable the cop.

**Comment by maxjacobson** [comment]
I would be sad to disable it because most of the time it is producing more beautiful code. In cases like the above example, to preserve the semantic meaning and keep the cop I found myself changing the code to something like:

```ruby
is_senior = { :age.gte => 75 }
is_child = { :age.lte => 10 }
User.or(is_senior, is_child)
```

And I'll probably keep doing that. I understand the inclination to keep it simple, for sure.

I'm tempted to submit a PR which adds a configuration option to tolerate braces when all of the parameters are hash literals, and default it to false, but I understand this would introduce maintenance complexity so I'll refrain from doing it if y'all are against it.

**Comment by alexdowad** [comment]
> I understand this would introduce maintenance complexity so I'll refrain from doing it if y'all are against it.

I'm skeptical, but not really against it. Not sure what other contributors think.

**Comment by jawshooah** [comment]
Another solution is to disable the cop on a case-by-case basis. Could get
pretty ugly, though, depending on how often you use this pattern.

**Comment by mikegee** [comment]
This is now supported with:
```yaml
Style/BracesAroundHashParameters:
  EnforcedStyle: context_dependent
```

**Comment by maxjacobson** [comment]
Wow, that’s great. Thanks!
