### ISSUE TITLE
Add a rule that disallows usage of `protected` and suggests `private` isntead

### ISSUE THREAD

**Issue by dsbonev** [bbatsov/rubocop#2787]
In some teams and projects there is such a convention, but it is not enforced by a tool and leads to wasteful code review comments and code changes. Based on my experience `protected` is almost never needed, and when used it usually turns out that `private` is to be used instead. So, please, add this rule and maybe even enable it by default.

**Comment by bbatsov** [comment]
Unless there are others who'd support your request, I'd suggest you develop a small custom cop for this. RuboCop can never cover every possible team preference out there - we aim to support out-of-the-box only popular conventions & practices.

**Comment by alexdowad** [comment]
Agree with @bbatsov here. Occasionally, I do use `protected` in Ruby code, and it is always with a good reason.

**Comment by lamont-granquist** [comment]
I've only ever seen it used mistakenly by people who expected protected and private to be java-like on inheritance.  Disabled-by-default cop that could be turned on?

**Comment by alexdowad** [comment]
> Disabled-by-default cop that could be turned on?

Writing a custom cop would take about 12 lines of code or so. I suggest that would be a better idea than adding unnecessary bulk to core.
