### ISSUE TITLE
alias_method no longer preffered

### ISSUE THREAD

**Issue by brewster1134** [bbatsov/rubocop#2820]
from v0.35.1, i believe the default enforced style for `Style/Alias` changed from `alias_method` to `alias`. at thats how it seems based on the yml file at [line 13](https://github.com/bbatsov/rubocop/blob/master/config/enabled.yml#L13). I started getting the cop failing after upgrading to the latest.

**Comment by bbatsov** [comment]
Yes, the community style guide was recently updated and RuboCop's default config reflects the style guide.

**Comment by brewster1134** [comment]
hm interesting.... in that case, the aforementioned link to the line in enabled yml might want to me be re-worded as well. thanks for the quick response!

**Comment by floehopper** [comment]
@bbatsov:

> Yes, the community style guide was recently updated and RuboCop's default config reflects the style guide.

[The Rubocop documentation for `Style/Alias`][1] references [this section of the styleguide][2] which still recommends using `alias_method` vs `alias`. Why/where has the recommendation changed?

[1]: https://rubocop.readthedocs.io/en/latest/cops_style/#stylealias
[2]: https://github.com/rubocop-hq/ruby-style-guide#alias-method

**Comment by Drenmi** [comment]
@floehopper That part is a recommendation for runtime aliasing. The relevant section for write-time is above it, [here](https://github.com/rubocop-hq/ruby-style-guide#alias-method-lexically). 🙂

**Comment by floehopper** [comment]
@Drenmi Thanks for pointing that out. However, I'm still confused. As far as I can see there is only *one* alias-related rule in Rubocop, i.e. [`Style/Alias`][1], which doesn't allow me to discriminate between write-time or run-time aliasing. So I have to choose to either prefer `alias` or `alias_method` for *all* scenarios which means I can't completely satisfy the style guide. Or am I missing something?

[1]: https://rubocop.readthedocs.io/en/latest/cops_style/#stylealias

**Comment by jaredbeck** [comment]
> .. `Style/Alias` .. doesn't allow me to discriminate between write-time or run-time aliasing. So I have to choose to either prefer `alias` or `alias_method` for _all_ scenarios which means I can't completely satisfy the style guide. Or am I missing something?

I had the same question. It looks like the cop is more sophisticated than that. It behaves differently in "dynamic" and "lexical" scopes. See eg. https://github.com/rubocop-hq/rubocop/blob/2f303909317f241336e52eedc340dc96bed71f39/lib/rubocop/cop/style/alias.rb#L36
