### ISSUE TITLE
0.37.1 doesn't includes /assets directory

### ISSUE THREAD

**Issue by ragm87** [bbatsov/rubocop#2825]
I generate HTML reports everytime I run Rubocop. But since I've installed 0.37.1 version, I'm getting this error:
`No such file or directory - /Users/ragm87/.rvm/gems/ruby-2.0.0-p353/gems/rubocop-0.37.1/assets/output.html.erb
/Users/ragm87/.rvm/gems/ruby-2.0.0-p353/gems/rubocop-0.37.1/lib/rubocop/formatter/html_formatter.rb:55:in 'read'
/Users/ragm87/.rvm/gems/ruby-2.0.0-p353/gems/rubocop-0.37.1/lib/rubocop/formatter/html_formatter.rb:55:in 'render_html'
/Users/ragm87/.rvm/gems/ruby-2.0.0-p353/gems/rubocop-0.37.1/lib/rubocop/formatter/html_formatter.rb:49:in 'finished'
/Users/ragm87/.rvm/gems/ruby-2.0.0-p353/gems/rubocop-0.37.1/lib/rubocop/formatter/formatter_set.rb:30:in 'block (3 levels) in <class:FormatterSet>'
/Users/ragm87/.rvm/gems/ruby-2.0.0-p353/gems/rubocop-0.37.1/lib/rubocop/formatter/formatter_set.rb:30:in 'each'
/Users/ragm87/.rvm/gems/ruby-2.0.0-p353/gems/rubocop-0.37.1/lib/rubocop/formatter/formatter_set.rb:30:in 'block (2 levels) in <class:FormatterSet>'
/Users/ragm87/.rvm/gems/ruby-2.0.0-p353/gems/rubocop-0.37.1/lib/rubocop/runner.rb:68:in 'inspect_files'
/Users/ragm87/.rvm/gems/ruby-2.0.0-p353/gems/rubocop-0.37.1/lib/rubocop/runner.rb:35:in 'run'
/Users/ragm87/.rvm/gems/ruby-2.0.0-p353/gems/rubocop-0.37.1/lib/rubocop/cli.rb:30:in 'run'
/Users/ragm87/.rvm/gems/ruby-2.0.0-p353/gems/rubocop-0.37.1/bin/rubocop:14:in 'block in <top (required)>'
/Users/ragm87/.rvm/rubies/ruby-2.0.0-p353/lib/ruby/2.0.0/benchmark.rb:296:in 'realtime'
/Users/ragm87/.rvm/gems/ruby-2.0.0-p353/gems/rubocop-0.37.1/bin/rubocop:13:in '<top (required)>'
/Users/ragm87/.rvm/gems/ruby-2.0.0-p353/bin/rubocop:23:in 'load'
/Users/ragm87/.rvm/gems/ruby-2.0.0-p353/bin/rubocop:23:in '<main>'
/Users/ragm87/.rvm/gems/ruby-2.0.0-p353/bin/ruby_executable_hooks:15:in 'eval'
/Users/ragm87/.rvm/gems/ruby-2.0.0-p353/bin/ruby_executable_hooks:15:in '<main>'`

So I checked the installation directory of the gem, and no assets directory there.
I also checked previous version (0.37.0), and for that version the assets directory does exists.

I compared the gemspec between this 2 versions, and looks like this directory got excluded from the build.

**Comment by bbatsov** [comment]
Fixed on `master`.

**Comment by ragm87** [comment]
Thanks @bbatsov

Any estimated time of when it's going to be available on RubyGems?

**Comment by bbatsov** [comment]
1-2 days I guess. I'm waiting a bit to see if someone won't uncover other
serious bugs in 0.37.1.

On 10 February 2016 at 16:33, ragm87 <notifications@github.com> wrote:

> Thanks @bbatsov <https://github.com/bbatsov>
>
> Any estimated time of when it's going to be available on RubyGems?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bbatsov/rubocop/issues/2825#issuecomment-182398929>.
>



-- 
Best Regards,
Bozhidar Batsov

http://www.batsov.com

**Comment by ragm87** [comment]
Awesome @bbatsov :) thanks!

**Comment by bbatsov** [comment]
0.37.2 was released yesterday.

**Comment by ragm87** [comment]
Thanks!
