### ISSUE TITLE
UselessAssignment could autocorrect

### ISSUE THREAD

**Issue by ptarjan** [bbatsov/rubocop#2827]
Why doesn't it just change the variable names to `_`?

**Comment by alexdowad** [comment]
There are plenty of cops which *could* autocorrect but don't (yet).

**Comment by ptarjan** [comment]
Ok, so it isn't intentionally not autocorrecting. Thanks.

**Comment by alexdowad** [comment]
Uhh... but this issue is a useful "todo". If you are interested in seeing this worked on, please leave it open.

**Comment by bbatsov** [comment]
In general Lint cops don't autocorrect - something might be unused due to a mistake and the autocorrect would hide this mistake. It's not correcting 100% intentionally. @alexdowad is right that make cops simply lack autocorrection because nobody wrote it, but this is not one of them.
