### ISSUE TITLE
MultilineOperationIndentation wants different indentation when using multiple blocks

### ISSUE THREAD

**Issue by hoffi** [bbatsov/rubocop#2832]
I have enabled the `MultilineOperationIndentation` with `EnforcedStyle: aligned` and using Rubocop Version 0.36.0.

When i span an operation across multiple lines i can indent the subsequent lines by 2 spaces. But when i open a second block there, it looks like Rubocop gets confused and brings a warning when i do this there.

Example to show what i mean: 
```ruby
## This is ok:
a = b.map do |c|
  c +
    b
end

## Invalid:
a = b.map do |c|
  c +
    b + # This is allowed
    d do
      x +
        y # "Align the operands of an expression spanning multiple lines." at this line
    end
end

## Second example as valid code:
a = b.map do |c|
  c +
    b +
    d do
      x +
      y    # No 2 space indentation
    end
end
```

This is occurs in version 0.37.1.

**Comment by jonas054** [comment]
Yes, that looks like a bug. I'll try to fix it.
