### ISSUE TITLE
Style/FirstMethodParameterLineBreak autofixer ruins indentation

### ISSUE THREAD

**Issue by ptarjan** [bbatsov/rubocop#2844]
Turning on `Style/FirstMethodParameterLineBreak` and `Style/MultilineMethodDefinitionBraceLayout` and autofixing

```
def foo(a,
        b)
  nil
end
```

gives

```
def foo(
a,
        b
)
  nil
end
```

yuck. What can we do?

/cc @jonas054 @panthomakos since you seem to have worked on these.

**Comment by ptarjan** [comment]
`Style/AlignParameters` and `Style/ClosingParenthesisIndentation` can fix these. Sorry for the churn.

**Comment by tiagoefmoraes** [comment]
I was having this same problem and fixed with
```yaml
Layout/AlignParameters:
  EnforcedStyle: with_fixed_indentation
```
