### ISSUE TITLE
casecmp example using unrequired call to downcase

### ISSUE THREAD

**Issue by tomgrim** [bbatsov/rubocop#2851]
https://github.com/bbatsov/rubocop/blob/master/lib/rubocop/cop/performance/casecmp.rb#L21 doesnt need to use the `downcase` method.

```ruby
'abc'.casecmp('ABC'.downcase) # => 0
'abc'.casecmp('ABC') # => 0
```

http://ruby-doc.org/core-1.9.3/String.html#method-i-casecmp

**Comment by olliebennett** [comment]
Hey @tomgrim - while I agree at first glance that this seems illogical, I believe my issue (linked above) is one kind of situation where you'd use this sort of `casecmp('ABC'.downcase)` syntax. Would you agree?

**Comment by tomgrim** [comment]
@olliebennett I can not see a situation where using `downcase` and `casecmp` together would ever make sense. Maybe I'm just being dense?

**Comment by olliebennett** [comment]
Hmm yep, you're right. Appears that I'm the one being dense!

**Comment by tomgrim** [comment]
@olliebennett no problem! Seems you've tracked down the much bigger issue than just some comment. :smile:

**Comment by alexdowad** [comment]
@tomgrim. Thanks for pointing this out. This nonsensical example is removed in my open PR.

**Comment by alexdowad** [comment]
This has been resolved on `master`, please close.

**Comment by tomgrim** [comment]
thanks :)
