### ISSUE TITLE
Performance/Casecmp autocorrect breaks code logic

### ISSUE THREAD

**Issue by olliebennett** [bbatsov/rubocop#2852]
Suppose I use the following code to identify whether a string is all lowercase:

```ruby
# Check first_name is all lowercase characters
# eg. if first_name is "Ollie" this will be false, if it's "ollie" it will be true.
if first_name == first_name.downcase
```

This is auto-corrected by RuboCop as follows:

```ruby
if first_name.casecmp(first_name).zero?
```

However, the updated code behaves differently:

```
[1] pry(main)> "OLLIE" == "OLLIE".downcase # important that this is false!
=> false
[2] pry(main)> "OLLIE".casecmp("OLLIE").zero? # auto-corrected version returns true.
=> true
```

Reproduced using the latest code on `master`:
```
Hash: 95c2f065827dfba26847583c8b0887fb615238f6
0.37.2 (using Parser 2.3.0.6, running on ruby 2.3.0 x86_64-darwin15)
```

I appreciate there may be other approaches to checking whether something is "downcased" but regardless, this is breaking valid code.

Perhaps related, but not the same issue: https://github.com/bbatsov/rubocop/issues/2851

**Comment by olliebennett** [comment]
Not sure whether this is the best way to test code which should _not_ be autocorrected, but:

Proposed (failing) test case for [casecmp_spec.rb](https://github.com/bbatsov/rubocop/blob/master/spec/rubocop/cop/performance/casecmp_spec.rb):

```ruby
it "does not autocorrect if comparing string with itself" do
  old_source = "str.#{selector} == str"
  new_source = autocorrect_source(cop, old_source)
  expect(new_source).to eq old_source
end
```

**Comment by jetheredge** [comment]
We ran into this same issue as well with upcase when we were checking for an initialism (to see if a name was all uppercase). We were using this logic:

```
return name if name.upcase == name
```

Which was checking to see if the name "FBI" matched "FBI", but was autocorrected to:

```
return name if name.casecmp(name).zero?
```

Which always succeeds.

**Comment by rrosenblum** [comment]
If I remember correctly, the risks for this cop were discussed earlier. I like @olliebennett's proposed spec to not register an offense if comparing the same variable. The general use case that this cop solves is when comparing to something that is known to be all uppercase or all lowercase. It might be worth while to change this cop to only register an offense if comparing to a string that we can determine is all uppercase or all lowercase or if comparing to a constant that we will assume is already cased properly. @alexdowad authored the cop, I would like to get his opinion on the situation as well as @bbatsov and @jonas054.

**Comment by alexdowad** [comment]
The intention was to catch a case-insensitive comparison using something like `str1.downcase == str2.downcase` or `str1.upcase == str2.upcase`. Unfortunately, it doesn't do that quite right.

It should also catch cases where `eql?` is used, as well as where a string literal is used which is all upcase or all downcase. And yes, I didn't get autocorrection quite right either.

**Comment by olliebennett** [comment]
Really appreciate you creating the cop @alexdowad; very useful even with its quirks!

Is `Performance/Casecmp` one of the cops that would require the more involved `unparser` dependency discussed in #2498, or do you think a sophisticated fix is worth attempting with the existing approach?

Either way, a short-term solution could be to limit the scope of this cop to only identify the basic case you describe above, and not try to be so clever quite yet.

**Comment by alexdowad** [comment]
> Is Performance/Casecmp one of the cops that would require the more involved unparser dependency discussed in #2498, or do you think a sophisticated fix is worth attempting with the existing approach?

I don't think AST-level manipulation is required for this cop to autocorrect. Unless there's something I'm missing, relatively simple textual manipulation should be enough.

**Comment by jetheredge** [comment]
@alexdowad I'm assuming you mean that it could be scoped to catch trivial cases like `str1.upcase == str2.upcase` relatively easily with just text manipulation, but would probably need more involved parsing to figure out more complex cases such as comparing to a constant that may or may not have an upper/lower case? For us, catching/autofixing the simple cases like I mentioned would be more than enough. Thanks for your work on this @alexdowad

**Comment by alexdowad** [comment]
@jetheredge Even catching comparison to a string constant is simple. Look for a `str` node in the AST. Its only child will be the value of the constant.

**Comment by alexdowad** [comment]
Just pushed a fix to my open PR.
