### ISSUE TITLE
Performance/RedundantMerge keeps getting flagged on ActiveRecord models

### ISSUE THREAD

**Issue by devonestes** [bbatsov/rubocop#2858]
I keep seeing instances of the Performance/RedundantMerge cop flagging updates in my ActiveRecord code. For example, I have the following ActiveRecord class:
```ruby
class District < ActiveRecord::Base
  ...
end
```

And then I see infractions when I run the following code:
```ruby
district = District.find(1)
district.update(district_type: 'Public')
```

The message I've receiving is the following:
```ruby
Use district[:district_type] = 'Public' instead of district.update(district_type: 'Public').
```

Of course that change would be totally different than what is happening when `#update` is called on the object, but I'm assuming it's being flagged because of ActiveRecord's implementation of `#update`.

**Comment by alexdowad** [comment]
You need to update to the latest version of RC.

**Comment by devonestes** [comment]
That seems to have done it - thanks!
