### ISSUE TITLE
auto-correct changes logic

### ISSUE THREAD

**Issue by xithan** [bbatsov/rubocop#2859]
`a == a.downcase` is changed to `a.casecmp(a).zero?` 
(the former condition is supposed to check if uppercase letters are present; the auto-corrected condition is always true)

`return if (!a.include? b) && c` is changed to `return unless a.include? b && c`
(auto-correct converts `if !` to `unless` although there is a second expression involved)

**Comment by rrosenblum** [comment]
@xithan, the first issue that you mention, pertaining to `Perfomance/Casecmp` has a more detailed discussion in #2852. Please join the conversation there.

The second one sounds like a bug to me. I assume that the second issue is coming from `Style/NegatedIf` in combination with `Style/ParenthesesAroundCondition` or more likely `Style/RedundantParentheses`. Can you please provide the version of RuboCop that you are using as well as whether or not the listed cops are enabled or disabled.

**Comment by xithan** [comment]
latest rubocop version 0.37.2 with default style rules. I double-checked with `rubocop --show-cops`:
`Style/NegatedIf` enabled
`Style/RedundantParentheses` enabled
`Style/ParenthesesAroundCondition` enabled

`ParenthesesAroundCondition` doesn't matter. With `NegatedIf` enabled, the other two disabled and removed parentheses `return if !a.include? b && c` is still changed to `return unless a.include? b && c`

**Comment by rrosenblum** [comment]
Running RuboCop on the code produces this output:

```ruby
test.rb:4:1: C: [Corrected] Style/NegatedIf: Favor unless over if for negative conditions.
return if !a.include? b && c
^^^^^^^^^^^^^^^^^^^^^^^^^^^^
test.rb:4:11: C: [Corrected] Style/RedundantParentheses: Don't use parentheses around an unary operation.
return if (!a.include? b) && c
          ^^^^^^^^^^^^^^^
test.rb:4:15: W: Lint/RequireParentheses: Use parentheses in the method call to avoid confusion about precedence.
return unless a.include? b && c
```

Breaking it down, the first run will cause an offense in `Style/RedundantParentheses`. The second run will cause a new offense in `Style/NegatedIf`. 

I think this is an issue with `Style/NegatedIf` because `return if (!a.include?) b && c` and `return if !a.include? b && c` should be equivalent code, but `return unless a.include? b && c` is not.

**Comment by alexdowad** [comment]
> I think this is an issue with Style/NegatedIf because return if (!a.include?) b && c and return if !a.include? b && c should be equivalent code, but return unless a.include? b && c is not.

Not so. The transformation which `NegatedIf` is performing is valid. It doesn't *look* valid, but it is (precedence is a bit deceiving here).

`RedundantParentheses` is the problem.

**Comment by alexdowad** [comment]
Just pushing a fix to my open PR.

**Comment by rrosenblum** [comment]
Thanks for the fix @alexdowad
