### ISSUE TITLE
Auto-correcting RSpec/DescribedClass yields invalid code

### ISSUE THREAD

**Issue by RKushnir** [bbatsov/rubocop#2888]
I'm writing a test for a custom ActiveModel validator
```ruby
RSpec.describe CustomValidator do
  let(:model_class) do
    Class.new do
      include ActiveModel::Model
      attr_accessor :custom_attr

      validates_with CustomValidator
    end
  end
end
```
Rubocop tells me I should use `described_class` instead and corrects it to:
```
validates_with described_class
```
But `rspec` doesn't seem to agree:
```
Failure/Error: validates_with described_class
NameError:
  undefined local variable or method `described_class' for #<Class:0x007face28ac960>
```

**Comment by maxjacobson** [comment]
I think this issue is really with [rubocop-rspec](https://github.com/nevir/rubocop-rspec)

**Comment by RKushnir** [comment]
Oh, thanks, I didn't know it's a separate gem.
Closing as it's already reported https://github.com/nevir/rubocop-rspec/issues/59
