### ISSUE TITLE
Change the meaning of code after correct by Style/RedundantParentheses

### ISSUE THREAD

**Issue by ksss** [bbatsov/rubocop#2904]
## Expected behavior

```ruby
class Foo
  def +@
    :+
  end
end
class Fixnum
  def foo
    Foo.new
  end
end

# before correct
+1.foo #=> #<Foo>
+(1.foo) #=> :+

# after correct
+1.foo #=> #<Foo>
+(1.foo) #=> :+
```

## Actual behavior

```ruby
# snip...
# before correct
+1.foo #=> #<Foo>
+(1.foo) #=> :+

# after correct
+1.foo #=> #<Foo>
+1.foo #=> #<Foo>
```

## RuboCop version

Include the output of `rubocop -V`:

```
$ rubocop -V
0.37.2 (using Parser 2.3.0.6, running on ruby 2.4.0 x86_64-darwin15)
```

**Comment by alexdowad** [comment]
Looks like things have changed in 2.4.0!

**Comment by alexdowad** [comment]
I haven't looked at the MRI commit history to find where this change was introduced, but in the absence of further information, it appears more like a bug in Ruby 2.4.0 than anything else.

**Comment by jonas054** [comment]
I get the same result with all ruby versions I've tried. `+1.foo` and `+(1.foo)` are not equivalent. I think it's a bug to auto-correct the latter into the former.

**Comment by alexdowad** [comment]
Thanks for pointing this out, @jonas054. I was wrong.

**Comment by alexdowad** [comment]
I've got a fix, will open a PR shortly.
