### ISSUE TITLE
Style/ZeroLengthPredicate, accepts length < 1

### ISSUE THREAD

**Issue by dennisvandehoef** [bbatsov/rubocop#2905]
The cop Style/ZeroLengthPredicate allows "bad" length checks.
`length == 0` gets reported and should be replaced with `empty?` but `length < 1` is ok.
since `length < 1` also is an `empty?` question, it should report it.

## Expected behavior
as it does for `length == 0`, report it

## RuboCop version
0.37.2 (using Parser 2.3.0.6, running on ruby 2.1.7 x86_64-darwin14.0)

**Comment by alexdowad** [comment]
Thanks for the suggestion. Just added a fix to my open PR.
