### ISSUE TITLE
Feature request: Allow EnforcedStyle for Style/Lambda

### ISSUE THREAD

**Issue by agrimmtt** [bbatsov/rubocop#2909]
`Style/Lambda` doesn't have an `EnforcedStyle` option. Allowing users to have an enforced_style of always using `lambda` would be useful for those with an existing codebase that uses `lambda` and wants any new code to be consistent with existing code.

**Comment by maxnordlund** [comment]
The same would be very useful for those that have the opposite, existing codebase uses `->` and want new code to stay consistent with that.
