### ISSUE TITLE
unicode-display_width version 1.0.0

### ISSUE THREAD

**Issue by jspanjers** [bbatsov/rubocop#2918]
The unicode-display_width gem has released a new version 1.0.0.

Unfortunately this version 1.0.0 requires ruby >= 2.0.

Thus I do not think it is possible to use its 1.0.0 version with rubocop as long as rubocop supports ruby < 2.0.

Is dropping support for ruby < 2.0 on rubocop an option?

**Comment by aried3r** [comment]
I see that you made a PR to unicode-display_width to support 1.9.3, so I guess besides "just" API changes, this should no longer be an issue?

See also their changelog: https://github.com/janlelis/unicode-display_width/blob/master/CHANGELOG.txt

**Comment by jspanjers** [comment]
Yes, this is no longer an issue. Therefor, I've created a pull request to rubocop to update its dependencies to unicode-display_width >= 1.0.1.

https://github.com/bbatsov/rubocop/pull/2925
