### ISSUE TITLE
Rubocop and emacs

### ISSUE THREAD

**Issue by renard** [bbatsov/rubocop#2987]
I am using emacs (GNU Emacs 24.5.1) and I need rubocop to provide clean Cask for the homebrew-cask project. I contact you since you seem to also be an emacs contributor.

I am not a ruby developper and I don't intend to learn it.

The main problem I face is the alignments.

For example:

The default emacs indentation is:

``` ruby
      rmdir:  [
        '/Library/Preferences/Google',
      ]
```

Which lead to and error:

```
Inspecting 1 file
C

Offenses:

Casks/google-nik-collection.rb:35:9: C: Use 2 spaces for indentation in an array, relative to the position of the opening bracket.
        '/Library/Preferences/Google',
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

1 file inspected, 1 offense detected
```

And a second one:

```
Casks/google-nik-collection.rb:36:7: C: Indent the right bracket the same as the left bracket.
      ]
      ^
```

So I have to manually indent the 2 last lines which not efficient to end up to:

``` ruby
      rmdir:  [
                '/Library/Preferences/Google',
              ]
```

Seems like the 2-space indentation is based on the hash key (`rmdir:`) and no on the `[` char as it should be.

Is there a magic emacs configuration to solve that issue?

Thanks for your help.

**Comment by Drenmi** [comment]
I can no longer reproduce this in current `master`. Please feel free to re-open this issue with a reproducible example if you're still experiencing the problem. 🙂
