### ISSUE TITLE
In integration with rake unable to output html report file with html formatter

### ISSUE THREAD

**Issue by sudhanshusr** [bbatsov/rubocop#2991]
In CI of ROR using jenkins when I integrate rubocop with rake I also want to publish html report file with html formatter.

Existing rakefile:

RuboCop::RakeTask.new(:rubocop) do |task|
  task.patterns = ['lib/**/*.rb']
  # only show the files with failures
  task.formatters = ['files']
  
  # don't abort rake on failure
  task.fail_on_error = false
end

Please suggest the changes required in it

## RuboCop version

$ rubocop -v
0.37.2
```

**Comment by sudhanshusr** [comment]
please reply @bbatsov

**Comment by segiddins** [comment]
@sudhanshusr it doesn't look like you're setting the HTML formatter in your Makefile.

**Comment by sudhanshusr** [comment]
@segiddins when i set the task.formatters = ['html'] in mt rake file then it prints the html file on console itself. I want a separate output file for the rubocop report.

**Comment by iconoclast** [comment]
It's not elegant, but you can pass command line options in the rake task itself like this:

task.formatters = ['html']
task.options = ['--out', 'rubocop-report.html']

**Comment by sudhanshusr** [comment]
thanks @iconoclast it works for me
