### ISSUE TITLE
Test failure when rspec run from inside .gem sub directory

### ISSUE THREAD

**Issue by gerrywastaken** [bbatsov/rubocop#2995]
My $GEM_HOME is ~/.gem (I believe this is the default when using chruby). One of the rspec tests fail when run beneath a hidden directory.

## Expected behavior
No rspec failures when the code is stored beneath a hidden directory.

It seems this line is the cause of the match returning false: https://github.com/bbatsov/rubocop/blob/master/lib/rubocop/path_util.rb#L35

Can the deprecated behaviour be removed yet?
## Actual behavior
```
Failures:

  1) RuboCop::Config#file_to_exclude? when the passed path matches any of patterns to exclude returns true
     Failure/Error: expect(configuration.file_to_exclude?('bar.rb')).to be_truthy

       expected: truthy value
            got: false
     # ./spec/rubocop/config_spec.rb:234:in `block (4 levels) in <top (required)>'

Finished in 27.62 seconds (files took 5.31 seconds to load)
9425 examples, 1 failure, 3 pending

Failed examples:

rspec ./spec/rubocop/config_spec.rb:228 # RuboCop::Config#file_to_exclude? when the passed path matches any of patterns to exclude returns true
```

## Steps to reproduce the problem
* Move the RuboCop source directory beneath a hidden directory e.g. ~/.gem/rubocop
* run rspec in the ~/.gem/rubocop directory

## RuboCop version
```
$ rubocop -V
0.39.0 (using Parser 2.3.0.7, running on ruby 2.3.0 x86_64-darwin15)
```

**Comment by bbatsov** [comment]
> Can the deprecated behaviour be removed yet?

For sure. Feel free to update this.

**Comment by gerrywastaken** [comment]
> For sure. Feel free to update this.

Scary deprecating code in a project that a lot of people rely on, but there you go.
