### ISSUE TITLE
 Useless assignment to variable - `s`.  Use just operator `|`

### ISSUE THREAD

**Issue by envygeeks** [bbatsov/rubocop#3009]
## Behavior

* Useless assignment to variable - `s`.  Use just operator `|`. (Lint/UselessAssignment)

---

## Reproduction

```bash
printf "s = Set.new\ns |= [:a, :b]" > test.rb && \
  bundle exec rubocop test.rb
```

---

## Expected

It not to say that, `|=` is like `|` when it's not, `|=` is closer to `+=` than it is to `||=` which I am assuming this is confusing it with.  `|=` does ***not*** create a variable.  `|=` is a destructive union, not an `or`, see:

```ruby
a  = [:hello, :world] 
a |= [:world]
a
=> [
  :hello, :world
]
```

---
## Version

```
bundle exec rubocop -V
0.39.0 (using Parser 2.3.0.7, running on ruby 2.3.0 x86_64-linux-gnu)
```

**Comment by segiddins** [comment]
It's useless because the variable isn't used after that re-assignment

**Comment by envygeeks** [comment]
@segiddins If you want the example updated then ask for that, I can fix the example so it's closer to our code an not an immediate replication, but do not assume to take the mick.

**Comment by envygeeks** [comment]
Either way, this isn't a bug here anyways.  This was a problem with `Enumerator#each_with_object`.
