### ISSUE TITLE
Method has too many lines 23/20 (todo file being ignored)

### ISSUE THREAD

**Issue by whithajess** [bbatsov/rubocop#3021]
## Expected behavior
```
rubocop --auto-gen-config
```
Will mean the offence `Method has too many lines. [23/20]` will be ignored when running
```
rubocop
```

## Actual behavior
```
# Offense count: 2
# Configuration parameters: CountComments.
Metrics/MethodLength:
  Max: 23
```
Is added in the `.rubocop_todo.yml` but when running these 2 offences are still shown as an offence (The todo file is being used and ignoring other offences)

## Steps to reproduce the problem

Write a method of 23 lines and run `rubocop --auto-gen-config` and then `rubocop`

## RuboCop version
```
$ rubocop -V
0.39.0 (using Parser 2.3.0.7, running on ruby 2.2.2 x86_64-linux)
```

**Comment by segiddins** [comment]
What's the contents of your `.rubocop.yml`?

**Comment by whithajess** [comment]
Sorry just found

```
Metrics/MethodLength:
  Max: 20
```
