### ISSUE TITLE
Feature request: Add an option in Style/Lambda to enforce -> for lambdas regardless of length

### ISSUE THREAD

**Issue by kuon** [bbatsov/rubocop#3022]
An option should be added to `Style/Lambda` to allow the use of `->` syntax with multiline lambdas.

The following would be valid:

```ruby
foo = -> do
end

foo = -> {}
```

the following would not:

```ruby
foo = lambda do
end

foo = lambda {}
```

**Comment by Drenmi** [comment]
This looks very similar to #2909. Is it the same as is being discussed there? 😀

**Comment by kuon** [comment]
It's similar, but the other way around (lambda instead of ->) if I understand it correctly. The thing is, the current implementation wants both syntax `foo = -> {}` for single line and `foo = lambda do; end` for multiline lambda. What we are asking for (and I guess #2909 as well) is to enforce one style.

**Comment by bbatsov** [comment]
I think both issues make perfect sense. I won't be able to work on this in the next couple of months, but I'd gladly accept a PR.

**Comment by Neodelf** [comment]
You propose using `lambda` and `->` for multiline block doesn`t create offense?

**Comment by kuon** [comment]
Yeah, we should be able to pick either one of the syntax, and if `->` is used, then `->` don't create offense for multiline blocks.

**Comment by Neodelf** [comment]
Hi again all. If we remove replacement old style (with `lambda`) to new style (with `->`), should we leave the opportunity autocorrection from
```ruby
-> (x)do
  x
end
```
to
```ruby
->(x) do
  x
end
```
?
And needless to add offense?

**Comment by kuon** [comment]
Yeah I think the second form is better.

**Comment by Neodelf** [comment]
@bbatsov, what do you think?
