### ISSUE TITLE
Use Hound for PR checks?

### ISSUE THREAD

**Issue by lorentrogers** [bbatsov/rubocop#3027]
This project seems like it would really benefit from using [Hound CI](https://houndci.com/). Is there a reason why it's not used to validate PRs?

**Comment by bbatsov** [comment]
It uses an old version of RuboCop and we do use RuboCop in travis anyways. Might not be as fancy, but it gets the job done.

**Comment by lorentrogers** [comment]
Of course -- makes complete sense. (Duh. I watched the Rubocop tests run with `rake`...)
