### ISSUE TITLE
Autocorrect "or" and "and" expressions with predicates that don't have spaces

### ISSUE THREAD

**Issue by graemeboy** [bbatsov/rubocop#3032]
When autocorrecting "and" and "or" expression that contain predicates methods with no space before the args, the first character of the arg is removed.

## Expected behavior
```ruby
false or 'a'.is_a?String
=> false || 'a'.is_a?(String)
```

## Actual behavior
```ruby
false or 'a'.is_a?String
=> false || 'a'.is_a?(tring)
```

## Steps to reproduce the problem

````ruby
# test.rb
'1'.is_a?Integer or 1.is_a?Integer
````

```rubocop -a test.rb`
=> 1 file inspected, 1 offense detected, 1 offense corrected ``` 

```ruby
# updated test.rb
'1'.is_a?(nteger) || 1.is_a?(nteger)
```
## RuboCop version

```
$ rubocop -V
0.39.0 (using Parser 2.3.0.7, running on ruby 2.1.5 x86_64-darwin14.0)
```

**Comment by jonas054** [comment]
Fixed by #3033.
