### ISSUE TITLE
RedundantException should catch `RuntimeError.new`

### ISSUE THREAD

**Issue by ptarjan** [bbatsov/rubocop#3034]
## Expected behavior

Complains and autocorrects to `raise 'message'`

## Actual behavior

```
$ rubocop a.rb
Inspecting 1 file
.

1 file inspected, no offenses detected
$ cat a.rb
raise RuntimeError.new('message')
$ cat .rubocop.yml
Style/RaiseArgs:
  EnforcedStyle: compact
```
## Steps to reproduce the problem

Make the files as I showed above.

## RuboCop version

```
$ rubocop -V
0.39.0 (using Parser 2.3.0.7, running on ruby 2.1.2 x86_64-darwin15.0)```

**Comment by jonas054** [comment]
This issue was closed by mistake due to a faulty commit message.
