### ISSUE TITLE
signalstyle seems to have broken in 0.39.0

### ISSUE THREAD

**Issue by jaymzh** [bbatsov/rubocop#3046]
In 0.36.0 SignalStyle wanted you to use 'fail' for exceptions and 'raise' for re-throwing.

In 0.39.0 it complains about 'fail' saying "Always use raise to signal exceptions."

I tried to set Style/SIgnalStyle to 'semantic' in my config, but was told it was an unrecognized cop.

## Expected behavior

`fail` is the preferred way to signal exception.

## Actual behavior

`raise` is the preferred way to signal exception.

## Steps to reproduce the problem

Use 'fail', run rubocop 0.39.0.

## RuboCop version

Include the output of `rubocop -V`:

```
$ bundle exec rubocop -V
0.39.0 (using Parser 2.3.0.7, running on ruby 2.0.0 x86_64-linux)
```

**Comment by bbatsov** [comment]
The cop's name is `Style/SignalException`. The default was changed a few versions ago to reflect a change we've made to the Ruby style guide.
