### ISSUE TITLE
Rubocop doesn't work on Eamcs 

### ISSUE THREAD

**Issue by jvrn3** [bbatsov/rubocop#3054]
I get this error message when trying to run rubocop-check-current-file  on Emacs:
 
Suspicious state from syntax checker ruby-rubocop: Checker ruby-rubocop returned non-zero exit code 1, but no errors from output: /home/belph/.rbenv/versions/2.2.3/lib/ruby/2.2.0/rubygems/dependency.rb:315:in to_specs': Could not find 'rubocop' (>= 0) among 6 total gem(s) (Gem::LoadError)
Checked in 'GEM_PATH=', execute 'gem env' for more information
	from /home/belph/.rbenv/versions/2.2.3/lib/ruby/2.2.0/rubygems/dependency.rb:324:in 'to_spec'
	from /home/belph/.rbenv/versions/2.2.3/lib/ruby/2.2.0/rubygems/core_ext/kernel_gem.rb:64:in 'gem'
	from /home/belph/.rbenv/versions/2.2.3/bin/rubocop:22:in '<main>'

I want to use flycheck on Emacs, so I set my robocop and ruby location: 

(setq flycheck-ruby-rubocop-executable "~/.rbenv/shims/rubocop")
(setq flycheck-ruby-executable "/home/belph/.rbenv/shims/ruby")

`$rubocop -V`
'0.39.0 (using Parser 2.3.0.7, running on ruby 2.2.3 x86_64-linux)'

`$ruby -v`
'ruby 2.2.3p173 (2015-08-18 revision 51636) [x86_64-linux]'

`gem env`
RubyGems Environment:
  - RUBYGEMS VERSION: 2.4.5.1
  - RUBY VERSION: 2.2.3 (2015-08-18 patchlevel 173) [x86_64-linux]
  - INSTALLATION DIRECTORY: /home/belph/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0
  - RUBY EXECUTABLE: /home/belph/.rbenv/versions/2.2.3/bin/ruby
  - EXECUTABLE DIRECTORY: /home/belph/.rbenv/versions/2.2.3/bin
  - SPEC CACHE DIRECTORY: /home/belph/.gem/specs
  - SYSTEM CONFIGURATION DIRECTORY: /home/belph/.rbenv/versions/2.2.3/etc
  - RUBYGEMS PLATFORMS:
    - ruby
    - x86_64-linux
  - GEM PATHS:
     - /home/belph/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0
     - /home/belph/.gem/ruby/2.2.0
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => false
     - :bulk_threshold => 1000
  - REMOTE SOURCES:
     - https://rubygems.org/
  - SHELL PATH:
     - /home/belph/.rbenv/versions/2.2.3/bin
     - /home/belph/.rbenv/libexec
     - /home/belph/.rbenv/plugins/ruby-build/bin
     - /home/belph/.rbenv/shims
     - /home/belph/.rbenv/bin
     - /usr/local/heroku/bin
     - /usr/local/bin
     - /usr/bin
     - /bin
     - /home/belph/.rvm/bin

I used "exec-path-from-shell-initialize" and it still gives me the same message.

**Comment by alexdowad** [comment]
Please send this issue to the flycheck developers.

**Comment by AlexJakeGreen** [comment]
You have to install rvm and load it before flycheck

**Comment by jonas054** [comment]
Closing as this is not the right forum.

**Comment by ZzAntares** [comment]
For others reading after searching about this problem, I want to say that in the end this problem was caused because I'm using the plugin `rbenv-bundle-exec` and when you read their [README.md](https://github.com/maljub01/rbenv-bundle-exec) carefully, it says that this errors will happen.

The fix:

``` sh
echo "rubocop" >> ~/.no_bundle_exec
```

I don't know if the author of this issue managed it to solve it in the end, but in my case that did the trick.
