### ISSUE TITLE
Wrong automatic replacement for interpolation

### ISSUE THREAD

**Issue by uzzer** [bbatsov/rubocop#3057]
Rubocop autofix made mistake in replacement

## Expected behavior
```
-       "#{pretty_msisdn current_customer.msisdn}"
+      pretty_msisdn(current_customer.msisdn).to_s
```
## Actual behavior
```
-       "#{pretty_msisdn current_customer.msisdn}"
+      pretty_msisdn current_customer.msisdn.to_s
```
## Steps to reproduce the problem

`rubocop -a`

## RuboCop version

```
$ rubocop -V
0.39.0 (using Parser 2.3.0.7, running on ruby 2.2.4 x86_64-darwin15)
```

**Comment by mikegee** [comment]
I'm failing to reproduce this on the latest master. I get:

```ruby
(pretty_msisdn current_customer.msisdn).to_s
```

**Comment by uzzer** [comment]
Cannot reproduce either, while somehow it was fixed like this.

Do you think `(pretty_msisdn current_customer.msisdn).to_s` is better than `pretty_msisdn(current_customer.msisdn).to_s` ?

**Comment by jonas054** [comment]
> Do you think (pretty_msisdn current_customer.msisdn).to_s is better than pretty_msisdn(current_customer.msisdn).to_s ?

Yes I do, but we don't want to burden `Style/UnneededInterpolation` with knowing about such things. A new cop would be in order, I think.

Closing issue as original bug can't be reproduced.
