### ISSUE TITLE
Doesn't remove space from %w array

### ISSUE THREAD

**Issue by guyisra** [bbatsov/rubocop#3058]
for an array defined like 
`%w( 2016-04-01 2016-03-01 2016-02-01 2016-01-01)`

Rubocop won't fix the initial space (or add a space at the end)

Using latest rubocop

**Comment by jonas054** [comment]
I think the best solution is to add a new cop for space in `%w`/`%W` literals, and one for `%i`/`%I`.

**Comment by Drenmi** [comment]
@jonas054: Do you think it would be acceptable with a single cop for both styles of word array (`%w` and `%i`)? Since most of the functionality will be duplicated. For example `Style/SpaceInsideWordArray`?

(Arguably, `Style/SpaceInsideBrackets` should be named `Style/SpaceInsideArrayLiteral`. 😀 )

**Comment by jonas054** [comment]
Yes, that would be acceptable IMO. And let's only enforce "no space", and maybe add the configuration option later if there's a demand.
