### ISSUE TITLE
Custom code analysis

### ISSUE THREAD

**Issue by abhisheksarka** [bbatsov/rubocop#3066]
Hi,

First of all, thank you for the great work. Just started using it and love it. However, is there a way we can add a custom analysis(using regex)? For e.g I want my team members to use something like `raise AppError::Something` instead of `raise 'Something went wrong'`. Basically, constants instead of hardcoded strings when raising errors.

What I would like to put forward is, maybe in a configuration file we should be able specify a **regex** and the **message** it should display, when it comes across such a match in the source code.

**Comment by andyw8** [comment]
You can add a custom cop: https://github.com/bbatsov/rubocop#custom-cops

**Comment by jonas054** [comment]
A new cop that checks exception types against a blacklist or whitelist sounds like a reasonable idea to me. It could be part of RuboCop and wouldn't have to be a custom cop. But it would accept any exception type by default, or be disabled by default.

That's my opinion. Don't know if @bbatsov agrees.

**Comment by alexdowad** [comment]
Agree with @jonas054.
