### ISSUE TITLE
Feature Request: Style/EmptyLinesAroundAccessModifier option to have two lines around access modifier

### ISSUE THREAD

**Issue by mobilutz** [bbatsov/rubocop#3070]
In my project I use two lines around the access modifiers. This breaks the cop `Style/EmptyLinesAroundAccessModifier`

Maybe you could add an option for the cop with which one can set the line numbers around the access modifiers.

**Comment by alexdowad** [comment]
I think that this is quite an unconventional style and would be better served by a project-specific custom cop. (I've never seen it in any open-source Ruby code which I worked on, for example.)

**Comment by mobilutz** [comment]
Ok, I will see if I write my own cop for that. Thanks for the reply.
