### ISSUE TITLE
Style/SymbolProc: Do not suggest change when splash-arguments are used

### ISSUE THREAD

**Issue by krissi** [bbatsov/rubocop#3083]
Given this function

```
define_method(:give_first_arg) do |*args|
  args.first
end
```

rubocop tell me this:
```
Pass &:first as an argument to define_method instead of a block.
define_method(:give_first_arg) do |*args| ...
                               ^^^^^^^^^^
```

This suggestion is wrong, because of the splat operator. `first` would be sent to the first argument, not the Array `args`.

The only example I can think right now where this happens is `define_method` & co, but this example shows that it is related to the splash operator:

```
def up_you_go(ary)
  yield(*ary.collect(&:upcase))
end

y = up_you_go(%w(hello world)) do |*ary|
  ary.first
end
```

**Comment by rrosenblum** [comment]
This does sound like a bug to me. It should be pretty easy to fix.
