### ISSUE TITLE
TargetRubyVersion should be pulled from the Gemfile or .ruby_version files if available

### ISSUE THREAD

**Issue by thegranddesign** [bbatsov/rubocop#3096]
We already have standard locations where the desired Ruby version lives.  Adding yet another to this list seems unnecessary.

My request is that if a `Gemfile` Ruby requirement is set, use that, otherwise fall back to `.ruby_version` if available and as a last resort, look for the `TargetRubyVersion`.

**Comment by mikegee** [comment]
This was discussed most recently here: https://github.com/bbatsov/rubocop/issues/2956

**Comment by thegranddesign** [comment]
@mikegee I did a search for `TargetRubyVersion` and didn't see that one.  Thank you!
