### ISSUE TITLE
Rails cops: referer vs referrer

### ISSUE THREAD

**Issue by mockdeep** [bbatsov/rubocop#3105]
Rails supports both `request.referer` and `request.referrer`, and after perusing our codebase we discovered that we're using both. It would be great to have a cop to enforce one or the other for the sake of consistency.

**Comment by bbatsov** [comment]
Isn't `referrer` the only correct spelling of the word? :-) Yeah, guess we can have a cop for this. PR welcome!

**Comment by mockdeep** [comment]
Haha, well technically speaking... https://en.wikipedia.org/wiki/HTTP_referer#Etymology

**Comment by bbatsov** [comment]
Good to know! :-)

**Comment by rrosenblum** [comment]
@mockdeep, based on the wiki article, this is quite interesting. It appears that the misspelling has become the standard. It raises an interesting question of if `referer` or `referrer` should be used. I wonder which spelling other common libraries and frameworks prefer.

**Comment by mockdeep** [comment]
@rrosenblum something tells me it isn't very consistently spelled anywhere, though I think we'd go with `referer` in our codebase just for consistency with the spec.

**Comment by mockdeep** [comment]
I could see it being a configurable cop, though, so people can pick their flavor.

**Comment by rrosenblum** [comment]
> I think we'd go with `referer` in our codebase
> I could see it being a configurable cop

I was thinking the same things.

**Comment by mockdeep** [comment]
Nice, thanks!

**Comment by bquorning** [comment]
Oh, the confusion: https://www.w3.org/TR/html5/links.html#link-type-noreferrer 😆

**Comment by leewaa** [comment]
Old issue I know however, this one killed my flow 😂 a cop against something like this is imho, useless! and it takes the **incorrect** spelling of the word.

The correct spelling is **referrer** !

**Comment by whchi** [comment]
I think not to check is the best practice...

**Comment by leewaa** [comment]
I still can't believe that a cop like this even exists. Rubocop is a great concept, but the devs are taking it way to far with this one.

**Comment by mockdeep** [comment]
@leewaa you know you can disable rules that aren't useful to you, right? You can also configure it to your preferred spelling. I've been happy with this rule. Having inconsistent spelling makes it harder to grep for references.
