### ISSUE TITLE
Lint exception inheritance

### ISSUE THREAD

**Issue by lloeki** [bbatsov/rubocop#3127]
`Lint/RescueException` looks for misuse of `Exception` in a `rescue` statement, and dutifully suggests to rescue from `StandardError` which is Ruby's default for `rescue`. Since there is a high chance a similar mistake when declaring an exception class is being made, the suggested fix may lead to the exception never being caught.

As an example, picture someone following Rubocop's advice and fixes this:

```ruby
class FooError < Exception; end

begin
  raise FooError
rescue Exception
  puts 'rescued'
end
```

into this:

```ruby
class FooError < Exception; end

begin
  raise FooError
rescue StandardError
  puts 'rescued'
end
```

when he should have been doing this instead:

```ruby
class FooError < RuntimeError; end

begin
  raise FooError
rescue StandardError
  puts 'rescued'
end
```

As a consequence it is quite interesting to lint for custom exceptions that may mistakenly inherit from `Exception` instead of either `StandardError` or `RuntimeError`, the latter being preferred since it's the default for `fail`/`raise` (perusing the symmetry with `rescue` being prodded into Ruby's default behaviour).

Expected behaviour:

```ruby
# no problem
class FooError; end

# no problem, if RuntimeError is preferred (default)
class FooError < RuntimeError; end

# no problem, if StandardError is preferred (alternate `EnforcedStyle`)
class FooError < StandardError; end

# this is a problem
class FooError < Exception; end

# should it be legit, it should be explicitly ignored by a directive along with due documentation
class ReallyAnException < Exception; end # rubocop:disable Lint/InheritException
```

Suggested `-D` message:

```
Lint/InheritException: Avoid inheriting from the Exception class. Perhaps you meant to inherit from RuntimeError?
```

**Comment by jonas054** [comment]
Good idea.

**Comment by RKushnir** [comment]
@lloeki Could you, please, explain, why exactly `RuntimeError`? I googled for it, and every blog post suggests using `StandardError`.

**Comment by lloeki** [comment]
In terms of code execution, `raise` by itself or with a `String` argument raises a `RuntimeError` (which itself inherits `StandardError`).

Take it from there: someone wrote or encounters a `raise` or `raise 'foo'` at some point and now wants to create a proper `FooError` exception class instead. Somewhere someone else may have written a `rescue RuntimeError` since that was what `raise` without being passed an exception class raises. Now the person writing the new `FooError` exception class mistakenly inherits from `Exception`, and rubocop wants to helpfully suggest a thing. The isofunctional thing to suggest is `RuntimeError` since we are sure this will work whatever rescue other people may have been writing that was working before.

In terms of convention when writing an exception, sure `StandardError` is a good thing *when you write it before the `raise`/`rescue` are in place*, and one good thing to suggest, hence the `EnforcedStyle` option. But when you're refactoring a big pile of code of varying quality things may be different.

Also, when faced with `RuntimeError` there is IMHO a higher chance of asking oneself "is it really a runtime error or is it more of a standard error?".

**Comment by RKushnir** [comment]
I see. Thanks for the comprehensive reply 🙂
