### ISSUE TITLE
undefined method `source' for nil:NilClass in ZeroLengthPredicate

### ISSUE THREAD

**Issue by chronodm** [bbatsov/rubocop#3131]
## Expected behavior

`rubocop -a` completes without errors

## Actual behavior

`rubocop -a` bails after parsing five of 20 files, with the attached [stack trace](https://github.com/bbatsov/rubocop/files/262358/rubocop.txt) (originating at `zero_length_predicate.rb:65`).

## Steps to reproduce the problem

Run `rubocop -a` against the following source:

```ruby
class Foo
  attr_accessor :size

  def frob
    return nil if size == 0
    1
  end
end
```

## Notes

- Using `@size` instead of `size` fixes the problem, as does using `size <= 0` instead of `size == 0`.
- Using `self.size` instead of `size` does not fix the problem -- though `self.size` gets autocorrected to `size` before it fails.
- Introducing an `empty?` method does not fix the problem (although it's likely that in that case the failure is in the `empty?` method's own `size == 0` check).
- adding `# rubocop:disable Style/ZeroLengthPredicate` after `def frob`, surprisingly, does not fix the problem.

## RuboCop version

Include the output of `rubocop -V`:

```
$ bundle exec rubocop -V
0.40.0 (using Parser 2.3.1.0, running on ruby 2.2.3 x86_64-darwin14)
```

**Comment by tejasbubane** [comment]
Actually the bug is with the cop showing offense for `size == 0`:

```
Offenses:

rubocop_bug_test.rb:5:19: C: Style/ZeroLengthPredicate: Use empty? instead of size == 0.
    return nil if size == 0
                  ^^^^^^^^^

1 file inspected, 1 offense detected
Finished in 0.23116467497311532 seconds
```

This should not happen since the cop works on `Array#size` and not variables. Same happens for `length`. I added [some failing specs](https://github.com/tejasbubane/rubocop/commit/df9a4c66f069fb56f3108e3e1f82ccbf25231db4#diff-c725e21ae79b044ab19c51e9c91f9353R89) for these and will send a PR soon.
