### ISSUE TITLE
Frozen string literal comment treated as module/class documentation

### ISSUE THREAD

**Issue by md5** [bbatsov/rubocop#3159]
When `# frozen_string_literal: true` is added to a file, the `Style/Documentation` cop incorrectly considers a following `Module` or `Class` to be documented if there is no line break after the comment. If you add a blank line between the `frozen_string_literal` command and the module or class definition, `Style/Documentation` will correctly point out that the module or class is not documented.

**Comment by alexdowad** [comment]
Nice catch.
