### ISSUE TITLE
Metrics/MethodLength configuration inside of .rubocop.yml not being applied

### ISSUE THREAD

**Issue by c-abramson** [bbatsov/rubocop#3163]
We tried both 

``` .yml
Metrics/MethodLength:
    Enabled: false
```

and

``` .yml
Metrics/MethodLength:
    Max: 20
```

but the default values of 'Enabled' and '10' were not overwritten. Other cop configuration was properly applied in the same file.

```
$ rubocop -V
0.40.0 (using Parser 2.3.1.0, running on ruby 2.3.0 x86_64-darwin15)
```

**Comment by jonas054** [comment]
Run `rubocop --debug` to see which configuration files are read. I figure there must be a setting in some other configuration file that overrides the one you're talking about.

**Comment by alexdowad** [comment]
...Or else give us example code which can be used to reproduce the problem.

**Comment by maxjacobson** [comment]
With apologies, I got my numbers mixed up and led to this issue being closed instead of #3136 -- if you believe this is still an issue you may want to reopen this

**Comment by mikegee** [comment]
@c-abramson can you provide an example for others to reproduce the problem?

**Comment by c-abramson** [comment]
I'll re-open this issue if I can produce some sample code.
