### ISSUE TITLE
Move CopHelper to a file in lib so it can be included outside RuboCop?

### ISSUE THREAD

**Issue by tsigo** [bbatsov/rubocop#3176]
Recently at GitLab we've begun writing custom cops to enforce some things that are very specific to our style preferences and/or our codebase. Obviously we want to make sure these cops are covered by automated tests, but the tests make use of the methods from [`CopHelper`](https://github.com/bbatsov/rubocop/blob/master/spec/support/cop_helper.rb).

For now I've gotten by just copying the relevant parts of `CopHelper` into a file in our own `spec/support` directory, but I'm wondering if it would make sense to move the file into RuboCop's `lib` folder as something like `test_helper`, so that it can be required as-needed for testing custom cops.

**Comment by jonas054** [comment]
Since `cop_helper.rb` is packaged in the rubocop gem, you can require it by hacking your load path:
```ruby
require 'rubocop'
require 'rspec'
$LOAD_PATH << $LOAD_PATH.grep(/rubocop-/).first.sub(/lib$/, '')
require 'spec/support/cop_helper'
```
How do you feel about that?

**Comment by tsigo** [comment]
> How do you feel about that?

@jonas054 Not great, but thanks for the suggestion. 😃  #3179 has what we need.

**Comment by alexdowad** [comment]
I agree with @jonas054's suggestion. No need to expose more in our "public interface", which must then be kept and supported (because we'll break people's code if we change or remove it).

Better that @tsigo just copies the code and maintains his own version, which can be tailored to his team's needs.
