### ISSUE TITLE
Extract NodePattern into own gem

### ISSUE THREAD

**Issue by ngroman** [bbatsov/rubocop#3212]
`NodePattern` is great and very useful for many static code-analysis tasks, some of which don't involve the rest of rubocop.

Extracting it into its own gem would be really helpful.

**Comment by bbatsov** [comment]
Perhaps. I'm not really eager to deal with the overhead of maintaining two gems. The AST extensions we have are likely going to be useful on their own as well. I might get to doing this, but I don't expect it will happen any time soon.

**Comment by bbatsov** [comment]
I'll close this for now.
