### ISSUE TITLE
Add Lint check for commas in percentage arrays

### ISSUE THREAD

**Issue by TheSmartnik** [bbatsov/rubocop#3219]
I believe it may helpful to add check for commas in percentage arrays of words/symbol.
```ruby 
%w(array, of, words)
```
Commas in those arrays look like a mistake and more often than not, they are.
There have already been PR considering the issue: #2807, but I wanted to ask for your opinion regardless.

**Comment by owst** [comment]
I've got a open, pending PR for this: #3165

**Comment by TheSmartnik** [comment]
@owst :+1:
