### ISSUE TITLE
RequestReferer should be in the Rails namespace, not Style

### ISSUE THREAD

**Issue by bquorning** [bbatsov/rubocop#3240]
It seems to me that the `Style/RequestReferer` cop (suggested in #3105, implemented in #3171) should be a Rails cop. Actually, `#referer`/`#referrer` are implemented in Rack, not Rails, but I guess it’s a Rails cop nonetheless.

**Comment by bbatsov** [comment]
Definitely. This was an oversight on my part.

**Comment by bquorning** [comment]
I’ll whip up a PR.
