### ISSUE TITLE
Unable to run Rubocop

### ISSUE THREAD

**Issue by NekoNova** [bbatsov/rubocop#3248]
I just upgraded Rubocop to the latest version, but when I try to run it now, I receive the error:

```
➜  bundle exec rubocop
Error: Unknown Ruby version 0.0 found in `.ruby-version`.
Known versions: 1.9, 2.0, 2.1, 2.2, 2.3
```

This behaviour started after the upgrade.
--------

## Expected behavior
I expect Rubocop to work

## Actual behavior
It spits out this error. Worked fine before the upgrade.

## Steps to reproduce the problem
Have Ruby 2.2.5 installed, and upgrade from `0.40.0` to `0.41.1`
Then use the command `bundle exec rubocop --auto-gen-config` or just `bundle exec rubocop`
Running the `-V` command works for some reason.

## RuboCop version
```
$ rubocop -V
0.41.1 (using Parser 2.3.1.2, running on ruby 2.2.5 x86_64-darwin15)
```

**Comment by NekoNova** [comment]
## Update ##
Our `.ruby-version` file originally contained the value `ruby-2.2.5`.
When I switched this `2.2.5` it suddenly worked fine.

**Comment by bquorning** [comment]
Seems to be caused by #3228 - cc/ @pclalv

**Comment by bbatsov** [comment]
If rbenv supports both notations, I guess we should support them as well.

**Comment by aviflax** [comment]
I’m having the same problem, but I’m using JRuby, so my prefix in `.ruby-version` is `jruby`. It doesn’t seem like #3251 will fix the problem for JRuby users.

**Comment by achiinto** [comment]
We have our own build of Ruby, which is basically the same copy of Ruby as publicized, Just due to enterprise security reason, we ended up with our own and have a different naming. So, this bug is preventing it to work.

**Comment by bquorning** [comment]
@achiinto I believe #3261 will fix the problem?

**Comment by achiinto** [comment]
hi @bquorning, seems like that will fix it.
