### ISSUE TITLE
UniqBeforePluck assumes transitivity, but it isn't always.

### ISSUE THREAD

**Issue by jcoyne** [bbatsov/rubocop#3257]
## Given
I have code that looks like this:
```ruby
# dterm.local_authorities is an instance of AR::CollectionProxy
dterm.local_authorities.pluck(:id).uniq
```

## Expected behavior

It does nothing.

## Actual behavior

Rubocop complains:

```
Rails/UniqBeforePluck: Use uniq before pluck
```
when I follow the suggestion, I get an error.

```
     Failure/Error: authorities = dterm.local_authorities.uniq.pluck(:id)
     NoMethodError:
       undefined method `pluck' for [#<LocalAuthority id: 1, name: "lexvo_languages">]:Array
```

## Diagnosis

The `uniq` returns an Array here:
https://github.com/rails/rails/blob/master/activerecord/lib/active_record/associations/collection_association.rb#L375-L381 and Array does not support `pluck`

## Steps to reproduce the problem

Create a file with the following code:
```ruby
bar.pluck(:id).uniq
```
Rubocop will assumes that uniq and pluck are transitive.

## RuboCop version

Include the output of `rubocop -V`:

```
$ rubocop -V
0.40.0 (using Parser 2.3.1.2, running on ruby 2.3.0 x86_64-darwin14)
```

**Comment by tjwp** [comment]
@jcoyne This was addressed in https://github.com/bbatsov/rubocop/pull/3231 for v0.41
