### ISSUE TITLE
JSON::Parser not defined (NameError) with json_pure 2.0.0

### ISSUE THREAD

**Issue by shaicoleman** [bbatsov/rubocop#3273]
If json_pure 2.0.0 is required in the Gemfile, Rubocop breaks with an error.

I've opened an issue with json_pure, as the issue seem to be there, opening it here so other people can find it. 
https://github.com/flori/json/issues/287

**Comment by zach-dunton-sf** [comment]
It also breaks with json 2.0.0 from stdlib. I'm new to ruby, not sure if that is the same as json_pure.

/home/travis/.rvm/gems/ruby-2.1.0/gems/json-2.0.0/lib/json/common.rb:28:in `remove_const': constant JSON::Parser not defined (NameError)

**Comment by revett** [comment]
+1 saw this today

**Comment by revett** [comment]
This issue has been **fixed** in the _v2.0.1_ release 🎉

**Comment by tejasbubane** [comment]
This is not related to `rubocop` but anyways, I can confirm that `v2.0.1` indeed fixed the error. This issue can be closed now.
