### ISSUE TITLE
MRI < 2.0 dependency problem on CI

### ISSUE THREAD

**Issue by Drenmi** [bbatsov/rubocop#3278]
I just created https://github.com/bbatsov/rubocop/pull/3277, but Travis fails the Ruby 1.9 check because:

```
Gem::InstallError: json requires Ruby version ~> 2.0.
```

I assume this happens because `parser` tries to install `json 2.0.1`. From the [json](https://github.com/flori/json/blob/master/CHANGES.md) repo:

> Drops support for old rubies whose life has ended, that is rubies < 2.0.

(This is a bit strange though, because `parser`'s CI passes on all rubies.)

**Comment by bbatsov** [comment]
Yep, that's true. `json` 2.0 dropped support for Ruby 1.9, so I guess we'll have to drop support for 1.9 as well (or drop our `json` related features). `parser` itself supports even Ruby 1.8...
