### ISSUE TITLE
[Feature] A cop to catch load instead of require

### ISSUE THREAD

**Issue by rudyyazdi** [bbatsov/rubocop#3281]
Do you guys think it's a good idea to have cop catching:

```ruby
load 'pry.rb'
```
instead of:

```ruby
require 'pry'
```

If you think it's a good idea please let me know and I can submit a PR :)

Cheers,

**Comment by bbatsov** [comment]
There are legitimate uses of `load`, so I'm not sure how useful such a cop would be.

**Comment by rudyyazdi** [comment]
Oh cool, I didn't know about such use cases ;)
