### ISSUE TITLE
Drop support for MRI < 2.0

### ISSUE THREAD

**Issue by Drenmi** [bbatsov/rubocop#3325]
Opening an issue for this as a reminder, and for discussion and documentation. Initially mentioned by @bbatsov [here](https://github.com/bbatsov/rubocop/issues/3278#issuecomment-230322685) and [here](https://github.com/bbatsov/rubocop/pull/3290#issuecomment-230676243), we should drop support for MRI 1.9.3, whose end of life was over one and a half years ago.

This will allow us to use modern versions of `json`, and make use of some of the features added in 2.0, notably keyword arguments. Also, we shouldn't enable people to stay on old, moss covered tech. 😉 

Potentially, we could start adhering to the same EOL dates as MRI itself?

**Comment by bbatsov** [comment]
> Potentially, we could start adhering to the same EOL dates as MRI itself?

This is our official policy, it's even mentioned somewhere in the README or the manual. We didn't drop support for 1.9 right away mostly because at the time still a lot of people were using it and keeping it around didn't really limit us a lot. I'm fine with dropping support for 1.9 now.
