### ISSUE TITLE
StrongRuby support

### ISSUE THREAD

**Issue by tarcieri** [bbatsov/rubocop#3356]
Hi there,

I'm mentoring a Ruby Google Summer of Code project where my student @robblanco has added a static type annotation syntax to @whitequark's `parser` (nearly identical to Crystal's).

As RuboCop already provides powerful tools for working with `parser` ASTs, so far he has been implementing the typechecker within RuboCop itself:

https://github.com/bbatsov/rubocop/compare/master...strongruby:strongruby

My question is: what's the recommendation from the RuboCop developers for something like this? Should we try to get these changes upstream into RuboCop itself? Maintain our own RuboCop fork? Or could they be spun out into a separate gem that acts as a RuboCop plugin?

I believe @whitequark is amenable to merging StrongRuby support into upstream parser, which would at least make a StrongRuby type checker as part of RuboCop technically feasible. I'm not sure this functionality makes sense as part of RuboCop itself or a separate gem.

Thoughts?

**Comment by tarcieri** [comment]
Just a quick note: I think if we got basic support for the StrongRuby parser nodes added to RuboCop upstream, the rest of the code could be moved to a separate gem.

**Comment by alexdowad** [comment]
So RuboCop would report an "offense" if your code doesn't type-check properly?

**Comment by tarcieri** [comment]
@alexdowad exactly. This supports a workflow similar to Facebook's Hack language (optionally typed PHP) where type errors do not directly impact program execution, so you can e.g. edit some code, refresh your browser, and see the result immediately without waiting for the program to fully typecheck.

**Comment by alexdowad** [comment]
I would suggest that this can be something like a plugin or add-on for RC.
Not built-in.

**Comment by tarcieri** [comment]
@alexdowad yeah, a plugin makes sense to me. What's a bit less clear to me is to how to actually do that as the current implementation is pretty coupled to RuboCop itself. As a specific example: type information is added to every `RuboCop::Node` object, and in several places we need to configure various options to add StrongRuby support as a language target. I guess what I'm asking for here is some sort of plugin API.

Alternatively have you considered extracting some of the core functionality of RuboCop into a separate gem? It contains a lot of great code for e.g. walking Parser's AST which I think is potentially reusable.

**Comment by backus** [comment]
Not sure exactly how this fits in but @tarcieri you might want to look at #3414

**Comment by benkimball** [comment]
Is there still interest in extending rubocop in this way?

**Comment by tarcieri** [comment]
Will go ahead and close this issue.

@benkimball there's another GSoC proposal (with an interested student) to pick up this work: https://github.com/rubygsoc/rubygsoc/wiki/Ideas-for-MRI-(Matz-Ruby-Interpreter)#experimental-type-annotation-syntax-support

As far as how that relates to RuboCop... I think a plugin-based approach (as in #3414) would be nice. The other thing that'd really be nice, but is probably a ton of work, is to extract the AST-related code from RuboCop into separate, reusable gems
