### ISSUE TITLE
`Performance/RangeInclude` should not correct when argument to `include?` is a range

### ISSUE THREAD

**Issue by cheerfulstoic** [bbatsov/rubocop#3373]
It is possible to provide a `Range` to `Range#include?` like `range.include?(arg)` to check that `range.begin <= arg.begin && arg.end <= range.end`.  Unfortunately `rubocop` auto-corrects this from `include?` to `cover?`, which does not provide the same result

--------

## Expected behavior

Rubocop should not detect these cases

## Actual behavior

Rubocop detects and auto-corrects

## Steps to reproduce the problem

`(self.begin..self.end).include?(token.begin..token.end)`

## RuboCop version

`0.42.0 (using Parser 2.3.1.2, running on ruby 2.2.3 x86_64-darwin14)`

**Comment by Drenmi** [comment]
This is not a behaviour of Ruby. It's added through monkey patching by ActiveSupport. 😀

Our official stance right now is that we can't take into consideration different frameworks. (This should eventually be handled by extensions for each framework.)

**Comment by cheerfulstoic** [comment]
Ah, of corse that old scamp ActiveSupport ;)

I'll rubocop:disable for now, thanks!
