### ISSUE TITLE
HTML formatter: table of contents at the beginning of the file

### ISSUE THREAD

**Issue by hedgesky** [bbatsov/rubocop#3379]
Wouldn't it be great if HTML formatter renders list of files with offenses with links to quick access to them? For example, imagine following use case: you are trying to check your project for a first time, and there are hundreds of files with offends. Quick navigation between them would be very helpful from my point of view.
I can try to implement this but would like to hear a word from maintainers before. Is this feature needed in the project?

**Comment by jonas054** [comment]
Would be useful IMO. Go right ahead!
