### ISSUE TITLE
Lint/ShadowedException can't handle multiple rescue blocks

### ISSUE THREAD

**Issue by ptarjan** [bbatsov/rubocop#3388]
If you don't know the inheritance between exceptions, why are you complaining about shadowing?

--------

## Expected behavior

```
$ cat a.rb
begin
rescue A, B
  nil
rescue C
  nil
end
$ rubocop a.rb
Inspecting 1 file
.

1 file inspected, no offenses detected
```

## Actual behavior

```
$ cat a.rb
begin
rescue A, B
  nil
rescue C
  nil
end
$ rubocop a.rb
Inspecting 1 file
W

Offenses:

a.rb:2:1: W: Do not shadow rescued Exceptions
rescue A, B ...
^^^^^^^^^^^

1 file inspected, 1 offense detected
```

## Steps to reproduce the problem

See above

## RuboCop version

```
$ rubocop -V
0.42.0 (using Parser 2.3.1.2, running on ruby 2.2.4 x86_64-darwin15)
```

**Comment by rrosenblum** [comment]
Definitely sounds like a bug. I thought I had a test case to check for a condition like this. I will take a look.

**Comment by rrosenblum** [comment]
Interesting, rescuing a single custom exception works fine. Rescueing multiple custom exceptions in the same `rescue` works fine. Rescuing a custom exception in different rescues works. Rescuing multiple custom exceptions in a `rescue` group followed by a group with a different custom exception causes this bug. I will hopefully find a fix for this shortly.
