### ISSUE TITLE
Allow TrailingCommaInLiteral to enforce Arrays but not Hashes

### ISSUE THREAD

**Issue by CyborgMaster** [bbatsov/rubocop#3394]
I would like TrailingCommaInLiteral to be enforced for arrays, but not hashes.  Could that be done with a configuration option?

**Comment by garettarrowood** [comment]
Over the next few days I'll tackle this.

Reviewing the cop, I do not believe a new config option is the way to go. There are already `no_comma`, `comma` & `consistent_comma` config options. This looks like a good candidate to break into 2 Cops, `TrailingCommaInArrayLiteral` & `TrailingCommaInHashLiteral`. This will allow unique configuration for both data types.
