### ISSUE TITLE
TernaryParentheses should have an option for complicated predicates

### ISSUE THREAD

**Issue by ptarjan** [bbatsov/rubocop#3399]
I'd like to enforce parens whenever the predicate has an operator in it and enforce there isn't any parens when there is no operator.

---
## Expected behavior

These are good:

```
foo ? 1 : 2
Foo::Bar.baz ? 1 : 2
(foo && bar) ? 1 : 2
(foo > 91) ? 1 : 2
```

and the inverse are bad as well as:

```
((foo)) ? 1 : 2
((foo > 91)) ? 1 : 2
```
## Actual behavior

There isn't a style option for this
## Steps to reproduce the problem

Feature request
## RuboCop version

```
$ rubocop -V
0.42.0 (using Parser 2.3.1.2, running on ruby 2.2.4 x86_64-darwin15)
```

**Comment by Drenmi** [comment]
Added in #3703. 🙂

**Comment by ptarjan** [comment]
Great thank you!
