### ISSUE TITLE
Cop Idea: linter for focused specs

### ISSUE THREAD

**Issue by Bartlebyy** [bbatsov/rubocop#3405]
add a checker for focussed specfiles > fit, fdescribe

If it sees one, it throws an error. 

This way people don't accidentally forget to remove them from their commits.

**Comment by backus** [comment]
Looks like you want rubocop-rspec. It has that cop: https://github.com/nevir/rubocop-rspec/blob/master/lib/rubocop/cop/rspec/focus.rb

**Comment by Bartlebyy** [comment]
thanks for letting me know! That works
