### ISSUE TITLE
Support editorconfig INI files for rubocop config

### ISSUE THREAD

**Issue by stephengroat** [bbatsov/rubocop#3409]
rubocop could use .editorconfig files to configure rubocop (only for the rules that editorconfig support).

This is a feature request, but I'm also wondering if this would be something that rubocop community would be interested in.

**Comment by jonas054** [comment]
It would add too much complexity to the already pretty hairy configuration file parsing IMO. I'd recommend starting a side project that converts `.editorconfig` files to `.rubocop.yml` files.

**Comment by stephengroat** [comment]
No problem. Thanks for the feedback!
