### ISSUE TITLE
TargetRubyVersion and embedded not working

### ISSUE THREAD

**Issue by smoothdvd** [bbatsov/rubocop#3412]
app/controllers/categories_controller.rb:7:3: F: embedded document meets end of file (and they embark on a romantic journey)
(Using Ruby 2.3 parser; configure using TargetRubyVersion parameter, under AllCops)
  =begin
  ^^^^^^

## RuboCop version

Include the output of `rubocop -V`:

```
$ rubocop -V
0.42.0 (using Parser 2.3.1.2, running on ruby 2.3.1 x86_64-darwin15)```

**Comment by bbatsov** [comment]
I don't quite understand the problem. More details would be useful.

**Comment by smoothdvd** [comment]
@bbatsov Sorry, it's my fault, I have not run "rbenv rehash" when I upgrade ruby.
