### ISSUE TITLE
Rails enabled true and IndentationConsistency

### ISSUE THREAD

**Issue by johndel** [bbatsov/rubocop#3440]
I am using rubocop in a rails 5 project, I've enabled rails rubocop with the following syntax:
```
Rails:
  Enabled: true
```
but I still need to enforce `IndentationConsistency` to rails with the following syntax: 
```
Style/IndentationConsistency:
  EnforcedStyle: rails
```

If I remove the `Style/IndentationConsistency` reference, I am getting offenses regarding the private indentation on the project above. Is this something that is expected?

The complete rubocop.yml I've used is here: 
https://github.com/johndel/rails5-api-test/blob/master/.rubocop.yml#L1-L4

```
$ rubocop -V
0.42.0 (using Parser 2.3.1.2, running on ruby 2.3.1 x86_64-darwin14)
```

**Comment by bbatsov** [comment]
> If I remove the Style/IndentationConsistency reference, I am getting offenses regarding the private indentation on the project above. Is this something that is expected?

Is `rails5-api-test` the project above?

**Comment by johndel** [comment]
Yes this one happens on this rails project as well. Steps to reproduce:
Type `rubocop` with the current `rubocop.yml` it won't throw any related offense.
Removing the lines:
```
Style/IndentationConsistency:
  EnforcedStyle: rails
```
from the `rubocop.yml` config and running `rubocop` again, it will throw these offenses:
```
app/controllers/v1/users_controller.rb:37:7: C: Inconsistent indentation detected.
      def set_user ...
      ^^^^^^^^^^^^
app/controllers/v1/users_controller.rb:41:7: C: Inconsistent indentation detected.
      def user_params ...
      ^^^^^^^^^^^^^^^
db/migrate/20160807082302_create_versions.rb:48:5: C: Inconsistent indentation detected.
    def item_type_options ...
    ^^^^^^^^^^^^^^^^^^^^^
db/migrate/20160807082302_create_versions.rb:54:5: C: Inconsistent indentation detected.
    def mysql? ...
    ^^^^^^^^^^
db/migrate/20160807082302_create_versions.rb:73:5: C: Inconsistent indentation detected.
    def versions_table_options ...
    ^^^^^^^^^^^^^^^^^^^^^^^^^^
```
My question is if this one should work without the need of the above lines, only with the following (which appears on the current `rubocop.yml`):
```
Rails:
  Enabled: true
```

**Comment by bbatsov** [comment]
> If I remove the Style/IndentationConsistency reference, I am getting offenses regarding the private indentation on the project above. Is this something that is expected?

Yep, that's expected. Not everyone is using this style in Rails projects. It's just the style used the Rails codebase itself.
