### ISSUE TITLE
Commented-out calls to debugger

### ISSUE THREAD

**Issue by booch** [bbatsov/rubocop#3443]
I'm really happy that RuboCop catches when I leave in a debugging statement. But it misses those same debugger calls if I comment them out. I think it'd be nice to have the `Lint/Debugger` cop also find instances where I've forgotten to remove commented-out calls to the debugger.

**Comment by bbatsov** [comment]
It would be pretty hard to figure out whether something in a comment is an actual Ruby code or just some text that could be interpreted as Ruby code. Ideally we'd have a cop for commented out code, but some such code might be just an example... All in all - I don't think this is something we can do in a straightforward and reliable manner.

**Comment by booch** [comment]
I was really only suggesting looking for the same exact things that `Lint/Debugger` looks for, but with `/#+\s?/` in front of them.
