### ISSUE TITLE
MultilineMethodCallIndentation false positive?

### ISSUE THREAD

**Issue by jacob-carlborg** [bbatsov/rubocop#3468]
When running RuboCop on a file with the following content:

```ruby
def dependencies
  @dependencies ||= begin
    p 'foo'
    DEFAULT_DEPENDENCIES
      .reject { |e| e }
      .map { |e| e }
  end
end
```

I get the following offenses:

```
Inspecting 1 file
C

Offenses:

foo.rb:5:7: C: Align .reject with begin on line 2.
      .reject { |e| e }
      ^^^^^^^
foo.rb:6:7: C: Align .map with begin on line 2.
      .map { |e| e }
      ^^^^
```

Is that the expected behavior? Following what RuboCop suggests, I would need to write the code like this:

```ruby
def dependencies
  @dependencies ||= begin
    p 'foo'
    DEFAULT_DEPENDENCIES
                    .reject { |e| e }
                    .map { |e| e }
  end
end
```

Formatting the code like that looks very strange to me. Is anyone actually writing code formatted like that?

0.42.0 (using Parser 2.3.1.2, running on ruby 2.1.5 x86_64-darwin15.0)

**Comment by maxjacobson** [comment]
I think this is fixed in #3464 -- want to check and maybe review that fix?

**Comment by maxjacobson** [comment]
Actually I misread, it's unrelated :grimacing:. I think your concern can be fixed by changing the configuration to match your preference.

**Comment by jacob-carlborg** [comment]
I just don't see how my code is related to the examples in the documentation: http://www.rubydoc.info/github/bbatsov/RuboCop/RuboCop/Cop/Style/MultilineMethodCallIndentation

**Comment by maxjacobson** [comment]
I see what you're saying. Agreed, that looks like a bug in the output of the message. FWIW, the following config produces no offenses and I believe is more in line with your preference:

```yaml
MultilineMethodCallIndentation:
  EnforcedStyle: indented
```

**Comment by jacob-carlborg** [comment]
I don't agree, I think changing the style is a workaround. If I remove the begin block, then there are no complains without changing the style.
