### ISSUE TITLE
Erroneous "Useless assignment to variable" when processing model

### ISSUE THREAD

**Issue by alexvkcr** [bbatsov/rubocop#3525]
--------

## Expected behavior

When assigning to a variable in a rails model, it should check its schema to see if "new variables" are declared for the model.

## Actual behavior

I assign a value to a variable in a rails model, and that variable exists in the schema.rb and the method where the value is asigned works in rails console, but when I run rubocop it says "Useless assignment to variable"

## Steps to reproduce the problem

It doen't happen with all the variables of the model, so I don't know how to reproduce it but I am working on a GitHub private repository, if the team is interested in cheking the problem out, I would give temporal access!

Just to give a brief explanation of what's going on, I have a method `code_assignmet=` which checks if you are an admin and allows you to modify the code of a game. But i have the same method callled "lang=" to change the lang of the game and after checking if you are an admin, when I call `code_lang = new_code_lang`, rubocop raises the error!

## RuboCop version

rubocop -V
0.42.0 (using Parser 2.3.1.2, running on ruby 2.2.5 x86_64-linux)

**Comment by tejasbubane** [comment]
If I understand you correctly, you want to assign value to a model attribute. You need to use `self.attribute_name = ` instead of `attribute_name = `, both of which are different.

**Comment by alfie-max** [comment]
@tejasbubane if i may ask, different how?

**Comment by tejasbubane** [comment]
> @tejasbubane if i may ask, different how?

@alfie-max `attribute_name =` is a local variable not an attribute. See difference in this gist: https://gist.github.com/tejasbubane/6d944b3c2ada75aa6da8c774a9e5bbc7#file-activerecord_assignment_diff-rb-L49-L64

**Comment by mikegee** [comment]
This IRB session might also help clarify the issue:

```
>> def attribute_name=(value)
>>   puts "method attribute_name=() was called."
>> end

>> self.attribute_name = "this is a method call"
method attribute_name=() was called.
=> "this is a method call"

>> defined?(attribute_name)
=> nil

>> attribute_name = "this is local variable assignment"
=> "this is local variable assignment"

>> defined?(attribute_name)
=> "local-variable"
```
