### ISSUE TITLE
Style/MutableContent array

### ISSUE THREAD

**Issue by cdenneen** [bbatsov/rubocop#3531]
rubocop 0.43.0

```ruby
  IGNORE_LIST = [
    '.bundle',
    '.git',
  ]
```

```
Offenses:

file.rb:17:17: C: Style/MutableConstant: Freeze mutable objects assigned to constants.
  IGNORE_LIST = [ ...
```

**Comment by bbatsov** [comment]
What about this? The warning seems correct to me.

**Comment by RobertAudi** [comment]
@bbatsov the warning is only correct for one dimensional arrays. Here is an example (taken from [here](http://www.java2s.com/Code/Ruby/Array/Freezeanarray.htm):

```Ruby
sequences = [[1,2,3], [1,2,4], [1,4,9]].freeze
sequences << [2,3,5]
# TypeError: can't modify frozen array
sequences[2] << 16                               # => [1, 4, 9, 16]
```

While the warning might be relevant to some extend, it still is futile in a lot of cases.

**Comment by bquorning** [comment]
Same problem for hash values:
```rb
LOCALES = { "da" => "Danish" }.freeze
#=> {"da"=>"Danish"}
LOCALES["da"] << " troll"
#=> "Danish troll"
```

**Comment by bbatsov** [comment]
I'm aware of this - ideally we'd be doing the checks recursively, but I didn't have time to do this. Patches welcome! :-)

**Comment by bquorning** [comment]
I opened #3593 which I hope you’ll mark as a bug. :-)
