### ISSUE TITLE
Ignore `rubocop:disable` comments at the end of long lines

### ISSUE THREAD

**Issue by twe4ked** [bbatsov/rubocop#3542]
For example, given we have a max line length of 80:

``` ruby
#                                                                            vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
def method_definition_that_is_just_under_the_line_length_limit(foo, bar, baz) # rubocop:disable Metrics/AbcSize
  # The method body is too complicated and fails the ABC complexity cop
end
```

The `rubocop:disable` comment pushes the line length over the limit. I'd like an option to ignore counting the disable comment in the length of the line.

This could also be solved with an ignore pattern as described here: https://github.com/bbatsov/rubocop/issues/3479.

Thanks :)

**Comment by smlparry** [comment]
:wave:
