### ISSUE TITLE
Enter our low hanging fruit into Hacktoberfest

### ISSUE THREAD

**Issue by Drenmi** [bbatsov/rubocop#3543]
DigitalOcean are running [Hacktoberfest](https://hacktoberfest.digitalocean.com/#featured-projects-Ruby) throughout the month of October.

This could be a nice way to attract some new contributors to RuboCop. I suggest we add the `hacktoberfest` ~~tag~~ label to some of our simpler issues. 😀 

WDYT? @bbatsov, @jonas054?

**Comment by bbatsov** [comment]
Fine by me. By tag you mean label, right?

**Comment by jonas054** [comment]
Good idea. I've created the label.

**Comment by jonas054** [comment]
And a first candidate, #3103. View list [here](https://github.com/bbatsov/rubocop/issues?q=is%3Aopen+is%3Aissue+label%3Ahacktoberfest).

**Comment by Drenmi** [comment]
> By tag you mean label, right?

Yes. Brain fart. 😁 

> I've created the label.

Awesome! 😄
