### ISSUE TITLE
Guard clauses on multi-line statements

### ISSUE THREAD

**Issue by booch** [bbatsov/rubocop#3570]
In doing a code review, I came across something like the following:

~~~ ruby
      foo[:bar] = {
        # Several more lines
      } unless baz.nil?
~~~

I was rather surprised that RuboCop didn't flag that. Guard clauses are great, but if the guard clause is so far away from the beginning of the statement, it gets too confusing. This seems like a cop worth adding. (And I suppose there should be a corresponding change to the Ruby style guide.)

**Comment by bbatsov** [comment]
Agreed.

**Comment by palkan** [comment]
> if the guard clause is so far away from the beginning of the statement

How many lines are "so far away"? I think, >1. Or should it be configurable?

**Comment by Drenmi** [comment]
> How many lines are "so far away"? I think, >1. Or should it be configurable?

+1 for "more than one." I think multiline is the most unambiguous and least arbitrary condition.

**Comment by tessi** [comment]
I'm 👍 for that change and startet with proposing that advise to the styleguide. As I'm new to rubocop, I am not sure yet how to implement this best in rubocop. We'll see if I can manage to follow up with a PR.

**Comment by tessi** [comment]
There is a PR now (#3636). I'd be happy for some reviews :)
