### ISSUE TITLE
Cop for raise arguments doesn't account for a splat operator

### ISSUE THREAD

**Issue by mattdowdell** [bbatsov/rubocop#3577]
*Related to #552.*

The following example causes an offense:
```ruby
class MyException < StandardError
  def initialize(message, other_arg)
    super "#{message.inspect} -- #{other_arg.inspect}"
  end
end

args = ['message', 'other argument']

begin
  raise MyException.new(*args)
rescue MyException => exc
  puts exc.message
end
```

The offense here being  "Provide an exception class and message as arguments to raise."

I think the example is relatively self explanatory in what it's trying to achieve, but let me know if there's any questions.

## Expected behavior
Rubocop should either not have a problem with use of the splat operator in this case, or detect if the array has more than one argument before raising the offense.

## RuboCop version
```
$ rubocop -V
0.43.0 (using Parser 2.3.1.4, running on ruby 2.3.0 x86_64-linux)
```

**Comment by jonas054** [comment]
> Rubocop should either not have a problem with use of the splat operator in this case, or detect if the array has more than one argument before raising the offense.

Yes. I think we should contend ourselves with not reporting when the splat operator is used, like in `raise MyException.new(*args)`. Determining the size of the array is just too hard, generally speaking.
