### ISSUE TITLE
Style/VariableNumber breaks when variables are in snake_case

### ISSUE THREAD

**Issue by guyisra** [bbatsov/rubocop#3599]
using style normalcase for Style/VariableNumber seems to break when the variable uses underscore for the words such as:

```
my_variable_1 = true # works for snake_case
my_variable_1 = false # doesn't work for normalcase
my_variable1 = false # doesn't work for normalcase
```
so while the cop is for the variable number, it seems to care on the rest of the variable, which I don't think should be on that cop.

**Comment by bbatsov** [comment]
What RuboCop version are you using?

**Comment by guyisra** [comment]
@bbatsov 0.43

**Comment by bbatsov** [comment]
Try 0.44.1.

**Comment by guyisra** [comment]
cool, didn't see there was a 0.44
