### ISSUE TITLE
Pry not defined as a dependency

### ISSUE THREAD

**Issue by b4ldr** [bbatsov/rubocop#3609]
## Expected behavior

I expected pry to be installed as a dependency of rubocop

## Actual behavior

pry is not installed

## Steps to reproduce the problem

in the last release you added a require for pry

https://github.com/bbatsov/rubocop/compare/v0.43.0...v0.44.0#diff-88d81d6507579a295b8fa0f3043df7d2R3
however you have not added it as a dependency in the gem spec.  

here is a travis job failing
https://travis-ci.org/icann-dns/puppet-ditl/jobs/167377966

adding `gem "pry"` to the Gemfile fixes the problem

https://travis-ci.org/icann-dns/puppet-ditl/jobs/167393274

**Comment by savef** [comment]
This was fixed in the `v0.44.1` hotfix release.

**Comment by b4ldr** [comment]
thanks
