### ISSUE TITLE
Add a cop checking for empty when expressions

### ISSUE THREAD

**Issue by bbatsov** [bbatsov/rubocop#3646]
Code like this is valid, but slightly confusing:

```
case x
when y then 1
when z # do nothing
else
    3
end
```

Probably it'd be better to encourage people to use an explicit `nil` as a return value. And we definitely need a cop checking for `nil` returns, as those are evil (but that's another matter).

**Comment by Drenmi** [comment]
> And we definitely need a cop checking for nil returns, as those are evil [...]

Yay! Someone [agrees with me](https://www.youtube.com/watch?v=_KuTdD-MO70). 😁
