### ISSUE TITLE
Ignore .rubocop.yml and force default config

### ISSUE THREAD

**Issue by jawshooah** [bbatsov/rubocop#3647]
Is there a way to force the default config, even if there is a `.rubocop.yml` file in the current directory or further up the tree? Currently it seems the only way is to pass a placeholder to `--config`, e.g. `--config /dev/null`.

Refs https://github.com/Homebrew/brew/pull/1317#issuecomment-254530408

**Comment by mikegee** [comment]
If `--config /dev/null` works as you need, that seems like a fairly good solution. It is relatively clear about your intention to use no configuration.

**Comment by jawshooah** [comment]
@mikegee Yes, it works, but it's certainly not obvious, and since it isn't documented anywhere it basically relies on an implementation detail.

**Comment by bbatsov** [comment]
I'm fine with adding an explicit switch for this behaviour.
