### ISSUE TITLE
Infinite loop detected in this code snippet

### ISSUE THREAD

**Issue by terryyin** [bbatsov/rubocop#3690]
```ruby
def x
  a b {
    %(
-
    )
  }
end
```

**Comment by tejasbubane** [comment]
I cannot reproduce this on rubocop `0.45.0`, rather got this offense:

```
Offenses:

rubocop_bug_test.rb:3:8: C: Style/SpaceInsideBlockBraces: Space missing inside {.
  a b { ...


1 file inspected, 1 offense detected
```

**Comment by rrosenblum** [comment]
@tejasbubane I was able to reproduce on RuboCop `0.45.0` running `rubocop -a`. The offense is registered when `rubocop` is run on the file. The infinite loop comes from the auto-correction.

**Comment by rrosenblum** [comment]
I was able to narrow this down to a single cop. Running `rubocop -a --only Style/SpaceInsideBlockBraces` will produce the infinite loop. I wasn't able to do much more digging than this yet. It looks like there might be some auto-correct tests missing from that cop.

**Comment by terryyin** [comment]
Thanks!
