### ISSUE TITLE
Style/VariableNumber reasoning

### ISSUE THREAD

**Issue by novikserg** [bbatsov/rubocop#3711]
`Rubocop` uses [`Style/VariableNumber`](https://github.com/bbatsov/rubocop/blob/2375b15a55d0d732c2e5b4ae076c40c7cdf9a3f5/spec/rubocop/cop/style/variable_number_spec.rb#L5) cop, which, by default, doesn't allow `invoice_1` and prefers `invoice1`.   
However, this is not covered in [style guide] (https://github.com/bbatsov/ruby-style-guide), and I am really curious what's the reasoning behind it (i.e. why is `invoice1` better than `invoice_1`)?

--------
## RuboCop version
```
0.45.0
```

**Comment by Drenmi** [comment]
I don't think anyone dares argue that one is better than the other, but I could be wrong. 😀  (The better style would be to not have numbered variables at all.)

Many cops are not in the Style Guide (i.e. they don't have a strong convention, at least yet), but they're added to RuboCop anyway, to let developers enforce consistency in their projects.

In the end, we can only have one default configuration, and sometimes that must be picked arbitrarily. 😀

**Comment by bbatsov** [comment]
I completely agree with what @Drenmi said. The cop is configurable, the default is just a default.
