### ISSUE TITLE
Cop Suggestion: Duplicate "enum" explicit value in Rails

### ISSUE THREAD

**Issue by olliebennett** [bbatsov/rubocop#3723]
An [enum in Rails](http://edgeapi.rubyonrails.org/classes/ActiveRecord/Enum.html) can be defined either as an array or a hash with specific integer keys defined.

```ruby
# array syntax
enum status: [ :active, :archived ]

# hash syntax
enum status: { active: 0, archived: 1 }
```

With the latter syntax, it's possible to accidentally specify duplicate keys:

```ruby
enum status: { active: 4, archived: 4 }
```

Bugs resulting from this can be hard to identify, and I cannot see a valid use-case for defining duplicate keys in this way.

Is this a reasonable candidate for inclusion as a Rails-specific cop in RuboCop?

Note: Enums are available [since Rails 4.1.0](http://weblog.rubyonrails.org/2014/4/8/Rails-4-1/).

**Comment by Drenmi** [comment]
Makes perfect sense. It would probably also be useful to have another cop that enforces either array- or hash values for enums. 😀

**Comment by bbatsov** [comment]
I'm fine with the addition of such a cop as well.
