### ISSUE TITLE
Bundler/OrderedGems autocorrection doesn't move inline comments

### ISSUE THREAD

**Issue by swrobel** [bbatsov/rubocop#3776]
## Expected behavior

When the Bundler/OrderedGems moves gems between lines of a Gemfile, their inline comments should move with them

## Actual behavior

The gem declaration moves, but the comments stay on the same line, which means that comments no longer match up with the lines they were intended for.

## Steps to reproduce the problem

Create a simple `Gemfile`

```ruby
gem 'rubocop', github: 'bbatsov/rubocop' # The good stuff
gem 'bundler'
```

Run rubocop

```
$ rubocop -a Gemfile
Inspecting 1 file
C

Offenses:

Gemfile:2:1: C: [Corrected] Gem bundler should appear before rubocop in their gem group.
gem 'bundler'
^^^^^^^^^^^^^

1 file inspected, 1 offense detected, 1 offense corrected
```

Note the new `Gemfile`

```ruby
gem 'bundler' # The good stuff
gem 'rubocop', github: 'bbatsov/rubocop'
```

## RuboCop version

```
$ rubocop -V
0.46.0 (using Parser 2.3.3.1, running on ruby 2.3.3 x86_64-darwin16)
```

**Comment by swrobel** [comment]
cc @pocke

**Comment by pocke** [comment]
Hi, thanks for your feedback.

I'll fix this problem.
