### ISSUE TITLE
OK to do case-insensitive checks on the OrderedGems cop?

### ISSUE THREAD

**Issue by breckenedge** [bbatsov/rubocop#3802]
I love the new OrderedGems cop, it's a fantastic idea!

However, the OrderedGems cop uses the `<` sign to perform its comparison, and I have one pesky dependency that starts with a capital letter (the wonderful-yet-inconsistently-named [StreetAddress](https://github.com/derrek/street-address) gem). Since `'a' < 'Z' #=> false`, it wants to sort this dependency at the top of my Gemfile. Would it be acceptable to write a PR that performs a case-insensitive comparison?

--------

## Expected behavior

The OrderedGems cop doesn't consider case when checking the Gemfile.

## Actual behavior

The OrderedGems cop considers case when checking the Gemfile.

## Steps to reproduce the problem

```ruby
# in Gemfile
source 'https://rubygems.org'
gem 'sinatra'
gem 'StreetAddress'
```

```sh
rubocop
Inspecting 1 file
C

Offenses:

Gemfile:4:1: C: Gem StreetAddress should appear before sinatra in their gem group.
gem 'StreetAddress'
^^^^^^^^^^^^^^^^^^^

1 file inspected, 1 offense detected
```

## RuboCop version

```
$ rubocop -V
0.46.0 (using Parser 2.3.3.1, running on ruby 2.3.1 x86_64-darwin16)
```

**Comment by bbatsov** [comment]
Make sense to me. Although I'd also suggest to the gem author to rename this, so it would match common conventions.
