### ISSUE TITLE
Add Linter for Method Level Documentation

### ISSUE THREAD

**Issue by PascalTurbo** [bbatsov/rubocop#3805]
At the moment there seems to be only a linter for Class / Module Level Documentation.
Would it be suitable to add a Linter that checks if Method Level Documentation is missing.

**Comment by backus** [comment]
You can enable [`Style/DocumentationMethod`](https://github.com/bbatsov/rubocop/blob/master/lib/rubocop/cop/style/documentation_method.rb) for public methods. If you want more than that I'd recommend looking to [yardstick](http://github.com/dkubb/yardstick) or [inch](https://github.com/rrrene/inch)

**Comment by bbatsov** [comment]
Indeed. I guess we can close this ticket now.
