### ISSUE TITLE
Style/NumericPredicate should be a bit smarter 

### ISSUE THREAD

**Issue by lloeki** [bbatsov/rubocop#3812]
## Expected behavior

`whatevs.select { |id| id % 100 == 0 }` should be accepted in spite of `Style/NumericPredicate` not being `comparison` because writing `whatevs.select { |id| (id % 100).zero? }` is ludicrous. IOW, `Style/NumericPredicate` should apply only to chained method calls, not numeric operations.

## Actual behavior

`whatevs.to_a.select { |id| id % 100 == 0 }` is a violation.

## Steps to reproduce the problem

Obvious.

## RuboCop version

```
> rubocop -V
0.46.0 (using Parser 2.3.3.1, running on ruby 2.2.5 x86_64-darwin16)
```

**Comment by bbatsov** [comment]
> whatevs.select { |id| id % 100 == 0 } should be accepted in spite of Style/NumericPredicate not being comparison because writing whatevs.select { |id| (id % 100).zero? } is ludicrous. IOW, Style/NumericPredicate should apply only to chained method calls, not numeric operations.

I don't see anything ludicrous here. This is extremely subjective and I'd rather us not complicate the code further.

**Comment by lloeki** [comment]
Well "ludicrous" is admittedly a bit strong a term but I feel some impedance mismatch having to wrap math into parentheses to call a method.

Your argument is sound though, and well received.
