### ISSUE TITLE
CopStore assumes that all cop departments have one capital letter

### ISSUE THREAD

**Issue by backus** [bbatsov/rubocop#3838]
I noticed this while working on #3887 and figured I would open an issue even though I'm working on a fix. The `CopStore` assumes that you can downcase all cop namespaces and then capitalize them to get the original namespace. See https://github.com/bbatsov/rubocop/blob/ffe9743b1d8c4b37f04041022ec6fb388c04e531/lib/rubocop/cop/cop.rb#L29.

This works for all of rubocop's department but not for rubocop-rspec:

| Original Department   | Downcased     | Capitalized   |
|:---------------------|:--------------|:--------------|
| `Bundler`            | `bundler`     | `Bundler`     |
| `Lint`               | `lint`        | `Lint`        |
| `Metrics`            | `metrics`     | `Metrics`     |
| `Performance`        | `performance` | `Performance` |
| `Style`              | `style`       | `Style`       |
| `Rails`              | `rails`       | `Rails`       |
| `Security`           | `security`    | `Security`    |
| `RSpec`              | `rspec`       | `Rspec`       |

As a result, writing `rubocop:disable IndentArray` works but `rubocop:disable AnyInstance` (rubocop-rspec cop) does not.

Expected behavior would be to properly inflect `:rspec` back to `:RSpec`.

**Comment by Drenmi** [comment]
This is almost a bit scary. I was thinking about this just last night, because the Style Guide has a recommendation to keep initialisms uppercase, i.e. `XMLParser`, rather than `XmlParser`, but this breaks inference between constant- and file names.

**Comment by backus** [comment]
It isn't *that* bad since it is just the namespaces. I do think that it might be worth just having a cop name abstraction though:

```ruby
$ ag 'cop.+capitalize' --ruby lib
lib/rubocop/config.rb
145:      department = cop.cop_type.to_s.capitalize!

lib/rubocop/cop/cop.rb
124:          given_names.include?(cop_type.to_s.capitalize)

lib/rubocop/options.rb
182:      namespaces = Cop::Cop.all.types.map { |t| t.to_s.capitalize }

**Comment by bbatsov** [comment]
Yeah, we have to fix this. Probably we can simply create some mapping between the lowercase symbols and the original namespaces. This would be easy and clean.
