### ISSUE TITLE
Have the NodePattern compiler handle hyphens more elegantly

### ISSUE THREAD

**Issue by Drenmi** [bbatsov/rubocop#3846]
Parser's AST has a number of node types with hyphens in them, e.g. `op-asgn` and `block-pass`, but specifying these in a `node_matcher` will result in an exception:

```
RuboCop::NodePattern::Invalid:
  Couldn't compile due to invalid token "-". Pattern: (block-pass)
```

This is because the scanner (essentially a collection of regular expressions) will scan `block-pass` into three tokens: `block`, `-`, and `pass`.

Currently, you can match these in a `node_matcher` by manually replacing the hyphen with an underscore. This isn't immediately apparent however, and you can only find it out through trial and error, as there are no test cases highlighting this.

### The ideal solution:

Ideally, the `node_matcher` input should match the Parser AST directly. This would require some fiddling with the scanner expressions, to have it replace hyphens in node type declarations with underscores automatically.

### A possible improvement:

As a crutch, we could (at the least) add some test cases for the compiler spec, that highlights the current behaviour, and possibly improve the error message for this particular case. 

--------

## Expected behavior

RuboCop's node pattern compiler recognizes Parser node types with hyphens.

## Actual behavior

An exception is raised.

## Steps to reproduce the problem

Use the node pattern compiler to try and compile:

```
(block-pass)
```

## RuboCop version

Include the output of `rubocop -V`. Here's an example:

```
$ rubocop -V
0.46.0 (using Parser 2.3.3.1, running on ruby 2.4.0 x86_64-darwin16)
```

**Comment by bbatsov** [comment]
Yeah, we'll definitely have to fix this.

/cc @alexdowad
