### ISSUE TITLE
Generated documentation alternating between two states

### ISSUE THREAD

**Issue by backus** [bbatsov/rubocop#3851]
I've been scratching my head as to why certain parts of the documentation seem to change on unrelated PRs still and I think I figured it out. I don't have time to fix it right now so I'm opening an issue.

`rake generate_cops_documentation` has been specifically alternating between two states for `manual/cops_rails.md`. To see for yourself run `git --no-pager log -S ConvertTry -- manual/cops_rails.md`. Here are the commits that turns up:

- a9c598c
- 1838089
- 36fe656
- 0f514d0
- 96a53db
- bb9ac67
- f7e00f2
- 476297d
- d516771

The task seems to be swapping the documentation for `Style/SafeNavigation` and `Rails/SafeNavigation`! I don't know where in the code this is happening, but it seems like something in `tasks/cops_documentation.rake` is not properly grouping YARD docs by the corresponding cop and as a result we are getting nondeterministic manual builds. Fixing this should finally make building the rubocop manual deterministic :smile:

**Comment by bbatsov** [comment]
Yeah, I've recently noticed this myself. It's extremely annoying.

**Comment by backus** [comment]
Yeah. Personally I think this code should be significantly refactored since right now it isn't tested at all and its just a bag of methods inside a rake task

**Comment by backus** [comment]
Ah looking a bit closer, this is the problem code https://github.com/bbatsov/rubocop/blob/767b546285eb7f818a8c44e2ce1d5f0b220bf6d7/tasks/cops_documentation.rake#L99

**Comment by backus** [comment]
I lied, I was able to find time :smile:. I think #3852 fixes the problem
