### ISSUE TITLE
Style/SignalException enabled: false is not disabling as expected

### ISSUE THREAD

**Issue by pitosalas** [bbatsov/rubocop#3856]
It seems to me that adding:

```
Style/SignalException:
  Enabled: false
```
to my .rubocop.yml is not disabling the error message.

Thanks for a great product!

Pito Salas

/V/M/m/cosi166b-s2017 (master=) rubocop -v
0.46.0

![screen shot 2017-01-03 at 4 31 03 pm](https://cloud.githubusercontent.com/assets/44681/21623769/0cc0bfbe-d1d2-11e6-9413-b0c672c73f48.png)

**Comment by bbatsov** [comment]
Perhaps the editor you're using is executing RuboCop outside the project folder or something? That's the only reason something like this won't work. You can check by running RuboCop directly using the command-line tool in the project folder.

P.S. This cop is configurable - you can make it enforce either `fail` everything or semantic exceptions (`fail` for top-level exceptions, `raise` to raise a different exception from an exception handler).

**Comment by bbatsov** [comment]
Closing this due to lack of information.
