### ISSUE TITLE
Figure out why our tests run so slow on Ruby 2.4.0

### ISSUE THREAD

**Issue by Drenmi** [bbatsov/rubocop#3877]
I noticed this when switching over to 2.4.0 and trying to work on RuboCop. Boot up time of the test suite is extremely long, and the entire test run takes almost twice as long as on 2.3.3. At first I thought it was something with my local installation, but the problem persists on Travis as well. 😅 

<img width="925" alt="screen shot 2017-01-05 at 22 32 38" src="https://cloud.githubusercontent.com/assets/5259935/21741650/1fed8df8-d518-11e6-8960-2d49f193d295.png">

I checked with [rspec-core](https://github.com/rspec/rspec-core/issues/2365), but it seems like the issue is with our test suite in particular.

For now I'm using 2.3.3 to develop, to avoid going insane. 😅 

--------

## Expected behavior

Tests run in approximately the same time as on Ruby 2.3.3.

## Actual behavior

Tests run in twice the amount of time.

## Steps to reproduce the problem

Switch to 2.4.0 (that's `rvm use 2.4.0` or `rbenv global 2.4.0`) and run the tests.

## RuboCop version

```
$ rubocop -V
0.46.0 (using Parser 2.3.3.1, running on ruby 2.4.0 x86_64-darwin15)
```

**Comment by pocke** [comment]
Ruby 2.4
--------

https://travis-ci.org/bbatsov/rubocop/jobs/189770391

`rake` command  took 620.98 seconds.
![1483793937](https://cloud.githubusercontent.com/assets/4361134/21741795/8659571e-d524-11e6-81c5-a3e4db296dc2.png)

Ruby 2.3.3
----

 https://travis-ci.org/bbatsov/rubocop/jobs/189770390

`rake` command  took 346.03 seconds.
![1483793976](https://cloud.githubusercontent.com/assets/4361134/21741803/9c24b426-d524-11e6-8f7e-f87188cff66e.png)

In ruby 2.4, `rake` is slow... 🤔

**Comment by pocke** [comment]
I created docker images to test the problem in local machine.

```dockerfile
FROM ruby:2.3.3

RUN git clone --depth 1 https://github.com/bbatsov/rubocop \
  && cd rubocop \
  && bundle install \
  && bundle exec rake install \
  && rubocop -V
```

```dockerfile
FROM ruby:2.4.0

RUN git clone --depth 1 https://github.com/bbatsov/rubocop \
  && cd rubocop \
  && bundle install \
  && bundle exec rake install \
  && rubocop -V
```

```
# each the dockerfiles
$ docker build -t rubocop:2.4.0 .
$ docker build -t rubocop:2.3.3 .
```


First time, I executed `rubocop` command in rubocop's repository with two MRI version.

```sh
$ pwd # => /home/pocke/ghq/github.com/bbatsov/rubocop

$ time docker run -v $(pwd):/tmp/work -it rubocop:2.4.0 bash -c "cd /tmp/work && rubocop"
54.39s

$ time docker run -v $(pwd):/tmp/work -it rubocop:2.3.3 bash -c "cd /tmp/work && rubocop"
55.45s
```

From this results, I think `rubocop` command doesn't have performance problem.


Second time, I executed `rspec` command in rubocop's repository with two MRI version.

```sh
$ pwd # => /home/pocke/ghq/github.com/bbatsov/rubocop


$ time docker run -v $(pwd):/tmp/work -it rubocop:2.4.0 bash -c "cd /tmp/work && rspec"
628.71s

$ time docker run -v $(pwd):/tmp/work -it rubocop:2.3.3 bash -c "cd /tmp/work && rspec"
31.61s
```

RSpec has a difference of 20 times!


So, I think the problem

**Comment by Drenmi** [comment]
> From this results, I think rubocop command doesn't have performance problem.

Yeah. RuboCop runs 1-2 seconds faster on my machine as well.

**Comment by bbatsov** [comment]
That's quite fascinating. I guess the problem should be in RSpec after all.

**Comment by Drenmi** [comment]
I guess if it gets fixed only in Ruby 2.4.1 only, we'll always have a slow running 2.4.0 build in the matrix on Travis. 😓 

We should at least move 2.4.0 up towards the top in the configuration so that it starts early, much like how we treat JRuby. WDYT?

**Comment by deivid-rodriguez** [comment]
I had a similar problem a while ago and fixed it by manually patching the problematic ruby. In this case, the problem was a SEGV, not sure if a slow build is worth doing that but I thought I would mention it. This is what I did: https://github.com/deivid-rodriguez/byebug/commit/b58e56b96a030f126543dd85654e7b8589e4a724

**Comment by deivid-rodriguez** [comment]
Actually, patching ruby probably takes longer than the slow build, so... forget about it! :smiley:

**Comment by backus** [comment]
Ruby 2.4.1 is out and it will probably close this issue FYI.
