### ISSUE TITLE
How to handle ActiveSupport's starts_with? and ends_with? in Performance/DoubleStartEndWith

### ISSUE THREAD

**Issue by rrosenblum** [bbatsov/rubocop#3893]
I recently discovered that [`ActiveSupport` adds in `starts_with?` and `ends_with?` as aliases to `start_with?` and `end_with?`](http://edgeguides.rubyonrails.org/active_support_core_extensions.html#starts-with-questionmark-and-ends-with-questionmark). I would like to add support for these methods, but I am not sure what the best way to accomplish this is.

One idea is to add a configuration to `Performance/DoubleStartEndWith` to enable checks for `starts_with?` and `ends_with?`.

Another idea is to add a Rails specific cop to handle this check separately from the Performance cop.

What is the preferred way to implement this check?

## RuboCop version

Any version that includes `Performance/DoubleStartEndWith`

**Comment by bbatsov** [comment]
I'd go with configuration.

On a related note - it would be nice to have a Rails cop checking for usages of the aliases added by `ActiveSupport` - some people like to use only them, some people like to use only the names in the core library.

**Comment by rrosenblum** [comment]
> I'd go with configuration.

Thank you. I was leaning towards using a configuration. I figured I would ask before I started implementing this to avoid having to potentially code it twice.

> it would be nice to have a Rails cop checking for usages of the aliases

Agreed, this could be a useful cop. It would be really nice if we could come up with a generic solution that could swap out any method with some other method that are defined in configuration. I am not sure how possible a generic solution is because of different method signatures and needed to check for a method called on nothing vs on a variable.

**Comment by bbatsov** [comment]
> Agreed, this could be a useful cop. It would be really nice if we could come up with a generic solution that could swap out any method with some other method that are defined in configuration. I am not sure how possible a generic solution is because of different method signatures and needed to check for a method called on nothing vs on a variable.

Guess it will just need more extensive configuration - not just method names.
