### ISSUE TITLE
alerting on rails rest methods

### ISSUE THREAD

**Issue by chrishough** [bbatsov/rubocop#3895]
Curious about this SO post: http://stackoverflow.com/questions/41604826/why-is-rubocop-alerting-on-rails-5-rest-methods 

Does rubocop `0.46.0` alert on controller methods that do not have specs? This seems odd.
![screen shot 2017-01-11 at 8 06 21 pm](https://cloud.githubusercontent.com/assets/744056/21876634/7294f036-d839-11e6-97ed-47d88635844f.png)

**Comment by backus** [comment]
@chrishough that isn't a rubocop error. Looks like it is a rails best practices error: https://github.com/railsbp/rails_best_practices/blob/71dd596500782fd76d5a4a2b2cf2fcc705a3d9a2/lib/rails_best_practices/reviews/remove_unused_methods_in_helpers_review.rb#L29

**Comment by chrishough** [comment]
Thank you for connecting me to the other project.  Curious though.  Since this is a dependency here do rubocop users have issues with this too?

**Comment by mikegee** [comment]
> Since this is a dependency here 

What is "this" and "here"?

Rubocop doesn't depend on rails_best_practices, if that's what you mean.

**Comment by chrishough** [comment]
Correct, but users will use this inside of rails projects.  That is what I was referring to 👍
