### ISSUE TITLE
Bundler cop idea: recommend eval_gemfile

### ISSUE THREAD

**Issue by backus** [bbatsov/rubocop#3903]
To make it easy for developers to locally work with additional dependencies without having to wrestle with source control (adding it locally and then avoiding committing it) a pretty common pattern is to do this:

```ruby
eval(File.read('Gemfile.local')) if File.exist?('Gemfile.local')
```

I believe this is why Bundler added [`eval_gemfile`](http://www.rubydoc.info/github/bundler/bundler/Bundler%2FDsl%3Aeval_gemfile) to their DSL. 

It seems like this is public API for it to be in the bundler DSL so it probably makes sense to encourage it. Helps people avoid having to write `# rubocop:disable Security/Eval` too :smile:

**Comment by backus** [comment]
BTW here is the evidence that this is a pretty common pattern people follow. https://github.com/search?utf8=%E2%9C%93&q=eval+File.read+Gemfile&type=Code&ref=searchresults

**Comment by bbatsov** [comment]
Sounds good to me.

**Comment by segiddins** [comment]
Please note that `eval_gemfile` is still (purposefully) undocumented, and while we strive to support it, we do not fully consider it public API at this point

**Comment by backus** [comment]
Oh ok interesting. Thanks @segiddins
