### ISSUE TITLE
Add `expect_violation` from rubocop-rspec

### ISSUE THREAD

**Issue by backus** [bbatsov/rubocop#3905]
A while back I implemented a helper for rubocop-rspec that builds on top of `inspect_source`. I think it makes cops really easy to test, it makes the specs very clear even to someone who is new to the codebase, and it actually generates much more strict test cases. Here is an example from the rubocop-rspec tests:

```ruby
it 'detects :each for hooks' do
  expect_violation(<<-RUBY)
    before(:each) { true }
    ^^^^^^^^^^^^^ Omit the default `:each` argument for RSpec hooks.
    after(:each)  { true }
    ^^^^^^^^^^^^ Omit the default `:each` argument for RSpec hooks.
    around(:each) { true }
    ^^^^^^^^^^^^^ Omit the default `:each` argument for RSpec hooks.
  RUBY
end
```

An equivalently thorough test with `inspect_source` would look like this:

```ruby
it 'detects :each for hooks' do
  inspect_source(cop, ['before(:each) { true }',
                       'after(:each)  { true }',
                       'around(:each) { true }'])

  expect(cop.messages)
    .to all(eq('Omit the default `:each` argument for RSpec hooks.'))
  expect(cop.offenses.map(&:line)).to eq([1, 2, 3])
  expect(cop.highlights).to eq([
                                 'before(:example)',
                                 'after(:example)',
                                 'around(:example)'
                               ])
end
```

In practice I think people end up only writing something like the `inspect_source` followed by an assertion that three offenses were detected.

I think writing the tests like this is a big win. Let me know if you'd like me to upstream this spec support.

**Comment by Drenmi** [comment]
Definitely like how this looks. 😀 The test suite sure could use some work. 

We have a lot of alignment cops and whatnot, checking leading space. Do you figure they will work properly with the HEREDOC?

**Comment by bbatsov** [comment]
That's quite interesting indeed! Quite compact!

Apart from what @Drenmi mentioned:

- violations -> offenses
- it took me a moment to understand the format of the heredoc - I wonder if there isn't something we can do to make it even easier to comprehend
- what happens when you're dealing with long code highlights and long messages? This won't look nearly as pretty...

**Comment by backus** [comment]
> what happens when you're dealing with long code highlights and long messages? This won't look nearly as pretty...

Can't do much about long code highlights (at least off the top of my head). For long messages we could possibly adopt a rule like this

```ruby
let(:message) { 'Omit the default `:each` argument for RSpec hooks.' }

# No message in the annotation. Looks to see if `let(:message) { ... }` is defined

it 'detects :each for hooks' do
  expect_violation(<<-RUBY)
    before(:each) { true }
    ^^^^^^^^^^^^^
    after(:each)  { true }
    ^^^^^^^^^^^^
    around(:each) { true }
    ^^^^^^^^^^^^^
  RUBY
end
```

**Comment by backus** [comment]
The nice thing about building it on top of `inspect_source` is that you don't have to use it in cases where it is too noisy
