### ISSUE TITLE
Rails/EnumUniqueness crashes

### ISSUE THREAD

**Issue by savef** [bbatsov/rubocop#3918]
These seem to be related to what #3751 was fixing.

I am getting an error fetching my keys from a method call like so:
```ruby
enum status: User.statuses.keys
# undefined method `values' for "s(:send,\n  s(:send,\n    s(:const, nil, :User), :statuses), :keys)":RuboCop::AST::Node
```

Additionally, here's another form using a variable that errors:
```ruby
var = %w(one two three)
enum status: var
# undefined method `values' for s(:lvar, :var):RuboCop::AST::Node
```
Whereas `enum status: %w(one two three)` is fine.

----------
## RuboCop version

Include the output of `rubocop -V`. Here's an example:

```
$ rubocop -V
0.47.0 (using Parser 2.3.3.1, running on ruby 2.3.1 x86_64-linux)
```

**Comment by bquorning** [comment]
Fails also if the `state` value is a hash:

```rb
STATES = { foo: 0, bar: 1 }
enum state: STATES
```

**Comment by UksonCode** [comment]
And also if the enums are stored in normal array

> ROLES = [:boss, :employee].freeze
> enum role: ROLES

**Comment by Drenmi** [comment]
I looked into this, and found the reason this cop was so fragile. The node matcher would match any node type passed as a value to the hash, whereas it's only possible for us to inspect (hash- and array) literals.

I've submitted a [fix](https://github.com/bbatsov/rubocop/pull/3920) for this. 😀
