### ISSUE TITLE
Implement a cop enforcing a consistent use of ActiveSupport aliases

### ISSUE THREAD

**Issue by bbatsov** [bbatsov/rubocop#3937]
`ActiveSupport` defines a bunch of core lib method aliases (such as `String#starts_with?` and so on). 
In most Rails projects people end up with a mixed usage of the built-in method names and the ActiveSupport aliases. It'd be nice if we had a cop to enforce using either the AS aliases or the core lib method names consistently.

This cop would be pretty easy to implement and would be a great opportunity for someone to dive into the RuboCop codebase.

**Comment by noraj** [comment]
I opened a discussion for a larger scope of this: https://github.com/rubocop/rubocop/discussions/13082, having aliases cops for more components.
