### ISSUE TITLE
Style/RaiseArgs doesn't handle exception classes with just keyword arguments properly

### ISSUE THREAD

**Issue by wvanbergen** [bbatsov/rubocop#3944]
## Expected behavior

When using an exception class with just keyword arguments, it should not find an offense.
``` ruby
raise MyError.new(keyword: argument, key: word)
```

## Actual behavior

It finds an offense, telling me I should be using `raise MyError, message` instead. This is because the code simply checks if there's only 1 argument, and keyword argument always count as one.

## Steps to reproduce the problem

Run rubocop on the following snippet, with Style/RaiseArgs enabled

``` ruby
raise MyError.new(keyword: argument, key: word)
```
## RuboCop version

Include the output of `rubocop -V`. Here's an example:

```
rubocop -V
0.46.0 (using Parser 2.3.3.1, running on ruby 2.3.3 x86_64-darwin16)
```

**Comment by mikegee** [comment]
I confirmed the reported behavior on master with the default configuration. Additionally, `raise MyError.new(argument, word)` produces no offense.

This seems like an inconsistency that should be allowed.
