### ISSUE TITLE
Separate prefix-unless from postfix-unless - currently both covered by Style/NegatedIf

### ISSUE THREAD

**Issue by david-a-wheeler** [bbatsov/rubocop#3961]
This is an enhancement request.

Currently Style/NegatedIf forbids both "if !condition statement" (prefix position) and "statement if !condition" (postfix position).  But in the style samples, *only* the postfix position is listed as the preferred style; there's no indication that everyone actually prefers "unless condition statement" over "if !condition statement".

I'd like to be able to configure Rubocop to trigger on *postfix* "statement if !condition" position to change to "statement unless condition", but accept "if !condition statement" (I find the latter easier to read).  Specifically, I'd like "Style/NegatedIf" to only cover the postfix position, and have a separate "Style/NegatedIfPrefix" that could be separately controlled.  Rubocop already has to detect both cases, I'd just like finer control over when they trigger.

Thanks so much for rubocop!  We use it continuously.

**Comment by bbatsov** [comment]
This was an oversight in the Ruby style guide, but I understand your reasoning and I'm fine with making this more granular in RuboCop.

**Comment by brandonweiss** [comment]
Yes! I was wondering about this—I too only want to run this on postfix statements. For prefix I think negated if is clearer.

**Comment by david-a-wheeler** [comment]
Hooray!  Thank you so much!
