### ISSUE TITLE
Not ignoring files from .rubocop.yml when specifying a list of files to be inspected

### ISSUE THREAD

**Issue by Dorian** [bbatsov/rubocop#3979]
I'm trying to have a git pre-commit hook that only runs rubocop on changed files and I encountered this bug.

When ignoring `db/schema.rb` in `.rubocop.yml`, running `rubocop db/schema.rb` will still detect offenses on `db/schema.rb`.

--------

## Expected behavior

It doesn't inspect `db/schema.rb` and exits successfully.

## Actual behavior

It inspects `db/schema.rb` and gives me a list of offenses.

## Steps to reproduce the problem

Let's say I have a `.rubocop.yml` with:

```yaml
AllCops:
  Exclude:
    - 'db/schema.rb'
```

And then I execute:

```bash
bundle exec rubocop -c .rubocop.yml db/schema.rb
# or
bundle exec rubocop db/schema.rb
# or
rubocop -c .rubocop.yml db/schema.rb
# or
rubocop db/schema.rb
```

## RuboCop version

```
$ rubocop -V
0.47.1 (using Parser 2.3.3.1, running on ruby 2.3.3 x86_64-darwin16)
# Also tried with
0.45.0 (using Parser 2.3.3.1, running on ruby 2.3.3 x86_64-darwin16)
```

**Comment by mikegee** [comment]
I think you're gonna like this command line argument:

```
        --force-exclusion            Force excluding files specified in the
                                     configuration `Exclude` even if they are
                                     explicitly passed as arguments.
```

**Comment by Dorian** [comment]
@mikegee oops thanks :)

**Comment by Dorian** [comment]
BTW this is the pre-commit hook I ended with for now:

```
#!/usr/bin/env ruby
#
# To add it to your git hooks:
#
#   ln -s ../../bin/pre-commit .git/hooks/pre-commit

changed_files = `git diff --cached --name-only --diff-filter=ACM`.split("\n").join(" ")

puts("bundle exec rubocop --force-exclusion #{changed_files} 2>&1 > /dev/null")
ok = system("bundle exec rubocop --force-exclusion #{changed_files} 2>&1 > /dev/null")

unless ok
  system('bundle exec rubocop -a')
  exit(1)
end
```

**Comment by Dorian** [comment]
@mikegee When there is a `TODO.md` for instance.

To reproduce:

- In an empty directory, create a `TODO.md` file with `- one` as the content
- run `rubocop`: `no offenses`
- run `rubocop TODO.md`: `1 offense`
- run `rubocop --force-exclusion TODO.md`: `1 offense`
- `rubocop -L | grep md`: none

(in my project's `.rubocop.yml`, none of the `Include` or `Exclude` matches `TODO.md`

**Comment by mikegee** [comment]
Hrm. I can see why you are surprised by that behavior but I think it is doing what it says it will do:

> Force excluding files specified in the configuration `Exclude` even if they are explicitly passed as arguments.

and `TODO.md` isn't in any `Exclude`s.

**Comment by Dorian** [comment]
On top of `lib/rubocop/target_finder.rb` it says:

>   # This class finds target files to inspect by scanning the directory tree
>   # and picking ruby files.

And I think that's the default behavior expected, I should not have to put all my non-ruby file paths in the `Exclude` (I don't have to do it for a normal `rubocop` command)

(BTW, I just discovered the `--fail-fast` option, so happy :) ).

I'm trying to see if I can fix it (even if it's just for my fork):

```
    context 'with already excluded by default' do
      let(:target_file) { 'TODO.md' }

      before do
        create_file(target_file, '- one')
      end

      it 'excludes files excluded by default even if they are ' \
         'explicitly passed as arguments' do
        expect(cli.run(['--force-exclusion', target_file])).to eq(0)
      end
    end
```

**Comment by Dorian** [comment]
@mikegee Ok, maybe you are right:

> Generate a list of target files by expanding globbing patterns
> (if any). If args is empty, recursively find all Ruby source
> files under the current directory

But what about a change of behavior or a new option? (`--only-ruby-files`?)

**Comment by Dorian** [comment]
@mikegee Nice code BTW, ok I found how to do it, now I need to do it nicely :)

```
--- a/lib/rubocop/target_finder.rb
+++ b/lib/rubocop/target_finder.rb
@@ -132,7 +132,7 @@ module RuboCop

       files.reject do |file|
         config = @config_store.for(file)
-        config.file_to_exclude?(file)
+        config.file_to_exclude?(file) || !ruby_executable?(file)
       end
     end
   end
```

**Comment by mikegee** [comment]
I dunno. I just try to help triage issues sometimes.

What about tweaking that command in your pre-commit hook?

`git diff --cached --name-only --diff-filter=ACM | grep .rb`

**Comment by Dorian** [comment]
@mikegee Then it would not match bin scripts for instance
