### ISSUE TITLE
Bug in 0.47.1 with Rails/FilePath and **/*

### ISSUE THREAD

**Issue by chrishough** [bbatsov/rubocop#4002]
```
spec/spec_helper.rb:23:1: C: Rails/FilePath: Please use Rails.root.join('path', 'to') instead.
Dir[Rails.root.join('spec', 'concerns', '**/*.rb')].each { |f| require f }
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
spec/spec_helper.rb:23:5: C: Rails/FilePath: Please use Rails.root.join('path', 'to') instead.
Dir[Rails.root.join('spec', 'concerns', '**/*.rb')].each { |f| require f }
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
spec/spec_helper.rb:24:1: C: Rails/FilePath: Please use Rails.root.join('path', 'to') instead.
Dir[Rails.root.join('spec', 'support', '**/*.rb')].each { |f| require f }
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
spec/spec_helper.rb:24:5: C: Rails/FilePath: Please use Rails.root.join('path', 'to') instead.
Dir[Rails.root.join('spec', 'support', '**/*.rb')].each { |f| require f }
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
spec/spec_helper.rb:41:1: C: Rails/FilePath: Please use Rails.root.join('path', 'to') instead.
Dir[Rails.root.join('spec/support/**/*.rb')].each { |f| require f }
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
spec/spec_helper.rb:41:5: C: Rails/FilePath: Please use Rails.root.join('path', 'to') instead.
Dir[Rails.root.join('spec/support/**/*.rb')].each { |f| require f }
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
spec/support/helpers/load_fixture_helper.rb:14:5: C: Rails/FilePath: Please use Rails.root.join('path', 'to') instead.
    Dir[Rails.root.join('spec', 'fixtures', '**/*')].map do |path|
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
spec/support/helpers/load_fixture_helper.rb:14:9: C: Rails/FilePath: Please use Rails.root.join('path', 'to') instead.
    Dir[Rails.root.join('spec', 'fixtures', '**/*')].map do |path|
```

**Comment by deivid-rodriguez** [comment]
@chrishough This seems legit, you should use `Rails.root.join('spec', 'fixtures', '**', '*')` instead.

**Comment by mikegee** [comment]
@deivid-rodriguez unfortunately that code isn't equivalent.

The instance of `Pathname` you get from joining with `Rails.root` doesn't support file globbing like `Dir[]` does. `Dir[Rails.root.join('spec', 'concerns', '**/*.rb')]` is about as idiomatic as it gets.

I suppose that `'**/*.rb'` at the end should be `'**', '*.rb'` in case the code needs to work on Windows.

**Comment by deivid-rodriguez** [comment]
mmmm can you show an example of what you mean? It seems to work with my expectations.

**Comment by mikegee** [comment]
```
% cat require_me/a.rb
puts 'a.rb required!'

% cat require_me/subdir/b.rb
puts 'b.rb required!'
```
```
pry> Rails.root.join('require_me', '**', '*.rb').each { |f| require f }
NoMethodError: undefined method `each' for #<Pathname:/app/require_me/**/*.rb>
from (pry):1:in `__pry__'

pry> Rails.root.join('require_me', '**', '*.rb').each_entry { |f| require f }
Errno::ENOENT: No such file or directory @ dir_initialize - /app/require_me/**/*.rb
from (pry):3:in `open'

pry> Dir[Rails.root.join('require_me', '**', '*.rb')].each { |f| require f }
a.rb required!
b.rb required!
=> ["/app/require_me/a.rb", "/app/require_me/subdir/b.rb"]
```

**Comment by deivid-rodriguez** [comment]
I still don't get it. I get exactly the same results if I use `Rails.root.join('require_me', '**/*.rb')` instead of `Rails.root.join('require_me', '**', '*.rb')` in your examples.

**Comment by mikegee** [comment]
Oh, you're just wondering about the little note about Windows compatibility about the bottom of my first comment? I thought we were talking about the reported bug.

**Comment by deivid-rodriguez** [comment]
Mmmm... I guess the little note about Windows compatibility is one of the reasons for the cop to exist. The ticket itself (as I understand it) reports some false positives for the cop, but I think they are actually true positives.

**Comment by mikegee** [comment]
Ok, this was mostly miscommunication. When you said:

> you should use `Rails.root.join('spec', 'fixtures', '**', '*')`

for some reason, I thought you were recommending removal of the `Dir[].each` part.

**Comment by deivid-rodriguez** [comment]
Nono, sorry for not being clear. I meant the OP should do what the cops tells you to do: avoid `/` as a path separator and use `Rails.root.join` with the different parts as arguments instead.

So do we agree this is not a bug and it should be closed?

**Comment by mikegee** [comment]
> So do we agree this is not a bug and it should be closed?

Indeed we do.

**Comment by chrishough** [comment]
Yep, you were correct it should be like `Dir[Rails.root.join('spec', 'fixtures', '**', '*')].map do |path|`.  Thank you.
