### ISSUE TITLE
AllCops:EnabledByDefault

### ISSUE THREAD

**Issue by betesh** [bbatsov/rubocop#4005]
Rubocop should have an EnabledByDefault option, just like there's a DisabledByDefault option.

If I want to Enable all cops, I need to read through all the docs to figure out which ones are disabled by default.  It would be far more efficient if I could simply configure Rubocop to enable all of them.

Also, even if I've already enabled all cops that are disabled by default, if a new cop is added in a later version, I need to read through the Change Log to know about it.

**Comment by bbatsov** [comment]
Sounds like a reasonable idea to me.

**Comment by betesh** [comment]
Great, I'm working on a PR

**Comment by betesh** [comment]
@bbatsov Can you take a look at the failing test on the PR (#4014)?  I think it's a bug in the existing code but I'm not sure.
