### ISSUE TITLE
Recommend `File.expand_path(__dir__)` over `File.expand_path('..', __FILE__)`

### ISSUE THREAD

**Issue by backus** [bbatsov/rubocop#4008]
Since Ruby 2.0 we've had `__dir__` as well as `__FILE__`. Still, I think a very standard practice is write

```ruby
File.expand_path('..', __FILE__)
```

even though now you can do

```ruby
File.expand_path(__dir__)
```

Other corrections we could make like this:

```ruby
File.expand_path('../..', __FILE__) == File.expand_path('..', __dir__)         # => true
Pathname.new(__FILE__).parent.expand_path == Pathname.new(__dir__).expand_path # =>true
```

**Comment by bbatsov** [comment]
I'm fine with the idea. I think I planned to implement this myself years ago, but I never got to doing so.

**Comment by dabroz** [comment]
@backus `Dir.pwd` is the current directory, which can be changed with `Dir.chdir`. `__dir__` is always constant for a specific file.

**Comment by backus** [comment]
@dabroz good point I'll adjust that

**Comment by reitzig** [comment]
The message is `Style/Dir: Use `__dir__` to get an absolute path to the current file's directory. [Style/Dir]` but `__dir__` alone gives us a relative path. The autofix from `File.expand_path(File.dirname(__FILE__))` to `__dir__` is therefore wrong.

This is with Ruby 2.3.1 and RuboCop 0.52.1.
