### ISSUE TITLE
Style/MutableConstant autocorrect wraps `%w` and `%i` arrays

### ISSUE THREAD

**Issue by benwalsh** [bbatsov/rubocop#4009]
When assigning a `%w` array of words or `%i` array of symbols to a constant which is not frozen, Rubocop's autocorrect nests the array by wrapping it in brackets

## Expected behavior

Running `rubocop -a` on a file containing this line:

```
PERMITTED_MARSUPIALS = %w(thylacine quokka wombat)
```

should change it to:

```
PERMITTED_MARSUPIALS = %w(thylacine quokka wombat).freeze
```

## Actual behavior

Autocorrect changes the line to:

```
PERMITTED_MARSUPIALS = [%w(thylacine quokka wombat)].freeze
```

## Steps to reproduce the problem

`echo "PERMITTED_MARSUPIALS = %w(thylacine quokka wombat)" > test.rb && rubocop -a test.rb && cat test.rb`

## RuboCop version

```
0.47.1 (using Parser 2.3.3.1, running on ruby 2.3.1
```

**Comment by backus** [comment]
Seems like a duplicate of https://github.com/bbatsov/rubocop/issues/3959 which @mikegee fixed here https://github.com/bbatsov/rubocop/pull/3962

**Comment by benwalsh** [comment]
Yep, looks like it. Closing as a dupe. Thanks!
