### ISSUE TITLE
Gem install rubocop doesn't work from Gemfile

### ISSUE THREAD

**Issue by missvenus** [bbatsov/rubocop#4024]
Gemfile:

source 'http://rubygems.org' do
  gem 'activesupport'
  gem 'aws-sdk', '2.2.9'
  gem 'aws-sdk-v1'
  gem 'capybara'
  gem 'cucumber'
  gem 'logger'
  gem 'mail'
  gem 'net-sftp'
  gem 'net-ssh'
  gem 'rest-client'
  gem 'retriable'
  gem 'rspec'
  gem 'rubyzip'
  gem 'splunk-sdk-ruby'
  gem 'spork'
  gem 'uuidtools'
  gem 'rubocop', require: false
end

--------

## Actual behavior

bundle install
Fetching gem metadata from https://gems.cloud.bbc.co.uk/...
Fetching version metadata from https://gems.cloud.bbc.co.uk/..
Fetching dependency metadata from https://gems.cloud.bbc.co.uk/..
Fetching gem metadata from http://rubygems.org/............
Fetching version metadata from http://rubygems.org/.
Fetching gem metadata from https://gems.cloud.bbc.co.uk/...
Fetching gem metadata from http://rubygems.org/............
Fetching version metadata from https://gems.cloud.bbc.co.uk/..
Fetching version metadata from http://rubygems.org/.
Resolving dependencies...
Using concurrent-ruby 1.0.2
Using i18n 0.7.0
Using minitest 5.9.1
Using thread_safe 0.3.5
Using addressable 2.4.0
Using ast 2.3.0
Using jmespath 1.3.1
Using json 1.8.3
Using mini_portile2 2.1.0
Using builder 3.2.2
Using mime-types-data 3.2016.0521
Using rack 2.0.1
Using gherkin 4.0.0
Using cucumber-wire 0.0.1
Using diff-lcs 1.2.5
Using multi_json 1.12.1
Using multi_test 0.1.2
Using unf_ext 0.0.7.2
Using logger 1.2.8
Using net-ssh 3.2.0
Using netrc 0.11.0
Using powerpack 0.1.1
Installing rainbow 2.2.1 with native extensions
Using retriable 2.1.0
Using rspec-support 3.5.0
Using ruby-progressbar 1.8.1
Using unicode-display_width 1.1.3
Using rubyzip 1.2.0
Using splunk-sdk-ruby 1.0.5
Using spork 0.9.2
Using uuidtools 2.1.5
Using bundler 1.14.3
Using tzinfo 1.2.2
Using parser 2.4.0.0
Using aws-sdk-core 2.2.9
Using nokogiri 1.6.8.1
Using mime-types 3.1
Using rack-test 0.6.3
Using cucumber-core 1.5.0
Using unf 0.1.4
Using net-sftp 2.1.2
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    current directory: /Users/jainv02/AMP/amp_code/.gems/ruby/2.3.0/gems/rainbow-2.2.1/ext
/Users/jainv02/.rvm/rubies/ruby-2.3.1/bin/ruby mkrf_conf.rb 

current directory: /Users/jainv02/AMP/amp_code/.gems/ruby/2.3.0/gems/rainbow-2.2.1/ext
rake RUBYARCHDIR=/Users/jainv02/AMP/amp_code/.gems/ruby/2.3.0/extensions/x86_64-darwin-14/2.3.0/rainbow-2.2.1 RUBYLIBDIR=/Users/jainv02/AMP/amp_code/.gems/ruby/2.3.0/extensions/x86_64-darwin-14/2.3.0/rainbow-2.2.1
/Users/jainv02/.rvm/rubies/ruby-2.3.1/lib/ruby/site_ruby/2.3.0/rubygems.rb:270:in `find_spec_for_exe': can't find gem rake (>= 0.a) (Gem::GemNotFoundException)
	from /Users/jainv02/.rvm/rubies/ruby-2.3.1/lib/ruby/site_ruby/2.3.0/rubygems.rb:298:in `activate_bin_path'
	from /Users/jainv02/.rvm/gems/ruby-2.3.1/bin/rake:22:in `<main>'
	from /Users/jainv02/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `eval'
	from /Users/jainv02/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `<main>'

rake failed, exit code 1

Gem files will remain installed in /Users/jainv02/AMP/amp_code/.gems/ruby/2.3.0/gems/rainbow-2.2.1 for inspection.
Results logged to /Users/jainv02/AMP/amp_code/.gems/ruby/2.3.0/extensions/x86_64-darwin-14/2.3.0/rainbow-2.2.1/gem_make.out

An error occurred while installing rainbow (2.2.1), and Bundler cannot continue.
Make sure that `gem install rainbow -v '2.2.1'` succeeds before bundling.

ruby version 2.3.1
bundler version tried with 1.12.5 and 1.14.3

**Comment by rrosenblum** [comment]
This appears to be an issue with `Rainbow` not with `RuboCop`. According to the message, `rake` is not installed and `Rainbow` seems to be relying on `Rake` for the install. Try adding `gem 'rake'` to your `Gemfile` before `gem 'rubocop', require: false`. I know it isn't the best solution since you might not want to have a dependency on `Rake`. 

Assuming that `Rake` is not installed at the system level, `gem install rainbow -v '2.2.1'` should fail for the same reason.

**Comment by mikegee** [comment]
We've run into this problem at work, too. Here's the discussion about it:

https://github.com/sickill/rainbow/issues/44

It is not a bug in Rubocop.

**Comment by Drenmi** [comment]
Scary. Just watched this error on CI, and while waiting for it to rerun, I went to check GitHub issues ... 😅

**Comment by missvenus** [comment]
adding gem 'rake', worked for me. Thanks for very quick response.
