### ISSUE TITLE
Add ability to analyze arbitrary strings of code without files

### ISSUE THREAD

**Issue by michaelherold** [bbatsov/rubocop#4030]
## Problem

Currently, RuboCop requires files to be present in the analysis directory in order to perform its analysis. This causes any tools that use its functionality to go through a song and dance if they want to operate on something less than a file. For instance, the [haml-lint] tool [generates Tempfiles] from code that is extracted from Haml files to lint the Ruby code using RuboCop.

Having the ability to just pass in strings of Ruby code would make this a lot easier. Since the gem currently requires Tempfiles to do its work, the RuboCop linter within haml-lint cannot operate in the [codeclimate-haml_lint] engine that I have been working on. Without having the ability to lint arbitrary strings of code, I cannot get the two to play nicely.

[haml-lint]: https://github.com/brigade/haml-lint
[generates Tempfiles]: https://github.com/brigade/haml-lint/blob/778e9116aa188596020b4bdfc3ff58881e2da824/lib/haml_lint/linter/rubocop.rb#L21-L43
[codeclimate-haml_lint]: https://github.com/michaelherold/codeclimate-haml_lint

--------

## Value Statement

By (1) extending the RuboCop Runner, (2) making a special class of Runner that works specifically on strings, or (3) refactoring the Runner to first extract strings from files then delegating to another class that does the analysis, we could make RuboCop friendlier to integrate into other tools.

Option (3) probably has the most value to it because the Runner class already has several responsibilities. By splitting up the responsibility of preparing the code blocks to analyze and performing the analysis, RuboCop could be extended in other ways, such as linting code blocks within a Markdown document or examples in documentation comments.

I believe that RuboCop will have a better code base and be more open for extension with these changes.

--------

## Possible Solutions

For a full-fledged feature, there would need to be an addition to the CLI and a change to the internal API for RuboCop.

### Suggested CLI Command

To analyze the code written in the terminal, a possible CLI command could be:

    $ rubocop --inline-code '
    class Test
      def get_name
        "Testy McTesterson"
      end
    end
    '

### Simplest Possible API?

To pass data into the Runner without doing much rearranging of code, there could be an extra option given to the runner. This example:

```ruby
runner = RuboCop::Runner.new(inline_code: true, RuboCop::ConfigStore.new)
code = <<CODE
class Test
  def get_name
    "Testy McTesterson"
  end
end
CODE
runner.run([code])
```

would analyze the code in the `code` variable.

--------

I'd be happy to help with this - the Runner class is a little dense to go through, so I thought I'd file the request to see if there's even any interest in supporting something like this.

**Comment by mikegee** [comment]
There's a command line flag that can help (`--stdin`):

```
% cat test/test.rb
class Test
  def get_name
    "Testy McTesterson"
  end
end
```
```
% cat test/test.rb | rubocop --stdin stdin.rb
Inspecting 1 file
C

Offenses:

stdin.rb:1:1: C: Missing top-level class documentation comment.
class Test
^^^^^
stdin.rb:1:1: C: Missing magic comment # frozen_string_literal: true.
class Test
^
stdin.rb:2:7: C: Do not prefix reader method names with get_.
  def get_name
      ^^^^^^^^
stdin.rb:3:5: C: Prefer single-quoted strings when you don't need string interpolation or special symbols.
    "Testy McTesterson"
    ^^^^^^^^^^^^^^^^^^^

1 file inspected, 4 offenses detected
```

**Comment by michaelherold** [comment]
... wow. I looked through all the options and somehow missed that one! Thanks for pointing that out. 

I'll close this since it appears to already exist.
