### ISSUE TITLE
end is not aligned with @app = case

### ISSUE THREAD

**Issue by bootstraponline** [bbatsov/rubocop#4048]
## Expected behavior

No offense.

## Actual behavior

Offense reported. Autocorrect fails to fix the indent.

> bug.rb:17:8: W: end at 17, 7 is not aligned with @app = case at 3, 0.

## Steps to reproduce the problem

```ruby
# frozen_string_literal: true
# fail.rb
@app = case a
       when :b
         case c
         when :d
           e
           f
         when :g
           h
         end
       when :i
         case j
         when :k
           l
         end
       end
```

> $ rubocop -a fail.rb

## RuboCop version

```
$ rubocop -V
0.47.1 (using Parser 2.4.0.0, running on ruby 2.3.3 x86_64-darwin16)
```

Is this the expected behavior?

```ruby
# fixed
# frozen_string_literal: true
# fail.rb
@app = case a
       when :b
         case c
         when :d
           e
           f
         when :g
           h
         end
       when :i
         case j
         when :k
           l
         end
end
```

**Comment by backus** [comment]
Dupe of https://github.com/bbatsov/rubocop/issues/3866, https://github.com/bbatsov/rubocop/issues/3980, https://github.com/bbatsov/rubocop/issues/3900

**Comment by bootstraponline** [comment]
Thanks. I'll follow #3980
