### ISSUE TITLE
0.47.1: Rails/ReversibleMigration misdetection 

### ISSUE THREAD

**Issue by dabroz** [bbatsov/rubocop#4063]
```
class AddNewColumn < ActiveRecord::Migration[5.0]
  def change
    change_table(:users) do |t|
      t.string :new_column
    end
  end
end
```

## Expected behavior

It should pass without problems. `change_table` is reversible. 

## Actual behavior

    C: Rails/ReversibleMigration: change_table is not reversible.

## RuboCop version

```
0.47.1 (using Parser 2.4.0.0, running on ruby 2.4.0 x86_64-darwin16)
```

**Comment by tejasbubane** [comment]
Docs say:
```
change_table is also reversible, as long as the block does not call 
change, change_default or remove.
```

And [looks like](https://github.com/rails/rails/issues/12546) it works only in Rails 4. 
Not sure if checking all these scenarios is in scope of Rubocop.

**Comment by gPrado** [comment]
Couldn't `TargetRailsVersion` be used for checking it?
The rails issue post is quite old (Oct/2013), so this probably works for Rails 5 too, otherwise it wouldn't be present in the edge guides.
