### ISSUE TITLE
`Performance/RegexpMatch` cop should check for `$LAST_MATCH_INFO` in addition to `$~` and `Regexp.last_match`

### ISSUE THREAD

**Issue by dark-panda** [bbatsov/rubocop#4070]
## Expected behavior

`$LAST_MATCH_INFO` is the name used by the `English` model for `$~` but the `Performance/RegexpMatch` cop only checks for `$~` and `Regexp.last_match`. `$LAST_MATCH_INFO` should be included as valid alias.

## Actual behavior

Describe here what actually happened.

## Steps to reproduce the problem

Use `=~` with a `Regexp` and reference `$LAST_MATCH_INFO` to have the cop complain. Replacing `$LAST_MATCH_INFO` with `$~` or `Regexp.last_match` produces no such complaint.

## RuboCop version

```
0.47.1 (using Parser 2.4.0.0, running on ruby 2.4.0 x86_64-darwin16)
```

**Comment by pocke** [comment]
This problem is fixed in https://github.com/bbatsov/rubocop/pull/3978 .

**Comment by dark-panda** [comment]
So it is! Serves me right for not checking more thoroughly!
