### ISSUE TITLE
Class instance variable assignment

### ISSUE THREAD

**Issue by tdeo** [bbatsov/rubocop#4072]
Hi,

I've been recently running into odd issues with @ericsaboia because of assignment to a class instance variable. Our code runs in Sidekiq, and turns out several threads are sharing this class instance variable, so it's not very safe re-assigning it.

Do you think it would be in the scope of rubocop to check this kind of things? If so, I'd be happy to give it a try.

**Comment by mikegee** [comment]
We were having similar troubles so I created an extension to check for some thread-safety issues: https://github.com/covermymeds/rubocop-thread_safety

**Comment by tdeo** [comment]
Awesome, thanks.

@bbatsov Would there be any plan to show a list of rubocop "extensions" for people like me looking for some extras? Or does it already exists and I miss it?

**Comment by mikegee** [comment]
I just went looking and found "Known Custom Cops" at http://rubocop.readthedocs.io/en/latest/extensions/

**Comment by tdeo** [comment]
Great, thanks for your help
