### ISSUE TITLE
0.47.1: undefined method `map' for "only_raise":String

### ISSUE THREAD

**Issue by JakeTheSnake3p0** [bbatsov/rubocop#4075]
Rubocop Version: 0.47.1  
Ruby Version: 2.3 x64  

Running through the command prompt `rubocop -d [my-filepath.rb]`, I get a series of the same error:  
```
undefined method `map' for "only_raise":String
Did you mean?  tap
C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/rubocop-0.47.1/lib/rubocop/cop/mixin/configurable_enforced_style.rb:89:in `supported_styles'
C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/rubocop-0.47.1/lib/rubocop/cop/mixin/configurable_enforced_style.rb:67:in `style'
C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/rubocop-0.47.1/lib/rubocop/cop/style/signal_exception.rb:36:in `on_send'
C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/rubocop-0.47.1/lib/rubocop/cop/commissioner.rb:43:in `block (2 levels) in on_send'
C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/rubocop-0.47.1/lib/rubocop/cop/commissioner.rb:102:in `with_cop_error_handling'
C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/rubocop-0.47.1/lib/rubocop/cop/commissioner.rb:42:in `block in on_send'
C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/rubocop-0.47.1/lib/rubocop/cop/commissioner.rb:41:in `each'
C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/rubocop-0.47.1/lib/rubocop/cop/commissioner.rb:41:in `on_send'
```

**Comment by mikegee** [comment]
Please help me reproduce the problem by providing a ruby file and your `.rubocop.yml`.

**Comment by JakeTheSnake3p0** [comment]
It had to do with my rubocop configuration. In past versions I had not encountered this error nor had I recently changed the config file so I didn't know to look for the solution there.

Old `.rubocop.yml`
```
Style/SignalException:
  SupportedStyles:
    only_raise
```

New `.rubocop.yml`
```
Style/SignalException:
  EnforcedStyle: only_raise
  SupportedStyles:
    - only_raise
```

Essentially the hyphen-space was missing before `only_raise` under `SupportedStyles` which was probably causing a misconfiguration in the rule parser.

The error produced however, was misleading:

> An error occurred while Style/SignalException cop was inspecting [file]

Which lead me to think that there was something wrong with my ruby file (which there wasn't) or the rubocop application itself. I'm not sure how difficult it will be to fix the misleading error but I would have expected the message to be akin to:

> Rubocop error: Check the configuration file
