### ISSUE TITLE
Style/IndentationWidth might be conflicting with start_of_line Lint/EndAlignment style

### ISSUE THREAD

**Issue by brandonweiss** [bbatsov/rubocop#4105]
I have:

```yaml
Lint/EndAlignment:
  EnforcedStyleAlignWith: "start_of_line"
```

And if I turn on Style/IndentationWidth I get weird suggestions, like this:

```ruby
def carry_attribution_data_from_previous_customer_invoice
  items = if line_items.retrospective.pre_subtotal.any?
            line_items.retrospective.pre_subtotal
  else
    line_items.bill_ahead.pre_subtotal
  end
end
```

It's obviously trying to indent two lines relative to the `if` statement, but that's not what I'd want/expect. What I'd expect is:

```ruby
def carry_attribution_data_from_previous_customer_invoice
  items = if line_items.retrospective.pre_subtotal.any?
    line_items.retrospective.pre_subtotal
  else
    line_items.bill_ahead.pre_subtotal
  end
end
```

**Comment by stakach** [comment]
I have the same issue:

```yml
Lint/EndAlignment:
  EnforcedStyleAlignWith: start_of_line
```
and
```ruby
msg << if queued.empty?
  'send queue is empty'
else
  "send queue contains: \n#{queued.join("\n")}"
end
```

outputs

```
Use 2 (not -1) spaces for indentation.
                'send queue is empty'
                ^^^
Align else with if.
        else
        ^^^^
```

If I disable `Style/ElseAlignment` then I only get the `Use 2 (not -1) spaces for indentation.`
So I also have to disable `Style/IndentationWidth` which is undesirable

**Comment by brandonweiss** [comment]
@bbatsov Hey! I've started a [PR](https://github.com/bbatsov/rubocop/pull/4652) where I refactored the tests such that they also run `Lint/EndAlignment` configured with `start_of_line` in order to create a set of failing tests. I spent several hours today stepping through the `on_if` block of the cop, introspecting the various nodes and trying to figure out where the bug is, but I don't think I really got anywhere.

My very rudimentary understanding seems to be that when it gets to [here](https://github.com/bbatsov/rubocop/blob/4abb67df0aa5b53cb42ceaae899636ef7cae2529/lib/rubocop/cop/layout/indentation_width.rb#L214), the `base_loc` is wrong. But `base_loc` is passed through into the `on_if` hook (via `base_node`). So… maybe the problem is occurring higher up somewhere? If you could help me by taking a look yourself and/or pointing me in the right direction that would be awesome. Thanks!

**Comment by jonas054** [comment]
@brandonweiss I think the problem is that in `IndentationWidth#check_assignment`, we're looking at the `Lint/EndAlignment: EnforcedStyleAlignWith` configuration when calculating `base`, but there's only support for the `variable` alignment style. The `start_of_line` style is treated the same as `keyword`, which is a bug.
