### ISSUE TITLE
Incorrect autocorrection of increment

### ISSUE THREAD

**Issue by tarkeshwar1** [bbatsov/rubocop#4109]
i=i+1
gets autocorrected as:
i+ = 1

which raises syntax error with ruby 2.1.8.

--------

## Expected behavior
i += 1 

## Actual behavior

i+ = 1

## Steps to reproduce the problem

$ cat increment.rb
i=i+1
$ rubocop -a increment.rb 
Inspecting 1 file
E

Offenses:

increment.rb:1:1: C: [Corrected] Use self-assignment shorthand +=.
i=i+1
^^^^^
increment.rb:1:2: C: [Corrected] Surrounding space missing for operator =.
i=i+1
 ^
increment.rb:1:4: C: [Corrected] Surrounding space missing for operator +.
i=i+1
   ^
increment.rb:1:4: E: unexpected token tEQL
(Using Ruby 2.1 parser; configure using TargetRubyVersion parameter, under AllCops)
i+ = 1
   ^

1 file inspected, 4 offenses detected, 3 offenses corrected
$ cat increment.rb 
i+ = 1

## RuboCop version
```
$ rubocop -V
0.47.1 (using Parser 2.4.0.0, running on ruby 2.1.8 x86_64-darwin15.0)
```

**Comment by bbatsov** [comment]
Likely a bad interaction with some other auto-correct.
