### ISSUE TITLE
Rake task generated with an external .rubocop.yml has wrong absolute paths

### ISSUE THREAD

**Issue by ys** [bbatsov/rubocop#4122]
We have a gem we include in all our projects, in its root, there is a `.rubocop.yml` with the following block.

```
AllCops:
  Exclude:
    - "db/**/*"
    - "bin/**/*"
    - "script/**/*"
    - "config/**/*"
    - "vendor/**/*"
```

## Expected behavior

We expect it to have path relative to the project in which the gems are included and from where we run the rubocop rake task

## Actual behavior

The excluded paths are relative to the gem installation directory.
Which means it will scan all our vendor `.rb` files in our CI. 

## Steps to reproduce the problem

Run rubocop with the `-c` flag and a file that is not in the current directory.
Or in our case we have this rake task defined in our swiss knife gem
```
desc "Run rubocop with current flags"
RuboCop::RakeTask.new do |t|
  config_file = File.join(File.dirname(__FILE__),
                          "..", "..", ".rubocop.yml")
  t.options = ["-E", "-S", "-c", config_file]
end
```

## Current fix

We have to use regular expressions instead of strings. this fixes the issue but unsure if the relative to `.rubocop.yml` behavior is expected or not.

```
AllCops:
  Exclude:
    - !ruby/regexp /(db|bin|script|config|vendor)\/.*/
```

## RuboCop version

```
$ rubocop -V
0.47.1 (using Parser 2.4.0.0, running on ruby 2.3.1 x86_64-darwin16)
```

**Comment by jonas054** [comment]
Yes, that's expected behavior. From the manual:

> In .rubocop.yml and any other configuration file beginning with .rubocop, files and directories are specified relative to the directory where the configuration file is. In configuration files that don't begin with .rubocop, e.g. our_company_defaults.yml, paths are relative to the directory where rubocop is run.
