### ISSUE TITLE
Style/ClosingParenthesisIndentation Changes

### ISSUE THREAD

**Issue by jfelchner** [bbatsov/rubocop#4136]
I want to outline my goals here and try to get some discussion started.

## Goal

I'd like to update the `Style/ClosingParenthesisIndentation` cop to be more robust and handle specific indentation scenarios.  Currently the `Style/ClosingParenthesisIndentation` cop is pretty basic which unfortunately means that it doesn't achieve the desired result in a lot of cases.

## Examples

```ruby
        hello_this_is_my_variable = what.could.this_method_be_doing(
                                      i_dunno: 'but',
                                      i_like:  'it',
)
```

It's fairly clear from this code that the developer would want to align the parenthesis with the opening one.  Because this:

```ruby
        hello_this_is_my_variable = what.could.this_method_be_doing(
                                      i_dunno: 'but',
                                      i_like:  'it',
        )
```

looks ridiculous.  However in the same codebase, there may be a case like this:

```ruby
        what.could.this_method_be_doing(
          i_dunno: 'but',
          i_like:  'it',
)
```

where it's fairly obvious to the reader that the right paren should be aligned by the beginning of the line with the method call.

There's also an (albeit weirder) situation like this:

```ruby
        what.could.this_method_be_doing(i_dunno: 'but',
                                        i_like:  'it',
)
```

Where the right paren should be aligned with the right paren.  Even though that looks weird, it looks better than the current result of this cop, which is:

```ruby
        what.could.this_method_be_doing(i_dunno: 'but',
                                        i_like:  'it',
        )
```

## Possibilities

What I'd like to do is have a discussion about the possible changes to the `Style/ClosingParenthesisIndentation` which could cover these use cases.

**Comment by jfelchner** [comment]
Ping @jonas054 @Drenmi  😁

**Comment by bbatsov** [comment]
I might be missing something, but it's unclear to me whether you're reporting a bug or proposing an improvement.

**Comment by jfelchner** [comment]
@bbatsov improvement for the most part.  I believe the cop only handles one simple case.  I'm asking for feedback on configuration changes that would allow it to handle the cases outlined above.

**Comment by jfelchner** [comment]
@bbatsov I think the best approach for this cop is to remove most of the logic and let it depend on where the parameters are aligned at.  I think there should be only two rules:

If the method is called (or defined) and the arguments/parameters...

* that span more than one line, the closing paren should be outdented by one `IndentationWidth` from the last argument/parameter
* that are all on one line, the closing paren should be aligned with the opening paren

This lets the other cops like `Layout/FirstParameterIndentation`, `Layout/FirstMethodParameterLineBreak`, `Layout/FirstMethodArgumentLineBreak`, `Layout/MultilineMethodDefinitionBraceLayout`, `Layout/MultilineMethodCallBraceLayout` and `Layout/AlignParameters` be responsible for their jobs and `Layout/ClosingParenthesisIndentation` would simply be the result of the end of that flow.

By simplifying the cop, it allows for all of the cases described in #5650, all of my use cases here, and will keep almost every current `ClosingParenthesisIndentation` spec passing.

**Comment by jfelchner** [comment]
@Drenmi I see what was missed.  The cop needs to have a config added to the default config which sets its IndentationWidth to `~`.

Reference in the code is [here](https://github.com/rubocop-hq/rubocop/commit/68609e6bcd53e82043c404d6c1e4fe1e82457b63#diff-84278b38a8a718e15ad796e211b6c0c2R142)
