### ISSUE TITLE
invalid substitution with rubocop -a ( .match("string") -> =~ "string" )

### ISSUE THREAD

**Issue by TheSimkin** [bbatsov/rubocop#4140]
Replacing .match("string") with =~ "string" causes a runtime error.

--------

## Expected behavior

.match("Search Results") ->  =~ /Search Results/

## Actual behavior

.match("Search Results") ->  =~ "Search Results"

## Steps to reproduce the problem

rubocop -a somefile.rb

## RuboCop version

```
$ rubocop -V
0.42.0 (using Parser 2.3.2.0, running on ruby 2.3.1 x86_64-darwin16)
```

**Comment by mikegee** [comment]
I confirmed the behavior with 0.42.0, but on master it doesn't autocorrect.

**Comment by bbatsov** [comment]
@mikegee Thanks for checking this!
