### ISSUE TITLE
Auto-correct bug with percentage literal and square brackets

### ISSUE THREAD

**Issue by cabello** [bbatsov/rubocop#4148]
## Steps to reproduce the problem

Run `rubocop -a` on the following code:
```
TERMINAL_STATES  = %w[rejected failed complete undefined]
```

## Actual behavior

Results in the following code:
```
TERMINAL_STATES = [%w(rejected failed complete undefined)].freeze
```

Which ultimately changes the behaviour of the code.

## Expected behavior

```
TERMINAL_STATES = %w(rejected failed complete undefined).freeze
```

## RuboCop version

```
$ rubocop -V
0.47.1 (using Parser 2.4.0.0, running on ruby 2.3.0 x86_64-darwin16)
```

**Comment by mikegee** [comment]
This was fixed by https://github.com/bbatsov/rubocop/pull/3962, but isn't released yet.

@bbatsov, we've had a few reports of this problem. I suggest releasing in the next couple weeks, if you can. How can I help?

**Comment by Drenmi** [comment]
0.48.0 is now released. Can we close this @cabello? 🙂

**Comment by cabello** [comment]
Sure, I will update the gem on my projects, thank you very much!
