### ISSUE TITLE
Style/InverseMethods broke defined method `none?`

### ISSUE THREAD

**Issue by ShockwaveNN** [bbatsov/rubocop#4192]
I have a class with defined method `none?` and after using autofix by `Style/InverseMethods` it broke my code

## Steps to reproduce the problem
1. Create test.rb file with content:
```
class MyClass
  def none?
    false
  end
end

obj = MyClass.new
p !obj.none?
```
2. Run it and it seems fine
3. Perform `rubocop -a test.rb`, it change last line to `p obj.any?` and cause `undefined method `any?' for #<MyClass:0x0000000190bce8> (NoMethodError)` 

## RuboCop version
```
$ rubocop -V
0.48.0 (using Parser 2.4.0.0, running on ruby 2.1.10 x86_64-linux)
```

**Comment by bbatsov** [comment]
There's no way for us to change reliably detect this. I'd suggest either defining the inverse method in your class or simply tweaking the configuration of the cop. Classic limitations of doing static analysis in a dynamic language - there's a lot of guesswork involved.
