### ISSUE TITLE
Why prefer_alias is the enforced style in Style/Alias

### ISSUE THREAD

**Issue by Ana06** [bbatsov/rubocop#4193]
In the [Ruby Style guide](https://github.com/bbatsov/ruby-style-guide#alias-method) it is said:

> Always use alias_method when aliasing methods of modules, classes, or singleton classes at runtime, as the lexical scope of alias leads to unpredictability in these cases.

Then, why `prefer_alias` is the enforced style in Style/Alias? I think the enforced style should be `prefer_alias_method`

**Comment by bbatsov** [comment]
Because there it also says https://github.com/bbatsov/ruby-style-guide#alias-method-lexically :-)

**Comment by Drenmi** [comment]
This comes up often enough (I mentioned it here #3619) that it deserves its own FAQ entry. 😅
