### ISSUE TITLE
++ is not correctly parsed

### ISSUE THREAD

**Issue by Ana06** [bbatsov/rubocop#4194]
`@variable++` should be correct, but Rubocop complains about it with errors that are unrelated to the `++` itself.

--------

## Example 1

``` Ruby
def example1
  @variable++
end
```

**Error:** 

```
E: unexpected token $end
(Using Ruby 2.1 parser; configure using TargetRubyVersion parameter,
under AllCops)

```
## Example2

``` Ruby
def example2
  @variable++
  1 + 2
end
```

**Error:**

```
C: Style/SpaceAroundOperators:
Surrounding space missing for operator +.
    @variable++
             ^
```
## RuboCop version

```
0.47.1 (using Parser 2.4.0.0, running on ruby 2.2.5 x86_64-linux-gnu)
```

**Comment by bbatsov** [comment]
That's a bug in the parser, not in RuboCop. Please, report it here https://github.com/whitequark/parser

**Comment by bbatsov** [comment]
Actually I'm not sure why it's a syntax error in one of the examples and a style error in the other, but it's definitely something to do with the parser.

**Comment by Drenmi** [comment]
Am I missing something obvious? Ruby doesn't have a `++` operator? 😕

**Comment by bbatsov** [comment]
I assumed the point of this ticket is that `+` is allowed in identifiers names, which seems a bit doubtful to me.  But on second thought - probably you're right. :-)

**Comment by Ana06** [comment]
@Drenmi 

> Ruby doesn't have a ++ operator

You are right, wondering why my code is not failing... Nevermind, I'll close this
