### ISSUE TITLE
Suggestion: Inherit from ApplicationRecord

### ISSUE THREAD

**Issue by coding-bunny** [bbatsov/rubocop#4236]
Hello,

I wonder if it's possible make a cop that enforces all models to inherit from ApplicationRecord instead of `ActiveRecord::Base`?

Would be a tremendous help for migrating Rails 4 -> Rails 5 applications.
And would help eliminate problems as well in code for those apps.
We ran into some weird database-fu, and had to solve it by inheriting from the correct classes for some old models.

**Comment by tjwp** [comment]
We have a custom cop that does this: https://github.com/salsify/salsify_rubocop/blob/master/lib/rubocop/cop/salsify/rails_application_record.rb

Now that the `TargetRailsVersion` configuration is available I'd be happy to contribute something along these lines.

**Comment by coding-bunny** [comment]
would be really cool, cause that Cop is a life saver :D

**Comment by tjwp** [comment]
@coding-bunny You may also want to look at https://github.com/xinminlabs/synvert. 

With it you can run 

```ruby
synvert --run rails/upgrade_4_2_to_5_0 app_path/
```

to apply a collection of Rails5-isms to a code base, including replacing `ActiveRecord::Base`.

**Comment by coding-bunny** [comment]
nope, not going there anymore.
We did something like that with our Rails 3 -> 4 upgrade, and I don't want to go through that again...

Doing it step by step ourselves atm

**Comment by bbatsov** [comment]
@tjwp feel free to submit this upstream. :-)

**Comment by tjwp** [comment]
PR https://github.com/bbatsov/rubocop/pull/4279 opened

**Comment by ngelx** [comment]
Just to mention. If you are still in 4.2 and not planning to move to 5, it would be good to let it know to rubocop.

```
AllCops:
  ...
  TargetRailsVersion: 4.2
```
