### ISSUE TITLE
Ability to specify files/directories to look at and ignore everything else

### ISSUE THREAD

**Issue by olegantonyan** [bbatsov/rubocop#4247]
Situation:
A big old project written without any specific style. It's impossible to integrate Rubocop to the whole project. But, it's possible to enable it for new code only and incrementally add new directories as we go.

What I want to do:
Add global `.rubocop.yml` to the project and specify directories to look at. Everything else should be ignored. We're going to add more directories to that list as we go, but we need to start with a small step.

Right now the only way to do this looks very ugly and unreadable:
```yaml
Exclude:
    - !ruby/regexp /^((?!(something|some\/other\/dir)).)*$/
```
I bet everyone will give up on this after a 10 directories added.

My first try was this:
```yaml
Include:
    - 'something/**/*.rb'
Exclude:
  - '**/*'
```
I.e. exclude everything, but include these.

Second try was:
```yaml
Include:
    - 'something/**/*.rb'
```
Ok, just include these, and I'm not telling you to include anything else, so why do you even look at `./*`?

I'm not sure how syntax should look like, but I hope the problem was clear. Any thoughts appretiated

**Comment by Drenmi** [comment]
Welcome over from StackOverflow land. 🙂 Will have a look at the existing code and give this a think over the weekend. Any input from others is appreciated. 😊

**Comment by jonas054** [comment]
The best way to do this currently is to build up a list of `AllCops: Exclude` patterns. They can be regexp or glob patterns, and you don't have to cram everything into a single pattern.

The alternative is that you build a wrapper script that finds the files to inspect (using the version control history for example) and gives them as command line arguments to `rubocop`.

**Comment by gettalong** [comment]
I would also prefer to specify what to include instead of excluding all the things I don't want. A typical Ruby project has `bin`, `lib` and `test`/`spec` folders. So a config like

~~~ yaml
AllCops:
  Include:
    - bin/**/*
    - lib/**/*.rb
    - test/**/*.rb
~~~

would allow one to use Rubocop easily. No temporary Ruby files would raise a false alarm.

Would it be possible to add a new config option to `AllCops` to specify the exclude/include order? The default could be the current "find all files, exclude those from exclude list, use ones that are Ruby files, use ones that are specially included", with the alternative being "find all files, only use the ones from the include list, exclude the ones from the exclude list".

**Comment by revolter** [comment]
I thought that the default `Include` is `**/*` and as soon as you set it to `my_folder/**/*`, it overwrites the default "all folders and files" setting, so it would only look in the files inside the `my_folder`.

**Comment by revolter** [comment]
So, what is the solution to this closed issue?!

**Comment by olegantonyan** [comment]
I've added all existing files in the project to `Exclude`. It's very long list, but it seems to work just fine. Any new file created since then will be inspected by rubocop. And when refactoring old code we usually remove the file from the rubocop's exceptions.

**Comment by revolter** [comment]
That's not an elegant solution at all :( Couldn't there be a `DisableImplicitIncludes` option instead?

**Comment by jonas054** [comment]
Yes, I guess so. Opening again.

Either we add a `DisableImplicitIncludes` option, or we add an `IncludeOnly` option. It would be `nil` or empty by default, and if it contained any files or patterns, the implicit includes and the `Include` option would be disregarded.

Either way, the `Exclude` option could still work as today, I think.

**Comment by revolter** [comment]
I, too, think that the `Exclude` option should not be modified.

`IncludeOnly` sounds like the best way to achieve this, because that's exactly what I expected when first started using it: only run against the specified files in the `Include` option.

**Comment by Onumis** [comment]
Same here!

**Comment by chuckd** [comment]
Aha, thanks @Onumis - I'd missed *.rake.

**Comment by joshuapinter** [comment]
I got burned by this, too. Just noticed our rubocop tests were only doing 40 or so files instead of 1000+. 

Just to be clear, was this a change in functionality between one of the releases? If so, which one?

I could have sworn that adding entries to the `Include` would _append_ to the existing list, not _overwrite_ the existing list.

Thanks!

**Comment by bbatsov** [comment]
I think we changed this in 0.56 or 0.57. 

> I could have sworn that adding entries to the Include would append to the existing list, not overwrite the existing list.

True. The problem was that this way there was no way to modify the hardcoded defaults, which was frustrating for some people. Now people have the ultimate flexibility, as nothing's hardcoded anymore.

**Comment by joshuapinter** [comment]
Thanks for the clarification. So, quick question, how does one go about adding a specific file, whilst keeping the default files included?

**Comment by bbatsov** [comment]
See https://github.com/leklund/rubocop/commit/6c7e5ed29fd6c18ad20df3c0864fe21929e884e7

Probably we should make this more prominent in the docs.

**Comment by gresbtim** [comment]
what happened to `IncludeOnly`?

we have a huge codebase and want to enable it step by step for small parts of the codebase (mainly new written things or things we touched) 

config looks

```
AllCops:
  IncludeOnly:
    - 'app/models/building_data/*'

however this gives me a warning: **Warning: AllCops does not support IncludeOnly parameter.**

```

**Comment by jonas054** [comment]
`IncludeOnly` was never added, but if you override `AllCops:Include` locally it will do what you want.
