### ISSUE TITLE
Use logical lines of code instead of physical lines of code for Metrics/LineLength violations

### ISSUE THREAD

**Issue by JAMSUPREME** [bbatsov/rubocop#4251]
Might overlap with https://github.com/bbatsov/rubocop/issues/3059 ?

## Expected behavior

I expected rubocop to consider logical lines of code (LLOC) instead of physical lines of code.

## Actual behavior

Rubocop considers physical lines of code instead of logical lines.

## Steps to reproduce the problem

Right now Rubocop evaluates physical lines of code (PLOC or LOC) instead of logical lines of code (LLOC). Would it possible to enhance it to look at LLOC instead? Or allow us to pass a flag into `.rubocop.yml` which indicates a preference for LLOC vs. PLOC?

Given the following (somewhat facetious) example:
```
class LottaArgs
  def print
    print_one(a1: 'a',
              a2: 'b',
              a3: 'c',
              a4: 'd',
              a5: 'e')
    print_two(a1: 'a',
              a2: 'b',
              a3: 'c',
              a4: 'd',
              a5: 'e',
              a6: 'f')
  end

  def print_one(a1:, a2:, a3:, a4:, a5:)
    Rails.logger.info "#{a1}#{a2}#{a3}#{a4}#{a5}"
  end

  def print_two(big_hash)
    Rails.logger.info "#{big_hash[:a1]}#{big_hash[:a2]}#{big_hash[:a3]}#{big_hash[:a4]}#{big_hash[:a5]}#{big_hash[:a6]}"
  end
end
```

With the above, I'll be confronted with `C: Metrics/MethodLength: Method has too many lines. [11/10]` when it is [logically] only two lines of code. I would prefer if the above was instead interpreted as 2 lines, as it is easier to read than condensing into 2 lines.

## RuboCop version

```
$ rubocop -V
0.48.1 (using Parser 2.4.0.0, running on ruby 2.3.3 x86_64-linux)
```

**Comment by bbatsov** [comment]
There's no such thing as a logical line. :-) A line length check is supposed to count lines, it's as simple as that. If don't find it useful - simply disable it. 

There are other complexity metrics that you might find more useful https://rubocop.readthedocs.io/en/latest/cops_metrics/
