### ISSUE TITLE
Bump unicode-display_width to 1.2.0 breaks the default behavior of Style/PercentLiteralDelimiters

### ISSUE THREAD

**Issue by kassiansun** [bbatsov/rubocop#4256]
## Steps to reproduce the problem

Use default rubocop config
```
  rubocop -a test.rb
```

`%i(test)` will be converted to `%i[test]`

## RuboCop version

```
$ rubocop -V
0.48.1 (using Parser 2.4.0.0, running on ruby 2.4.0 x86_64-linux)
```

**Comment by Drenmi** [comment]
The defaults were changed in #4231 to reflect a change in the Style Guide. You can follow the thread over to the Style Guide to see the discussion there. 🙂

**Comment by kassiansun** [comment]
@Drenmi Thanks for the information. I forgot that `%i: []` in `default.yml` overwrites the previous `default: ()`, my mistake.
