### ISSUE TITLE
Empty Comment

### ISSUE THREAD

**Issue by matrinox** [bbatsov/rubocop#4274]
```bash
$ rubocop -V
0.48.1 (using Parser 2.4.0.0, running on ruby 2.3.1 x86_64-darwin16)
```

This is a feature suggestion for detecting empty comments
```ruby
1 class User
2   #
3   def initialize
4     ...
5   end
6 end
```

Line 2 sticks out like a sore thumb. I know some people who do it just to add an extra line after a class, a way to circumvent one of the rubocop rules: `Style/EmptyLinesAroundBody`. I know the abuse case of this is just to add a dot or something but at least that can be argued as a useless comment

**Comment by bbatsov** [comment]
Yeah, it'd be nice to deal with those.

**Comment by matrinox** [comment]
@bbatsov glad you feel the same way :)

**Comment by tejasbubane** [comment]
I am working on this.
