### ISSUE TITLE
set rubocop version in .rubocop.yml

### ISSUE THREAD

**Issue by robertlabrie** [bbatsov/rubocop#4326]
Seems like every time I upgrade rubocop, my projects are offending some new preference or other. It'd be nice if in my yml file I could say `defaults: 0.47.1` so that I can stay on the latest rubocop for fixes and features and what-have-you but not get slammed with 477 offenses because I have `%w()` instead of `%w[]`

Yes `rubocop -a` can help in those cases, but we prefer to tune the code ourselves

**Comment by bbatsov** [comment]
I understand your point but this is a feature I'm not willing to introduce as it will add a lot of extra complexity to an already complex codebase. 

I'm always advising people to go over the extremely detailed changelog before updating RuboCop.

**Comment by donv** [comment]
@robertlabrie You can limit your rubocop version in your Gemfile and run rubocop with `bundle exec rubocop`.  That will ensure a predictable version.

**Comment by pjscopeland** [comment]
Refusal notwithstanding, I'd like to see this too – I have multiple projects that all have different versions of Rubocop and it's a bit of a pain having to keep all of them so religiously up-to-date.
