### ISSUE TITLE
Idea: RubyMine started using Rubocop. But I want more visible feedback and that made my .rubocop.yml file nightmare.

### ISSUE THREAD

**Issue by ipepe** [bbatsov/rubocop#4331]
Recently I opened an Issue for JetBrains RubyMine support of Rubocop (https://youtrack.jetbrains.com/issue/RUBY-19498). I wanted all code that offences RuboCop, get marked with red underlines (syntax errors). Turns out that developers of Jetbrains hardcoded highlighting of Rubocop to it's Severities. So basically I had to add `Severity: fatal` or `Severity: error` to every Cop definition. Which has downside at the moment: had to create a ruby script that added Severity to all Cops in my 600 lines of code .rubocop.yml file and made it pretty ugly and not does not make me confident that someone in future will remeber to add that.

So I came up with idea. What do You think about adding support of Severity into AllCops rule? So that all Cops defined in a file are inheriting Seveirty from it?

If You think that might not be a bad idea. I could provide a pull request for that feature.

**Comment by bbatsov** [comment]
Seems like a very odd thing to do - severities exist for a reason and I don't think it's good to make them all `fatal`/`error`. But I also see your point. I'll leave this open for discussion for a while before we decide what to do about it.

**Comment by rrosenblum** [comment]
Based on the comments in the issue, it sound to me like they would like to be able to customize the colors of RuboCops output.

**Comment by ipepe** [comment]
Is it technically possible and reasonable to add this through extension?
