### ISSUE TITLE
Some departments don't exist in the documentation.

### ISSUE THREAD

**Issue by pocke** [bbatsov/rubocop#4335]
http://rubocop.readthedocs.io/en/latest/cops/
https://github.com/bbatsov/rubocop/blob/8c3e90466b970dfbcd4d8fe6256a0562995b9c84/manual/cops.md
In the above page, we can't find descriptions for `Layout` and `Security` departments.

My English is not good, so, could anyone add descriptions to the documentation?

**Comment by bbatsov** [comment]
This part of the manual was written manually - guess we have to update it.
