### ISSUE TITLE
Rubocop raises exception for a specific unusual but valid ruby syntax

### ISSUE THREAD

**Issue by wendelscardua** [bbatsov/rubocop#4344]
When checking the code below:
```ruby
def foobar
else
end
```
Rubocop raises an exception, while ruby only reports a warning

--------
## Expected behavior

Either some message about the warning, a message about unexpected token, or even no message at all.

## Actual behavior

Rubocop raises an exception, displaying a stacktrace.

## Steps to reproduce the problem

Create a file `test.rb` with the content below
```ruby
def foobar
else
end
```
Run rubocop:
```sh
$ rubocop test.rb
```

## RuboCop version

```sh
$ rubocop -V
0.48.1 (using Parser 2.4.0.0, running on ruby 2.2.5 x86_64-linux)
```

**Comment by backus** [comment]
I think this is an upstream error. You probably should report this to https://github.com/whitequark/parser

**Comment by wendelscardua** [comment]
@backus I've managed to reproduce on `parser 2.4.0.0`, reported it there: https://github.com/whitequark/parser/issues/345

As rubocop depends on `('parser', '>= 2.3.3.1', '< 3.0')`, any future fix from there will probably fix this issue here, so I'll close this one.
