### ISSUE TITLE
Wong --auto-correct in Style/AndOr

### ISSUE THREAD

**Issue by inyerade** [bbatsov/rubocop#4352]
I do not know if I miss something or I found a bug

## Expected behavior

    return nil unless user and user[:id]

to

    return nil unless user && user[:id]

## Actual behavior

    return nil unless user and user[:id]

to

    return nil unless user && user[:id)](

## Steps to reproduce the problem

I have the lines 

    return nil unless user and user[:id]
    {  
        status: "success",
        validation: true,
    }

And  when I run 

    rubocop --auto-correct
    
I get

    return nil unless user && user[:id)]( 
    {  
        status: "success",
        validation: true,
    }

Also rubocop detect the new error

    E: unexpected token tRPAREN
    (Using Ruby 2.1 parser; configure using TargetRubyVersion parameter, under AllCops)
            return nil unless user && user[:id)](

## RuboCop version

```
$ rubocop -V
0.48.1 (using Parser 2.4.0.0, running on ruby 2.3.1 x86_64-linux-gnu)
```

**Comment by ClayShentrup** [comment]
Assuming this is the same thing I'm experiencing:

```ruby
(a[:a] or a)
# Becomes
(a[:a)](|| a)
```
