### ISSUE TITLE
Yard docs contain deleted class?

### ISSUE THREAD

**Issue by vergenzt** [bbatsov/rubocop#4360]
I was browsing the [Yard docs](http://www.rubydoc.info/github/bbatsov/rubocop/Rubocop) and stumbled upon a class that shows up in the docs but no longer exists in the codebase: [`Rubocop::SourceParser`](http://www.rubydoc.info/github/bbatsov/rubocop/Rubocop/SourceParser). (It was deleted in 1315aac.)

The page says at the bottom:
> Generated on Mon May 8 22:59:22 2017 by yard 0.9.8 (ruby-2.3.1).

Any idea why that class is still getting included?

---

![image](https://cloud.githubusercontent.com/assets/1725615/25833924/87c4a446-3429-11e7-9b92-b0e1efa9e132.png)

**Comment by Drenmi** [comment]
If you check the `Version` class, it says the version constant is `'0.20.1'`, so despite being generated today, it probably generates from an old release. 🤔

**Comment by Drenmi** [comment]
Any idea how this works (or doesn't work?) @bbatsov

**Comment by backus** [comment]
I don't know *why* it works this way, but if you search `rubocop` after selecting "github" in the rubydoc homepage then you get two results:

![image](https://cloud.githubusercontent.com/assets/2085622/26045959/9922c4e8-3901-11e7-9018-a6f6a0289439.png)

There is an entry for [`RuboCop`](http://www.rubydoc.info/github/bbatsov/RuboCop) and an entry for [`rubocop`](http://www.rubydoc.info/github/bbatsov/rubocop) (uppercase vs. lowercase).

The uppercase one is up to date.

Most people should be using the gems version anyways: http://www.rubydoc.info/gems/rubocop

**Comment by bbatsov** [comment]
No idea. Don't recall anything doing something with respect to RubyDoc.

**Comment by Drenmi** [comment]
I've opened [an issue](https://rubydoc.tenderapp.com/discussions/problems/524-duplicate-entries-for-rubocop-one-which-is-severely-outdated) asking to remove the outdated duplicate. I think that's as much as we can do about this right now. 🙂

**Comment by bbatsov** [comment]
Thanks! Guess we can close this issue then.
