### ISSUE TITLE
Misleading message for incorrect negative number syntax

### ISSUE THREAD

**Issue by obromios** [bbatsov/rubocop#4382]
If I have an rspec line like
`it{ expect(p_bias).to eq -1.01 }`
the code works, but I get a rubocop warning
`put parentheses or a space even after '-' operator`
However if I change it, as instructed by puttin in a space, I get an exception
`wrong number of arguments (0 for 1)`

 I can see in many circumstances adding the space will work fine e.g.
`it{ expect(p_bias).to eq(- 1.01) }`
but there will be cases where it does not work.  Is there a better warning that does not cause the user to make a change that can create an exception?

## Steps to reproduce the problem

I think this should work with any rspec set up, just try a line like I am showing there.

## RuboCop version

`0.32.1 (using Parser 2.3.3.1, running on ruby 2.2.2 x86_64-darwin14)`

**Comment by Drenmi** [comment]
Your RuboCop is quite outdated. Current version is `0.48.1`, and this is the message displayed if you run that version:

> Ambiguous negative number operator. Parenthesize the method arguments if it's surely a negative number operator, or add a whitespace to the right of the - if it should be a subtraction.

Do you think this message is better? Or would you like to add some additional clarification? 🙂

**Comment by obromios** [comment]
The message is clear, the only problem is that in certain cases, following the recommendation in the message can cause an exception.  The example I gave where this happens is  
`it{ expect(p_bias).to eq -1.01 }`

The original form of the ```eq``` operator was  ```eq(<argument>)``` but an optional form is ```eq <argument>```.  If you are using the parentheses form then the rubocop suggestion works. Many operators in ruby on rails offer the option to omit the parentheses.  Do you think this problem is a specific one to the rspec implementation of  ```eq <argument>``` i.e. it is a rspec bug, or is common to all operators with this optional, parentheses-less syntax?

**Comment by obromios** [comment]
Sorry, just reread the new message carefully, and that it now is clear to me.
