### ISSUE TITLE
No idea how to override excludes from inherited yaml

### ISSUE THREAD

**Issue by obfuscoder** [bbatsov/rubocop#4387]
I have a project where I have a root directory with a .rubocop.yml defining specific rules to be applied to all files and folders except one particular folder which shall not be checked. So I put this folder in the exclude list:

```
AllCops:
  Exclude:
    - 'subproject/**/*'
...
```

In that subproject I have another .rubocop.yml which inherits the rules from that parent file and in addition defines other rules or overrides some of the parent. These rules shall be applied to all files within the subproject when run rubocop from within that directory.

The problem is: when running rubocop inside of the subproject directory, none of the files are picked up by rubocop as the exclude filter from the parent config file still applies. Adding the files in the include list of the subproject config does not fix this. Neither does defining a different Exlude in the subproject config file:

/subproject/.rubocop.yml
```
inherit_from: ../.rubocop.yml
AllCops:
  Exclude:
    - 'db/**/*'
...
```
According to the documentation, the exclude definition of the subproject config should override the excludes defined by the inherited config.

I tried to extract the common ruleset into */.rubocop-rules.yml* and let */.rubocop.yml* and */subproject/.rubocop.yml* inherit from this file while solely defining the exclude in the */.rubocop.yml*. It turns out that the files within subproject are still not picked up by rubocop when run within the subproject folder. Somehow the exclude filter of the config file of the parent directory is still being applied:

/.rubocop-rules.yml:
```
AllCops:
  TargetRubyVersion: 1.9
...
```
/.rubocop.yml:
```
inherit_from: .rubocop-rules.yml

AllCops:
  Exclude:
    - 'subproject/**/*'
```

/subproject/.rubocop.yml:
```
inherit_from: ../.rubocop-rules.yml
...
```

Result:
```
~/subproject/# rubocop
Inspecting 0 files

0 files inspected, no offenses detected
```

As soon as I remove the exclude from the /.rubocop.yml, the files in the subproject are picked up when running rubocop within the subproject folder as well as when run within the root folder of the project.

**Comment by jonas054** [comment]
I cannot reproduce the problem. Please run with `rubocop -d` and show us the output.

**Comment by obfuscoder** [comment]
I created a demo repository here: https://github.com/obfuscoder/rubocop-issue

The output of rubocop -d from within the subproject is:

```
For /home/<user>/rubocop-issue/subproject: configuration from /home/<user>/rubocop-issue/subproject/.rubocop.yml
Inheriting configuration from /home/<user>/rubocop-issue/.rubocop.yml
Default configuration from /home/<user>/.rvm/gems/ruby-2.4.1/gems/rubocop-0.49.1/config/default.yml
Inheriting configuration from /home/<user>/.rvm/gems/ruby-2.4.1/gems/rubocop-0.49.1/config/enabled.yml
Inheriting configuration from /home/<user>/.rvm/gems/ruby-2.4.1/gems/rubocop-0.49.1/config/disabled.yml
AllCops/Exclude configuration from /home/<user>/rubocop-issue/.rubocop.yml
Inspecting 0 files


0 files inspected, no offenses detected
Finished in 0.028619242999411654 seconds
```

I was expecting that the AllCops/Exclude config from the base .rubocop.yml was not applied as the subprojects rubocop.yml does overwrite this setting. So I was expecting the t.rb file within the subproject to be picked up and checked by rubocop.

**Comment by jonas054** [comment]
I think #4329 addresses your concern, but nothing has happened in that PR for a while.

**Comment by obfuscoder** [comment]
That looks exactly like it could help me. Maybe I can try to get the change done which you requested?

**Comment by jonas054** [comment]
Yes! I think the easiest way is to copy the code from that PR, and finish the job in a new PR. I've "pinged" the author in the other PR in case he wants to finish the job.

**Comment by inner-whisper** [comment]
Some investigation of problem discussed here - https://gitlab.com/gitlab-org/gitlab-development-kit/issues/271#note_38360820

As I can understand, `RuboCop::ConfigLoader.configuration_from_file` merges excludes from current project `.rubocop.yml` and possible higher level `.rubocop.yml` in your path.

Example of fix:

```
➜  gitlab git:(24121_extract_yet_another_users_finder) pwd
/Users/rydkinmaxim/rails_projects/gitlab-development-kit/gitlab
➜  gitlab git:(24121_extract_yet_another_users_finder) bundle exec rubocop --only Metrics/AbcSize
Inspecting 0 files
0 files inspected, no offenses detected
➜  gitlab git:(24121_extract_yet_another_users_finder) touch /Users/rydkinmaxim/rails_projects/.rubocop.yml
➜  gitlab git:(24121_extract_yet_another_users_finder) bundle exec rubocop --only Metrics/AbcSize
Inspecting 4955 files
....................................................................................................................................................................................................^C
Exiting... Interrupt again to exit immediately.
.
197 files inspected, no offenses detected
➜  gitlab git:(24121_extract_yet_another_users_finder)
```

In what cases we need to merge excludes from current directory `.rubocop.yml` and parent's one?

**Comment by jonas054** [comment]
> In what cases we need to merge excludes from current directory .rubocop.yml and parent's one?

Maybe never. The original idea was that
1. You exclude something in the project root directory's `.rubocop.yml`. The excluded directories might have their own `.rubocop.yml` files (where they don't exclude themselves), but we want "our" configuration file to decide what gets excluded.
2. The behavior should be the same regardless of current directory.

The second objective is probably not important. We can scratch it. Then we don't need a special command line option. We just avoid loading `Exclude` configuration from a `.rubocop.yml` *above* the current directory.

**Comment by obfuscoder** [comment]
I also top for not having a specific command line option to tunr of inheriting excludes. I'd rather have excludes not inherited if there are excludes specified in the yaml of the subdirectory.

Inheriting excludes (as long as there are no excludes specified in the yaml of the subdirectory) does make sense as long as specific file patterns are defined (e.g. **/*.rbx). Apart from that, I also don't see a reason why this would make sense.

**Comment by jonas054** [comment]
@obfuscoder It makes more sense to me if the condition is that you do not implicitly inherit `Exclude`s from a file in a directory above the current one. Let's say a project excludes `vendor/**/*`, which is done by default. If a user goes to a subdirectory of `vendor` and runs `rubocop`, I'd prefer it to inspect the files there whether there is a local `.rubocop.yml` or not.

**Comment by obfuscoder** [comment]
@jonas054 Uhm, I'd say this sounds about right to me too. Running rubocop from within a subfolder which is excluded in any .rubocop.yml up the directory tree it should not still include this directory as rubocop is per default running the checks for all files in cwd and all subfolders. Otherwise running rubocop there wouldn't make sense at all.

**Comment by Drenmi** [comment]
> Did #4329 resolve this?

Feel free to reopen if it didn't.
