### ISSUE TITLE
Autocorrect of Style/InverseMethods breaks double negatives

### ISSUE THREAD

**Issue by capripot** [bbatsov/rubocop#4393]
Autocorrect of Style/InverseMethods breaks double negatives for at least regexp checks as following.

--------
## Given code

`!!(string =~ /^\w+$/)`

## Expected behavior

`!!(string =~ /^\w+$/)`

## Actual behavior

`!string !~ /^\w+$/`

## Steps to reproduce the problem

`rubocop -a` on files containing the given code

## RuboCop version

```
$ rubocop -V
0.48.1 (using Parser 2.4.0.0, running on ruby 2.2.7 x86_64-darwin16)
```

**Comment by rrosenblum** [comment]
It seems like it should be easy enough to ignore double negation.
