### ISSUE TITLE
YodaCondition cop crashes autocorrect

### ISSUE THREAD

**Issue by ihatemornings** [bbatsov/rubocop#4428]
The `YodaCondition` cop includes `:!` in its list of operators to check, but it also expects the operator to have two operands. If the operand is not in the cop's whitelist of node types, it makes a false arrest. Here's an example that triggers the bug:

```
!a.find { |x| x }
```

--------

## Expected behavior

The `YodaCondition` cop should ignore this statement because it doesn't have two operands.

## Actual behavior

- It wrongly displays the "reverse the order of the operands" message.
- Autocorrect crashes with `undefined method 'source' for nil:NilClass` when it tries to swap the operands.

## Steps to reproduce the problem

Save a file containing:
```
!a.find { |x| x }
```

Run Rubocop with and without autocorrect.

## RuboCop version

```
$ rubocop -V
0.49.0 (using Parser 2.4.0.0, running on ruby 2.2.2 x86_64-darwin14)
```

**Comment by bbatsov** [comment]
Is this a problem in `master`?

**Comment by smakagon** [comment]
Nope, your commit https://github.com/bbatsov/rubocop/commit/5700720cb92521e3a673e91ba517cc7884822826 fixed that case as well. No offense in master.

**Comment by ihatemornings** [comment]
Cool! Thanks for the update. I checked open issues but missed the recent `master` commit.
