### ISSUE TITLE
YodaCondition complains regardless of order of comparison

### ISSUE THREAD

**Issue by jnardone** [bbatsov/rubocop#4430]
C: Style/YodaCondition: Reverse the order of the operands pushtype&.to_sym == :SPAN.
      opts[:properties] = { pushType: :SPAN } if pushtype&.to_sym == :SPAN
                                                 
C: Style/YodaCondition: Reverse the order of the operands :SPAN == pushtype&.to_sym.
      opts[:properties] = { pushType: :SPAN } if :SPAN == pushtype&.to_sym

It's complaining about the comparison at the end in both cases.

**Comment by jnardone** [comment]
sorry, this might be a dup of https://github.com/bbatsov/rubocop/issues/4426

**Comment by bbatsov** [comment]
That's fixed on `master`.
