### ISSUE TITLE
Lint/AssignmentInCondition warning message is confusing

### ISSUE THREAD

**Issue by brandonweiss** [bbatsov/rubocop#4470]
The `Lint/AssignmentInCondition` warning message is `"Assignment in condition - you probably meant to use =="`.

This doesn't do a great job of explaining what the problem is—it just asserts something which may or may not be true. This cop also has an `AllowSafeAssignment` option that is set to `true` by default, but the warning message doesn't take that into account, leading someone to erroneously believe that the solution is to not assign in the condition, rather than wrapping the expression in parentheses.

**Comment by bbatsov** [comment]
I think we just copied the text of the warning you'd normally get from Ruby. There's certainly some room for improvement.

**Comment by brandonweiss** [comment]
👍 I'll have a go at an improvement.
