### ISSUE TITLE
Layout/MultilineMethodCallIndentation affected by inline private keyword

### ISSUE THREAD

**Issue by patrick-gleeson** [bbatsov/rubocop#4476]
Using 0.49.1, rubocop will complain about indentation of a multi-line method call inside a method if the method declaration starts `private def ...` but not if it starts `def ...`

## Expected behavior

```ruby
class FooBar
  def foo
    this_method.chain
               .should_be
               .allowed(:by)
               .rubocop
  end

  private def bar
    this_method.chain
               .should_be
               .allowed(:by)
               .rubocop
  end
end
```
One might reasonably expect that if the top method's internal indentation is permitted, the bottom one's would be too.
## Actual behavior
Output of rubocop:
```
test.rb:11:16: C: Layout/MultilineMethodCallIndentation: Use 2 (not 11) spaces for indenting an expression spanning multiple lines.
               .should_be
               ^^^^^^^^^^
```
Note that there's another twist - if you replace `.allowed(:by)` with `.allowed_by` in the above example, rubocop stops complaining as well!

## Steps to reproduce the problem
Copy the above code into a file called test.rb. Run `rubocop -D`

## RuboCop version

```
$ rubocop -V
0.49.1 (using Parser 2.4.0.0, running on ruby 2.3.1 x86_64-darwin16)
```

**Comment by jnardone** [comment]
I wonder if this is the trigger for #4431 (the method is a `private_class_method` in that bug)

**Comment by Drenmi** [comment]
@jnardone: You are correct. Closing this as a duplicate. Please follow #4431 for updates.

**Comment by patrick-gleeson** [comment]
Well spotted @jnardone!
