### ISSUE TITLE
Performance/Caller: Clearer message

### ISSUE THREAD

**Issue by koppen** [bbatsov/rubocop#4478]
I have the following line of code

    caller[0][/`.*'/]

which RuboCop 0.49.1 flags with

    caller.rb:5:11: C: Performance/Caller: Use caller(n..n) instead of caller[n].
        caller[0][/`.*'/]

Looking at the suggested solution I'd expect to change the code to

    caller(0..0)[/`.*'/]

but that isn't feature equivalent because

    caller[0] #=> "caller.rb:13:in `<main>'"
    caller(0..0) #=> ["caller.rb:9:in `modified'"]

`caller(0..0)` not only returns an `Array` instead of a `String`, but even if we use the first item in the returned `Array` we get a different result. In short; the default message is confusing and potentially misleading (at least to me).

## Expected behavior

I'd expect RuboCop to guide me to a correct solution, or not at all. The pipe dream is

> Use caller(1..1).first instead of caller[0].

but that's a bit specific to my concrete case, I reckon. Perhaps we could settle for:

> Use caller(n..n).first instead of caller[n].

but that might hide the changed behavior too much. More precisely:

> Use caller((n + 1)..(n + 1)).first instead of caller[n].

but that's hardly concise or easily understandable. How about some form of

> Use arguments with caller instead of returning the full array

¯\\\_(ツ)_/¯

There is some discussion ongoing on the now closed pull request as well: https://github.com/bbatsov/rubocop/pull/4078

## Actual behavior

RuboCop suggest

> Use caller(n..n) instead of caller[n].

## Steps to reproduce the problem

1. Create a file containing `caller[0]`
2. Run RuboCop on it

## RuboCop version

    $ rubocop -v
    0.49.1

**Comment by pocke** [comment]
Thanks for the reporting! 👍 
I'll work it.

**Comment by sleekweasel** [comment]
Isn't this rather the tail wagging the dog? Surely Ruby should be preening its parse tree to optimise this sort of nonsense invisibly - not developers forced to waste brain cells creating increasingly unreadable code.

In any case, when is caller called in time-critical situations? This is like the time someone optimised an RPC call failure mode by microseconds, ignoring that the network call was going to take milliseconds anyway.

**Comment by ianfixes** [comment]
For those of you arriving via a google search as to what this cryptic message could possibly mean (and why this bizarre syntax is "preferable"), the answer seems to be along these lines:

```ruby
# bad
caller[0] # extracts only one element after receiving an enormous array 

# good
caller(0..0).first # extracts only one element after receiving a single-element array
```

I hope the array size is actually something to be concerned about here, because this is a very odd edit for a _style_ checker to suggest.

**Comment by sleekweasel** [comment]
```ruby
# bad
caller[0] # extracts only one element after receiving an enormous array 
```

Since when has passing a huge or tiny array involved anything more than passing a pointer to something, in any language whatsoever? Much as I hate Ruby, I don't believe it's so stupid to copy an entire array.

**Comment by ianfixes** [comment]
You're right, I'm going to update that comment
