### ISSUE TITLE
Style/SymbolArray auto-correct creating invalid syntax

### ISSUE THREAD

**Issue by bbugh** [bbatsov/rubocop#4481]
This seems to be more of surprising behavior with the Ruby parser than Rubocop, but nonetheless it is still creating errors.

```
# original, valid syntax, pre-Rubocop
prepend_before_filter only: [ :create, :destroy ] { request.env["devise.skip_timeout"] = true }

# invalid (Ruby 2.2.4) syntax created by Rubocop
prepend_before_filter only: %i[create destroy] { request.env["devise.skip_timeout"] = true }
```

The Ruby error:

```
app/controllers/users/sessions_controller.rb:4: syntax error, unexpected '{', expecting keyword_end
...tion only: %i[create destroy] { request.env['devise.skip_tim...
...                               ^
app/controllers/users/sessions_controller.rb:4: syntax error, unexpected '}', expecting keyword_end
```

--------

## Expected behavior

When running `rubocop -a`, it produces valid Ruby syntax.

## Actual behavior

It creates invalid syntax.

## Steps to reproduce the problem

1. Given a file:
    ```ruby
    # thing.rb
    class Thing
      do_anything only: [:word, :two] { 5 }
    end
    ```

2. When you run Rubocop with auto-correct `rubocop -a thing.rb`

3. It produces an error:
  ```
  Inspecting 1 file
  E

  Offenses:

  thing.rb:2:21: C: [Corrected] Use %i or %I for an array of symbols.
    do_anything only: [:word, :two] { 5 }
                      ^^^^^^^^^^^^^
  thing.rb:2:34: E: unexpected token tLCURLY
  (Using Ruby 2.1 parser; configure using TargetRubyVersion parameter, under AllCops)
    do_anything only: %i[word two] { 5 }
                                   ^

  1 file inspected, 2 offenses detected, 1 offense corrected
  ```

## RuboCop version

`0.48.1 (using Parser 2.4.0.0, running on ruby 2.2.4 x86_64-darwin16)`

**Comment by Drenmi** [comment]
Interesting. Looks like `parser` follows MRI and throws a parsing error as well. Good catch!

**Comment by pocke** [comment]
The above code has same problem...


```ruby
# not error
foo [:foo, :bar] { something }

# Syntax error
foo %i[foo bar] { something }
```

Ref:

- https://bacon-cannon.herokuapp.com/parmlinks/b3c1ffc5-347a-4389-8c62-87e0649df628
- https://bacon-cannon.herokuapp.com/parmlinks/a3f72d53-4764-4c33-8cea-46cb4bda421c

**Comment by Drenmi** [comment]
As a note, I have opened an [upstream issue for this](https://bugs.ruby-lang.org/issues/13691) in Redmine.
