### ISSUE TITLE
New return nil cop

### ISSUE THREAD

**Issue by Ana06** [bbatsov/rubocop#4508]
`return` and `return nil` are the same thing, so `return nil` should be avoided. A new cop to check this would be great! :wink:

**Comment by rrosenblum** [comment]
This cop should be configurable to support the implicit `nil` (`return`) and the explicit `nil` (`return nil`).

**Comment by danielkman** [comment]
Hey, I'd like to try and submit a PR for it

**Comment by pocke** [comment]
https://github.com/bbatsov/rubocop/pull/4638
@danielkman Thanks, but a pull-request for this issue is already opened.

**Comment by bbatsov** [comment]
> return and return nil are the same thing, so return nil should be avoided. A new cop to check this would be great! 

I can see why some people would want to make this uniform, but I for instance always use `return` when I just want to get out from some place in a method (meaning the return is in void context and no one cares about it) and `return nil` if I actually want to explicitly return `nil`.
