### ISSUE TITLE
Cop for detecting use of Kernel.open and IO.read methods

### ISSUE THREAD

**Issue by jobertabma** [bbatsov/rubocop#4516]
RuboCop currently contains four cops for potential security vulnerabilities, `eval`, `Marshal.load`, `JSON.restore`, and `YAML.load`. It does not contain a cop for the use of `Kernel.open` or `IO.read`. These methods can be used for multiple purposes: reading a file, a stream, executing commands, or reading URLs in combination with `open-uri`. This can be very convenient, but using this method is often an indicator of bad design. Passing user input directly to these methods may lead to arbitrary command execution on the system.

https://ruby-doc.org/core-2.4.1/Kernel.html#method-i-open
https://ruby-doc.org/core-2.4.1/IO.html#method-c-read

My proposal is to start marking the use of `Kernel.open` and `IO.read` as an offense and give tips how to use other, safer, methods, such as `File.open`, `Net::HTTP`, `IO.popen`.

Thoughts? Reasons not to do this? Would it result in too many false-positives?

**Comment by mikegee** [comment]
I think this is a great suggestion, but I'm concerned about the false positives too. Especially `IO.read` (frequently written as `File.read`).

Can we really determine if something is user input? I suspect we can only distinguish between literal values and variables.

**Comment by jobertabma** [comment]
> Can we really determine if something is user input? I suspect we can only distinguish between literal values and variables.

No, I believe you're correct that it's limited to (static) values and variables. Even though it'd be great to have these offenses, I don't think it's possible right now. Perhaps this would be a better addition to `brakeman` or the like. If this comes up again this can be reopened. Thanks for your comment @mikegee!

**Comment by jobertabma** [comment]
I just noticed this: https://github.com/bbatsov/rubocop/pull/5319 introduced a cop for `Kernel.open`. Thanks @mame!

🎊
