### ISSUE TITLE
Should there be a `Naming` namespace?

### ISSUE THREAD

**Issue by Drenmi** [bbatsov/rubocop#4521]
I liked the separation of `Layout` from `Style`. It makes it easier to get an overview of the cops and their jurisdictions, and it also helps prevent the creation of cops that check too many things.

In that spirit, I was wondering if we should also split out `Naming`, which seems to have about as many cops as `Layout` does.

WDYT?

**Comment by bbatsov** [comment]
I'm not opposed to the idea.

**Comment by chrisnicola** [comment]
It would be awesome if changes like this had some kind of support in an upgrade tool. I'm finding every update of Rubocop involves a lot of housework afterwards.

**Comment by chrisnicola** [comment]
Sorry ignore my comment above. The changes were smaller than I had realized. For some reason during the execution of `--auto-gen-config` it showed dozens of errors related to this. Rerunning it normally only reported 3 changes.
