### ISSUE TITLE
Rubocop autocorrect changes code behavior

### ISSUE THREAD

**Issue by jomei** [bbatsov/rubocop#4538]
In my project I have legacy code like this:
```ruby
def before(str)
  !!(str =~ /DUP(?:LICAT)?E?D?(\s|\z)/)
end
```
I ran `rubocop -a` on this code, and I got this:

```ruby
def after(str)
  !str !~ /DUP(?:LICAT)?E?D?(\s|\z)/
end
```

`str` argument examples:

```
"ADTK1GTOUT BY 21JUN 1550Z OTHERWISE WILL BE CANCELLED"
"ADTK1GTOTK BY 22JUN 1348 IRC-2/ADV OTO TKT"
"PLS ADV FQTV NUMBER IF AVAILABLE WITH SSR FORMAT"
"PLS ADV PSGR MOBILE AND/OR EMAIL AS SSR CTCM/CTCE"
```

## Expected behavior
Code before and after autocorrect should works the same

## Actual behavior

It's not

## RuboCop version

Include the output of `rubocop -V`. Here's an example:

```
$ rubocop -V
0.48.1 (using Parser 2.4.0.0, running on ruby 2.3.4 x86_64-darwin16)
```

**Comment by Drenmi** [comment]
I can not reproduce this on `master`. Can you try upgrading to the latest RuboCop version (0.49.1) and see if this persists?
