### ISSUE TITLE
Style/TernaryParentheses detect offense but If I correct the code return other result

### ISSUE THREAD

**Issue by inyerade** [bbatsov/rubocop#4545]
Hi

## Expected behavior

I expect to not trigger Style/TernaryParentheses

## Actual behavior

I have this line

    email = ( [  "/" , "?" ].include? info_user["e_mail"] ) ? "" : info_user["e_mail"].strip

and I get the email or empty string like I want , but rubocop trigger Style/TernaryParentheses

If I delete the parentheses  I get `true` or `false` 

## Steps to reproduce the problem

Check output of:

    ( [  "/" , "?" ].include? "e_mail"  ) ? "" : "e_mail".strip

and

    [  "/" , "?" ].include? "e_mail" ? "" : "e_mail".strip

## RuboCop version

0.48.1 (using Parser 2.4.0.0, running on ruby 2.3.1 x86_64-linux-gnu)

**Comment by inyerade** [comment]
My error in the code :disappointed:  

    [  "/" , "?" ].include? [ "e_mail" ] 

do not work like I want.

**Comment by Drenmi** [comment]
Likely a duplicate of #4460. 🙂

**Comment by inyerade** [comment]
Yes, only search in google :disappointed:. Sorry
