### ISSUE TITLE
Autocorrect messes up heredocs with <<~

### ISSUE THREAD

**Issue by cbothner** [bbatsov/rubocop#4572]
Rubocop autocorrect doesn’t seem to understand the `<<~` heredoc syntax. It separates the operator into `<< ~` and unindents the following text.

--------

## Expected behavior

I expect this not to change

```ruby
    scope :interesting, -> { joins(:user).where <<~SQL }
      readers.id NOT IN
        (SELECT reader_id
           FROM readers_roles
                JOIN roles ON role_id = roles.id
          WHERE roles.name = 'invisible')
      SQL
```

## Actual behavior

It changes to this:

```ruby
    scope :interesting, -> { joins(:user).where << ~SQL }
    readers.id NOT IN
    (SELECT reader_id
     FROM readers_roles
     JOIN roles ON role_id = roles.id
     WHERE roles.name = 'invisible')
    SQL
```

## Steps to reproduce the problem

Try it out. I’m using the latest version.

## RuboCop version

Include the output of `rubocop -V`. Here's an example:

```
$ rubocop -V
0.49.1 (using Parser 2.4.0.0, running on ruby 2.3.1 x86_64-darwin16)
```

**Comment by pocke** [comment]
`<<~` is added since Ruby 2.3. So, `TargetRubyVersion` settings is needed in `.rubocop.yml` to use `<<~` style heredoc.

```yaml
AllCops:
  TargetRubyVersion: 2.3
```

Could you try configuring it?

**Comment by cbothner** [comment]
That does fix it. Sorry that I didn’t read the docs closely enough!

**Comment by cbothner** [comment]
Although, per https://github.com/bbatsov/rubocop/blob/master/manual/configuration.md#setting-the-target-ruby-version it seems it should be able to detect this from `.ruby-version`. I did have that file present, containing `2.3.1`. Does this not climb the tree to project root?

**Comment by Drenmi** [comment]
Hm. In earlier (pre-2.3) parsers, this is likely interpreted as:

```
(send ... :<<
  (send
    (const nil :SQL) :~))
```

That is, unary method `#~` sent to constant `SQL`, as an argument to method `#<<`.
