### ISSUE TITLE
is Style/not enabled by default?

### ISSUE THREAD

**Issue by Ana06** [bbatsov/rubocop#4590]
In it is said that `Style/Not` is enabled by default, but it doesn't appear in the [current Rubocop default configuration file](https://github.com/bbatsov/rubocop/blob/master/config/default.yml). Is that correct? I thought that everything is not in the default configuration file is disabled unless you enable it for your project. :thinking:

**Comment by pocke** [comment]
> In it is said that Style/Not is enabled by default, but it doesn't appear in the current Rubocop default configuration file. Is that correct?

Yes, it's correct. 
`config/default.yml` inherits `config/enabled.yml` and `config/disabled.yml`. And `Style/Not` exists in `config/enabled.yml`.

`config/default.yml` only has cops that have configuration.

**Comment by Drenmi** [comment]
The `.default.yml` holds all configuration for both enabled and disabled cops. Whether they are disabled or not out of the box is determined by whether they are in `.enabled.yml` or `.disabled.yml`.

**Comment by Ana06** [comment]
ok, thanks! I'll close the issue then :slightly_smiling_face:
