### ISSUE TITLE
Performance/RegexpMatch: can't recognize use of MatchData via named capture

### ISSUE THREAD

**Issue by uasi** [bbatsov/rubocop#4617]
RuboCop says `MatchData` isn't used in the code below, which is false.

```ruby
def f
  return unless /(?<foo>.)/ =~ 'x'
  puts foo
end
```

--------

## Expected behavior

No offences reported.

## Actual behavior

RuboCop reports `Use match? instead of =~ when MatchData is not used.`

## Steps to reproduce the problem

test.rb

```ruby
def f
  return unless /(?<foo>.)/ =~ 'x'
  puts foo
end
```

.rubocop.yml

```yml
AllCops:
  TargetRubyVersion: 2.4
```

```
$ rubocop --only RegexpMatch --cache false test.rb
Inspecting 1 file
C

Offenses:

test.rb:2:17: C: Use match? instead of =~ when MatchData is not used.
  return unless /(?<foo>.)/ =~ 'x'
                ^^^^^^^^^^^^^^^^^^

1 file inspected, 1 offense detected
```

## RuboCop version

```
$ rubocop -V
0.49.1 (using Parser 2.4.0.0, running on ruby 2.4.1 x86_64-darwin16)
```

**Comment by pocke** [comment]
Duplicate https://github.com/bbatsov/rubocop/issues/4270 

And this problem is fixed in master. See https://github.com/bbatsov/rubocop/pull/4531 .
