### ISSUE TITLE
Examples for Performance/RedundantMatch don't match docs

### ISSUE THREAD

**Issue by timurb** [bbatsov/rubocop#4641]
I'm referring to this description of `Performance/RedundantMatch`: http://rubocop.readthedocs.io/en/latest/cops_performance/#performanceredundantmatch

Docs say that `=~` should be used instead of `match` (autocorrection works the same way).
Examples refer `match` both in good and bad examples and don't say anything about `=~` at all.

**Comment by pocke** [comment]
The documentation describes correct `match` usage only. I think we should add examples for `=~` usage into good examples.

**Comment by Drenmi** [comment]
Would you like to make a PR @timurb? 🙂

**Comment by timurb** [comment]
I'd do that but I myself don't understand why `=~` is considered better than `match()`. 
I've always been finding it confusing and using `match()` — that's actually why I glanced into the docs to find the issue :-P

**Comment by Drenmi** [comment]
@timurb: Using `#match` will create a `MatchData` object in memory, which is less performant than `#=~`, which just returns `true` or `false`. 🙂 The cop documentation doesn't necessarily explain the *why*, although it's nice to have in there.
