### ISSUE TITLE
Rule for "symbols as keys"?

### ISSUE THREAD

**Issue by spiffytech** [bbatsov/rubocop#4650]
Is there a rule for [forcing hash keys to be symbols](https://github.com/bbatsov/ruby-style-guide#symbols-as-keys)?

**Comment by mikegee** [comment]
I don't think so. `{ 'foo' => 'bar' }` raises no offenses and I don't see a cop in [`config/disabled.yml`](https://github.com/bbatsov/rubocop/blob/master/config/disabled.yml) that would enforce that rule.

**Comment by spiffytech** [comment]
Can it please be added? I'd like to enforce a uniform hash syntax.

**Comment by backus** [comment]
Sort of an odd cop to add since string and symbol keys are semantically different. Similar to adding a cop that enforces only integers for numbers

**Comment by spiffytech** [comment]
It doesn't seem strange to me, especially if the community style guide is comfortable declaring symbols to be the recommended practice.

At my company strings vs symbols aren't applied with different semantics in mind. Instead we have a lot of folks unfamiliar with Ruby idioms who jump in and out of various codebases, bringing over their idioms from other languages. I'd like the linter to tell people, "here's the community's recommended practice, please use it".

**Comment by backus** [comment]
Sure that makes sense then as a disable by default cop. Just chiming in since there have been issues opened in the past that just didn't understand the difference
