### ISSUE TITLE
Cop suggestion: CommentedEnd

### ISSUE THREAD

**Issue by deivid-rodriguez** [bbatsov/rubocop#4663]
I find this code frequently:

```ruby
class MyClassName
  # stuff
end # MyClassName
```

It'd be nice to have a cop to prevent comments right after the `end` keyword. The only use case I can think of (pointing out which block the `end` is closing) usually means that the block is too long or it has too much nesting.

**Comment by Drenmi** [comment]
I'm not against it. 🙂
