### ISSUE TITLE
New cop idea: enforce `# rubocop:enable cop` after `# rubocop:disable cop` 

### ISSUE THREAD

**Issue by tdeo** [bbatsov/rubocop#4674]
Hi,

I'd like to suggest a cop that enforces to find a matching `# rubocop:enable` statement after a non-inline `# rubocop:disable`. If the enable statement is not present, people might be writing some code further in the file not covered by some cops without being aware of it.

Let me know how it sounds, I can give a shot at a PR.

**Comment by Drenmi** [comment]
Makes sense to me. PR welcome. 🙂
