### ISSUE TITLE
Error: obsolete parameter AlignWith (for Lint/EndAlignment) 

### ISSUE THREAD

**Issue by asyaasha** [bbatsov/rubocop#4678]
Keep getting this error while using with travis CI and can't figure out why. There are no AlignWith parameter in actual rubocop file. Will appreciate any tips. The error and a copy of rubocop.yml file is below. Hope this is the right place to ask it. Thank you. 
\\
Error: obsolete parameter AlignWith (for Lint/EndAlignment) found in /home/travis/build/firehosefirechess/chess_app/vendor/bundle/ruby/2.4.0/gems/rake-12.0.0/.rubocop.yml
`AlignWith` has been renamed to `EnforcedStyleAlignWith`
\\
inherit_from: .rubocop_todo.yml 
require: rubocop-rspec
Documentation:
  Enabled: false
EndOfLine:
  Enabled: false
AllCops:
  Include:
    - '**/Rakefile'
    - '**/config.ru'
    - '**/Gemfile'
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - !ruby/regexp /old_and_unused\.rb$/
    
Lint/EndAlignment:
  EnforcedStyleAlignWith: variable

Style/Encoding:
  Enabled: false

Metrics/LineLength:
  Max: 99

Metrics/BlockLength:
  Enabled: false

UnusedBlockArgument:
  Description: 'Checks for unused block arguments.'
  Enabled: false
 
Style/EmptyLines:
  Enabled: false
  
Style/TrailingBlankLines:
  Enabled: false

**Comment by jonas054** [comment]
The `AllCops: Exclude` you have in your `.rubocop.yml` overrides the default value of this configuration parameter. For this reason, the `vendor` directory is not excluded from the inspection (which it is with default configuration). Add
```yaml
  - 'vendor/**/*'
```
to the `Exclude` list.

**Comment by Drenmi** [comment]
Note that the latest `rake` has fixed this, so updating your dependencies will also solve this. 🙂
