### ISSUE TITLE
Autocorrect of Style/LambdaCall buggy

### ISSUE THREAD

**Issue by felixyz** [bbatsov/rubocop#4691]
In some cases autocorrecting Style/LambdaCall *to enforce `braces`* results in unparseable code.

I realize enforcing braces (`.()` rather than `.call`) is the opposite of Rubocop's defaults but it's what I prefer.

--------

## Expected behavior

autocorrected to:

```Ruby
form.(input)
form.(arg1, arg2)
my_proc.() unless condition?
my_proc.()[:key]
my_proc.() do |item|
  # ...
end
```

## Actual behavior

autocorrected to:

```Ruby
form. input
form. arg1, arg2
my_proc. unless condition?
my_proc.[:key]
my_proc. do |item|
  # ...
end
```

## Steps to reproduce the problem

Place this in a file (`test.rb`):

```Ruby
form.call input
form.call arg1, arg2
my_proc.call unless condition?
my_proc.call[:key]
my_proc.call do |item|
  # ...
end
```

And autocorrect with:

`rubocop -a --only Style/LambdaCall test.rb`

## RuboCop version

```
$ bundle exec rubocop -V
0.49.1 (using Parser 2.4.0.0, running on ruby 2.4.1 x86_64-darwin15)
```

**Comment by pocke** [comment]
This bug is fixed already in master. https://github.com/bbatsov/rubocop/pull/4604
