### ISSUE TITLE
Time for v0.50.0 release?

### ISSUE THREAD

**Issue by bquorning** [bbatsov/rubocop#4692]
It’s been a few months since the last release, and [a lot of changes](https://github.com/bbatsov/rubocop/compare/v0.49.1...master) on master since then. Is there an estimate on release date?

If something is blocking a release, perhaps we could start using [milestones](https://github.com/bbatsov/rubocop/milestones) again?

**Comment by bbatsov** [comment]
I've been extremely busy and that's blocking the release. I want to clean up the outstanding PRs before cutting it. If people want a release sooner, they'll have to help review the PRs and get them into a mergeable state.

**Comment by bquorning** [comment]
There are currently 19 open pull requests. By the time they are merged in, new pull requests will have been opened. I’m sorry, but I think this project has become too popular to aim for 0 open pull requests. (But also, I’m also very happy that RuboCop has become this popular ✨)

I will take a look at the open pull requests, see if I can contribute anything. But I would also advocate for frequent releases (once per month or so) like we’re used to. I personally prefer to upgrade to a new version of RuboCop when the changes aren’t too overwhelming.

**Comment by bbatsov** [comment]
> There are currently 19 open pull requests. By the time they are merged in, new pull requests will have been opened. I’m sorry, but I think this project has become too popular to aim for 0 open pull requests. (But also, I’m also very happy that RuboCop has become this popular ✨)

The rate of PRs hasn't really increased over the past couple of years, but unfortunately I have a lot less time for OSS. It is what it is. 

> I will take a look at the open pull requests, see if I can contribute anything. But I would also advocate for frequent releases (once per month or so) like we’re used to. I personally prefer to upgrade to a new version of RuboCop when the changes aren’t too overwhelming.

This has been the case for most of the existence of the project. I'd file the current situation under "anomalies". If I ever get to writing a script that extracts the relevant part of the changelog for the current version (the release notes), I might start releasing even more often. Right now this annoying manual process (which takes less than 5 minutes :D) is the main reason why I don't release more often.

**Comment by bquorning** [comment]
> … unfortunately I have a lot less time for OSS. It is what it is.

I understand. That’s totally reasonable.

> If I ever get to writing a script that extracts the relevant part of the changelog …

Done: #4700. We’re here to help :-)

**Comment by cgriego** [comment]
I too have been wondering about the lack of a release. In the project's recent past couple of years, major releases have been, at most, 1-2 months apart and currently we're at about 4 months.

**Comment by bbatsov** [comment]
> I too have been wondering about the lack of a release. In the project's recent past couple of years, major releases have been, at most, 1-2 months apart and currently we're at about 4 months.

Well, too much predictability gets boring after a while, doesn't it? ;-)

**Comment by bbatsov** [comment]
Anyways - https://github.com/bbatsov/rubocop/releases/tag/v0.50.0

Thanks for the new release task @bquorning - works exactly as advertised. 😉
