### ISSUE TITLE
rubocop cache is not invalidated when file permissions change

### ISSUE THREAD

**Issue by chrisdtaylor** [bbatsov/rubocop#4763]
The [Lint/ScriptPermission Cop](http://www.rubydoc.info/gems/rubocop/0.49.1/RuboCop/Cop/Lint/ScriptPermission) checks that files that have a shebang line as their first line also have execute permissions.  However, just adding execute permissions to the file does NOT invalidate the rubocop cache, so the check continues to fail.

--------

## Expected behavior

Rubocop caches should be invalidated for any kind of file change, including permission changes.

## Actual behavior

Permission changes do not invalidate the cache, meaning correcting Lint/ScriptPermission cop violations by adding execute permission to a file does not satisfy the cop unless the cache is manually invalidated or deleted.

## Steps to reproduce the problem

create a script with a #! line and without execute permissions
run rubocop on it
fix permissions
run rubocop again
*boom*

## Rubocop Version:
> rubocop -V
0.49.1 (using Parser 2.4.0.0, running on ruby 2.3.0 x86_64-linux)

**Comment by pocke** [comment]
This problem has been fixed already. 
https://github.com/bbatsov/rubocop/pull/4530
https://github.com/bbatsov/rubocop/issues/4469
