### ISSUE TITLE
Erroneous "unnecessary utf-8 encoding comment" message

### ISSUE THREAD

**Issue by kyrylo** [bbatsov/rubocop#4767]
I installed fresh Rubocop and saw this offence that wasn't an offence on v0.49 and earlier.
 
```sh
% rubocop benchmarks/truncator_string_encoding.rb
Inspecting 1 file
C

Offenses:

benchmarks/truncator_string_encoding.rb:1:1: C: Style/Encoding: Unnecessary utf-8 encoding comment. (https://github.com/bbatsov/ruby-style-guide#utf-8)
# coding: utf-8
^^^^^^^^^^^^^^^

1 file inspected, 1 offense detected
```

--------

## Expected behavior

No offence.

## Actual behavior

Offence.

## Steps to reproduce the problem

Grab the file [here](https://raw.githubusercontent.com/airbrake/airbrake-ruby/v2.3.2/benchmarks/truncator_string_encoding.rb).

## RuboCop version

```
% rubocop -V
0.50.0 (using Parser 2.4.0.0, running on ruby 2.4.0 x86_64-darwin16)
```

**Comment by deivid-rodriguez** [comment]
@kyrylo Does your program break if you remove the comment?

**Comment by kyrylo** [comment]
Hey @deivid-rodriguez! It doesn't break (I have this exact issue in some other spec files and they pass).

I use Emacs and some mode (can't remember for sure, but could be `ruby-mode`) that automatically inserts the magic comment because my files contain Japanese, Russian and other symbols such as the Euro sign.

Do you think it is okay not to add the magic comment? (that is, it's not a rubocop issue)

**Comment by ShockwaveNN** [comment]
@kyrylo according to https://www.ruby-lang.org/en/news/2013/02/24/ruby-2-0-0-p0-is-released/ `utf-8` is default encoding for rb files (`The UTF-8 default encoding, which make many magic comments omissible`), so if you use ruby no older than 2.0.0 your should be fine.

**Comment by kyrylo** [comment]
That makes sense now, thanks!

**Comment by deivid-rodriguez** [comment]
Indeed! This was a feature, not a bug :smiley:
