### ISSUE TITLE
Performance/HashEachMethods is being triggered on things that are not Hashes

### ISSUE THREAD

**Issue by jcoyne** [bbatsov/rubocop#4774]
Specifically an instance of `Config::Options`, which has `keys` but not `each_keys`

https://github.com/railsconfig/config/blob/master/lib/config/options.rb

in rubocop 0.50.0

**Comment by mikegee** [comment]
It is hard (impossible) for Rubocop to know the class of an object by which methods are called on it. It assumes objects that respond to `keys` also respond to `each_key` as `Hash` does. Perhaps `Config::Options` should implement `each_key`?

**Comment by Drenmi** [comment]
As @mikegee pointed out, we can unfortunately not know what an identifier will point to at runtime.

> Perhaps `Config::Options` should implement `each_key`?

It should. In well behaved, hash like objects, `#keys` is usually implemented in terms of `#each_key`.

In the case of `Config::Options` it even delegates to an underlying hash. 🙂
