### ISSUE TITLE
Performance/StartWith false positive

### ISSUE THREAD

**Issue by kddeisz** [bbatsov/rubocop#4778]
## Expected behavior

StartWith should only failing on strings

## Actual behavior

StartWith is called on anything that calls `match` or uses `=~`. For instance in my example, symbols are used but `Symbol#start_with?` doesn't exist so the corrective action docs are not good.

## Steps to reproduce the problem

```ruby
p :abc.match(/\Aa/)
```

## RuboCop version

Include the output of `rubocop -V`. Here's an example:

```
0.50.0 (using Parser 2.4.0.0, running on ruby 2.4.1 x86_64-darwin15)
```

**Comment by Drenmi** [comment]
We can only check this when called directly on a literal, but we should at least do that.

**Comment by kddeisz** [comment]
You're totally right and I'm sold. 

```ruby
#!/usr/bin/env ruby

require 'bundler/inline'
gemfile do
  source 'https://rubygems.org'
  gem 'benchmark-ips'
end

Benchmark.ips do |x|
  x.report('Symbol#match') do
    :abc.match(/\Aabc/)
  end

  x.report('String#start_with') do
    :abc.to_s.start_with?('abc')
  end

  x.compare!
end
```

```
Warming up --------------------------------------
        Symbol#match    82.081k i/100ms
   String#start_with   206.251k i/100ms
Calculating -------------------------------------
        Symbol#match      1.020M (± 4.2%) i/s -      5.171M in   5.076658s
   String#start_with      4.038M (± 3.1%) i/s -     20.213M in   5.010892s

Comparison:
   String#start_with:  4037668.9 i/s
        Symbol#match:  1020479.0 i/s - 3.96x  slower
```

**Comment by Drenmi** [comment]
@kddeisz: I checked in the code. The auto-correct will just ignore it if it isn't a string. We could, like you suggest, update the docs, and extend the auto-correct to make this change.
