### ISSUE TITLE
Check ruby version may be not fixed

### ISSUE THREAD

**Issue by Ana06** [bbatsov/rubocop#4795]
https://github.com/bbatsov/rubocop/issues/2956 was supposed to be fixed in https://github.com/bbatsov/rubocop/pull/3228. I am not sure if I didn't understand it properly or if it is really not fixed.

--------

## Actual behavior
I get the following offense in Rubocop:

```
spec/controllers/webui/package_controller_spec.rb:347:15: E: unexpected token tLT
(Using Ruby 2.2 parser; configure using TargetRubyVersion parameter, under AllCops)
              <param name="host">raw.github.com</param>
              ^
```

And that's my Rubocop version:

```
rubocop -V
0.47.1 (using Parser 2.3.3.1, running on ruby 2.4.1 x86_64-linux-gnu)
```

## Expected behavior

I had expected that the parser is `2.3.3.1` and not `2.2` in the error message

## Steps to reproduce the problem

The following file with the mentioned Rubocop versions fails: https://github.com/evanrolfe/open-build-service/blob/a0788e52ae3100403971b16130c1a3bbbec921a0/src/api/spec/controllers/webui/package_controller_spec.rb

It seems that this fail because of a bug in the parser, and then is when I realised of fact that a wrong Ruby version is used. If you take a look in the [first issue](https://github.com/bbatsov/rubocop/issues/2956) there are some people pointing there with the same problem and the way the solved it was adding `TargetRubyVersion: 2.4`.

## RuboCop version
```
0.47.1 (using Parser 2.3.3.1, running on ruby 2.4.1 x86_64-linux-gnu)
```

But it is not the only version in which this is failing

**Comment by jonas054** [comment]
> I had expected that the parser is 2.3.3.1 and not 2.2 in the error message

It's the functionality for parsing Ruby 2.2 source code that's activated within parser 2.3.3.1. You need to set `TargetRubyVersion: 2.3` or higher to enable parsing of "squiggly heredocs" (`expected = <<~EOT`).

If `TargetRubyVersion` is not set, RuboCop reads `.ruby-version` or falls back on the oldest supported Ruby version.
