### ISSUE TITLE
Errno::EAGAIN != Errno::EWOULDBLOCK

### ISSUE THREAD

**Issue by reitermarkus** [bbatsov/rubocop#4843]
## Expected behavior

Running RuboCop on a file with the contents

```ruby
begin
rescue Errno::EAGAIN, Errno::EWOULDBLOCK
  raise
end
```

should not show an error, since they *may* be the same, but don't have to be.

## Actual behavior

The following offense is detected:

```
errno.rb:2:1: W: Do not shadow rescued Exceptions.
rescue Errno::EAGAIN, Errno::EWOULDBLOCK
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

## RuboCop version

```
$ rubocop -V
0.50.0 (using Parser 2.4.0.0, running on ruby 2.3.3 universal.x86_64-darwin17)
```

**Comment by Drenmi** [comment]
Interesting edge case. As far as the Ruby on your system is concerned, they are the same, but that may not be the case on the machine running in production ...
