### ISSUE TITLE
Lint/UnusedMethodArgument overriding reassignment and zsuper

### ISSUE THREAD

**Issue by akhramov** [bbatsov/rubocop#4892]
Per https://github.com/bbatsov/rubocop/issues/4823#issuecomment-338120387 @mvz discovered an interesting case when overriding reassignment appears with zero-arity super call.

In this case, the value of a variable is unused, so cop suggests to rename the variable. But since `super` call is `zsuper`, it captures the reassigned variable:
```ruby
def foo(a)
  a = 43

  super
end
```

The problem has been resolved by using non-zero arity super:
```ruby
def foo(_a)
  super 43
end
```

That being said, reassignment is capured by `zsuper`, but original variable's value is not used.

What should we do in such situation? Suggest using `super` instead of `zsuper`? Add a configuration option to ignore this case? Both?

*Update*: `binding` call should have a similar problem.

**Comment by Drenmi** [comment]
I think we could augment the "unused argument" logic to tell if there's a call to `super`. In that case we consider it used. 🙂

**Comment by akhramov** [comment]
@Drenmi, i thought of that solution. My concern is that argument's value is unused. Is it a big deal?

**Comment by Drenmi** [comment]
@akhramov: Perhaps that is a new cop entirely? `Lint/ShadowedArgument`?

Something like:

```
Argument `a` was shadowed by a local variable before it was used.
```

WDYT?

**Comment by akhramov** [comment]
@Drenmi, agreed.

Should the cop have config options for disabling `zsuper` / `binding` cases? Like `IgnoreBinding` and `IgnoreZeroAritySuper`?

**Comment by mvz** [comment]
I solved my case by changing the `zsuper` to `super` with arguments. If that's the preferred syntax (and I tend to agree that it is), then the cops basically work and the only issue is documentation.
