### ISSUE TITLE
Cannot load config from unreleased gems

### ISSUE THREAD

**Issue by wafcio** [bbatsov/rubocop#5000]
RuboCop cannot load config from unreleased gems.

--------

## Expected behavior

RuboCop should load config from unreleased gem(s).

## Actual behavior

```
Unable to find gem foo; is the gem installed? Gem::MissingSpecError
/.../gems/rubocop-0.51.0/lib/rubocop/config_loader.rb:243:in `rescue in gem_config_path'
/.../gems/rubocop-0.51.0/lib/rubocop/config_loader.rb:240:in `gem_config_path'
/.../gems/rubocop-0.51.0/lib/rubocop/config_loader_resolver.rb:39:in `block (2 levels) in resolve_inheritance_from_gems'
/.../gems/rubocop-0.51.0/lib/rubocop/config_loader_resolver.rb:37:in `each'
/.../gems/rubocop-0.51.0/lib/rubocop/config_loader_resolver.rb:37:in `block in resolve_inheritance_from_gems'
/.../gems/rubocop-0.51.0/lib/rubocop/config_loader_resolver.rb:30:in `each_pair'
/.../gems/rubocop-0.51.0/lib/rubocop/config_loader_resolver.rb:30:in `resolve_inheritance_from_gems'
/.../gems/rubocop-0.51.0/lib/rubocop/config_loader.rb:47:in `load_file'
/.../gems/rubocop-0.51.0/lib/rubocop/config_loader.rb:124:in `configuration_from_file'
/.../gems/rubocop-0.51.0/lib/rubocop/config_store.rb:44:in `for'
/.../gems/rubocop-0.51.0/lib/rubocop/cli.rb:108:in `apply_default_formatter'
/.../gems/rubocop-0.51.0/lib/rubocop/cli.rb:30:in `run'
/.../gems/rubocop-0.51.0/bin/rubocop:13:in `block in <top (required)>'
```

## Steps to reproduce the problem

Gemfile
```
gem 'foo', github: 'foo/foo'
```

.rubocop.yml
```
inherit_gem:
  foo: .rubocop.yml
```

## RuboCop version

```
$ rubocop -V
0.51.0
```

I have investigated this problem and it looks that problem is here: https://github.com/bbatsov/rubocop/blob/9e3fce91e119ff849ab29f849cca35bd5c82fe44/lib/rubocop/config_loader_resolver.rb#L134
It loads only released gems. If we want to load unreleased gem then this solution will work:
```
Bundler.rubygems.find_name('foo')
```
Unfortunatelly it requires to use bundler, and I am not sure in which way we should fix it. I have this proposition:
```
spec = if defined?(Bundler)
  Bundler.rubygems.find_name(gem_name).first  
else
  Gem::Specification.find_by_name(gem_name)
end
```

What do you think about it ? I can create PR for this issue.

**Comment by pocke** [comment]
You can use `bundle exec rubocop` to load unreleased gems.

Reproduce
====

See https://github.com/pocke/unreleased-rubocop-config

`Gemfile`

```ruby
source 'https://rubygems.org'

gem 'unreleased-rubocop-config', github: 'pocke/unreleased-rubocop-config'
gem 'rubocop'
```

`.rubocop.yml`

```yaml
inherit_gem:
  unreleased-rubocop-config: .rubocop.yml
```

```bash
$ rubocop 
Unable to find gem unreleased-rubocop-config; is the gem installed? Gem::MissingSpecError
/home/pocke/.gem/ruby/2.4.0/gems/rubocop-0.51.0/lib/rubocop/config_loader.rb:243:in `rescue in gem_config_path'
/home/pocke/.gem/ruby/2.4.0/gems/rubocop-0.51.0/lib/rubocop/config_loader.rb:240:in `gem_config_path'
/home/pocke/.gem/ruby/2.4.0/gems/rubocop-0.51.0/lib/rubocop/config_loader_resolver.rb:39:in `block (2 levels) in resolve_inheritance_from_gems'
/home/pocke/.gem/ruby/2.4.0/gems/rubocop-0.51.0/lib/rubocop/config_loader_resolver.rb:37:in `each'
/home/pocke/.gem/ruby/2.4.0/gems/rubocop-0.51.0/lib/rubocop/config_loader_resolver.rb:37:in `block in resolve_inheritance_from_gems'
/home/pocke/.gem/ruby/2.4.0/gems/rubocop-0.51.0/lib/rubocop/config_loader_resolver.rb:30:in `each_pair'
/home/pocke/.gem/ruby/2.4.0/gems/rubocop-0.51.0/lib/rubocop/config_loader_resolver.rb:30:in `resolve_inheritance_from_gems'
/home/pocke/.gem/ruby/2.4.0/gems/rubocop-0.51.0/lib/rubocop/config_loader.rb:47:in `load_file'
/home/pocke/.gem/ruby/2.4.0/gems/rubocop-0.51.0/lib/rubocop/config_loader.rb:124:in `configuration_from_file'
/home/pocke/.gem/ruby/2.4.0/gems/rubocop-0.51.0/lib/rubocop/config_store.rb:44:in `for'
/home/pocke/.gem/ruby/2.4.0/gems/rubocop-0.51.0/lib/rubocop/cli.rb:108:in `apply_default_formatter'
/home/pocke/.gem/ruby/2.4.0/gems/rubocop-0.51.0/lib/rubocop/cli.rb:30:in `run'
/home/pocke/.gem/ruby/2.4.0/gems/rubocop-0.51.0/bin/rubocop:13:in `block in <top (required)>'
/usr/lib/ruby/2.4.0/benchmark.rb:308:in `realtime'
/home/pocke/.gem/ruby/2.4.0/gems/rubocop-0.51.0/bin/rubocop:12:in `<top (required)>'
/home/pocke/.gem/ruby/2.4.0/bin/rubocop:23:in `load'
/home/pocke/.gem/ruby/2.4.0/bin/rubocop:23:in `<main>'

$ bundle exec rubocop
Inspecting 1 file
C

Offenses:

Gemfile:4:1: C: Bundler/OrderedGems: Gems should be sorted in an alphabetical order within their section of the Gemfile. Gem rubocop should appear before unreleased-rubocop-config.
gem 'rubocop'
^^^^^^^^^^^^^

1 file inspected, 1 offense detected
```

**Comment by wafcio** [comment]
It is possible when you have rubocop directly in project, but I used rubocop from 3rd part gem which add rake task which run rubocop with predefined flags. Why you closed this issue before feedback from my side?

**Comment by pocke** [comment]
> It is possible when you have rubocop directly in project.

We can use unreleased gems with rubocop that is not installed directory. We have several choices to resolve the problem.

- Replace `rubocop` with `bundle exec rubocop`
  - I believe it is the best solution, but sometimes we can't replace it.
- Set `GEM_PATH` or some environment variables
  - Maybe it works (I didn't try it).
- Install unreleased gems how same as rubocop.
  - For example:
    ```bash
    cd unreleased-rubocop-config
    gem build unreleased-rubocop-config.gemspec
    gem install --local unreleased-rubocop-config
    ```



>  I use rubocop from 3rd part gem which add rake task which run rubocop with predefined flags. 

Is it like the following?

```ruby
# Rakefile
require 'some_gem/rake_task'

# some_gem/rake_task.rb
task 'run_rubocop' do
  system('rubocop')
end
```




> Why you closed this issue before feedback from my side?

I closed this issue because I think this problem was solved.
But I had overlooked the 3rd party gem case, sorry.

-----


It is not a rubocop's bug. It is a specification of Rubygems and/or Bundler.
RuboCop should be able to find only proper gems. In other words, RuboCop should not be able to find gems that are installed with bundler without `bundle exec`.
So I think we should not change the rubocop's behaviour of searching gems. I believe we made the 3rd part gem's behaviour to configurable.

**Comment by Drenmi** [comment]
> I use rubocop from 3rd part gem which add rake task which run rubocop with predefined flags.

Which gem?

**Comment by wafcio** [comment]
I have created `rubocop-stylecheck` gem which wrao rubocop with simple rake tasks and in `alterans-stylecheck` gem I have rubocop config

**Comment by wafcio** [comment]
I made a few changes, I switched from `sh` command to `system` in rubocop and it looks that problem disappeard.

IMHO problem solved, so I am closing issue.
