### ISSUE TITLE
Feature request) Multi-Line disable

### ISSUE THREAD

**Issue by luke-hill** [bbatsov/rubocop#5023]
## Expected behavior

There exists a way to disable a cop on a line by line basis. The following syntax is used

```
for x in (0..19) # rubocop:disable Style/For
```

In my project (I'm an Automater), I use a POM which has many lines that read like this:
```
    elements(:labels, '.filters__label')
    elements(:section_headings, '.filters__group-heading')
```

For these lines, I don't care if I go over the metric limit, as the css (latter string part of the method), can sometimes be quite long-winded. Plus I'm indented several times sometimes.

It would be nice to have a way to start the disable at say Line 3, and then re-enable it at line 10, instead of having to write 8 comments on the end of each line.

## RuboCop version
Fresh install (Gemfile.lock extraction below)
```
rubocop (0.51.0)
      parallel (~> 1.10)
      parser (>= 2.3.3.1, < 3.0)
      powerpack (~> 0.1)
      rainbow (>= 2.2.2, < 3.0)
      ruby-progressbar (~> 1.7)
      unicode-display_width (~> 1.0, >= 1.0.1)
```

I hope this makes sense. Could you please advise on next steps?

**Comment by Drenmi** [comment]
You can accomplish this using:

```ruby
# rubocop:disable Style/For
...
# rubocop:enable Style/For
```

🙂

**Comment by luke-hill** [comment]
Awesome, apologies for the hassle. I did spend a while googling and looking around.

In my eyes it makes sense to place this here: https://github.com/bbatsov/rubocop/blob/master/manual/configuration.md#disabling-cops-within-source-code
