### ISSUE TITLE
Incorrect Performance/RegexpMatch autocorrect behavior

### ISSUE THREAD

**Issue by yevhene** [bbatsov/rubocop#5026]
When I use autocorrect for Performance/RegexpMatch autocorrect, it replaces `=~` with `.match?`, but it should be `&.match?`. Becuase it breacs code what tries to match `nil`.

.rubocop.yml
```
AllCops:
  TargetRubyVersion: 2.4
```

example.rb
```
# frozen_string_literal: true

value = nil
puts 'Hello' unless value =~ /.*/
```

```
$ ruby example.rb
Hello
```

example-autocorrected.rb
```
# frozen_string_literal: true

value = nil
puts 'Hello' unless value.match?(/.*/)
```

```
$ ruby example-autocorrected.rb
example-autocorrected.rb:4:in `<main>': undefined method `match?' for nil:NilClass (NoMethodError)
```

--------

## Expected behavior
`a =~ /regexp/` -> `a&.match?(/regexp/)`

## Actual behavior
`a =~ /regexp/` -> `a.match?(/regexp/)`

## Steps to reproduce the problem
Try `nil` as matched value.

## RuboCop version
```
$ rubocop -V
0.51.0 (using Parser 2.3.3.1, running on ruby 2.4.1 x86_64-linux)
```

**Comment by pocke** [comment]
Duplicated https://github.com/bbatsov/rubocop/issues/4298 , and pull-request welcome!
Maybe we should disable auto-correction of this cop when lhs is not a literal. See this comment https://github.com/bbatsov/rubocop/issues/4298#issuecomment-314139720 .
