### ISSUE TITLE
Incorrect Performance/HashEachMethods behavior with array

### ISSUE THREAD

**Issue by yevhene** [bbatsov/rubocop#5028]
Performance/HashEachMethods decides that goes through hash whe he saw `|a, _|`. But it can be splatted array.

```
ARR = [[1, 2], [4, 5]].freeze                                                   
ARR.each do |a, _|                                                              
  puts a                                                                        
end 
```

--------
## Expected behavior
No offenses for code above.

## Actual behavior
Offense for code above.

## Steps to reproduce the problem
See code above.

## RuboCop version
```
$ rubocop -V
0.51.0 (using Parser 2.3.3.1, running on ruby 2.4.1 x86_64-linux)
```

**Comment by Drenmi** [comment]
Unfortunately we have no way of knowing what a identifier will reference at runtime. The current suggestion for multi-dimensional arrays is to use parentheses around the block arguments. This will silence the cop, and indicate to others that you're destructuring an array.

```ruby
ARR.each do |(a, _)|                                                              
  puts a                                                                        
end 
```

**Comment by yevhene** [comment]
@Drenmi Maybe it should be a separate Cop for this purpose?

**Comment by Drenmi** [comment]
@yevhene: Not being able to do runtime type checking is a universal (and the biggest) constraint of RuboCop. It's a result of doing static analysis on a dynamic language. 🙂 Unless the `#each` is sent to an array literal, there's nothing we can do. (We cover this case already.)
