### ISSUE TITLE
`Style/RedundantParentheses` makes wrong ternary autocorrection

### ISSUE THREAD

**Issue by garettarrowood** [bbatsov/rubocop#5075]
While cleaning up a large codebase, I stumbled upon the autocorrection plunder below.

--------

## Expected behavior

`Style/RedundantParentheses` should autocorrect this line of code:

```ruby
(user.active)? "Y" : "N"
```

to

```ruby
user.active ? "Y" : "N"
```

## Actual behavior

However, what actually happens is that the necessary whitespace is not added. And non-executable code is produced in place of the ternary.

```ruby
-  (user.active)? "Y" : "N"
+  user.active? "Y" : "N"
```

Attempting to execute the corrected line (where `active?` is also a defined method):

```
SyntaxError: unexpected ':', expecting end-of-input
```

## Steps to reproduce the problem

Run rubocop autocorrection on this snippet to produce the results described above.

```ruby
(user.active)? "Y" : "N"
```

## RuboCop version

```
0.51.0 (using Parser 2.4.0.0, running on ruby 2.3.3 x86_64-darwin15)
```

**Comment by tiagotex** [comment]
I'm working on a fix for this bug.
