### ISSUE TITLE
Bundler/OrderedGems not fit for all gems

### ISSUE THREAD

**Issue by FLemon** [bbatsov/rubocop#5115]
hi, just want to point out that we are using a [Gem](https://github.com/codez/delayed_cron_job#installation)
that specified has to be listed after certain gems, which throws this violation

am happy to put this into ignore, but wondering if we should still enforce such rule

**Comment by Drenmi** [comment]
I personally have this disabled in projects. Feel free to do so as well. I hardly consider it critical. 🙂 (Note that it only enforces ordering for gems which are grouped together, not separated by empty lines.)
