### ISSUE TITLE
ruby2.4.0 run rubocop get a Error

### ISSUE THREAD

**Issue by huyong36** [bbatsov/rubocop#5118]
When I run `rubocop`,I get this error:
`
/.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/psych/visitors/to_ruby.rb:123:in visit_Psych_Nodes_Scalar': stack level too deep (SystemStackError)
	from /.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/psych/visitors/visitor.rb:16:in 'visit'
	from /.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/psych/visitors/visitor.rb:6:in 'accept'
	from /.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/psych/visitors/to_ruby.rb:32:in 'accept'
	from .rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/psych/visitors/to_ruby.rb:330:in 'block in register_empty'
	from /.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/psych/visitors/to_ruby.rb:330:in 'each'
	from /.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/psych/visitors/to_ruby.rb:330:in 'register_empty'
	from /.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/psych/visitors/to_ruby.rb:141:in 'visit_Psych_Nodes_Sequence'
	from .rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/psych/visitors/visitor.rb:16:in 'visit'
	 ... 10903 levels...
	from /.rvm/gems/ruby-2.4.0/bin/rubocop:22:in 'load'
	from /.rvm/gems/ruby-2.4.0/bin/rubocop:22:in '<main>'
`

My rubocop version:
0.51.0 (using Parser 2.4.0.2, running on ruby 2.4.0 x86_64-darwin17)

**Comment by Drenmi** [comment]
Since this is originating in Psych, please include your `.rubocop.yml`.

**Comment by huyong36** [comment]
thank you.
