### ISSUE TITLE
I'd like to contribute some Bitcoin

### ISSUE THREAD

**Issue by schmijos** [bbatsov/rubocop#5167]
The README now has a section where you search for financial support. I'd like to make a one-time payment. Do you accept Bitcoin?

**Comment by bbatsov** [comment]
> The README now has a section where you search for financial support. I'd like to make a one-time payment. Do you accept Bitcoin?

Not yet, but if something like this is easy to setup I'm open to it.

**Comment by schmijos** [comment]
It depends if you want to receive and keep Bitcoin or if you want to get rid of them asap:

Receiving and keeping is easy:

1. Set up a wallet, for example on your phone with [Bread Wallet](https://breadapp.com/)
2. Generate a QRCode from your Bitcoin address
3. Upload address and QRCode into the Rubocop readme.

Receiving and selling instantly is harder:

1. Set up an account on a trading platform, for example [Coinbase](https://www.coinbase.com/)
2. Integrate a donation button, for example [with Coinbase](https://developers.coinbase.com/docs/wallet/tutorials/donations)
