### ISSUE TITLE
Option for `--auto-gen-config` not to include timestamp when it was generated

### ISSUE THREAD

**Issue by dominicsayers** [bbatsov/rubocop#5188]
## Feature request

As part of our dev cycle we try to manage our `.rubocop_todo.yml` config file actively, with the aim of reducing its size and ultimately eliminating it.

As part of each pull request, we run Rubocop with `--auto-gen-config --no-offense-counts` to check whether we have fortuitously fixed any existing offences.

If we have *not* fixed any offences then `.rubocop_todo.yml` should be unchanged and we can submit the PR for review.

*But* whenever we use `--auto-gen-config` even with `--no-offense-counts` the `.rubocop-todo.yml` file always changes because of the timestamp comment near the top of the file:

```yaml
# on 2017-12-04 17:40:09 +0000 using RuboCop version 0.51.0.
```

We would like the option to generate a `.rubocop_todo.yml` file that does not change unless there are substantive changes to its content.

One solution would be an option (e.g. `--no-timestamp`) that omits this comment from the top of the generated file.

--------

## Expected behavior

```bash
rubocop --auto-gen-config --no-offense-counts --no-timestamp
```

would generate a `.rubocop_todo.yml` file that does not change unless there is a material change to the code it is reviewing (or the version of Rubocop).

## Actual behavior

Rubocop does not have an option to generate a `.rubocop_todo.yml` file that does not change from one run to the next.

## Steps to reproduce the problem

```bash
rubocop --auto-gen-config --no-offense-counts
```

```bash
$ git status
diff --git a/.rubocop_todo.yml b/.rubocop_todo.yml
index 068dc05e6..9c4369644 100644
--- a/.rubocop_todo.yml
+++ b/.rubocop_todo.yml
@@ -1,6 +1,6 @@
 # This configuration was generated by
 # `rubocop --auto-gen-config --exclude-limit 999 --no-offense-counts`
-# on 2017-12-05 17:40:09 +0000 using RuboCop version 0.51.0.
+# on 2017-12-06 09:30:29 +0000 using RuboCop version 0.51.0.
 # The point is for the user to remove these configuration records
 # one by one as the offenses are removed from the code base.
 # Note that changes in the inspected code, or installation of new
```

## RuboCop version

```
$ rubocop -V
0.51.0 (using Parser 2.4.0.2, running on ruby 2.2.2 x86_64-darwin16)
```

**Comment by dominicsayers** [comment]
If you agree this is a good idea I'd be willing to submit a PR to deliver it.

**Comment by bbatsov** [comment]
That's fine by me.

**Comment by Ana06** [comment]
@dominicsayers I like the idea of running rubocop for every PR to check if the offenses have been fixed 😉 

I am not against having a new option for the timestamp, but I would say that it should be the default that if there are no substantive changes the comment shouldn't change and it should keep the old date. So, if we change this, the new option may not be needed. 🤔

**Comment by dominicsayers** [comment]
I would also be fine with having this as the default but it might be considered a breaking change.

Perhaps it should be an option first then introduce it as the default when a major version release is planned.

**Comment by Ana06** [comment]
@dominicsayers 

> I would also be fine with having this as the default but it might be considered a breaking change.


What I was suggesting to have as the default is not to update the file if there were no substantive changes (not removing the timestamp, which can still be an option). That doesn't seem to be a breaking change. 🤔

**Comment by dominicsayers** [comment]
@Ana06 It's unlikely I agree, but somebody might depend on that timestamp for something 🤷‍♂️ 

I'll try to find time to do a PR over the holiday and you can add your suggestion there.

**Comment by Ana06** [comment]
@dominicsayers 

> @Ana06 It's unlikely, I agree, but somebody might depend on that timestamp for something 🤷‍♂️

Another option could be that the by the default the timestamp doesn't change unless there are substantive changes and adding an option to force that it is updated. That would make more sense for me. 🤔 

> I'll try to find time to do a PR over the holiday and you can add your suggestion there.

Great! 😉

**Comment by Ana06** [comment]
I am also thinking that Rubocop could also have an option that make it fails when there are more excludes in the todo file than needed. So that you don't need to compare the files, but that this is internally done by Rubocop. I think that what you are doing is a great idea and I would also like to use it in my projects. Instead that every of as compare the files, it may be easier that Rubocop does it for us. 🤔
