### ISSUE TITLE
Standard convention for public/private `autocorrect` cop methods

### ISSUE THREAD

**Issue by garettarrowood** [bbatsov/rubocop#5206]
As a developer of Rubocop, I would like to see a standard location and access level for our `autocorrect` methods. Currently, the standard location for the `investigation` and `on_type(node)` methods are at the top of a Cop Class as public methods. `autocorrect` methods are a mix of public and private throughout the codebase. When they are allocated as `private`, they may be at the top of the private section, or they may be further down.

Part of the reason for this is that [here in the AutocorrectLogic Module](https://github.com/bbatsov/rubocop/blob/master/lib/rubocop/cop/autocorrect_logic.rb#L16), `respond_to?` is passed a [second argument to include methods of all access levels](https://ruby-doc.org/core-2.4.2/Object.html#method-i-respond_to-3F).

I purpose we make all our Cop `autocorrect` methods public, placed just before the `private` access modifier as they mostly are now. This convention can remain enforced by removing the second argument to `respond_to?` linked above.

**Comment by bbatsov** [comment]
> I purpose we make all our Cop autocorrect methods public, placed just before the private access modifier as they mostly are now. This convention can remain enforced by removing the second argument to respond_to? linked above.

I agree. `autocorrect` is definitely part of the public API at this point. I'm guessing the current situation is just a historical leftover.

**Comment by garettarrowood** [comment]
Great! I'll open a PR for this in the next few days.
