### ISSUE TITLE
Rails/HasManyOrHasOneDependent false positive

### ISSUE THREAD

**Issue by 6temes** [bbatsov/rubocop#5234]
## Expected behavior

With the following code snippet, Rubocop should not trigger any error:

```ruby
class MyModel
  with_options inverse_of: :my_model, dependent: :restrict_with_exception do
    has_many :some_associations
    has_many :a_other_associations, class_name: 'A::OtherAssociation'
    has_many :b_other_associations, class_name: 'B::OtherAssociation'
  end
end
```

## Actual behavior

Rubocop triggers "Rails/HasManyOrHasOneDependent" for the two `has_many` associations that have the `class_name` argument.

## Steps to reproduce the problem

Copypaste the example code above.

## RuboCop version

```
$ rubocop -V
0.52.0
```

**Comment by koic** [comment]
I confirmed this issue reproduce and opened a PR. Thanks!
#5235
