### ISSUE TITLE
undefined local variable or method `path'

### ISSUE THREAD

**Issue by aristotelesbr2014** [bbatsov/rubocop#5322]
*`cd my project` and  `rubocop`*
with rbenv or rvm return this error

undefined local variable or method `path' for #<RuboCop::Config:0x00563a4254d260>
/home/aristoteles/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rubocop-0.52.0/lib/rubocop/config.rb:198:in `block in check'
/home/aristoteles/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rubocop-0.52.0/lib/rubocop/config.rb:288:in `block in deprecation_check'
/home/aristoteles/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rubocop-0.52.0/lib/rubocop/config.rb:282:in `each'
/home/aristoteles/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rubocop-0.52.0/lib/rubocop/config.rb:282:in `deprecation_check'
/home/aristoteles/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rubocop-0.52.0/lib/rubocop/config.rb:197:in `check'
/home/aristoteles/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rubocop-0.52.0/lib/rubocop/config.rb:193:in `create'
/home/aristoteles/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rubocop-0.52.0/lib/rubocop/config_loader.rb:48:in `load_file'
/home/aristoteles/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rubocop-0.52.0/lib/rubocop/config_loader.rb:79:in `configuration_from_file'
/home/aristoteles/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rubocop-0.52.0/lib/rubocop/config_store.rb:44:in `for'
/home/aristoteles/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rubocop-0.52.0/lib/rubocop/cli.rb:149:in `apply_default_formatter'
/home/aristoteles/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rubocop-0.52.0/lib/rubocop/cli.rb:30:in `run'
/home/aristoteles/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rubocop-0.52.0/bin/rubocop:13:in `block in <top (required)>'
/home/aristoteles/.rbenv/versions/2.3.1/lib/ruby/2.3.0/benchmark.rb:308:in `realtime'
/home/aristoteles/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rubocop-0.52.0/bin/rubocop:12:in `<top (required)>'
/home/aristoteles/.rbenv/versions/2.3.1/bin/rubocop:23:in `load'
/home/aristoteles/.rbenv/versions/2.3.1/bin/rubocop:23:in `<main>
```
rubocop -V
0.52.0 (using Parser 2.4.0.2, running on ruby 2.3.1 x86_64-linux) 
arch linux
```

**Comment by aristotelesbr2014** [comment]
This fixed my problem:
[#114](https://github.com/codeclimate/codeclimate-rubocop/issues/114)

**Comment by pocke** [comment]
Yeah, it already fixed in master 👍 
https://github.com/bbatsov/rubocop/pull/5278
