### ISSUE TITLE
Unsafe removal of 'parentheses for method calls with no arguments'

### ISSUE THREAD

**Issue by martinvelez** [bbatsov/rubocop#5324]
Removing parentheses for method calls with no arguments is not always safe.

Here is the input source code.

```ruby
# Before rubocop -a original.rb
def success()
  42
end

def foo
  sucess = false
  return sucess()
end

foo() # returns 42
```

Here is the result after autocorrecting.  It is not equivalent.  The original script always returns **42**.  The autocorrected script always returns **false**.

```ruby
# After rubocop -a original.rb
def success()
  42
end

def foo
  sucess = false
  sucess
end

foo() # returns false
```
--------

## Expected behavior

Rubocop should not remove the parentheses for method calls with no arguments.

## Actual behavior

Rubocop removes the parentheses for method calls with no arguments.

## Steps to reproduce the problem

See code above.

## RuboCop version

```
$ rubocop -V
0.51.0 (using Parser 2.4.0.2, running on ruby 2.4.1 x86_64-linux)
```

**Comment by pocke** [comment]
Thank you for the feedback!

This is a problem of `Style/MethodCallWithoutArgsParentheses`.
It is duplicated with https://github.com/bbatsov/rubocop/issues/4524 .
