### ISSUE TITLE
Should `Style/IndentHeredoc` be moved to `Rails` namespace?

### ISSUE THREAD

**Issue by tdeo** [bbatsov/rubocop#5387]
`String#strip_heredoc` being a Rails-specific method, this cop breaks code when being ran on non-Rails code.

Moving it to the `Rails` department would prevent it from running for people not having Rails cop enabled.

**Comment by bbatsov** [comment]
It's not Rails-specific. RuboCop gets it from https://github.com/bbatsov/powerpack and obvious you can use `ActiveSupport` without Rails. Eventually those methods won't be needed, though - Ruby 2.2 is going to reach EOL soon.
