### ISSUE TITLE
Gemspec/RequiredRubyVersion has misleading message when TargetRubyVersion is not specified

### ISSUE THREAD

**Issue by jcoyne** [bbatsov/rubocop#5431]
When I haven't specified `TargetRubyVersion` in my `.rubocop.yml` it defaults to 2.1.  If this doesn't match my `required_ruby_version` (specified in a gemfile) then the error raised says:

```
Gemspec/RequiredRubyVersion: required_ruby_version (1.9, declared in blacklight-access_controls.gemspec) and TargetRubyVersion (2.1, declared in .rubocop.yml) should be equal.
```

The message should be adjusted from "declared in .rubocop.yml" to say "which may be specified in .rubocop.yml"

**Comment by koic** [comment]
Thanks for the feedback. I opened a PR #5440.
