### ISSUE TITLE
Do not show all offenses in the console for --auto-gen-config

### ISSUE THREAD

**Issue by Ana06** [bbatsov/rubocop#5451]
When generating the `rubocop_todo.yml` file, I do not see the point on showing all the offenses in the console as I just want to exclude them and it is not that important what offenses there are. In projects with a lot of offenses (for example if you introduce Rubocop for the first time) it fulls the console with the offenses.

I would suggest to directly remove this, we could also add this in an option.

**Comment by asherkach** [comment]
Happy to own implementing this feature. Does `--skip-console-output` seem like the right flag name?

**Comment by garettarrowood** [comment]
I'm with @Ana06 on this. I think there should be a flag to _enable_ output and change the default behavior to not output offenses anymore. Upgrading large codebases with output creates a lot of unwanted noise.  So perhaps an `--output-offenses` or `--with-offenses` flag for `--auto-gen-config`.

**Comment by Ana06** [comment]
@garettarrowood 
> I'm with @Ana06 on this. I think there should be a flag to enable output and change the default behavior to not output offenses anymore. Upgrading large codebases with output creates a lot of unwanted noise. So perhaps an --output-offenses or --with-offenses flag for --auto-gen-config.

`--output-offenses` seems like a good name 👍 

@asherkach 

> Happy to own implementing this feature.

will you send a PR then? 😉
