### ISSUE TITLE
Infer the TargetRailsVersion

### ISSUE THREAD

**Issue by roberts1000** [bbatsov/rubocop#5473]
The current code for setting the TargetRailsVersion lib/config.rb is straight forward:

```ruby
def target_rails_version
  @target_rails_version ||=
     for_all_cops.fetch('TargetRailsVersion', DEFAULT_RAILS_VERSION)
end
```

Taking this step further, we could read the resolved rails version from the Gemfile.lock (if it's present) and dynamically set the value.  This will save people from having to configure it.  We would just need to expand the above code a bit:

```ruby
def target_rails_version
  @target_rails_version ||=
    if for_all_cops['TargetRailsVersion']
      for_all_cops['TargetRailsVersion']
    elsif target_rails_version_from_gemfile_lock
      target_rails_version_from_gemfile_lock
    else
      DEFAULT_RAILS_VERSION
    end
end
```

and add set the value

```ruby
def target_rails_version_from_gemfile_lock
  @target_ruby_version_from_gemfile_lock ||= read_rails_version_from_gemfile_lock
end
```

after reading it from the file

```ruby
def read_rails_version_from_gemfile_lock
  return nil unless File.file?("Gemfile.lock")
  File.foreach('Gemfile.lock') do |line|
    # If rails is in the Gemfile, bundler should have resolved it to a specific version and placed it in the Gemfile.lock
    # There should be a line that looks like:
    #         rails (5.1.4)
    result = line.match(/^\s+rails\s\((\d\.\d\.\d)/)
    return result.captures.first if result
  end
end
```

We could generalize this a bit more so the logic could read from `Gemfile.lock` or the new `gems.locked` file that bundler supports.

**Comment by pocke** [comment]
it is a good idea! 👍 

> We could generalize this a bit more so the logic could read from Gemfile.lock or the new gems.locked file that bundler supports.


Yeah, I agree the generalize.

---

And you can use `Bundler::LockfileParser` instead of the regexp. For example

```ruby
lock = Bundler.read_file(path_to_gemfile_lock)
Bundler::LockfileParser.new(lock)
```
