### ISSUE TITLE
`cannot load such file -- rubocop/require_tools` after installing

### ISSUE THREAD

**Issue by Cyberbeni** [bbatsov/rubocop#5489]
After I installed rubocop on my MacBook with macOS 10.12.6, I get this error trying to run it:
```
cannot load such file -- rubocop/require_tools
/usr/local/Cellar/ruby/2.5.0/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
/usr/local/Cellar/ruby/2.5.0/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
/usr/local/lib/ruby/gems/2.5.0/gems/rubocop-0.52.1/lib/rubocop/config_loader_resolver.rb:15:in `block in resolve_requires'
/usr/local/lib/ruby/gems/2.5.0/gems/rubocop-0.52.1/lib/rubocop/config_loader_resolver.rb:11:in `each'
/usr/local/lib/ruby/gems/2.5.0/gems/rubocop-0.52.1/lib/rubocop/config_loader_resolver.rb:11:in `resolve_requires'
/usr/local/lib/ruby/gems/2.5.0/gems/rubocop-0.52.1/lib/rubocop/config_loader.rb:38:in `load_file'
/usr/local/lib/ruby/gems/2.5.0/gems/rubocop-0.52.1/lib/rubocop/config_loader.rb:79:in `configuration_from_file'
/usr/local/lib/ruby/gems/2.5.0/gems/rubocop-0.52.1/lib/rubocop/config_store.rb:44:in `for'
/usr/local/lib/ruby/gems/2.5.0/gems/rubocop-0.52.1/lib/rubocop/cli.rb:171:in `apply_default_formatter'
/usr/local/lib/ruby/gems/2.5.0/gems/rubocop-0.52.1/lib/rubocop/cli.rb:37:in `run'
/usr/local/lib/ruby/gems/2.5.0/gems/rubocop-0.52.1/bin/rubocop:13:in `block in <top (required)>'
/usr/local/Cellar/ruby/2.5.0/lib/ruby/2.5.0/benchmark.rb:308:in `realtime'
/usr/local/lib/ruby/gems/2.5.0/gems/rubocop-0.52.1/bin/rubocop:12:in `<top (required)>'
/usr/local/bin/rubocop:23:in `load'
/usr/local/bin/rubocop:23:in `<main>'
```

--------

## Expected behavior

rubocop runs succesfully

## Actual behavior

rubocop gives error when trying to run it

## Steps to reproduce the problem

```
sudo gem install rubocop
rubocop
```

## RuboCop version

Include the output of `rubocop -V`. Here's an example:

```
$ rubocop -V
0.52.1 (using Parser 2.4.0.2, running on ruby 2.5.0 x86_64-darwin16)
```

**Comment by mikegee** [comment]
What's in your `.rubocop.yml`?

**Comment by Cyberbeni** [comment]
I ran `sudo gem install rubocop` again and it fixed it
But found out I have to use `bundle exec` to run an older version anyways because https://github.com/fastlane/fastlane/blob/master/.rubocop.yml has TargetRubyVersion: 2.0

**Comment by mikegee** [comment]
Your initial error and the second line of that `.rubocop.yml` indicate you needed to install [rubocop-require_tools](https://rubygems.org/gems/rubocop-require_tools).

**Comment by pocke** [comment]
You can use `bundle install` and `bundle exec rubocop` instead.
Fastlane uses `rubocop-require_tools` gem. And you can install the gem with `bundle install` because it is listed in the gemspec. https://github.com/fastlane/fastlane/blob/750f9b39805732beccc554322ad5bdc33d9b2906/fastlane.gemspec#L89
