### ISSUE TITLE
Weird error message in Layout/IndentHeredoc: "<<~ instead of <<~"

### ISSUE THREAD

**Issue by herwinw** [bbatsov/rubocop#5498]
Using the following rubocop config:

```yaml
AllCops:
  TargetRubyVersion: 2.3
```

And this test script:

```ruby
# frozen_string_literal: true

var = <<~TXT
 foobar
TXT
puts var
```
"foobar" is indented with a single space.
The following error message is shown:

```
heredoc.rb:4:1: C: Layout/IndentHeredoc: Use 2 spaces for indentation in a heredoc by using <<~ instead of <<~.
 foobar ...
^^^^^^^
```

The part about using `<<~` instead of `<<~` doesn't really make much sense.

```
$ rubocop -V
0.52.1 (using Parser 2.4.0.2, running on ruby 2.3.3 i386-linux-gnu)
```

**Comment by pocke** [comment]
https://github.com/bbatsov/rubocop/issues/4662#issuecomment-322182388
It is already mentioned in the issue. Unfortunately it has not been fixed yet 😿

**Comment by fullofcaffeine** [comment]
+1
