### ISSUE TITLE
Style/RegexpLiteral recommends %r when default (or forced) slashes is in effect

### ISSUE THREAD

**Issue by nelsonjr** [bbatsov/rubocop#5531]
## Expected behavior

No warning from rubocop.

## Actual behavior

Fails. Even if we specify slashes in EnforcedStyle property in .rubocop.yml.

```
repro.rb:3:3: C: Style/RegexpLiteral: Use %r around regular expression.
  /.*\/tests~.*/
  ^^^^^^^^^^^^^^
```

## Steps to reproduce the problem

Run rubocop in this snippet:

```
TEST_FILE_REGEX = [
  /.*\.tools.*/,
  /.*\/tests~.*/
].freeze
```

## RuboCop version

```
$ bundle exec rubocop -V
0.52.1 (using Parser 2.4.0.2, running on ruby 2.5.0 x86_64-linux)
```

**Comment by bquorning** [comment]
For this behavior, you should configure `AllowInnerSlashes` as well:
```yaml
Style/RegexpLiteral:
  AllowInnerSlashes: true
```
