### ISSUE TITLE
Parser Deprecation warning during autocorrect

### ISSUE THREAD

**Issue by olbrich** [bbatsov/rubocop#5579]
*Be clear, concise and precise in your description of the problem.
Open an issue with a descriptive title and a summary in grammatically correct,
complete sentences.*

*Use the template below when reporting bugs. Please, make sure that
you're running the latest stable RuboCop and that the problem you're reporting
hasn't been reported (and potentially fixed) already.*

*Before filing the ticket you should replace all text above the horizontal
rule with your own words.*

--------

## Expected behavior

No warnings unrelated to the rubocop output, particularly to stderr.

## Actual behavior

running `rubocop -a` emits a warning to stderr saying
```
rubocop -a
Inspecting 737 files
Parser::Source::Rewriter is deprecated.
Please update your code to use Parser::Source::TreeRewriter instead
..........
```

Some tooling interpret the presence of output on stderr as an error and then fail.

## RuboCop version

Include the output of `rubocop -V`. Here's an example:

```
$ rubocop -V
0.52.1 (using Parser 2.5.0.0, running on ruby 2.2.8 x86_64-darwin16)
```

**Comment by mikegee** [comment]
This issue appears to be resolved by https://github.com/bbatsov/rubocop/pull/5575

**Comment by marcandre** [comment]
See #5611

**Comment by pocke** [comment]
It has been fixed. Thank you!
