### ISSUE TITLE
Performance/RegexpMatch auto-corrects match to match? when MatchData is used

### ISSUE THREAD

**Issue by jsteverman** [bbatsov/rubocop#5608]
Performance/RegexpMatch attempts to auto-correct 'match' to 'match?' when MatchData is not used. Unfortunately, it does not identify all uses of MatchData resulting in errant auto-corrects.
--------

## Expected behavior

RuboCop should identify Regexp.last_match() as a use of MatchData and not auto-correct. 

## Actual behavior

[Corrected] Performance/RegexpMatch: Use match? instead of match when MatchData is not used.
tt = ::Regexp.last_match(1) if /pa(tt)ern/.match(astring)

## Steps to reproduce the problem

The cop appears to correct any use of '.match' in a conditional. Both of the following are corrected:

Regexp.last_match(1) if /pa(tt)ern/.match(astring)

if /pa(tt)ern/.match(astring)
  Regexp.last_match(1)
end

## RuboCop version

0.52.1 (using Parser 2.5.0.1, running on ruby 2.4.3 x86_64-linux)

**Comment by koic** [comment]
Thanks for opening issue.
This issue related to #5038 and fixed by #5569. These cases didn't reproduce at the edge RuboCop. Thank you.
