### ISSUE TITLE
Style/StringLiterals auto-correction doesn't work well with non-ascii characeter

### ISSUE THREAD

**Issue by issei-m** [bbatsov/rubocop#5636]
I want to force the string literals consists of the double quotes, so my .rubocop.yml is like:

```yaml
# .rubocop.yml

Style/StringLiterals:
  EnforcedStyle: double_quotes
```

Then, I did `rubocop -D test.rb --only Style/StringLiterals --auto-correct` for `test.rb` (see following), the single quotes has been replaced actually, but contained characters also has been converted to an unicode **byte** style.
I don't like to do so, could anyone help me?

```ruby
# test.rb

'テスト'
```

Or this is expected behavior? 

Regards!

--------

## Expected behavior

My test.rb to be like:

```ruby
"テスト"
```

## Actual behavior

But is like:

```ruby
"\u30C6\u30B9\u30C8"
```

## Steps to reproduce the problem

Put `.rubocop.yml` and `test.rb` that I wrote in description, and execute command:

```
rubocop -D test.rb --only Style/StringLiterals --auto-correct
```

## RuboCop version

```
$ rubocop -V
0.53.0 (using Parser 2.5.0.3, running on ruby 2.5.0 x86_64-linux)
```

**Comment by pocke** [comment]
Can you check `LANG` environment variable in your computer?

Maybe related: https://github.com/bbatsov/rubocop/issues/5475

**Comment by issei-m** [comment]
@pocke I attempted to execute command in accordance with your nice comment [here](https://github.com/bbatsov/rubocop/issues/5475#issuecomment-359423743), it completely resolved my issue. Thank you so much!

```
$ RUBYOPT='-E UTF-8' bundle exec rubocop -D test.rb --only Style/StringLiterals --auto-correct
```
