### ISSUE TITLE
Parser::Source::Rewriter is deprecated

### ISSUE THREAD

**Issue by huyvohcmc** [bbatsov/rubocop#5662]
*Be clear, concise and precise in your description of the problem.
Open an issue with a descriptive title and a summary in grammatically correct,
complete sentences.*

*Use the template below when reporting bugs. Please, make sure that
you're running the latest stable RuboCop and that the problem you're reporting
hasn't been reported (and potentially fixed) already.*

*Before filing the ticket you should replace all text above the horizontal
rule with your own words.*

--------

## Expected behavior

`Parser::Source::Rewriter is deprecated` should never be print out of the screen

## Actual behavior

```
Parser::Source::Rewriter is deprecated.
Please update your code to use Parser::Source::TreeRewriter instead
```

## Steps to reproduce the problem

`rubocop --auto-correct a.rb`

## RuboCop version

```
$ rubocop -V
0.52.1 (using Parser 2.5.0.3, running on ruby 2.3.3 x86_64-darwin17)
```

**Comment by ShockwaveNN** [comment]
This was fixed in https://github.com/bbatsov/rubocop/pull/5611/files and released as RuboCop 0.53.0
