### ISSUE TITLE
Naming/UncommunicativeMethodParamName and keyword arguments

### ISSUE THREAD

**Issue by marcandre** [bbatsov/rubocop#5663]
Feature request.

I like the new `Naming/UncommunicativeMethodParamName` cop. 

Any way to be able to whitelist some parameter names? (e.g. `of:`, `x`, `y`, `age`, ...)?

Please keep in mind that named parameters are part of the API and can't be changed just like that), compared to positional parameters which can be renamed without consequences outside of the method.

**Comment by twalpole** [comment]
There is an `AllowedNames` parameter you can configure for the cop.

**Comment by marcandre** [comment]
Right, that's why I closed my request, thanks!
