### ISSUE TITLE
Enforce spaces in parentheses.

### ISSUE THREAD

**Issue by joshuapinter** [bbatsov/rubocop#5666]
Is there any way to enforce spaces in parentheses? It looks like the only option is to ensure there are _no_ spaces.

And, if not, is this something that you would consider merging in as an config option if I  create a PR for  it?

For support, we use ESLint for our mobile application and it supports this as a configuration, as can be seen [here](https://eslint.org/docs/rules/space-in-parens#always).

Thanks!

**Comment by Drenmi** [comment]
> Is there any way to enforce spaces in parentheses?

I don't believe there is.

> And, if not, is this something that you would consider merging in as an config option if I create a PR for it?

Yes. Would be nice to see a PR for a configuration option on `SpaceInsideParens` cop. 👍

**Comment by joshuapinter** [comment]
Excellent, thanks. Glad you're open to it. I'll put this on the weekend list to get implemented. 

It'll be nice to have our company's style guide for both Ruby and JavaScript consistent.

**Comment by joshuapinter** [comment]
I ended up getting to this quicker than I thought. I added an EnforcedStyle option to enforce spaces in parentheses. Tests as well. Everything is working great on our projects.

You can see the Pull Request here: #5672
