### ISSUE TITLE
Feature Suggestion: Allow CLI options to be set via .rubocop.yml

### ISSUE THREAD

**Issue by rmm5t** [bbatsov/rubocop#5754]
I'd like to assign a default `--fail-level` and enable `--ignore-parent-exclusion` for one of my projects. It would be nice to define these overrides directly in the `.rubocop.yml` file, so that a CLI run of rubocop automatically picks them up.

**Proposal:**

```yaml
# .rubocop.yml
options:
  - "--ignore-parent-exclusion"
  - "--fail-level=convention"
```

**Workaround:**

The only other way I have found to accomplish something similar is to build a rubocop rake task wrapper instead:

```ruby
RuboCop::RakeTask.new do |task|
  task.options << "--ignore-parent-exclusion"
  task.options << "--fail-level=convention"
end
```

**Comment by bbatsov** [comment]
I think we discussed this in the past and I'm fine with doing something like this, although I'm not interested in doing it myself. :-)

I think it'd be a mistake to just stuff the command line ops directly though - probably they can be exposed as regular key/value pairs in the config. if we're going the passing options to cli directly route, there are simpler ways to do it - e.g. just having a single entry in the config about this or some dedicated file with just the options string.

**Comment by rmm5t** [comment]
> I think it'd be a mistake to just stuff the command line ops directly though - probably they can be exposed as regular key/value pairs in the config

Potentially agreed, especially, because I think only a few of these kinds of command line options make sense to be set as defaults in the config file.  However, I just figured something more generic like the suggested approach would be better for forwards compatibility and discoverability.

> some dedicated file with just the options string

That's a reasonable approach too. Are you suggesting something  like a `.rubocop` (no yaml) file, similar to `.rspec` for rspec?

**Comment by bbatsov** [comment]
Exactly.

**Comment by rmm5t** [comment]
I just dug in to start a pull-request to support this feature request. After getting started, I realized soon after that rubocop already has support for a `.rubocop` file that specifies default CLI arguments. 

https://github.com/bbatsov/rubocop/blob/master/lib/rubocop/options.rb#L42-L48

Sheepishly closing this issue. 🐑
