### ISSUE TITLE
NodePattern does not match documented nil literal

### ISSUE THREAD

**Issue by andrew-stripe** [bbatsov/rubocop#5763]
## Expected behavior
The token `nil` in NodePatterns should match literal nils in the AST as documented

## Actual behavior
`nil` does not match.

## Steps to reproduce the problem
This example adapted from the documentation should match. If I change all instance of `nil` to `nil?` it does match.

```
require './lib/rubocop'
# Note that I had to fix some syntax issues with the documented pattern
pattern = RuboCop::NodePattern.new('(casgn nil :Const (send (const nil {:Class :Module}) :new))')
source = 'Const = Class.new'
node = RuboCop::ProcessedSource.new(source, RUBY_VERSION.to_f).ast
pattern.match(node)
```

## RuboCop version
```
[5] pry(main)> RuboCop::Version.version(true)
=> "0.54.0 (using Parser 2.4.0.2, running on ruby 2.4.1 x86_64-darwin17)"
```

**Comment by Drenmi** [comment]
Behaviour was changed in #4815, due to the need to differentiate between a missing value in the AST (`nil`) and a literal nil (`nil?`). The documentation in `NodePattern` needs to be updated.

**Comment by baweaver** [comment]
While this makes sense from a pattern matching perspective, it breaks interop with `Parser` and `ProcessedSource` generated ASTs from literal code, which makes for a very unintuitive experience for end-users.

Ideally the pattern matching syntax should retain parity with the literal AST. By breaking that I fear it's going to lead to a lot of questions like this and a lot of undue confusion.

I do not believe this to be an issue of documentation, rather one of breaking compatibility with literal AST translations.

One potential solution would be to introduce a concept like `NodeLiteral#match` which does not have patterns added to it:

```ruby
# Slight psuedo-matcher

BAD_CODE = Some::Deeply::Nested::Mod.new
GOOD_CODE = Other::Nested::Mod.new

MSG = "`#{BAD_CODE} is deprecated, use #{GOOD_CODE} instead."

matcher = NoteLiteral.new(RuboCop::ProcessedSource(BAD_CODE)))

replace(BAD_CODE, GOOD_CODE) if matcher.match(node)
```

Dealing with `ruby-parse -e '...'` and manually dropping ASTs into place feels brittle, and by breaking that interop it almost feels like a necessity.

Is there a better way to approach this?
