### ISSUE TITLE
up_only in migration reports Rails/ReversibleMigration

### ISSUE THREAD

**Issue by morgoth** [bbatsov/rubocop#5821]
Rails 5.2 introduced `up_only` method http://api.rubyonrails.org/classes/ActiveRecord/Migration.html#method-i-up_only

Rubocop reports `Rails/ReversibleMigration` violation for:
```ruby
class DoSomething < ActiveRecord::Migration[5.1]
  def change
    up_only { execute("SET SESSION statement_timeout = 0;") }

    add_column :users, :name, :string
  end
end
```
`Rails/ReversibleMigration: execute is not reversible`

```
rubocop -v
0.55.0
```

**Comment by koic** [comment]
Thanks for the feedback.
I reproduced it and opend PR #5828.
