### ISSUE TITLE
[Question] What is the reasoning behind UnusedMethodArgument?

### ISSUE THREAD

**Issue by jletizia** [bbatsov/rubocop#5826]
I was hoping to get some clarification on the reasoning behind the UnusedMethodArgument (#996) cop.

Internally on our current project, we are trying to figure out what the usefulness of having an unused method argument that is prepending with `_`, since if it is unused, it should probably just be deleted (I'm unable to think of a use case where it shouldn't be?).

As well, would the community be open to having a cop that (or option to this cop) that rather than prepending `_` as a solution, instead require the deletion of unused arguments?

**Comment by andy-smith-msm** [comment]
If the method in question is part of a public API and the implementation no longer needs the parameter then this forms a change of contract with the callers if the parameters are not maintained following a change of implementation.
Consider if this was a gem that you had dependencies upon, any changes to parameterisation of the public API would result in a change of contract so you would have to manage this change more carefully with your consumers (semver major version change etc.). Placeholder parameters may be used to maintain this contract going forward.

**Comment by Drenmi** [comment]
You may also not be in control of the call site for the method, like in the case of a callback. Or in the name of polymorphism you may create, say, a no-op for a parameterized method.
