### ISSUE TITLE
Rubocop 0.55 rejects .yml file that worked in 0.52

### ISSUE THREAD

**Issue by dplassgit** [bbatsov/rubocop#5855]
We specified `gem 'rubocop', '~> 0.52'` in our Gemfile.

After `bundle` installed the latest version (0.55), our .yml file was rejected, due to 

```.rubocop_todo.yml: Lint/BlockAlignment has the wrong namespace - should be Layout
.rubocop_todo.yml: Lint/DefEndAlignment has the wrong namespace - should be Layout
.rubocop_todo.yml: Lint/EndAlignment has the wrong namespace - should be Layout
Error: The `Style/TrailingCommaInLiteral` cop no longer exists. Please use `Style/TrailingCommaInArrayLiteral` and/or `Style/TrailingCommaInHashLiteral` instead.
(obsolete configuration found in .rubocop_todo.yml, please update it)
The `Performance/HashEachMethods` cop has been removed since it no longer provides performance benefits in modern rubies.
(obsolete configuration found in .rubocop_todo.yml, please update it)
.rubocop_todo.yml: Lint/BlockAlignment has the wrong namespace - should be Layout
.rubocop_todo.yml: Lint/DefEndAlignment has the wrong namespace - should be Layout
.rubocop_todo.yml: Lint/EndAlignment has the wrong namespace - should be Layout
Error: The `Style/TrailingCommaInLiteral` cop no longer exists. Please use `Style/TrailingCommaInArrayLiteral` and/or `Style/TrailingCommaInHashLiteral` instead.
(obsolete configuration found in .rubocop_todo.yml, please update it)
The `Performance/HashEachMethods` cop has been removed since it no longer provides performance benefits in modern rubies.
(obsolete configuration found in .rubocop_todo.yml, please update it)
```

This is unacceptable. Configuration files should be durable across "minor" version upgrades (0.52 to 0.55).

--------

## Expected behavior

Rubocop should continue to use the same format when a minor revision is released.

## Actual behavior

Rubocop rejected an existing .yml file.

## Steps to reproduce the problem

.rubocop.yml file with any one of the above-listed "obsolete" cop names.

## RuboCop version

Include the output of `rubocop -V`. Here's an example:

```
$ rubocop -V
0.55.0 (using Parser 2.5.1.0, running on ruby 2.4.2 x86_64-darwin17)
```

**Comment by mikegee** [comment]
SemVer allows breaking changes in versions less than 1.0, and pretty sure Rubocop intends to follow SemVer.

https://semver.org/#spec-item-4

**Comment by mikegee** [comment]
That topic was most recently opened in issue #5612

**Comment by bbatsov** [comment]
I'll close this, as I'd rather have related conversation be part of #5612. FYI - I'll speak about the road to 1.0 in about a month on RubyKaigi. I'll also put together a roadmap for it.
