### ISSUE TITLE
-a flag rewritten code incorrectly

### ISSUE THREAD

**Issue by laplacesdemon** [bbatsov/rubocop#5856]
I have an interesting problem. Rubocop has rewritten my code incorrectly. The piece of code reduces a list to an object using `inject`. I'm not a ruby master, in fact I rarely code in ruby and probably there's a better way to achieve what I was doing. But the resulting code after running `rubocop -a` did a different thing than the original one. See below:

Original code:
```ruby
operations.map { |o| wrap_error(&o) }.inject(Maybe.new) do |maybe, obj|
  if obj.is_a? StandardError then maybe.add_error(obj) else maybe.add_value(obj) end
  maybe
end
```

## Expected behavior

The code behavior should not change.

## Actual behavior

```ruby
operations.map { |o| wrap_error(&o) }.each_with_object(Maybe.new) do |obj, maybe|
  obj.is_a? StandardError ? maybe.add_error(obj) : maybe.add_value(obj)
end
```

here, `inject` became `each_with_object` which does a different thing.

## Steps to reproduce the problem

```
rubocop -a <filename.rb>
```

## RuboCop version

```
$ rubocop -V
0.55.0 (using Parser 2.5.1.0, running on ruby 2.3.3 x86_64-darwin17)
```

**Comment by mikegee** [comment]
You said `The code behavior should not change.`, but I can't tell which behavior changed by looking at it. It looks like Rubocop's version should behave the same.

Can you be more specific about the how it changed the code's behavior?

**Comment by laplacesdemon** [comment]
Having a closer look at this, in fact the transformation to `each_with_object` is correct. I didn't know that api before, it's cool! The problem however is with the ternary operation. 

Following line is rewritten:
```ruby
a = 'test'
if a.is_a? StandardError then true else false end
```

into

```ruby
a = 'test'
a.is_a? StandardError ? true : false
```

Which results in an error: `is_a?': class or module required (TypeError)`. So the problem is (I think) using a question marked method in a ternary operation.

**Comment by rrosenblum** [comment]
This sounds similar to other bugs that have been reported with `Style/TernaryParentheses`. See https://github.com/bbatsov/rubocop/issues/4460
