### ISSUE TITLE
Feature Req: Offence Explanation

### ISSUE THREAD

**Issue by jschank** [bbatsov/rubocop#824]
It would be nice if rubocop, provided a link to a page that describes why an offence is being reported.

For example, my code just reported
Use `module_function` instead of `extend self`.

I'd love to have a convenient link to understand the motivation behind this cop.

Thanks,
John

**Comment by bbatsov** [comment]
We've been slowly adding links to cops and we'll continue doing so. If we ever get to doing https://github.com/bbatsov/rubocop/issues/2051, we'll be able to link to even more information.
