### ISSUE TITLE
Exclude files instead of disabling cops in auto generated config

### ISSUE THREAD

**Issue by fabiopelosin** [bbatsov/rubocop#988]
If the offending files are a reasonable amount (e.g. `<= 5`) it would be convenient that rubocop would exclude them in the auto generated config instead of disabling them. Moreover after the file a comment including the number the offences could be included.

This has two benefits:

- Allows for a more granular fixing.
- Prevents style regression in the rest of the codebase.

**Comment by vassilevsky** [comment]
Looks like this issue can be closed as implemented.

**Comment by jonas054** [comment]
No, the pull request #1531 remains open.

**Comment by nysthee** [comment]
It is now I think.

**Comment by jonas054** [comment]
Now that #1980 has been merged, this issue can be closed.
